### PR TITLE
Better error handling when tracking zone datalinks

### LINKED ISSUE #7869: sled-agent internal metrics add/remove could handle errors more cleanly
I don't think this is urgent, but ran into it while working on related parts of sled-agent in the context of zone shutdown.

When shutting down a zone, we want to stop tracking its VNICs and OPTE ports. At the call site this looks infallible: https://github.com/oxidecomputer/omicron/blob/18a5c256086d24ebadcdeed6ca62c749ecdca51e/sled-agent/src/services.rs#L3647-L3651

However, this method returns a `bool` indicating success or failure: https://github.com/oxidecomputer/omicron/blob/18a5c256086d24ebadcdeed6ca62c749ecdca51e/sled-agent/src/metrics.rs#L492-L495

However again, that `bool` only indicates whether we successfully sent a message on an `mpsc` channel, using the blocking-indefinitely `send(...).await`. I believe this send can only fail if the metrics task has panicked, which in production would have already caused sled-agent to abort anyway: https://github.com/oxidecomputer/omicron/blob/18a5c256086d24ebadcdeed6ca62c749ecdca51e/sled-agent/src/metrics.rs#L434-L437

However a third time, the actual operation enqueued by that message _can_ fail, and if it does, we log an error but then throw that error away and therefore will never retry the operation: https://github.com/oxidecomputer/omicron/blob/18a5c256086d24ebadcdeed6ca62c749ecdca51e/sled-agent/src/metrics.rs#L233-L241

It looks like the "start tracking metrics" path has the same pattern. I think this API could use some rework:

* Returning the `bool` of whether send succeeded is not really useful.
* However, we almost certainly _should_ return the success or failure of the requested operation.
* We should probably consider using `try_send(...)` instead of `send(...).await` to detect if the metrics task has gotten wedged instead of being willing to block indefinitely.

### PR DESCRIPTION
**Pull request by bnaecker**
- Make operations for tracking / untracking datalinks in zones return actual error information, rather than a boolean.
- Use `try_send()` internally when sending messages to the actual metrics task, to avoid blocking indefinitely if that task is corked. This helps ensure we don't block things like the instance lifecycle simply because we couldn't track the Propolis zone's datalinks -- we'd rather the instance boot without those in that case.
- Fixes #7869

### CODE REVIEW

File: sled-agent/src/services.rs [hunk 1]
```diff
@@ -4203,12 +4225,17 @@ impl ServiceManager {
...
                     self.inner.log,
-                    "Failed to notify metrics queue of sled \
-                     time synchronization, metrics may not be produced."
-                );
+                    "Notified metrics task that time is now synced",
+                ),
+                Err(e) => error!(
+                    self.inner.log,
+                    "Failed to notify metrics task that \
+                     time is now synced, metrics may not be produced.";
```
Comment (jgallagher) [inline sled-agent/src/services.rs:4236]: How bad is this failure? It seems pretty bad at a glance since `on_time_sync()` can only fire once. Maybe worth filing an issue that we should retry this or wait for it or something?

File: sled-agent/src/probe_manager.rs [hunk 2]
```diff
@@ -406,7 +412,20 @@ impl ProbeManagerInner {
...
+                match self.metrics_queue.untrack_zone_links(&running_zone) {
+                    Ok(_) => debug!(
+                        self.log,
+                        "stopped tracking zone datalinks";
+                        "zone_name" => running_zone.name(),
+                    ),
+                    Err(errors) => error!(
+                        self.log,
+                        "Failed to stop tracking one or more datalinks in the \
+                        zone, some metrics will not be produced";
```
Comment (jgallagher) [inline sled-agent/src/probe_manager.rs:424]: Is "some metrics will not be produced" accurate for failing to _untrack_ links?

**Review by jgallagher — APPROVED** [review]
LGTM - thanks!

File: sled-agent/src/probe_manager.rs (hunk 2 above)
Comment (bnaecker) [reply sled-agent/src/probe_manager.rs:424]: It is not, thanks.

File: sled-agent/src/services.rs (hunk 1 above)
Comment (bnaecker) [reply sled-agent/src/services.rs:4239]: It's not great, since we'll never produce data from this sled. It also Should Not Happen, since we're not starting many zones at once before time is synchronized. I've filed #8022 to track this, and referenced it in 34822583d.
