### PR TITLE
Small IP pools fixes

### LINKED ISSUE #4005: IP Pools: include `is_default` value in the list/get ip pool response
The `is_default` attribute is currently missing from the get response body. It'll be useful for the admin to know whether a default pool is made for a silo and which one it is, instead of relying on the name or description to provide that information.

### PR DESCRIPTION
**Pull request by david-crespo**
Followup to #3985, closes #4005.

- Add `is_default` to IP pool response
- Inline `ip_pools_fetch` into the one callsite and delete it (per discussion https://github.com/oxidecomputer/omicron/pull/3985#discussion_r1312320845)
- Other small test tweaks suggested by @luqmana

### CODE REVIEW

File: nexus/db-queries/src/db/datastore/ip_pool.rs [hunk 1]
```diff
@@ -111,32 +109,6 @@ impl DataStore {
...
-        // scope, i.e., if it has a silo it is different from your current silo
-        if let Some(pool_silo_id) = pool.silo_id {
-            if pool_silo_id != authz_silo_id {
-                return Err(authz_pool.not_found());
-            }
-        }
-
-        Ok(pool)
-    }
-
```
Comment (david-crespo) [inline nexus/db-queries/src/db/datastore/ip_pool.rs:139]: This did not make sense as a function here. All the logic was related to the calling context.

File: nexus/db-queries/src/db/datastore/ip_pool.rs [hunk 2]
```diff
@@ -541,13 +514,6 @@ mod test {
             .expect("Failed to get silo's default IP pool");
         assert_eq!(ip_pool.name().as_str(), "default-for-silo");
 
-        // if we ask for the fleet default by name, we can still get that one
-        let ip_pool = datastore
-            .ip_pools_fetch(&opctx, &Name("default".parse().unwrap()))
-            .await
-            .expect("Failed to get fleet default IP pool");
-        assert_eq!(ip_pool.id(), fleet_default_pool.id());
-
```
Comment (david-crespo) [inline nexus/db-queries/src/db/datastore/ip_pool.rs:550]: can't do this anymore because the method is gone, but this integration test covers it.

https://github.com/oxidecomputer/omicron/blob/01e730acf3efeb6ff2181d558cf373ded383a365/nexus/tests/integration_tests/instances.rs#L3442-L3451
