### PR TITLE
Better USDT probes for ClickHouse protocol

### LINKED ISSUE #8595: Oximeter frequently hit SQL query timeout errors on rack2
My prometheus scrape jobs stopped getting any data from rack2 after it was updated to omicron commit `ae3ca81`. Most of the scrap jobs look for data points collected in the most recent 1 or 2 minutes. They used to get data back consistently until this recent rack update. I was able to get some data if I put "@now() - 45m" as the interval but I've also seen no data for a whole hour, e.g.
```
oxide experimental system timeseries query --query 'get hardware_component:amd_cpu_tctl | filter timestamp > @now() - 1h | last 1'
{
  "tables": [
    {
      "name": "hardware_component:amd_cpu_tctl",
      "timeseries": {}
    }
  ]
}
```
In the oximeter logs, I see errors like this which didn't exist in earlier logs:
```
20:29:51.751Z WARN oximeter (oximeter-agent): failed to insert some results into metric DB
    collector_id = da510a57-3af1-4d2b-b2ed-2e8849f27d8b
    collector_ip = fd00:1122:3344:10a::3
    error = Telemetry database unavailable: SQL query timed out after 30.000955486s
    file = oximeter/collector/src/results_sink.rs:92
```
There are also frequent errors like the one below but they are also there prior to the recent SW update:
```
22:28:10.427Z ERRO oximeter (oximeter-agent): timer-based collection request queue is full! This may indicate that the producer has a sampling interval that is too fast for the amount of data it generates
    collector_id = da510a57-3af1-4d2b-b2ed-2e8849f27d8b
    collector_ip = fd00:1122:3344:10a::3
    file = oximeter/collector/src/collection_task.rs:845
    interval = 1s
    producer_id = c334fc56-155a-4d7f-a2c9-e104f73603a2
```
The ClickHouse database were up and running when I logged into them. I'll see if there is anything useful from their log files during the database unavailable moments.

### PR DESCRIPTION
**Pull request by bnaecker**
This adds more observability into the network protocol used to talk to ClickHouse, in an attempt to help resolve #8595

### CODE REVIEW

File: oximeter/db/src/client/mod.rs [hunk 1]
```diff
@@ -1124,16 +1126,16 @@ impl Client {
...
         let now = tokio::time::Instant::now();
         let result = tokio::time::timeout(
             self.request_timeout,
-            handle.insert(sql, block),
+            handle.insert(id, sql, block),
         )
         .await;
         let elapsed = now.elapsed();
-        probes::sql__query__done!(|| (&id));
+        probes::sql__query__done!(|| id.to_string());
```
Comment (ahl) [inline oximeter/db/src/client/mod.rs:1142]: that's interesting; maybe we should figure out how to to_string() things that implement it rather than doing serde (which is--I assume--why you're doing this).

File: oximeter/db/src/native/connection.rs [hunk 2]
```diff
@@ -264,27 +278,10 @@ impl Connection {
                             | ServerPacket::EndOfStream =>
                         {
                             let kind = packet.kind();
-                            probes::unexpected__server__packet!(|| kind);
+                            probes::unexpected__server__packet!(|| (self.address.ip().to_string(), kind));
                             break Err(Error::UnexpectedPacket(kind));
                         }
                         ServerPacket::Data(block) => {
-                            probes::data__packet__received!(|| {
```
Comment (ahl) [inline oximeter/db/src/native/connection.rs:271]: I'm confused; were we getting this twice or something?

File: oximeter/db/src/client/mod.rs [hunk 3]
```diff
@@ -78,10 +78,12 @@ const DEFAULT_REQUEST_TIMEOUT: Duration = Duration::from_secs(30);
 #[usdt::provider(provider = "clickhouse_client")]
 mod probes {
     /// Fires when a SQL query begins, with the query string.
-    fn sql__query__start(_: &usdt::UniqueId, sql: &str) {}
+    ///
+    /// The first argument is the query ID, and the same sent to the server.
```
Comment (ahl) [inline oximeter/db/src/client/mod.rs]: I couldn't parse this

File: oximeter/db/src/native/connection.rs [hunk 4]
```diff
@@ -173,12 +178,15 @@ impl Connection {
...
             Some(Ok(ServerPacket::Pong)) => Ok(()),
             Some(Ok(packet)) => {
-                probes::unexpected__server__packet!(|| packet.kind());
+                probes::unexpected__server__packet!(|| (
+                    self.address.ip().to_string(),
+                    packet.kind()
+                ));
                 Err(Error::UnexpectedPacket(packet.kind()))
             }
             Some(Err(e)) => Err(e),
```
Comment (ahl) [inline oximeter/db/src/native/connection.rs:187]: are we interested in probes for this condition?

File: oximeter/db/src/native/io/packet/server.rs [hunk 5]
```diff
@@ -14,12 +14,20 @@ use crate::native::packets::server::PasswordComplexityRule;
 use crate::native::probes;
 use bytes::Buf as _;
 use bytes::BytesMut;
+use std::net::IpAddr;
 
 /// A decoder for packets from the ClickHouse server.
 #[derive(Debug)]
-pub struct Decoder;
+pub struct Decoder {
+    pub addr: IpAddr,
```
Comment (ahl) [inline oximeter/db/src/native/io/packet/server.rs:25]: comment?

File: oximeter/db/src/client/mod.rs (hunk 1 above)
Comment (bnaecker) [reply oximeter/db/src/client/mod.rs:1142]: Yeah, that'd be sweet, especially for types like this where there's a canonical form or just one piece of data. The `{"ok": "xxxx-yyyy-zzzz"}` serialization form is annoying in that case.

File: oximeter/db/src/native/connection.rs (hunk 2 above)
Comment (bnaecker) [reply oximeter/db/src/native/connection.rs:271]: We were not. I removed this probe, subsuming it in the new `packet-received` probe that has the entire packet structure in it. This one is duplicative now.

File: oximeter/db/src/client/mod.rs (hunk 3 above)
Comment (bnaecker) [reply oximeter/db/src/client/mod.rs]: Good to know! I'll make it more clear now.

File: oximeter/db/src/native/connection.rs (hunk 4 above)
Comment (bnaecker) [reply oximeter/db/src/native/connection.rs:187]: The error condition? I think we get the `invalid-packet` probe firing in those cases, such as [here](https://github.com/oxidecomputer/omicron/blob/0beb2708766e89e7562045c17bf93f96cd5ad633/oximeter/db/src/native/io/packet/server.rs#L134). Does that seem like it covers it?

File: oximeter/db/src/native/io/packet/server.rs (hunk 5 above)
Comment (bnaecker) [reply oximeter/db/src/native/io/packet/server.rs:25]: Added in 975a4c3aa

File: oximeter/db/src/client/mod.rs (hunk 3 above)
Comment (bnaecker) [reply oximeter/db/src/client/mod.rs]: Expanded in 975a4c3aa
