### PR TITLE
repo-depot-standalone should assume an Omicron repo and unpack composite artifacts

### LINKED ISSUE #8286: `repo-depot-standalone` should have mode to serve packed Omicron repo
`repo-depot-standalone` currently serves targets in a TUF repo.  It doesn't really know about artifacts or Omicron-level stuff, like composite artifacts.  This worked fine for testing SP images, which are themselves top-level targets.  But it doesn't work well for RoT artifacts.  On real systems, those get unpacked and turned into their own artifacts.  But `repo-depot-standalone` doesn't know how to do that.

It'd be handy to have a mode like:

```
repo-depot-standalone --omicron /path/to/tuf.zip
```

Instead of serving this like a TUF repo using the `tough` crate, it would use `ArtifactsWithPlan::from_zip()` to unpack it the way Omicron does.

### PR DESCRIPTION
**Pull request by davepacheco**
Prior to this change, you'd run `repo-depot-standalone` as:

```
repo-depot-standalone /path/to/extracted/TUF/repo ...
```

and (I think) it could serve any TUF repo, but it would only serve the TUF targets in that repo.  For us, this was enough for the SP artifacts, but doesn't work for the RoT or host OS artifacts.

After this change, you run `repo-depot-standalone` as:

```
repo-depot-standalone /path/to/ZIP/file ...
```

It now assumes it's looking at an Omicron repo (it won't work with generic TUF repos any more).  It extracts the data to a temporary directory and serves all the artifacts (including artifacts within composite artifacts).

So the net change is:

- it only works on Omicron TUF repos (seems fine for us)
- you give it a ZIP file, not an extracted TUF repo
- it extracts it to a temporary directory (cleaned up only on graceful shutdown), rather than using the files you already have
- it serves strictly more artifacts (the same as before, plus the ones inside composite artifacts)

Before, I think you could really only use this tool to serve SP images.  Now, it can be useful for RoT images, the host OS images, and zone images (though we probably won't use it for that).

We could have it continue to operate in the old mode (work on generic TUF repos, serve data out of the already-extracted contents) but that's more work and didn't seem as useful.

Fixes #8286.

@karencfv @jgallagher if you think this is useful for you, can you give it a try?

### CODE REVIEW

**Comment by davepacheco** [comment]
I tested this with an (ancient) R13rc2 repo that I had lying around.  Started it up:

```
$ cargo run --bin=repo-depot-standalone -- ~/tuf-repos/R13rc2/tuf-mupdate.zip 
   Compiling omicron-repo-depot-standalone v0.1.0 (/home/dap/omicron-work/dev-tools/repo-depot-standalone)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 7.95s
     Running `target/debug/repo-depot-standalone /home/dap/tuf-repos/R13rc2/tuf-mupdate.zip`
Jul 24 17:47:39.802 INFO extracting Omicron TUF repository, path: /home/dap/tuf-repos/R13rc2/tuf-mupdate.zip
Jul 24 17:47:39.807 INFO extracting uploaded archive to /dangerzone/omicron_tmp/.tmpIcqrOs
Jul 24 17:47:46.390 INFO created directory to store extracted artifacts, path: /dangerzone/omicron_tmp/update-artifacts.JWQXYI
Jul 24 17:47:46.470 INFO added artifact, length: 4911519, hash: 607369d9afa1e1da040f299732f4ac9323d823809ad0e09970c06af791b6ce97, version: 1.0.34, kind: gimlet_sp, name: gimlet-b
Jul 24 17:47:46.602 INFO added artifact, length: 4911685, hash: c7fdab7f3f36f60c2aa433b9383a5e1df723f605f4a7d09c17662a9de4e39b41, version: 1.0.34, kind: gimlet_sp, name: gimlet-c
Jul 24 17:47:46.722 INFO added artifact, length: 4912188, hash: 68d9f36406cdc412d8d0bdaeab8942577ac91d4de285404b081cdbd8bcaa595c, version: 1.0.34, kind: gimlet_sp, name: gimlet-d
Jul 24 17:47:46.844 INFO added artifact, length: 4912107, hash: 47266ede81e13f5f1e36623ea8dd963842606b783397e4809a9a5f0bda0f8170, version: 1.0.34, kind: gimlet_sp, name: gimlet-e
Jul 24 17:47:46.997 INFO added artifact, length: 4911788, hash: c9c627baf01a04b0e9f0af75f3e596b1399563b8e092c73f9f265224192410a5, version: 1.0.34, kind: gimlet_sp, name: gimlet-f
Jul 24 17:47:47.193 INFO added artifact, length: 1466696, hash: 584b09e756d33a988626522b1581c5a78d1240b618eb292e152ea9e3d260e147, version: 1.0.33, kind: gimlet_rot_image_a, name: oxide-rot-1-staging-devel
Jul 24 17:47:47.193 INFO added artifact, length: 1467115, hash: d9dc9ff53d3f0faddbb5240b0c971423fa2222d457b89de7d93d371deef2be17, version: 1.0.33, kind: gimlet_rot_image_b, name: oxide-rot-1-staging-devel
Jul 24 17:47:47.340 INFO added artifact, length: 1602374, hash: e335ab178ff5b0659741e245902d0719cdc91a2eafded3125bfa5021e8d9cc3b, version: 1.0.33, kind: gimlet_rot_image_a, name: oxide-rot-1-selfsigned-staging-devel
Jul 24 17:47:47.340 INFO added artifact, length: 1602924, hash: 4689fe0b97d5945fdf80c7608e5dec2c626fe0631e399edf9829f56e56986a17, version: 1.0.33, kind: gimlet_rot_image_b, name: oxide-rot-1-selfsigned-staging-devel
Jul 24 17:47:47.492 INFO added artifact, length: 1597296, hash: 3463734172c2f9be020d3c523f69573cb6e11773dde02c2af868804bf945f1ac, version: 1.0.33, kind: gimlet_rot_image_a, name: oxide-rot-1-selfsigned-bart
Jul 24 17:47:47.492 INFO added artifact, length: 1597834, hash: 4304c47026acda8742677023453bb751838720ab8ae21923273adb667c6ef2dc, version: 1.0.33, kind: gimlet_rot_image_b, name: oxide-rot-1-selfsigned-bart
Jul 24 17:47:47.627 INFO added artifact, length: 1466529, hash: 417a32a97885961956f9546cb619539553b6841b0929eee749ab7de604fc208a, version: 1.0.33, kind: gimlet_rot_image_a, name: oxide-rot-1-production-release
Jul 24 17:47:47.627 INFO added artifact, length: 1467023, hash: 203fccdc1c4571fe7c3d6a73d27e1e526cdb5f73dbcaabdca416fc71f2bb5b0f, version: 1.0.33, kind: gimlet_rot_image_b, name: oxide-rot-1-production-release
Jul 24 17:47:47.629 INFO added artifact, length: 87585, hash: d3d280f9f1279fbe19709da0d99b89be9f8c2264a06f3347c2e91f74934cf2c2, version: 1.3.3, kind: gimlet_rot_bootloader, name: gimlet_rot_bootloader-staging-devel
Jul 24 17:47:47.630 INFO added artifact, length: 82938, hash: dd3dcce349ebcf64474771f39249abe846545f1921f336336d39d3bbb4f66865, version: 1.3.3, kind: gimlet_rot_bootloader, name: gimlet_rot_bootloader-bart
Jul 24 17:47:47.632 INFO added artifact, length: 87584, hash: 6d5839de7781f4ee0e1b22a3d8cc6f659619bfff47ccc77b7c172c3d69aa3eea, version: 1.3.3, kind: gimlet_rot_bootloader, name: gimlet_rot_bootloader-production-release
Jul 24 17:48:05.118 INFO added artifact, length: 33554432, hash: 6152008121861f5c784fe868d95f8b75873c6bd28ab66847000232f8d57d73f3, version: 13.0.0-0.ci+git3316a45e464, kind: host_phase_1, name: host
Jul 24 17:48:05.118 INFO added artifact, length: 1048580096, hash: 5883b5a39b03c6278ab2a3400875c5b522c625e2a4d48f187480b295c73eda0e, version: 13.0.0-0.ci+git3316a45e464, kind: host_phase_2, name: host
Jul 24 17:48:08.154 INFO added artifact, length: 33554432, hash: 36049f3ded565f2d60d7d52c090f92ed307c8b44e11538cf8f79f291f75d79af, version: 13.0.0-0.ci+git3316a45e464, kind: trampoline_phase_1, name: trampoline
Jul 24 17:48:08.154 INFO added artifact, length: 127855396, hash: 5ff374e5ee4edcb3efc368cebc4ea8742ad6e7bc07281f586541bfeb0a508a40, version: 13.0.0-0.ci+git3316a45e464, kind: trampoline_phase_2, name: trampoline
Jul 24 17:48:17.019 INFO added artifact, length: 288417246, hash: d921dc4bec05ff44ec794df663b5c22b4ec83afce059e12e7856a8fc7fc068d8, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: clickhouse_keeper
Jul 24 17:48:26.212 INFO added artifact, length: 301538348, hash: 63da1e570d8dead6b2402932bcdd6b865fa0633c9d14211527e800f97f05c8de, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: clickhouse
Jul 24 17:48:30.462 INFO added artifact, length: 138188143, hash: 5e16c1c67102720689a3f63eac94ee6a535fc3dbd7c6754977092491756075ee, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: cockroachdb
Jul 24 17:48:31.347 INFO added artifact, length: 29224652, hash: 98797546d4d59fc05ff584115fc4e0808b3661ff7784ec03868e0bbd56d78bb1, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: crucible-pantry-zone
Jul 24 17:48:32.448 INFO added artifact, length: 37798957, hash: 2658965c9fb322a547c417396cca168c9e805ff6919bd9eb514c1ef0a8cc3e23, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: crucible-zone
Jul 24 17:48:33.521 INFO added artifact, length: 36272431, hash: cea92e547f143781dcf9f35833f3e2ef3231c170268ee45019e4844932e24973, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: external-dns
Jul 24 17:48:34.635 INFO added artifact, length: 36273350, hash: d53351e07897d157a904e561e0523b3abc32cf7086b2a9c9dec2622d0160c6da, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: internal-dns
Jul 24 17:48:37.806 INFO added artifact, length: 102990999, hash: 84ebb865b800568ac07733c13c6dce1b4522e180fe0f15925b936771baf88b07, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: nexus
Jul 24 17:48:38.130 INFO added artifact, length: 10752599, hash: 5749efc5333a9f451b76041bbfb104cf1fb5ba1973d9c77daf0240ef53983fe1, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: ntp
Jul 24 17:48:39.652 INFO added artifact, length: 49413057, hash: e499e8e47f804f7aff526e209c7dfee5a6dc053b5d39d7e90d8607d31ee5fab7, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: oximeter
Jul 24 17:48:39.737 INFO added artifact, length: 2830183, hash: 9b8e22cab5693df69809ad82cb609a269c046e692de5c68b969db59f80a7b928, version: 13.0.0-0.ci+git3316a45e464, kind: zone, name: probe
Jul 24 17:48:39.785 INFO added artifact, length: 3718352, hash: c2f06c89e9d9f257e7a2aef8f5a2c5c5b42cd6e965f1c04cdd29224f880412a6, version: 1.0.33, kind: psc_sp, name: psc-b
Jul 24 17:48:39.832 INFO added artifact, length: 3722350, hash: 17d6f6f6221614638df5f4f694eb4d9d15aa8bca8affb29e507afaa04e79ad63, version: 1.0.33, kind: psc_sp, name: psc-c
Jul 24 17:48:39.962 INFO added artifact, length: 1466679, hash: 781f5f620df0b5097d1fbb78c82eb45d520f6fd21f1c6de9035379e0e9975c75, version: 1.0.33, kind: psc_rot_image_a, name: oxide-rot-1-staging-devel
Jul 24 17:48:39.962 INFO added artifact, length: 1467175, hash: 6b2c94de54b416a7aef112f1eaed43512a8e45b8199cff0e3fd1a7a6f985098a, version: 1.0.33, kind: psc_rot_image_b, name: oxide-rot-1-staging-devel
Jul 24 17:48:40.105 INFO added artifact, length: 1602586, hash: c8a286f8ad2ead7e27d4c75dde0446e3ebded6b0962db9cc4913735a3a1fecfb, version: 1.0.33, kind: psc_rot_image_a, name: oxide-rot-1-selfsigned-staging-devel
Jul 24 17:48:40.105 INFO added artifact, length: 1602941, hash: 63c2ba5180bdac877f916b29ca0e15bf9a66f4bc7bbc1a224a47ea896a310a77, version: 1.0.33, kind: psc_rot_image_b, name: oxide-rot-1-selfsigned-staging-devel
Jul 24 17:48:40.255 INFO added artifact, length: 1597296, hash: 3463734172c2f9be020d3c523f69573cb6e11773dde02c2af868804bf945f1ac, version: 1.0.33, kind: psc_rot_image_a, name: oxide-rot-1-selfsigned-bart
Jul 24 17:48:40.255 INFO added artifact, length: 1597834, hash: 4304c47026acda8742677023453bb751838720ab8ae21923273adb667c6ef2dc, version: 1.0.33, kind: psc_rot_image_b, name: oxide-rot-1-selfsigned-bart
Jul 24 17:48:40.394 INFO added artifact, length: 1466641, hash: 3dc883d34ad33d15cb4ec98fc01ed1bdab4b8441067027f3b0a0abcb7cc143dc, version: 1.0.33, kind: psc_rot_image_a, name: oxide-rot-1-production-release
Jul 24 17:48:40.394 INFO added artifact, length: 1467100, hash: 1c9bb7ada56f6522b2439511182b54c2e678933bb1852a999681c56d67a1ab09, version: 1.0.33, kind: psc_rot_image_b, name: oxide-rot-1-production-release
Jul 24 17:48:40.395 INFO added artifact, length: 87543, hash: f90371c0d51c58820eaf2ba14ef4da313113a049ab37dfbd8652e2ca2c3174c4, version: 1.3.3, kind: psc_rot_bootloader, name: psc_rot_bootloader-staging-devel
Jul 24 17:48:40.397 INFO added artifact, length: 82938, hash: dd3dcce349ebcf64474771f39249abe846545f1921f336336d39d3bbb4f66865, version: 1.3.3, kind: psc_rot_bootloader, name: psc_rot_bootloader-bart
Jul 24 17:48:40.398 INFO added artifact, length: 87556, hash: 05d45d18ff802c79a340c59cbad3100efee93c74ae1d807db3b7cbff8ed0f4c1, version: 1.3.3, kind: psc_rot_bootloader, name: psc_rot_bootloader-production-release
Jul 24 17:48:40.483 INFO added artifact, length: 6508993, hash: 1d2be23df37418cb0362aa66e3f70604f5697c5d08c017423015b7f2c2255ebb, version: 1.0.35, kind: switch_sp, name: sidecar-b
Jul 24 17:48:40.645 INFO added artifact, length: 6526431, hash: 20faf5a2a8591e1a90bb6062d6934a83478b5a80184aed4b10a121017af658ac, version: 1.0.35, kind: switch_sp, name: sidecar-c
Jul 24 17:48:40.819 INFO added artifact, length: 6526310, hash: e8362534dea966e25de054cf8b962761b0fa00326d55ec17e913352ec1b0d6d0, version: 1.0.35, kind: switch_sp, name: sidecar-d
Jul 24 17:48:41.030 INFO added artifact, length: 1466666, hash: ff82f4db7dd18596a3998cc44e214cc48e4e32ecc990a11c7b9b1870c5d0ff5e, version: 1.0.33, kind: switch_rot_image_a, name: oxide-rot-1-staging-devel
Jul 24 17:48:41.030 INFO added artifact, length: 1467198, hash: 6f70c6ee2e34b0504feb3a00d054dbc5876dc02816b32df9728c619fa3b509cd, version: 1.0.33, kind: switch_rot_image_b, name: oxide-rot-1-staging-devel
Jul 24 17:48:41.172 INFO added artifact, length: 1602518, hash: fece711a3e955dfa619519d266bc473e85b8df1242fa8824bd54ac734566c4f8, version: 1.0.33, kind: switch_rot_image_a, name: oxide-rot-1-selfsigned-staging-devel
Jul 24 17:48:41.173 INFO added artifact, length: 1603018, hash: 2926a8d0adf1a21b1392567fb76cd02dd193ef1f73b7240c96e7883f8d04565f, version: 1.0.33, kind: switch_rot_image_b, name: oxide-rot-1-selfsigned-staging-devel
Jul 24 17:48:41.312 INFO added artifact, length: 1597296, hash: 3463734172c2f9be020d3c523f69573cb6e11773dde02c2af868804bf945f1ac, version: 1.0.33, kind: switch_rot_image_a, name: oxide-rot-1-selfsigned-bart
Jul 24 17:48:41.312 INFO added artifact, length: 1597834, hash: 4304c47026acda8742677023453bb751838720ab8ae21923273adb667c6ef2dc, version: 1.0.33, kind: switch_rot_image_b, name: oxide-rot-1-selfsigned-bart
Jul 24 17:48:41.441 INFO added artifact, length: 1466620, hash: 26387c5e9cc520aa788ab5fba77629b96afe7908fa5bd4daa1b4e1e50419a06b, version: 1.0.33, kind: switch_rot_image_a, name: oxide-rot-1-production-release
Jul 24 17:48:41.441 INFO added artifact, length: 1467110, hash: 5756280b81d1950404b5ff4c9caf892530e09fde25be4ade89d42e1c6d63e799, version: 1.0.33, kind: switch_rot_image_b, name: oxide-rot-1-production-release
Jul 24 17:48:41.442 INFO added artifact, length: 87609, hash: 66e480d0a051d413e8c6bcf324df0df2f75235da31f8857a6ac8336c30ec703a, version: 1.3.3, kind: switch_rot_bootloader, name: switch_rot_bootloader-staging-devel
Jul 24 17:48:41.443 INFO added artifact, length: 82938, hash: dd3dcce349ebcf64474771f39249abe846545f1921f336336d39d3bbb4f66865, version: 1.3.3, kind: switch_rot_bootloader, name: switch_rot_bootloader-bart
Jul 24 17:48:41.445 INFO added artifact, length: 87578, hash: 46afc89a8e0602c5c153fc67bd5b67ed1e35a238db5759fd800e105bf8a7bed6, version: 1.3.3, kind: switch_rot_bootloader, name: switch_rot_bootloader-production-release
Jul 24 17:48:41.461 WARN artifact hash found multiple times, old_kind: gimlet_rot_image_a, name: oxide-rot-1-selfsigned-bart, new_kind: psc_rot_image_a, hash: 3463734172c2f9be020d3c523f69573cb6e11773dde02c2af868804bf945f1ac
Jul 24 17:48:41.461 WARN artifact hash found multiple times, old_kind: gimlet_rot_image_b, name: oxide-rot-1-selfsigned-bart, new_kind: psc_rot_image_b, hash: 4304c47026acda8742677023453bb751838720ab8ae21923273adb667c6ef2dc
Jul 24 17:48:41.461 WARN artifact hash found multiple times, old_kind: gimlet_rot_bootloader, name: psc_rot_bootloader-bart, new_kind: psc_rot_bootloader, hash: dd3dcce349ebcf64474771f39249abe846545f1921f336336d39d3bbb4f66865
Jul 24 17:48:41.461 WARN artifact hash found multiple times, old_kind: psc_rot_image_a, name: oxide-rot-1-selfsigned-bart, new_kind: switch_rot_image_a, hash: 3463734172c2f9be020d3c523f69573cb6e11773dde02c2af868804bf945f1ac
Jul 24 17:48:41.461 WARN artifact hash found multiple times, old_kind: psc_rot_image_b, name: oxide-rot-1-selfsigned-bart, new_kind: switch_rot_image_b, hash: 4304c47026acda8742677023453bb751838720ab8ae21923273adb667c6ef2dc
Jul 24 17:48:41.462 WARN artifact hash found multiple times, old_kind: psc_rot_bootloader, name: switch_rot_bootloader-bart, new_kind: switch_rot_bootloader, hash: dd3dcce349ebcf64474771f39249abe846545f1921f336336d39d3bbb4f66865
Jul 24 17:48:41.462 INFO loaded Omicron TUF repository, path: /home/dap/tuf-repos/R13rc2/tuf-mupdate.zip
Jul 24 17:48:41.462 INFO listening, local_addr: [::]:45971
Jul 24 17:49:46.854 INFO accepted connection, remote_addr: [::1]:63341, local_addr: [::]:45971
Jul 24 17:49:46.854 INFO request completed, error_message_external: Not Found, error_message_internal: no route found (no path in router), latency_us: 140, response_code: 404, uri: /artifacts/sha256/607369d9afa1e1da040f299732f4ac9323d823809ad0e09970c06af791b6ce97, method: GET, req_id: a0086240-9a52-4075-a6ac-f9faac95a054, remote_addr: [::1]:63341, local_addr: [::]:45971
Jul 24 17:49:46.875 INFO accepted connection, remote_addr: [::1]:35742, local_addr: [::]:45971
Jul 24 17:49:46.876 INFO request completed, error_message_external: Not Found, error_message_internal: no route found (no path in router), latency_us: 72, response_code: 404, uri: /artifacts/sha256/584b09e756d33a988626522b1581c5a78d1240b618eb292e152ea9e3d260e147, method: GET, req_id: 152b09ce-267e-4108-9203-28470b21d12a, remote_addr: [::1]:35742, local_addr: [::]:45971
Jul 24 17:49:46.901 INFO accepted connection, remote_addr: [::1]:58338, local_addr: [::]:45971
Jul 24 17:49:46.901 INFO request completed, error_message_external: Not Found, error_message_internal: no route found (no path in router), latency_us: 102, response_code: 404, uri: /artifacts/sha256/6152008121861f5c784fe868d95f8b75873c6bd28ab66847000232f8d57d73f3, method: GET, req_id: fdb86735-7e53-4acb-985d-2b7e07abb33f, remote_addr: [::1]:58338, local_addr: [::]:45971
Jul 24 17:49:46.932 INFO accepted connection, remote_addr: [::1]:63250, local_addr: [::]:45971
Jul 24 17:49:46.933 INFO request completed, error_message_external: Not Found, error_message_internal: no route found (no path in router), latency_us: 55, response_code: 404, uri: /artifacts/sha256/63da1e570d8dead6b2402932bcdd6b865fa0633c9d14211527e800f97f05c8de, method: GET, req_id: 3b30d53b-f56c-467b-b346-d9601d4887d6, remote_addr: [::1]:63250, local_addr: [::]:45971
Jul 24 17:49:53.485 INFO accepted connection, remote_addr: [::1]:46078, local_addr: [::]:45971
Jul 24 17:49:53.540 INFO request completed, latency_us: 54261, response_code: 200, uri: /artifact/sha256/607369d9afa1e1da040f299732f4ac9323d823809ad0e09970c06af791b6ce97, method: GET, req_id: 78b39364-1e59-4402-91e9-f099ee174409, remote_addr: [::1]:46078, local_addr: [::]:45971
Jul 24 17:49:53.573 INFO accepted connection, remote_addr: [::1]:42298, local_addr: [::]:45971
Jul 24 17:49:53.595 INFO request completed, latency_us: 21926, response_code: 200, uri: /artifact/sha256/584b09e756d33a988626522b1581c5a78d1240b618eb292e152ea9e3d260e147, method: GET, req_id: 7dd7df43-8665-4fa9-a39f-67b607631a25, remote_addr: [::1]:42298, local_addr: [::]:45971
Jul 24 17:49:53.624 INFO accepted connection, remote_addr: [::1]:54323, local_addr: [::]:45971
Jul 24 17:49:54.255 INFO request completed, latency_us: 630160, response_code: 200, uri: /artifact/sha256/6152008121861f5c784fe868d95f8b75873c6bd28ab66847000232f8d57d73f3, method: GET, req_id: 284877fb-3591-455a-aedd-c06f7b57d0d6, remote_addr: [::1]:54323, local_addr: [::]:45971
Jul 24 17:49:54.390 INFO accepted connection, remote_addr: [::1]:37408, local_addr: [::]:45971
Jul 24 17:50:21.570 INFO request completed, latency_us: 27179683, response_code: 200, uri: /artifact/sha256/63da1e570d8dead6b2402932bcdd6b865fa0633c9d14211527e800f97f05c8de, method: GET, req_id: b4abb7c7-d7ec-44d1-bb62-ca647e4beba6, remote_addr: [::1]:37408, local_addr: [::]:45971
```

Downloaded a smattering of artifacts of different types, including individual RoT images:

```
$ for id in 607369d9afa1e1da040f299732f4ac9323d823809ad0e09970c06af791b6ce97 584b09e756d33a988626522b1581c5a78d1240b618eb292e152ea9e3d260e147 6152008121861f5c784fe868d95f8b75873c6bd28ab66847000232f8d57d73f3 63da1e570d8dead6b2402932bcdd6b865fa0633c9d14211527e800f97f05c8de; do echo $id; curl -s http://[::]:45971/artifact/sha256/$id | shasum -a 256; done
607369d9afa1e1da040f299732f4ac9323d823809ad0e09970c06af791b6ce97
607369d9afa1e1da040f299732f4ac9323d823809ad0e09970c06af791b6ce97  -
584b09e756d33a988626522b1581c5a78d1240b618eb292e152ea9e3d260e147
584b09e756d33a988626522b1581c5a78d1240b618eb292e152ea9e3d260e147  -
6152008121861f5c784fe868d95f8b75873c6bd28ab66847000232f8d57d73f3
6152008121861f5c784fe868d95f8b75873c6bd28ab66847000232f8d57d73f3  -
63da1e570d8dead6b2402932bcdd6b865fa0633c9d14211527e800f97f05c8de
63da1e570d8dead6b2402932bcdd6b865fa0633c9d14211527e800f97f05c8de  -
```

Then I hit ^C:

```
^CJul 24 17:53:37.043 INFO caught signal, shutting down and removing temporary directories
Jul 24 17:53:37.043 INFO beginning graceful shutdown, local_addr: [::]:45971
```

and confirmed that the temporary directories that it reported were gone:

```
$ ls -l /dangerzone/omicron_tmp/update-artifacts.JWQXYI
/dangerzone/omicron_tmp/update-artifacts.JWQXYI: No such file or directory
$ ls -l /dangerzone/omicron_tmp/.tmpIcqrOs
/dangerzone/omicron_tmp/.tmpIcqrOs: No such file or directory
$
```

File: dev-tools/repo-depot-standalone/src/main.rs [hunk 1]
```diff
@@ -121,33 +159,50 @@ impl RepoMetadata {
...
+                .insert(artifact_meta.hash, (repo_index, artifact_hash_id))
+            {
+                warn!(
+                    log,
+                    "artifact hash found multiple times";
+                    "hash" => %artifact_hash,
+                    "new_kind" => %artifact_id.kind,
+                    "name" => %artifact_id.name,
+                    "old_kind" => %old_hash_id.kind,
+                );
```
Comment (karencfv) [inline dev-tools/repo-depot-standalone/src/main.rs]: This is expected with fake TUF repos. It might alarm someone new using this. Perhaps we can add a note or something that it's OK if you're using a fake repo?

File: dev-tools/repo-depot-standalone/src/main.rs [hunk 2]
```diff
@@ -121,33 +159,50 @@ impl RepoMetadata {
...
-        let (repo_index, target_name) =
+    ) -> Option<anyhow::Result<ReaderStream<impl AsyncRead>>> {
+        let (repo_index, artifact_hash_id) =
             self.targets_by_hash.get(requested_sha)?;
-        let omicron_repo = &self.repos[*repo_index];
-        Some((omicron_repo.repo(), target_name))
+        let repo = &self.repos[*repo_index];
+        Some(
+            repo.get_by_hash(artifact_hash_id)
+                .expect("find SHA in repo that we recorded has this SHA")
```
Comment (karencfv) [inline dev-tools/repo-depot-standalone/src/main.rs]: I'm not sure I understand this sentence 😄

**Review by karencfv — APPROVED** [review]
This is really nice, thank you!! I tested updating the RoT on a simulated system and it worked like a charm. Disclaimer: It was an incomplete zip file since I had removed all additional artifacts I didn't need previously.

```console
$ ./target/debug/repo-depot-standalone /var/tmp/my-fake-repo1.zip /var/tmp/my-fake-repo2.zip 
Jul 24 21:28:16.934 INFO extracting Omicron TUF repository, path: /var/tmp/my-fake-repo1.zip
Jul 24 21:28:16.935 INFO extracting uploaded archive to /tmp/.tmpeI5osw
Jul 24 21:28:16.940 INFO created directory to store extracted artifacts, path: /tmp/update-artifacts.w3xjKI
Jul 24 21:28:16.940 INFO added artifact, length: 747, hash: 7e6667e646ad001b54c8365a3d309c03f89c59102723d38d01697ee8079fe670, version: 1.0.0, kind: gimlet_sp, name: fake-gimlet-sp
Jul 24 21:28:16.941 INFO added artifact, length: 735, hash: 04e4a7fdb84acca92c8fd3235e26d64ea61bef8a5f98202589fd346989c5720a, version: 1.0.0, kind: gimlet_rot_image_a, name: fake-gimlet-rot
Jul 24 21:28:16.941 INFO added artifact, length: 735, hash: 04e4a7fdb84acca92c8fd3235e26d64ea61bef8a5f98202589fd346989c5720a, version: 1.0.0, kind: gimlet_rot_image_b, name: fake-gimlet-rot
Jul 24 21:28:16.942 INFO added artifact, length: 750, hash: 005ea358f1cd316df42465b1e3a0334ea22cc0c0442cf9ddf9b42fbf49780236, version: 1.0.0, kind: gimlet_rot_bootloader, name: fake-gimlet-rot-bootloader
Jul 24 21:28:16.948 INFO added artifact, length: 524288, hash: 2053f8594971bbf0a7326c833e2ffc12b065b9d823b9c0b967d275fa595e4e89, version: 1.0.0, kind: host_phase_1, name: fake-host
Jul 24 21:28:16.948 INFO added artifact, length: 1048576, hash: f3dd0c7a1bd4500ea0d8bcf67581f576d47752b2f1998a4cb0f0c3155c483008, version: 1.0.0, kind: host_phase_2, name: fake-host
Jul 24 21:28:16.955 INFO added artifact, length: 524288, hash: 9b7575cad720f017e936fe5994fc4e21fe040acaaf83c2edd86132aa3d667c7b, version: 1.0.0, kind: trampoline_phase_1, name: fake-trampoline
Jul 24 21:28:16.955 INFO added artifact, length: 1048576, hash: f355fb8429a7e0f0716dad035f9a06c799168d6c0ffcde85b1a96fef21d4b53e, version: 1.0.0, kind: trampoline_phase_2, name: fake-trampoline
Jul 24 21:28:16.956 INFO added artifact, length: 6612, hash: 584bcfabf852d22ca322ca92076836cc8c9aa0489bc4132fef345271f2a00daf, version: 1.0.0, kind: zone, name: zone1
Jul 24 21:28:16.956 INFO added artifact, length: 6613, hash: 4063276e4ce47896848da87c83a9e28949c104d92581d62e50bea7ff7a8cfe1c, version: 1.0.0, kind: zone, name: zone2
Jul 24 21:28:16.956 INFO added artifact, length: 744, hash: f896cf5b19ca85864d470ad8587f980218bff3954e7f52bbd999699cd0f9635b, version: 1.0.0, kind: psc_sp, name: fake-psc-sp
Jul 24 21:28:16.957 INFO added artifact, length: 750, hash: 179eb660ebc92e28b6748b6af03d9f998d6131319edd4654a1e948454c62551b, version: 1.0.0, kind: psc_rot_image_a, name: fake-psc-rot
Jul 24 21:28:16.957 INFO added artifact, length: 750, hash: 179eb660ebc92e28b6748b6af03d9f998d6131319edd4654a1e948454c62551b, version: 1.0.0, kind: psc_rot_image_b, name: fake-psc-rot
Jul 24 21:28:16.957 INFO added artifact, length: 750, hash: 005ea358f1cd316df42465b1e3a0334ea22cc0c0442cf9ddf9b42fbf49780236, version: 1.0.0, kind: psc_rot_bootloader, name: fake-psc-rot-bootloader
Jul 24 21:28:16.958 INFO added artifact, length: 740, hash: ab32ec86e942e1a16c8d43ea143cd80dd05a9639529d3569b1c24dfa2587ee74, version: 1.0.0, kind: switch_sp, name: fake-switch-sp
Jul 24 21:28:16.958 INFO added artifact, length: 735, hash: 04e4a7fdb84acca92c8fd3235e26d64ea61bef8a5f98202589fd346989c5720a, version: 1.0.0, kind: switch_rot_image_a, name: fake-switch-rot
Jul 24 21:28:16.958 INFO added artifact, length: 735, hash: 04e4a7fdb84acca92c8fd3235e26d64ea61bef8a5f98202589fd346989c5720a, version: 1.0.0, kind: switch_rot_image_b, name: fake-switch-rot
Jul 24 21:28:16.958 INFO added artifact, length: 750, hash: 005ea358f1cd316df42465b1e3a0334ea22cc0c0442cf9ddf9b42fbf49780236, version: 1.0.0, kind: switch_rot_bootloader, name: fake-switch-rot-bootloader
Jul 24 21:28:16.959 WARN artifact hash found multiple times, old_kind: gimlet_rot_image_a, name: fake-gimlet-rot, new_kind: gimlet_rot_image_b, hash: 04e4a7fdb84acca92c8fd3235e26d64ea61bef8a5f98202589fd346989c5720a
Jul 24 21:28:16.959 WARN artifact hash found multiple times, old_kind: psc_rot_image_a, name: fake-psc-rot, new_kind: psc_rot_image_b, hash: 179eb660ebc92e28b6748b6af03d9f998d6131319edd4654a1e948454c62551b
Jul 24 21:28:16.959 WARN artifact hash found multiple times, old_kind: gimlet_rot_bootloader, name: fake-psc-rot-bootloader, new_kind: psc_rot_bootloader, hash: 005ea358f1cd316df42465b1e3a0334ea22cc0c0442cf9ddf9b42fbf49780236
Jul 24 21:28:16.959 WARN artifact hash found multiple times, old_kind: gimlet_rot_image_b, name: fake-switch-rot, new_kind: switch_rot_image_a, hash: 04e4a7fdb84acca92c8fd3235e26d64ea61bef8a5f98202589fd346989c5720a
Jul 24 21:28:16.959 WARN artifact hash found multiple times, old_kind: switch_rot_image_a, name: fake-switch-rot, new_kind: switch_rot_image_b, hash: 04e4a7fdb84acca92c8fd3235e26d64ea61bef8a5f98202589fd346989c5720a
Jul 24 21:28:16.959 WARN artifact hash found multiple times, old_kind: psc_rot_bootloader, name: fake-switch-rot-bootloader, new_kind: switch_rot_bootloader, hash: 005ea358f1cd316df42465b1e3a0334ea22cc0c0442cf9ddf9b42fbf49780236
Jul 24 21:28:16.959 INFO loaded Omicron TUF repository, path: /var/tmp/my-fake-repo1.zip
Jul 24 21:28:16.959 INFO extracting Omicron TUF repository, path: /var/tmp/my-fake-repo2.zip
Jul 24 21:28:16.959 INFO extracting uploaded archive to /tmp/.tmpWhOpef
Jul 24 21:28:16.962 INFO created directory to store extracted artifacts, path: /tmp/update-artifacts.x5xmAw
Jul 24 21:28:16.962 INFO added artifact, length: 751, hash: ce1e98a8a9ae541654508f101d59a3ddeba3d28177f1d42d5614248eef0b820b, version: 2.0.0, kind: gimlet_sp, name: fake-gimlet-sp
Jul 24 21:28:16.963 INFO added artifact, length: 743, hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, version: 2.0.0, kind: gimlet_rot_image_a, name: fake-gimlet-rot
Jul 24 21:28:16.963 INFO added artifact, length: 743, hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, version: 2.0.0, kind: gimlet_rot_image_b, name: fake-gimlet-rot
Jul 24 21:28:16.963 INFO added artifact, length: 750, hash: 238a9bfc87f02141c7555ff5ebb7a22ec37bc24d6f724ce3af05ed7c412cd115, version: 2.0.0, kind: gimlet_rot_bootloader, name: fake-gimlet-rot-bootloader
Jul 24 21:28:16.970 INFO added artifact, length: 524288, hash: 44714733af7600b30a50bfd2cbaf707ff7ee9724073ff70a6732e55a88864cf6, version: 2.0.0, kind: host_phase_1, name: fake-host
Jul 24 21:28:16.970 INFO added artifact, length: 1048576, hash: 0c0362b640cece5b9a5e86d8fa683bd2eb84c3e7f90731f597197d604ffa76e3, version: 2.0.0, kind: host_phase_2, name: fake-host
Jul 24 21:28:16.977 INFO added artifact, length: 524288, hash: f04c7d7010fe557aad879780b955bbca2aa8a5e5597ebefd1d5102bdbc17f549, version: 2.0.0, kind: trampoline_phase_1, name: fake-trampoline
Jul 24 21:28:16.977 INFO added artifact, length: 1048576, hash: 20d5f7f00d7f3ad9cda2c2087db195347fdf90e5bf2e494a65f80d2a2a86f18d, version: 2.0.0, kind: trampoline_phase_2, name: fake-trampoline
Jul 24 21:28:16.977 INFO added artifact, length: 6612, hash: 3de35852b83f37628290d80047cd2dc1a5982b6554215517d3cb5d37fe9cafb2, version: 2.0.0, kind: zone, name: zone1
Jul 24 21:28:16.978 INFO added artifact, length: 6613, hash: bf445d313aef331fb1c36138e406d474a46a96f6868a500b0b707ad90770fdea, version: 2.0.0, kind: zone, name: zone2
Jul 24 21:28:16.978 INFO added artifact, length: 748, hash: 7adf04de523865003dbf120cebddd5fcf5bad650640281b294197e6ca7016e47, version: 2.0.0, kind: psc_sp, name: fake-psc-sp
Jul 24 21:28:16.979 INFO added artifact, length: 746, hash: 6d1c432647e9b9e4cf846ff5d17932d75cba49c0d3f23d24243238bc40bcfef5, version: 2.0.0, kind: psc_rot_image_a, name: fake-psc-rot
Jul 24 21:28:16.979 INFO added artifact, length: 746, hash: 6d1c432647e9b9e4cf846ff5d17932d75cba49c0d3f23d24243238bc40bcfef5, version: 2.0.0, kind: psc_rot_image_b, name: fake-psc-rot
Jul 24 21:28:16.979 INFO added artifact, length: 750, hash: 238a9bfc87f02141c7555ff5ebb7a22ec37bc24d6f724ce3af05ed7c412cd115, version: 2.0.0, kind: psc_rot_bootloader, name: fake-psc-rot-bootloader
Jul 24 21:28:16.979 INFO added artifact, length: 746, hash: 5a9019c484c051edfab4903a7a5e1817c89bd555eea3e48f6b92c6e67442e13e, version: 2.0.0, kind: switch_sp, name: fake-switch-sp
Jul 24 21:28:16.980 INFO added artifact, length: 743, hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, version: 2.0.0, kind: switch_rot_image_a, name: fake-switch-rot
Jul 24 21:28:16.980 INFO added artifact, length: 743, hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, version: 2.0.0, kind: switch_rot_image_b, name: fake-switch-rot
Jul 24 21:28:16.980 INFO added artifact, length: 750, hash: 238a9bfc87f02141c7555ff5ebb7a22ec37bc24d6f724ce3af05ed7c412cd115, version: 2.0.0, kind: switch_rot_bootloader, name: fake-switch-rot-bootloader
Jul 24 21:28:16.980 WARN artifact hash found multiple times, old_kind: gimlet_rot_image_a, name: fake-gimlet-rot, new_kind: gimlet_rot_image_b, hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77
Jul 24 21:28:16.980 WARN artifact hash found multiple times, old_kind: psc_rot_image_a, name: fake-psc-rot, new_kind: psc_rot_image_b, hash: 6d1c432647e9b9e4cf846ff5d17932d75cba49c0d3f23d24243238bc40bcfef5
Jul 24 21:28:16.980 WARN artifact hash found multiple times, old_kind: gimlet_rot_bootloader, name: fake-psc-rot-bootloader, new_kind: psc_rot_bootloader, hash: 238a9bfc87f02141c7555ff5ebb7a22ec37bc24d6f724ce3af05ed7c412cd115
Jul 24 21:28:16.980 WARN artifact hash found multiple times, old_kind: gimlet_rot_image_b, name: fake-switch-rot, new_kind: switch_rot_image_a, hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77
Jul 24 21:28:16.981 WARN artifact hash found multiple times, old_kind: switch_rot_image_a, name: fake-switch-rot, new_kind: switch_rot_image_b, hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77
Jul 24 21:28:16.981 WARN artifact hash found multiple times, old_kind: psc_rot_bootloader, name: fake-switch-rot-bootloader, new_kind: switch_rot_bootloader, hash: 238a9bfc87f02141c7555ff5ebb7a22ec37bc24d6f724ce3af05ed7c412cd115
Jul 24 21:28:16.981 INFO loaded Omicron TUF repository, path: /var/tmp/my-fake-repo2.zip
Jul 24 21:28:16.981 INFO listening, local_addr: [::]:39359
Jul 24 21:43:08.390 INFO accepted connection, remote_addr: [::1]:60521, local_addr: [::]:39359
Jul 24 21:43:08.392 INFO request completed, latency_us: 1380, response_code: 200, uri: /artifact/sha256/e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, method: GET, req_id: cc2b630e-11b7-4ed5-b160-dba664028a93, remote_addr: [::1]:60521, local_addr: [::]:39359
```

I updated the fake RoT via sp-updater

```console
〉set SimSidecar0 e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77 2.0.0 rot -s a -a 0.0.4 -b 0.0.3
updated configuration for SimSidecar0
Jul 24 21:43:08.334 INFO begin update attempt for baseboard, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.390 DEBG client request, body: None, uri: http://[::]:39359/artifact/sha256/e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, method: GET, repo_depot_url: http://[::]:39359
Jul 24 21:43:08.393 DEBG client response, result: Ok(Response { url: "http://[::]:39359/artifact/sha256/e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77", status: 200, headers: {"content-type": "application/octet-stream", "x-request-id": "cc2b630e-11b7-4ed5-b160-dba664028a93", "content-length": "743", "date": "Thu, 24 Jul 2025 21:43:08 GMT"} }), repo_depot_url: http://[::]:39359
Jul 24 21:43:08.394 DEBG loaded artifact contents, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.394 DEBG client request, body: None, uri: http://[::1]:52832/sp/switch/0, method: GET, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.395 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0", status: 200, headers: {"content-type": "application/json", "x-request-id": "46ec0c58-a314-4288-9e51-dd185271fddd", "content-length": "734", "date": "Thu, 24 Jul 2025 21:43:08 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.396 DEBG found SP state, state: SpState { base_mac_address: [0, 0, 0, 0, 0, 0], hubris_archive_id: "0000000000000000", model: "FAKE_SIM_SIDECAR", power_state: A2, revision: 0, rot: V3 { active: A, pending_persistent_boot_preference: None, persistent_boot_preference: A, slot_a_error: None, slot_a_fwid: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", slot_b_error: None, slot_b_fwid: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", stage0_error: None, stage0_fwid: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", stage0next_error: None, stage0next_fwid: "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd", transient_boot_preference: None }, serial_number: "SimSidecar0" }, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.396 DEBG client request, body: None, uri: http://[::1]:52832/sp/switch/0/component/rot/caboose?firmware_slot=0, method: GET, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.397 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0/component/rot/caboose?firmware_slot=0", status: 200, headers: {"content-type": "application/json", "x-request-id": "126e5fa9-67d9-4741-9a0d-1da41d51e6b2", "content-length": "170", "date": "Thu, 24 Jul 2025 21:43:08 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.398 DEBG found active slot caboose, caboose: SpComponentCaboose { board: "SimRot", epoch: None, git_commit: "eeeeeeee", name: "SimSidecarRot", sign: Some("11594bb5548a757e918e6fe056e2ad9e084297c9555417a025d8788eacf55daf"), version: "0.0.4" }, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.398 DEBG client request, body: None, uri: http://[::1]:52832/sp/switch/0/component/rot/caboose?firmware_slot=1, method: GET, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.399 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0/component/rot/caboose?firmware_slot=1", status: 200, headers: {"content-type": "application/json", "x-request-id": "d0b5097d-91df-4390-a6eb-fb0a2e5654ac", "content-length": "170", "date": "Thu, 24 Jul 2025 21:43:08 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.399 DEBG ready to start update, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.399 DEBG client request, body: Some(Body), uri: http://[::1]:52832/sp/switch/0/component/rot/update?firmware_slot=1&id=c4847f16-70dc-4d20-9541-5e9b0831911b, method: POST, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.400 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0/component/rot/update?firmware_slot=1&id=c4847f16-70dc-4d20-9541-5e9b0831911b", status: 204, headers: {"x-request-id": "9168fd09-fc56-4f78-a20c-4cfdb04eb501", "date": "Thu, 24 Jul 2025 21:43:07 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.400 INFO update started, mgs_addr: http://[::1]:52832, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.401 DEBG started update, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.401 DEBG client request, body: None, uri: http://[::1]:52832/sp/switch/0/component/rot/update-status, method: GET, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.401 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0/component/rot/update-status", status: 200, headers: {"content-type": "application/json", "x-request-id": "6a3e3dd6-fe7d-46aa-be3b-1eb9e04cd4ee", "content-length": "64", "date": "Thu, 24 Jul 2025 21:43:07 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.402 DEBG got update status, status: Complete { id: c4847f16-70dc-4d20-9541-5e9b0831911b }, mgs_addr: http://[::1]:52832, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.402 DEBG delivered artifact, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.402 DEBG attempting to set active slot, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.402 DEBG client request, body: Some(Body), uri: http://[::1]:52832/sp/switch/0/component/rot/active-slot?persist=true, method: POST, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.403 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0/component/rot/active-slot?persist=true", status: 204, headers: {"x-request-id": "5a87eb28-fc35-4b82-82b2-57855be703ba", "date": "Thu, 24 Jul 2025 21:43:07 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.403 DEBG attempting to reset device, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.403 DEBG client request, body: None, uri: http://[::1]:52832/sp/switch/0/component/rot/reset, method: POST, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.404 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0/component/rot/reset", status: 204, headers: {"x-request-id": "eef2de04-8613-4acc-87fc-596be47dc728", "date": "Thu, 24 Jul 2025 21:43:07 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.404 DEBG client request, body: None, uri: http://[::1]:52832/sp/switch/0, method: GET, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.404 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0", status: 200, headers: {"content-type": "application/json", "x-request-id": "82f6e3a1-bd93-47b5-98af-0685f3818883", "content-length": "734", "date": "Thu, 24 Jul 2025 21:43:07 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.405 DEBG found SP state, state: SpState { base_mac_address: [0, 0, 0, 0, 0, 0], hubris_archive_id: "0000000000000000", model: "FAKE_SIM_SIDECAR", power_state: A2, revision: 0, rot: V3 { active: B, pending_persistent_boot_preference: None, persistent_boot_preference: B, slot_a_error: None, slot_a_fwid: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", slot_b_error: None, slot_b_fwid: "c2e0710df1554ebfcfd9a06021648172bda2ed18366626b0b19a2d40dc69d8d9", stage0_error: None, stage0_fwid: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", stage0next_error: None, stage0next_fwid: "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd", transient_boot_preference: None }, serial_number: "SimSidecar0" }, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.405 DEBG client request, body: None, uri: http://[::1]:52832/sp/switch/0/component/rot/caboose?firmware_slot=1, method: GET, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.405 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0/component/rot/caboose?firmware_slot=1", status: 200, headers: {"content-type": "application/json", "x-request-id": "aa15b96e-3751-4ce1-ae11-43e79288d0a5", "content-length": "114", "date": "Thu, 24 Jul 2025 21:43:07 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.405 DEBG found active slot caboose, caboose: SpComponentCaboose { board: "SimRot", epoch: None, git_commit: "this-is-fake-data", name: "SimRot", sign: Some("SimRot"), version: "2.0.0" }, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.406 DEBG precheck result, precheck: Ok(UpdateComplete), update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.406 DEBG client request, body: None, uri: http://[::1]:52832/sp/switch/0, method: GET, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.406 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0", status: 200, headers: {"content-type": "application/json", "x-request-id": "5ef55a40-8337-4754-ae31-3c80a19b2fd9", "content-length": "734", "date": "Thu, 24 Jul 2025 21:43:07 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.407 DEBG found SP state, state: SpState { base_mac_address: [0, 0, 0, 0, 0, 0], hubris_archive_id: "0000000000000000", model: "FAKE_SIM_SIDECAR", power_state: A2, revision: 0, rot: V3 { active: B, pending_persistent_boot_preference: None, persistent_boot_preference: B, slot_a_error: None, slot_a_fwid: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", slot_b_error: None, slot_b_fwid: "c2e0710df1554ebfcfd9a06021648172bda2ed18366626b0b19a2d40dc69d8d9", stage0_error: None, stage0_fwid: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", stage0next_error: None, stage0next_fwid: "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd", transient_boot_preference: None }, serial_number: "SimSidecar0" }, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.407 DEBG client request, body: None, uri: http://[::1]:52832/sp/switch/0/component/rot/caboose?firmware_slot=1, method: GET, mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.407 DEBG client response, result: Ok(Response { url: "http://[::1]:52832/sp/switch/0/component/rot/caboose?firmware_slot=1", status: 200, headers: {"content-type": "application/json", "x-request-id": "c3567ebe-73e7-4452-b615-41865d666fb8", "content-length": "114", "date": "Thu, 24 Jul 2025 21:43:08 GMT"} }), mgs_backend_addr: [::1]:52832, mgs_backend_name: dendrite-b6d65341-167c-41df-9b5c-41cded99c229.host.control-plane.oxide.internal., update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.408 DEBG found active slot caboose, caboose: SpComponentCaboose { board: "SimRot", epoch: None, git_commit: "this-is-fake-data", name: "SimRot", sign: Some("SimRot"), version: "2.0.0" }, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
Jul 24 21:43:08.408 INFO update attempt done, result: CompletedUpdate, elapsed_millis: 73, update_id: c4847f16-70dc-4d20-9541-5e9b0831911b, part_number: FAKE_SIM_SIDECAR, serial_number: SimSidecar0, sp_type: Switch, sp_slot: 0, component: rot, expected_inactive_version: Version(ArtifactVersion("0.0.3")), expected_active_slot: ExpectedActiveRotSlot { slot: A, version: ArtifactVersion("0.0.4") }, expected_persistent_boot_preference: A, expected_pending_persistent_boot_preference: None, expected_transient_boot_preference: None, artifact_hash: e7047f500a5391e22cd8e6a8d3ae66c9d9de7a8d021e6e9a10e05bb6d554da77, artifact_version: 2.0.0
```

And everything worked!

```console
$ ./target/debug/faux-mgs --sp-sim-addr [::1]:57313 state
Jul 24 21:46:14.533 INFO creating SP handle on to talk to SP simulator at [::1]:57313, component: faux-mgs
Jul 24 21:46:14.536 INFO initial discovery complete, addr: [::1]:57313, component: faux-mgs
Jul 24 21:46:14.537 INFO V2(SpStateV2 { hubris_archive_id: [0, 0, 0, 0, 0, 0, 0, 0], serial_number: [83, 105, 109, 83, 105, 100, 101, 99, 97, 114, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], model: [70, 65, 75, 69, 95, 83, 73, 77, 95, 83, 73, 68, 69, 67, 65, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], revision: 0, base_mac_address: [0, 0, 0, 0, 0, 0], power_state: A2, rot: Ok(RotStateV2 { active: B, persistent_boot_preference: B, pending_persistent_boot_preference: None, transient_boot_preference: None, slot_a_sha3_256_digest: Some([170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170]), slot_b_sha3_256_digest: Some([194, 224, 113, 13, 241, 85, 78, 191, 207, 217, 160, 96, 33, 100, 129, 114, 189, 162, 237, 24, 54, 102, 38, 176, 177, 154, 45, 64, 220, 105, 216, 217]) }) }), component: faux-mgs
hubris archive: 0000000000000000
serial number: SimSidecar0
model: FAKE_SIM_SIDECAR
revision: 0
base MAC address: 00:00:00:00:00:00
power state: A2
rot: Ok(RotStateV2 {
active: B, 
persistent_boot_preference: B, 
pending_persistent_boot_preference: None, 
transient_boot_preference: None, 
slot_a_sha3_256_digest: Some("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), 
slot_b_sha3_256_digest: Some("c2e0710df1554ebfcfd9a06021648172bda2ed18366626b0b19a2d40dc69d8d9"), 
}

)
```

```console
$ ./target/debug/faux-mgs --sp-sim-addr [::1]:57313 read-component-caboose --component rot -s 1 VERS
Jul 24 21:46:30.166 INFO creating SP handle on to talk to SP simulator at [::1]:57313, component: faux-mgs
Jul 24 21:46:30.167 INFO initial discovery complete, addr: [::1]:57313, component: faux-mgs
2.0.0

```

File: dev-tools/repo-depot-standalone/src/main.rs (hunk 2 above)
Comment (davepacheco) [reply dev-tools/repo-depot-standalone/src/main.rs]: Yeah, I really don't love `expect()` for this reason.  I used to put a description of the problem there, but then saw guidance that it should say what was "expected".  Here, what's expected is that we were able to find the SHA within the repo that we recorded earlier as having contained this SHA.  I will turn this into a panic with a more explicit message.

File: dev-tools/repo-depot-standalone/src/main.rs (hunk 1 above)
Comment (davepacheco) [reply dev-tools/repo-depot-standalone/src/main.rs]: Yeah, I'll just remove this.  We get it even for release TUF repos.
