### PR TITLE
releng: allow pinning Helios

### LINKED ISSUE #7332: releng tools should be able to pin a Helios version
Under ordinary circumstances, when Omicron images are built, we use whatever the current version of Helios packages and tools is available.  This means we're generally testing new changes with current OS bits automatically.  This does, however, mean that images built this way are not automatically reproducible (i.e., one would need to pick apart a prior image to obtain the exact Helios version included in it, to then be able to reproduce it).

As part of the release engineering process for Omicron, we create a branch for a given release version.  We then push a commit onto that branch that pins the version of Helios that was contemporary with the base Omicron commit in the release.  This makes a given Omicron release commit reproducible with respect to the OS packages it includes.  This pinning is in two parts:

- we pin the commit of [oxidecomputer/helios.git](https://github.com/oxidecomputer/helios) that we use to obtain the **helios-build** tool
- we add an extra dependency on a release version-specific _incorporation_ package (see [Constraints and Freezing](https://man.omnios.org/man7/pkg#CONSTRAINTS_AND_FREEZING) in **pkg(7)** for more discussion) which then constrains the versions of all of the binary packages included in the image from the IPS repository

Today, we achieve this by doctoring the source for the **releng** tool; e.g., for V12:

- for rc0, [020fde1](https://github.com/oxidecomputer/omicron/commit/020fde11e74b09202d6c53b491768bc4912903af) added the base change that forces the tool to use the particular bits
- for rc1, [3a2ed5e](https://github.com/oxidecomputer/omicron/commit/3a2ed5e97b3f92dc78a1f9e2802f3ca7c9e7547e) updated the pins because we needed an OS backport to fix an issue

I think it would be best if these two details could come from some manifest file that is stored in the repository.  On the **main** branch it would specify no pinning, and then as part of release engineering we could just push an update to the file itself.  People could also then use this facility as part of building test images for various changes.

### PR DESCRIPTION
**Pull request by iliana**
Closes #7332.

This defines a new file, **tools/pins.toml**, and an associated dev-tools crate, **omicron-pins**, which is intended to eventually replace the various commit/checksum entries scattered across the tools directory. TOML is selected for its trivial Serde deserializability, Rust support for automatic editing of the file without destroying comments, and its built-in support in the Nix language, so we can easily continue supporting our download tools and the Nix development environment flake as we transition those pins over to pins.toml.

I expect `Pins::read_from_dir` will grow functionality for reading some commit refs from Cargo.toml or package-manifest.toml to avoid needing to update commits in several places where applicable. That is not relevant for Helios but will help for other tools we pin.

### CODE REVIEW

File: dev-tools/pins/src/lib.rs [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+#[derive(Debug, Clone, Deserialize)]
+pub struct Pins {
+    pub helios: Option<Helios>,
+}
+
+#[derive(Debug, Clone, Deserialize)]
+pub struct Helios {
+    pub commit: String,
+    pub incorporation: String,
+}
```
Comment (jclulow) [inline dev-tools/pins/src/lib.rs:18]: I feel like we should include `#[serde(deny_unknown_fields)]` to avoid typos?

File: dev-tools/releng/src/main.rs [hunk 2]
```diff
@@ -307,14 +342,19 @@ async fn main() -> Result<()> {
...
+            info!(
+                logger,
+                "checking out {} to {}", args.helios_dir, helios.commit,
+            );
+            Command::new(&args.git_bin)
+                .arg("-C")
+                .arg(&args.helios_dir)
+                .args(["checkout", &helios.commit])
+                .ensure_success(&logger)
+                .await?;
```
Comment (jclulow) [inline dev-tools/releng/src/main.rs:355]: In the **rel/v\*** branches, I've been using `git reset --hard $commit`; e.g., see https://github.com/oxidecomputer/omicron/commit/020fde11e74b09202d6c53b491768bc4912903af

Is `git checkout` always equivalent to that?

**Review by jclulow — COMMENTED** [review]
Thanks for doing this!  It'll be good to be able to just poke at the TOML file instead of altering the rust source.  Just a few questions:

File: dev-tools/releng/src/main.rs (hunk 2 above)
Comment (iliana) [reply dev-tools/releng/src/main.rs:355]: `git checkout` will fail if there's changes in the working tree, whereas `git reset --hard` will simply wipe them. In this branch we have freshly cloned the repo because the directory was nonexistent or empty, so in this particular case it should always be equivalent.

I'm hesitant to use `git reset --hard` even on a fresh clone out of paranoia, for the sake of running this tool outside of CI.

Comment (jclulow) [reply dev-tools/releng/src/main.rs:355]: Alright!

**Review by jclulow — APPROVED** [review]
Thanks!
