### PR TITLE
[ls-apis] check that only omicron-sled-agent depends on nexus-lockstep-client

### LINKED ISSUE #9057: ls-apis test should ensure we don't ship any unexpected consumers of the nexus-lockstep API
The nexus-lockstep API landing in https://github.com/oxidecomputer/omicron/pull/8983 must not be used by anything other than omdb or RSS. Add checks (and the necessary exceptions).

### PR DESCRIPTION
**Pull request by sunshowers**
Sled Agent depends on nexus-lockstep-client via RSS, and we now ensure that nothing else that's part of one of the deployment units depends on it. (We don't treat omdb as part of a deployment unit because it doesn't participate in upgrade in the typical sense.)

Also add an expectorate test for the output of `ls-apis check`, similar to the existing one for `ls-apis apis`.

Closes #9057.

### CODE REVIEW

**Comment by sunshowers** [comment]
## Testing notes

With this change:

```diff
diff --git a/dev-tools/ls-apis/api-manifest.toml b/dev-tools/ls-apis/api-manifest.toml
index 3143acd089..56556ef748 100644
--- a/dev-tools/ls-apis/api-manifest.toml
+++ b/dev-tools/ls-apis/api-manifest.toml
@@ -351,7 +351,8 @@
 # `packages` arrays in the deployment_units table above) are allowed to use this
 # API. ls-apis check will error out if the list of consumers is incorrect.
 consumers = [
-     { name = "omicron-sled-agent", reason = "RSS uses it, which isn't part of upgrade" },
+     #{ name = "omicron-sled-agent", reason = "RSS uses it, which isn't part of upgrade" },
+     { name = "omicron-nexus", reason = "Nexus uses it, which isn't part of upgrade" },
 ]
 
 [[apis]]
```

`ls-apis check` has this output:

https://gist.github.com/sunshowers/787f58ef7a34458ffdce430cb7b10129

`ls-apis apis` has this output:

https://gist.github.com/sunshowers/0ddf0da4ecb18d7c495abfd5ab594a85

File: dev-tools/ls-apis/src/bin/ls-apis.rs [hunk 1]
```diff
@@ -311,6 +338,30 @@ fn run_check(apis: &SystemApis) -> Result<()> {
...
+    fn print_failed_consumer_check(
+        api: &ApiMetadata,
+        check: &FailedConsumerCheck,
+        apis: &SystemApis,
+    ) {
+        println!("    {} ({}):", api.label, api.client_package_name);
+        for consumer in &check.unexpected {
+            let deployment_unit =
+                apis.server_component_unit(consumer).unwrap_or_else(|| {
+                    panic!(
```
Comment (davepacheco) [inline dev-tools/ls-apis/src/bin/ls-apis.rs:351]: Do you have examples of this problem?  I just want to make sure these messages are clear and actionable to people that might run into this.

File: dev-tools/ls-apis/api-manifest.toml [hunk 2]
```diff
@@ -347,6 +347,12 @@ server_package_name = "nexus-lockstep-api"
 # dependency with sled-agent-client, which is server-versioned.
 versioned_how = "client"
 versioned_how_reason = "Circular dependencies between Nexus and other services"
+# Exactly these consumers (Rust packages specified in one or more of the
+# `packages` arrays in the deployment_units table above) are allowed to use this
+# API. ls-apis check will error out if the list of consumers is incorrect.
+consumers = [
+     { name = "omicron-sled-agent", reason = "RSS uses it, which isn't part of upgrade" },
```
Comment (davepacheco) [inline dev-tools/ls-apis/api-manifest.toml]:
```suggestion
     { name = "omicron-sled-agent", reason = "Only RSS uses this API and it is not part of upgrade" },
```

File: dev-tools/ls-apis/src/api_metadata.rs [hunk 3]
```diff
@@ -228,6 +231,13 @@ pub struct ApiMetadata {
     pub label: String,
     /// package name of the server that provides the corresponding API
     pub server_package_name: ServerPackageName,
+    /// expected consumers (Rust packages) that use this API
+    ///
+    /// By default, we don't make any assertions about expected consumers. But
+    /// some APIs must have a fixed list of consumers, and we assert on that
+    /// via this array.
+    #[serde(default)]
+    pub consumers: ApiExpectedConsumers,
```
Comment (davepacheco) [inline dev-tools/ls-apis/src/api_metadata.rs]: nitty suggestion: what do you think about calling this `restricted_to_consumers` -- see my other comment.

I like that you used an explicit enum here.

File: dev-tools/ls-apis/src/api_metadata.rs [hunk 4]
```diff
@@ -248,6 +258,119 @@ impl ApiMetadata {
...
 }
 
+/// Expected consumers (Rust packages) for an API.
+#[derive(Debug, Default)]
+pub enum ApiExpectedConsumers {
+    /// No assertions are made about consumers.
+    #[default]
+    Any,
+    /// Exactly these consumers are allowed.
+    Exactly(IdOrdMap<ApiExpectedConsumer>),
```
Comment (davepacheco) [inline dev-tools/ls-apis/src/api_metadata.rs]: nit: what do you think about calling this `Restricted`?

Where I'm coming from is that the `reason` you've added to each entry (which is good!) implicitly assumes that the reader already knows that there's a reason why this API is restricted in the first place, but that's not really evident.  That is: if you didn't already know that nexus-lockstep is locked down, it's unclear why "RSS uses it and is not part of upgrade" is relevant to why this entry shows up there.  But if "restricted" appears here, then it's a little clearer.

File: dev-tools/ls-apis/src/api_metadata.rs [hunk 5]
```diff
@@ -248,6 +258,119 @@ impl ApiMetadata {
...
+    }
+    id_upcast!();
+}
+
+/// The status of an API consumer that was discovered by walking the Cargo
+/// metadata graph.
+#[derive(Clone, Debug, PartialEq, Eq)]
+pub enum ApiConsumerStatus {
+    /// No assertions were made about this API consumer.
+    NoAssertion,
```
Comment (davepacheco) [inline dev-tools/ls-apis/src/api_metadata.rs:369]: Thoughts on: `Unrestricted`, meaning "this API has no configured restrictions on which consumers can use it"?

File: dev-tools/ls-apis/src/system_apis.rs [hunk 6]
```diff
@@ -62,6 +68,54 @@ pub struct SystemApis {
...
+
+impl IdOrdItem for ApiConsumer {
+    type Key<'a> = &'a ServerComponentName;
+    fn key(&self) -> Self::Key<'_> {
+        &self.server_pkgname
+    }
+    id_upcast!();
+}
+
+/// An API consumer returned by [`SystemApis::api_consumers`].
```
Comment (davepacheco) [inline dev-tools/ls-apis/src/system_apis.rs:97]: This is definitely fine, but why not just use `&ApiConsumer` where we use this type?

File: dev-tools/ls-apis/src/system_apis.rs [hunk 7]
```diff
@@ -130,6 +184,28 @@ impl SystemApis {
             tracker.api_producers,
         );
 
+        // Ensure that if allowed_consumers is defined, all consumers listed are
```
Comment (davepacheco) [inline dev-tools/ls-apis/src/system_apis.rs]: Looks like the name in this comment got out of sync with the name in the file.

File: dev-tools/ls-apis/src/system_apis.rs [hunk 8]
```diff
@@ -182,13 +259,38 @@ impl SystemApis {
                     found
                 );
             }
+
+            // Are any consumers missing?
```
Comment (davepacheco) [inline dev-tools/ls-apis/src/system_apis.rs]:
```suggestion
            // Do any of the expected consumers of this API not actually use it?
```

Is that an accurate description of this condition?  I wasn't clear what "missing consumer" means because we've already checked that all the consumers in `consumers` fields are present in the file.

File: dev-tools/ls-apis/src/system_apis.rs [hunk 9]
```diff
@@ -297,11 +405,27 @@ impl SystemApis {
...
 
-        Ok(rv.into_iter())
+        Ok(rv)
+    }
+
+    /// Get the consumers for an API that were expected but not found.
+    ///
+    /// Returns `None` if there are no missing consumers, or if no assertions
+    /// were made about the set of expected consumers.
+    pub fn missing_consumers(
```
Comment (davepacheco) [inline dev-tools/ls-apis/src/system_apis.rs]:
```suggestion
    pub fn missing_expected_consumers(
```

I'd do this everywhere because I keep finding "missing consumer" confusing.

File: dev-tools/ls-apis/src/api_metadata.rs (hunk 3 above)
Comment (sunshowers) [reply dev-tools/ls-apis/src/api_metadata.rs]: I like `restricted_to_consumers`, it makes it clear that the goal of this is to put restrictions on an API.

File: dev-tools/ls-apis/src/api_metadata.rs (hunk 4 above)
Comment (sunshowers) [reply dev-tools/ls-apis/src/api_metadata.rs]: Sure, it aligns with the other changes.

File: dev-tools/ls-apis/src/system_apis.rs (hunk 6 above)
Comment (sunshowers) [reply dev-tools/ls-apis/src/system_apis.rs:97]: Ah that's because we apply filtering so `dep_paths` is a smaller list -- we return a `Vec<&DepPath>` rather than `&[DepPath]`.

File: dev-tools/ls-apis/src/system_apis.rs (hunk 7 above)
Comment (sunshowers) [reply dev-tools/ls-apis/src/system_apis.rs]: Done.

File: dev-tools/ls-apis/src/system_apis.rs (hunk 8 above)
Comment (sunshowers) [reply dev-tools/ls-apis/src/system_apis.rs]: Yeah, this is accurate, updated.

File: dev-tools/ls-apis/src/system_apis.rs (hunk 9 above)
Comment (sunshowers) [reply dev-tools/ls-apis/src/system_apis.rs]: sure

File: dev-tools/ls-apis/src/bin/ls-apis.rs (hunk 1 above)
Comment (sunshowers) [reply dev-tools/ls-apis/src/bin/ls-apis.rs:351]: For example, if you say

```toml
restricted_to_consumers = [
     { name = "omicron-foobar", reason = "..." },
]
```

Then, at load-time we error out with:

```
Error: api nexus-lockstep-client specifies unknown consumer: omicron-foobar (with expected reason: ...)
```

This panic asserts that the load-time check has already been performed.

File: dev-tools/ls-apis/src/api_metadata.rs (hunk 3 above)
Comment (sunshowers) [reply dev-tools/ls-apis/src/api_metadata.rs]: (definitely a fan of explicit enums over `Option` in general for this use case that's shaped like an algebraic lattice)

File: dev-tools/ls-apis/src/bin/ls-apis.rs (hunk 1 above)
Comment (davepacheco) [reply dev-tools/ls-apis/src/bin/ls-apis.rs:351]: Maybe add "this is a bug" or something, if the expectation is that they'd never see this message?

**Review by davepacheco — APPROVED** [review]
Thanks!
