### PR TITLE
omdb: Show clickhouse keeper membership in inventory

### LINKED ISSUE #6945: Keeper expungement failing on a4x2
### Steps to reproduce

All omdb ops performed on sled g0 

1. Launch a4x2
2. Set clickhouse-policy to `both` via omdb
3. regenerate a blueprint and make target
4. hyperstop g2 (node with one keeper)
5. expunge g2 via omdb 
6. regenerate a couple blueprints and set as targets
7. Ensure the zones get expunged in the blueprints

### Evidence 

Sled g2 can definitely no longer be reached. I see a log related to failing to contact it in the nexus node on g3. However, the keeper still shows it in inventory both in `keeper-config.xml` and via the `clickhouse keeper-client` command.

```
root@oxz_clickhouse_keeper_1d4c8dac:~# clickhouse keeper-client --host [fd00:1122:3344:104::21]
Connected to ZooKeeper at [fd00:1122:3344:104::21]:9181 with session_id 8
Keeper feature flag FILTERED_LIST: enabled
Keeper feature flag MULTI_READ: enabled
Keeper feature flag CHECK_NOT_EXISTS: disabled
/ :) get /keeper/config
server.1=fd00:1122:3344:101::21:9234;participant;1
server.2=fd00:1122:3344:104::21:9234;participant;1
server.3=fd00:1122:3344:103::21:9234;participant;1
server.4=fd00:1122:3344:103::22:9234;participant;1
server.5=fd00:1122:3344:102::21:9234;participant;1
```

The keeper on sled g2 is `server.5` 

I then checked to see that there has been keeper log entries committed by the leader and they are increasing. 

```
/ :) lgif
first_log_idx   1
first_log_term  1
last_log_idx    1515
last_log_term   1
last_committed_log_idx  1515
leader_committed_log_idx        1515
target_committed_log_idx        1515
last_snapshot_idx       0
```

I then checked crdb to see what the configuration was:

```sql
root@[fd00:1122:3344:101::3]:32221/omicron> select * from bp_clickhouse_cluster_config ;
              blueprint_id             | generation | max_used_server_id | max_used_keeper_id |   cluster_name   |            cluster_secret            | highest_seen_keeper_leader_committed_log_index
---------------------------------------+------------+--------------------+--------------------+------------------+--------------------------------------+-------------------------------------------------
  16dfac44-0091-453a-b5e0-2e1b8cad2329 |          2 |                  3 |                  5 | oximeter_cluster | 5b815633-062c-438d-8acc-1858bb059e9e |                                              0
  69cdc490-9a9d-46e9-b0c0-c8661b0b4794 |          2 |                  3 |                  5 | oximeter_cluster | 5b815633-062c-438d-8acc-1858bb059e9e |                                              0
  79d919a7-13cd-4b47-9e9c-d15515c8532f |          2 |                  3 |                  5 | oximeter_cluster | 5b815633-062c-438d-8acc-1858bb059e9e |                                              0
  bc23843c-1b2a-49d0-9b7b-224f1ed2e892 |          2 |                  3 |                  5 | oximeter_cluster | 5b815633-062c-438d-8acc-1858bb059e9e |                                              0
```

Interestingly the `highest_seen_keeper_leader_committed_log_index` is 0 for all blueprints.

There are also no related rows in inventory:

```sql
root@[fd00:1122:3344:101::3]:32221/omicron> select * from  inv_clickhouse_keeper_membership;
  inv_collection_id | queried_keeper_id | leader_committed_log_index | raft_config
--------------------+-------------------+----------------------------+--------------
(0 rows)


Time: 4ms total (execution 4ms / network 1ms)

root@[fd00:1122:3344:101::3]:32221/omicron>
```

It appears that retrieving this inventory data from `clickhouse-admin-keeper` is not working resulting in failure to modify the keepers.

### PR DESCRIPTION
**Pull request by andrewjstone**
Also fix a bug related to DNS lookup of clickhouse-admin-keeper servers.

Fixes #6945

### CODE REVIEW

File: nexus/src/app/background/tasks/inventory_collection.rs [hunk 1]
```diff
@@ -132,19 +132,33 @@ async fn inventory_activate(
...
+        Err(err) => {
+            warn!(
+                opctx.log,
+                concat!(
+                    "Failed to lookup ClickhouseAdminKeeper in internal DNS:",
+                    " {}. Is it enabled via policy?"
+                ),
+                err
+            );
+            vec![]
```
Comment (davepacheco) [inline nexus/src/app/background/tasks/inventory_collection.rs:159]: Is it easy to distinguish here between "found nothing" vs. some other DNS error?  It seems like we'd want to treat some other DNS error the way we treat an error to look up MGS.

I don't love adding a warning-level message for a condition that's expected on many systems today.  People might reasonably think something is wrong (especially since it's going to be repeated).  Where's the place where we'd be in a position to know whether this is wrong?  Would it be in Reconfigurator, when we look at this information?  Maybe that's where the warning should go?

Comment (andrewjstone) [reply nexus/src/app/background/tasks/inventory_collection.rs:159]: > Is it easy to distinguish here between "found nothing" vs. some other DNS error? It seems like we'd want to treat some other DNS error the way we treat an error to look up MGS.

Good point, so return early in that case it's not "found nothing".

> I don't love adding a warning-level message for a condition that's expected on many systems today. People might reasonably think something is wrong (especially since it's going to be repeated). Where's the place where we'd be in a position to know whether this is wrong? Would it be in Reconfigurator, when we look at this information? Maybe that's where the warning should go?

I went back and forth on this a bunch. Originally I had this as a debug message with a comment about changing it to a warning when we expect for multi-node clickhouse to always be deployed. But even in this case, we won't deploy it immediately until reconfigurator runs, and so we'd see a few warning messages. That doesn't seem that bad. We have lots of warnings that work like that now. I changed it to a warning in this PR thinking that even with a github issue I'd be likely to forget this altogether and never change from debug to warning. All that being said, this did make me uncomfortable for the reasons you mention.

We have two extra checks we could make to see if we should have DNS records or not: One is to check the `clickhouse-policy` in the datastore. We could do that easily enough here. Again, until reconfigurator runs and actually updates DNS and it propagates, we will still see this warning. The other is to do as you suggest and check the blueprint, but we wouldn't necessarily want to do that here, and I think it would have the same problem. 

> Where's the place where we'd be in a position to know whether this is wrong? Would it be in Reconfigurator, when we look at this information? Maybe that's where the warning should go? 

I put this here particularly because I was having trouble getting back records that reconfigurator put there. This is a nice local error that tells me where to look. I think putting it in reconfigurator is somewhat misguided, and in any case we don't know *why* the records didn't come back, just that they didn't. It could be a network partition, it could be that the keepers didn't start yet, or it could be DNS.

Comment (andrewjstone) [reply nexus/src/app/background/tasks/inventory_collection.rs:159]: > Where's the place where we'd be in a position to know whether this is wrong? Would it be in Reconfigurator, when we look at this information? Maybe that's where the warning should go?

Oh, are you saying to not just check the inventory, but to actually do the dns lookups and see if they succeed in the blueprint? That's kind odd since blueprint generation only happens on demand currently.

Comment (davepacheco) [reply nexus/src/app/background/tasks/inventory_collection.rs:159]: I'm not sure, honestly.  What I was thinking is: ideally the warning should be in a place where we know both (1) whether there should be records, and (2) whether there were records.  Here we know if there were records, but not if there _should_ have been any, so I was thinking maybe the thing to do is to make sure the inventory reflects what happened and defer the warning to a place where we know if it's wrong.  I thought blueprint planning could know both of these things.  But as I write this, that doesn't make sense either, in that that's the policy _then_, not necessarily when the inventory was collected.

I guess this warning has to be heuristic in that the condition it's warning about is only wrong if the policy says the records should be there and they're not there _and_ the system comes to rest in that state (i.e., it's not in the process of making it happen).

I'm not that worried about a couple of stray warnings while things are changing, just that these will be emitted every time inventory is collected.  But I don't have a suggestion that seems obviously better.  I probably would just leave it out, figuring it's a pretty uncommon case (though I know you _just_ hit it, so that's probably not a credible argument -- but the cause there seems pretty unlikely) but I'm happy if you want to leave it in in case we see something like that again!

Comment (andrewjstone) [reply nexus/src/app/background/tasks/inventory_collection.rs:159]: Thanks for the comprehensive reply @davepacheco. Yeah, I actually think it's worth just removing at this point. I don't anticipate this breaking again and I'll have the mechanism to debug it without going to logs ;)

Once again, I appreciate the thoughtfulness!

Comment (andrewjstone) [reply nexus/src/app/background/tasks/inventory_collection.rs]: I fixed this up as discussed in [dffe13e](https://github.com/oxidecomputer/omicron/pull/6950/commits/dffe13ef30fb2235cab36f1de1901117146ca299)

I'm launching to test in a4x2 now.

Comment (andrewjstone) [reply nexus/src/app/background/tasks/inventory_collection.rs]: Testing in a4x2 was successful. Inventory retrieved.

```
KEEPER MEMBERSHIP

    queried keeper: 1
    leader_committed_log_index: 21
    raft config: 1, 2, 3, 4, 5

    queried keeper: 2
    leader_committed_log_index: 27
    raft config: 1, 2, 3, 4, 5

    queried keeper: 3
    leader_committed_log_index: 33
    raft config: 1, 2, 3, 4, 5

    queried keeper: 4
    leader_committed_log_index: 45
    raft config: 1, 2, 3, 4, 5

    queried keeper: 5
    leader_committed_log_index: 59
    raft config: 1, 2, 3, 4, 5
```

**Comment by andrewjstone** [comment]
Gentle ping @davepacheco @jgallagher

File: dev-tools/omdb/src/bin/omdb/db.rs [hunk 2]
```diff
@@ -5517,6 +5518,28 @@ fn inv_collection_print_sleds(collection: &Collection) {
...
+        println!(
+            "    leader_committed_log_index: {}",
+            k.leader_committed_log_index
+        );
+        let raft_config =
+            k.raft_config.iter().fold("".to_string(), |mut acc, id| {
+                acc.push_str(&format!("{id}, "));
+                acc
+            });
+        let s = raft_config.trim_end_matches(", ");
```
Comment (jgallagher) [inline dev-tools/omdb/src/bin/omdb/db.rs:5534]: Maybe worth using [`itertools`](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.join) here? I think it'd let this block be

```rust
let s = k.raft_config.iter().join(", ");
```

File: nexus/src/app/background/tasks/inventory_collection.rs [hunk 3]
```diff
@@ -132,19 +133,39 @@ async fn inventory_activate(
...
+            .into_iter()
+            .map(|sockaddr| {
+                let url = format!("http://{}", sockaddr);
+                let log = opctx
+                    .log
+                    .new(o!("clickhouse_admin_keeper_url" => url.clone()));
+                clickhouse_admin_keeper_client::Client::new(&url, log)
+            })
+            .collect::<Vec<_>>(),
+        Err(err) => match err {
```
Comment (jgallagher) [inline nexus/src/app/background/tasks/inventory_collection.rs:151]: Piggy-backing on the discussion on an earlier version of this PR - do you think in the fullness of time (i.e., when all systems are running multinode clickhouse) we should stop swallowing errors here and always bubble them out? If so, is that worth an omicron issue + comment referring to it so we don't forget?

**Review by jgallagher — APPROVED** [review]

File: nexus/src/app/background/tasks/inventory_collection.rs (hunk 3 above)
Comment (andrewjstone) [reply nexus/src/app/background/tasks/inventory_collection.rs:151]: Maybe? I'm honestly not sure. One issue is that we don't plan to enable clickhouse-cluster without running reconfigurator first. That means that after RSS there will still be a small gap where this will fail and prevent the rest of inventory from being collected. In any case, I do think it warrants at least a comment. Happy to open an issue as well.

Comment (andrewjstone) [reply nexus/src/app/background/tasks/inventory_collection.rs:151]: Done in [94904b1](https://github.com/oxidecomputer/omicron/pull/6950/commits/94904b1b5e11212c65ff3fd41d2f35e5df3759b8)

File: dev-tools/omdb/src/bin/omdb/db.rs (hunk 2 above)
Comment (andrewjstone) [reply dev-tools/omdb/src/bin/omdb/db.rs]: Wow, that's much simpler. TIL. Thanks!

Done in [94904b1](https://github.com/oxidecomputer/omicron/pull/6950/commits/94904b1b5e11212c65ff3fd41d2f35e5df3759b8)
