### PR TITLE
[installinator] Better error reporting of hardware scan issues

### LINKED ISSUE #3414: [installinator] Installinator fails to log or report detailed errors during hardware scan
While investigating #3413, @smklein ran `installinator debug-hardware-scan` and saw this error:

```
Dec 28 02:08:25.572 INFO found gimlet hardware, num_disks: 12, is_scrimlet: false, baseboard: Gimlet { identifier: "BRM42220081", model: "913-0000019", revision: 6 }
Dec 28 02:08:25.572 INFO ignoring U.2 disk, path: /devices/pci@ab,0/pci1de,fff9@1,1/pci1b96,0@0/blkdev@w0014EE81000BC74F,0
Dec 28 02:08:25.572 INFO ignoring U.2 disk, path: /devices/pci@0,0/pci1de,fff9@3,2/pci1b96,0@0/blkdev@w0014EE81000BC720,0
Dec 28 02:08:25.572 INFO ignoring U.2 disk, path: /devices/pci@38,0/pci1de,fff9@1,2/pci1b96,0@0/blkdev@w0014EE81000BC56F,0
Dec 28 02:08:25.572 INFO ignoring U.2 disk, path: /devices/pci@ab,0/pci1de,fff9@1,4/pci1b96,0@0/blkdev@w0014EE81000BC729,0
Dec 28 02:08:25.572 INFO Disk at /devices/pci@0,0/pci1de,fff9@1,3/pci1344,3100@0/blkdev@w00A075013274955F,0 already has a GPT
Dec 28 02:08:25.575 INFO GPT exists without Zpool: formatting zpool at /devices/pci@0,0/pci1de,fff9@1,3/pci1344,3100@0/blkdev@w00A075013274955F,0:f
Error: failed to instantiate Disk handle for M.2

Caused by:
    0: Failed to create zpool: Zpool execution error: Command [/usr/sbin/zpool create oxi_955469bb-3fb3-49b1-9c07-84ba79f72442 /devices/pci@0,0/pci1de,fff9@1,3/pci1344,3100@0/blkdev@w00A075013274955F,0:f] executed and failed with status: exit status: 1  stdout:   stderr: cannot create 'oxi_955469bb-3fb3-49b1-9c07-84ba79f72442': one or more vdevs refer to the same device
       
    1: Zpool execution error: Command [/usr/sbin/zpool create oxi_955469bb-3fb3-49b1-9c07-84ba79f72442 /devices/pci@0,0/pci1de,fff9@1,3/pci1344,3100@0/blkdev@w00A075013274955F,0:f] executed and failed with status: exit status: 1  stdout:   stderr: cannot create 'oxi_955469bb-3fb3-49b1-9c07-84ba79f72442': one or more vdevs refer to the same device
       
    2: Command [/usr/sbin/zpool create oxi_955469bb-3fb3-49b1-9c07-84ba79f72442 /devices/pci@0,0/pci1de,fff9@1,3/pci1344,3100@0/blkdev@w00A075013274955F,0:f] executed and failed with status: exit status: 1  stdout:   stderr: cannot create 'oxi_955469bb-3fb3-49b1-9c07-84ba79f72442': one or more vdevs refer to the same device
```

However, that error was neither present in the installinator logs nor reported back to wicket. It should go to both places.

### PR DESCRIPTION
**Pull request by jgallagher**
Makes three independent but related changes when installinator encounters errors scanning for disks:

1. If `installinator` exits, `smf` no longer attempts to restart it. Installinator restarting can cause some confusing output in `wicket` (e.g., seeing the same steps repeated multiple times in the UI).
2. While in the "if hardware scan failed, sleep then retry" loop, we log errors that cause us to retry.
3. We `tokio::join!()` the futures for running the engine and reporting all progress events; previously, if the engine completed unsuccessfully, we could return before the failure that cause that unsuccessful termination to be reported to wicket.

The combination of all three means if `installinator` has problems finding disks, we will now see a series of warnings and then an error on the last attempt (below run with a patched `installinator` to return a fake error on disk scan):

```
Dec 28 00:00:47.983 WARN hardware scan failed; will retry after 500ms (attempt 1 of 20), err: fake hardware failure! kaboom
Dec 28 00:00:51.260 WARN hardware scan failed; will retry after 500ms (attempt 2 of 20), err: fake hardware failure! kaboom
Dec 28 00:00:55.110 WARN hardware scan failed; will retry after 500ms (attempt 3 of 20), err: fake hardware failure! kaboom
Dec 28 00:00:59.150 WARN hardware scan failed; will retry after 500ms (attempt 4 of 20), err: fake hardware failure! kaboom
Dec 28 00:01:04.393 WARN hardware scan failed; will retry after 500ms (attempt 5 of 20), err: fake hardware failure! kaboom
Dec 28 00:01:09.926 WARN hardware scan failed; will retry after 500ms (attempt 6 of 20), err: fake hardware failure! kaboom
Dec 28 00:01:15.839 WARN hardware scan failed; will retry after 500ms (attempt 7 of 20), err: fake hardware failure! kaboom
Dec 28 00:01:22.872 WARN hardware scan failed; will retry after 500ms (attempt 8 of 20), err: fake hardware failure! kaboom
Dec 28 00:01:30.928 WARN hardware scan failed; will retry after 500ms (attempt 9 of 20), err: fake hardware failure! kaboom
Dec 28 00:01:39.974 WARN hardware scan failed; will retry after 500ms (attempt 10 of 20), err: fake hardware failure! kaboom
Dec 28 00:01:51.164 WARN hardware scan failed; will retry after 500ms (attempt 11 of 20), err: fake hardware failure! kaboom
Dec 28 00:02:01.775 WARN hardware scan failed; will retry after 500ms (attempt 12 of 20), err: fake hardware failure! kaboom
Dec 28 00:02:14.638 WARN hardware scan failed; will retry after 500ms (attempt 13 of 20), err: fake hardware failure! kaboom
Dec 28 00:02:27.363 WARN hardware scan failed; will retry after 500ms (attempt 14 of 20), err: fake hardware failure! kaboom
Dec 28 00:02:40.696 WARN hardware scan failed; will retry after 500ms (attempt 15 of 20), err: fake hardware failure! kaboom
Dec 28 00:02:55.954 WARN hardware scan failed; will retry after 500ms (attempt 16 of 20), err: fake hardware failure! kaboom
Dec 28 00:03:12.772 WARN hardware scan failed; will retry after 500ms (attempt 17 of 20), err: fake hardware failure! kaboom
Dec 28 00:03:29.491 WARN hardware scan failed; will retry after 500ms (attempt 18 of 20), err: fake hardware failure! kaboom
Dec 28 00:03:47.766 WARN hardware scan failed; will retry after 500ms (attempt 19 of 20), err: fake hardware failure! kaboom
Dec 28 00:04:07.212 WARN hardware scan failed; will retry after 500ms (attempt 20 of 20), err: fake hardware failure! kaboom
Dec 28 00:04:27.656 ERRO hardware scan failed (retries exhausted), err: fake hardware failure! kaboom
```

and the error will be visible in wicket:

install-fail

Fixes #3414.

### CODE REVIEW

File: installinator/src/dispatch.rs [hunk 1]
```diff
@@ -336,10 +336,15 @@ impl InstallOpts {
             )
             .register();
 
-        engine.execute().await.context("failed to execute installinator")?;
+        // Wait for both the engine to complete and all progress reports to be
+        // sent, then possibly return an error to our caller if either failed
+        // (but we want both to run to completion first, e.g. so that an engine
+        // failure is still reported to wicketd).
```
Comment (sunshowers) [inline installinator/src/dispatch.rs:342]: Could you add a notation here about why we don't use `try_join!`? (It's due to the fact that one of the futures will be cancelled if the other exits).

**Review by sunshowers — APPROVED** [review]
Thanks!

File: installinator/src/dispatch.rs (hunk 1 above)
Comment (jgallagher) [reply installinator/src/dispatch.rs]: Definitely - reworded in [346654b](https://github.com/oxidecomputer/omicron/pull/3429/commits/346654b6d9e74a01578cc5ebe6d6a36218bb9785)
