### PR TITLE
report clearer error when authz fails on unregistered resource

### LINKED ISSUE #1378: failure mode when you forget to register an Oso class is awful
If you add a new resource but forget to update `make_omicron_oso()` to register the new Polar class with Oso, the failure mode is awful: authz checks fail even though the policy file appears to grant the correct privileges.  ~~This seems like an Oso bug -- why does it let you register and use a policy that depends on classes that weren't registered?  But I haven't dug in.~~  The next step is probably to create a minimal Oso test case and either ask in their Slack or file an issue.  At least two of us have run into this problem and it's a bear.  This is mentioned in the new authz debugging guide (#1376).

### PR DESCRIPTION
**Pull request by davepacheco**
Fixes #1378.  It sounds like Oso may also address this soon but I don't really know when and this is pretty easy to add.

### CODE REVIEW

**Comment by davepacheco** [comment]
Reminder to myself: I should update #1376 if/when this change lands.

File: nexus/src/authz/context.rs [hunk 1]
```diff
@@ -77,8 +81,29 @@ impl Context {
...
+        // What's likely happened is that somebody forgot to register the class
+        // with Oso.  This failure mode is very hard to debug because the Rust
+        // code generates a valid Polar snippet and there's a working PolarClass
+        // impl -- it's just that neither was ever given to Oso.  Make this
+        // failure mode more debuggable by reporting a 500 with a clear error
+        // message.  After all, this is a bug.  (We could panic, since it's more
+        // of a programmer error than an operational error.  But unlike most
+        // programmer errors, the nature of the problem and the blast radius are
+        // well understood, so we may as well avoid crashing.)
+        let class_name = &Resource::get_polar_class().name;
```
Comment (plotnick) [inline nexus/src/authz/context.rs:100]: I think doing the check here on `name` is fine for our use case, because we don't ever expect to reuse class names. But I think technically it's the `type_id` that's the true unique identifier for a Polar class.

**Review by plotnick — APPROVED** [review]
This looks great to me. I have two minor suggestions, and please feel free to ignore either or both.

1. Now that we're checking for duplicate class registration, it might be nice to test that, too. But the test for an unregistered class is definitely the more important one.
2. The class registration logic is short, but appears in two distinct places (lines 60-61 and 101-106 of `authz/oso_generic.rs`). That's just enough to make me wish for a `register_class` method on `OsoInit` that includes the duplicate check and `context`.

Thanks for doing this, it definitely files down an easy-to-hit sharp edge.

File: nexus/src/authz/context.rs (hunk 1 above)
Comment (davepacheco) [reply nexus/src/authz/context.rs:100]: That's interesting.  I guess if two things share a `type_id`, they almost certainly share a `name`.  But two things could share a name but have different types.  I assumed the class name had to be unique in order for Oso to map it to the corresponding actor or resource in Polar.  But I guess in other languages it's possible to use classes that have never been registered and aren't explicitly in the Polar file (because, say, they're subclasses of things that _are_ registered and named in the Polar file), and those wouldn't have to have unique names.

As you said, in our case, I think we expect them to be unique so I think I'd like to continue enforcing that.

**Comment by davepacheco** [comment]
> Now that we're checking for duplicate class registration, it might be nice to test that, too. But the test for an unregistered class is definitely the more important one.
> The class registration logic is short, but appears in two distinct places (lines 60-61 and 101-106 of authz/oso_generic.rs). That's just enough to make me wish for a register_class method on OsoInit that includes the duplicate check and context.

It'd be nice to address both of these... I think the best way is to turn `OsoInit` into something more first-class.  It'll wind up being a fair bit more code, but still pretty simple and better tested.  I'm going to give it a shot and see what it looks like.

**Review by plotnick — APPROVED** [review]
I think that turned out really nice! I find `make_omicron_oso` to be much more readable with the new builder.
