### PR TITLE
Background task: complete never-completed audit log entries

### LINKED ISSUE #8817: Audit log: background job to clean up entries that never completed
Followup to #7339.

Unlike with audit log entry initialization (because we bail if it fails), we do not have a guarantee that audit log completion runs successfully because we don't want to turn every loggable operation into a saga to enable rollbacks. While failures should be unlikely (and we do have retries in place), they are still possible, and we _really_ don't want there to be anything missing from the audit log.

To deal with this, we need a background job to complete any rows hanging around uncompleted for longer than N minutes or hours. Because these will not have success or error info about the logged operation, they will use the `Timeout` variant, which was already added for this purpose in #7339.

https://github.com/oxidecomputer/omicron/blob/6ab7e96e87c47944a73d31429dec4afdb545ae22/schema/crdb/dbinit.sql#L5776-L5783

https://github.com/oxidecomputer/omicron/blob/6ab7e96e87c47944a73d31429dec4afdb545ae22/nexus/db-model/src/audit_log.rs#L78-L81

https://github.com/oxidecomputer/omicron/blob/6ab7e96e87c47944a73d31429dec4afdb545ae22/nexus/types/src/external_api/views.rs#L1603-L1612

### PR DESCRIPTION
**Pull request by david-crespo**
Closes #8817 

The most important thing about an audit log is that every event you care about is in there. This PR adds a job to make sure requests that never complete (e.g., because Nexus crashed in the middle) appear in the audit log after some timeout.

The audit log gets written in two steps. At the beginning of a request we initialize the log entry row. If this fails, the request fails. This guarantees we never miss an initialization. Then, at the end of the request, we "complete" the row with the result of the operation and a `time_completed`. The audit log list API response is ordered by `time_completed`. This lets us guarantee that if you retrieve a chunk of the audit log that is fully in the past, it will never change — you never have to fetch that chunk of the log again. But this requires thate entries do not appear in the log until they are completed.

Completion can fail for variety of hopefully very rare reasons. It seemed unreasonably complicated to guarantee completion by rolling back whatever operation happened on a failed completion. Instead, the idea was that we would run a job that cleans up incomplete rows after a long enough amount of time that it's very unlikely the request will complete. When we clean up such rows, we don't know what actually happened to the request, so we have to give it a special `result_kind` of `timeout` (as opposed to `success` or `error`). 

https://github.com/oxidecomputer/omicron/blob/3d2d0c17002ef6291e1b4f88755ac7f7ba90dbd1/nexus/db-model/src/audit_log.rs#L275-L283

In the API response this becomes `AuditLogEntryResult::Unknown` because I feel like "timeout" is an implementation detail and makes it sound like the operation itself timed out.

https://github.com/oxidecomputer/omicron/blob/3d2d0c17002ef6291e1b4f88755ac7f7ba90dbd1/nexus/db-model/src/audit_log.rs#L413-L415

## How often are log entries left incomplete?

Fortunately, this should be a very rare event — I checked on dogfood and there were around 200k rows in the table and there was exactly 1 incomplete `disk_create` call from October 2025. Need to check on the colo rack.

## Config options

All three live in `[background_tasks.audit_log_timeout_incomplete]` in
the Nexus config (`AuditLogTimeoutIncompleteConfig` in `nexus_config.rs`):

* `period_secs` — how often the background task activates (currently 600 = 10 min)
* `timeout_secs` — how old an incomplete entry must be before it gets timed out (default 14400 = 4 hours)
* `max_update_per_activation` — max rows updated per activation (currently 1000), following the naming convention from `session_cleanup.max_delete_per_activation`

On the timeout, I think 4 hours is pretty conservative. My worry is that we could have a legitimate API call that takes an hour or two because it's a post of a giant file or something. I don't know how reasonable that worry is. This timeout could probably go down to two hours or an hour.

On the interval, 10 minutes seems maybe overkill for something that happens once every 5 months? But it's just one query, basically.

## Claude skill for adding background tasks

After #10009 I had Claude write the `add-background-task` skill and used it to make this one. It was pretty good, so I think it's probably worth checking in.

### CODE REVIEW

File: schema/crdb/audit-log-incomplete-timeout/up01.sql [hunk 1]
```diff
@@ -0,0 +1,4 @@
+-- Supports "find stale incomplete rows ordered by time_started".
+CREATE INDEX IF NOT EXISTS audit_log_incomplete_by_time_started
+    ON omicron.public.audit_log (time_started, id)
+    WHERE time_completed IS NULL;
```
Comment (david-crespo) [inline schema/crdb/audit-log-incomplete-timeout/up01.sql:4]: The robots in my employ pointed out that this index does have a cost — every single request that comes through causes this index to be updated because the audit log entry for it has `time_completed` null while the operation is in progress. That's probably worth it — otherwise I think the job would not work as written because it would have to do a table scan to find the incomplete rows.

File: nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs [hunk 2]
```diff
@@ -0,0 +1,253 @@
...
+        };
+
+        if timed_out > 0 {
+            slog::warn!(
+                &opctx.log,
+                "audit log timeout: timed out {timed_out} incomplete \
+                 entries (may indicate Nexus crashes or bugs)";
+                "cutoff" => %cutoff,
+                "limit" => self.max_update_per_activation,
+            );
```
Comment (david-crespo) [inline nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs:82]: I figured this should `warn!` since things showing up here should be quite unusual.

File: nexus/db-queries/src/db/datastore/audit_log.rs [hunk 3]
```diff
@@ -115,23 +123,73 @@ impl DataStore {
     ) -> UpdateResult<()> {
         use nexus_db_schema::schema::audit_log;
         opctx.authorize(authz::Action::CreateChild, &authz::AUDIT_LOG).await?;
-        diesel::update(audit_log::table)
+        let rows = diesel::update(audit_log::table)
             .filter(audit_log::id.eq(entry.id))
+            .filter(audit_log::time_completed.is_null())
```
Comment (david-crespo) [inline nexus/db-queries/src/db/datastore/audit_log.rs:127]: This is really important, otherwise in the bizarro world situation where the request actually does finish after the row has been timed out, completing it would change its `time_completed`, violating the Rules of Audit Log. See the comment above.

File: dev-tools/omdb/src/bin/omdb/nexus.rs [hunk 4]
```diff
@@ -2318,6 +2325,16 @@ fn print_task_read_only_region_replacement_start(details: &serde_json::Value) {
...
+fn print_task_reconfigurator_config_watcher(details: &serde_json::Value) {
+    match details.get("config_updated").and_then(|v| v.as_bool()) {
+        Some(updated) => println!("    config updated: {updated}"),
+        None => eprintln!(
+            "warning: failed to interpret task details: {:?}",
+            details
+        ),
+    }
+}
+
```
Comment (david-crespo) [inline dev-tools/omdb/src/bin/omdb/nexus.rs:2342]: This task isn't changed here but it was causing the tests to be flaky for me locally depending on whether I ran one test or the whole module.

File: nexus/db-queries/src/db/datastore/audit_log.rs [hunk 5]
```diff
@@ -115,23 +123,73 @@ impl DataStore {
...
+        let completion: AuditLogCompletionUpdate =
+            AuditLogCompletion::Timeout.into();
+
+        diesel::update(audit_log::table)
+            .filter(audit_log::id.eq_any(subquery))
+            .set(completion)
+            .execute_async(&*self.pool_connection_authorized(opctx).await?)
+            .await
+            .map_err(|e| public_error_from_diesel(e, ErrorHandler::Server))
+    }
```
Comment (david-crespo) [inline nexus/db-queries/src/db/datastore/audit_log.rs:181]: This is the core of the task: for any audit log entries older than `cutoff` with null `time_completed`, mark those as timed out. In practice the ordering and limit should not matter because the number of timed out requests should be small.

**Comment by david-crespo** [comment]
The numbers from colo: 5M rows in the table, only two (!!!!!) incomplete rows.


```
root@[fd00:1122:3344:116::3]:32221/omicron> select count(*) from omicron.public.audit_log;
   count
-----------
  4898486
(1 row)

root@[fd00:1122:3344:116::3]:32221/omicron> select count(*) from omicron.public.audit_log where time_started > now() - interval '7days';
  count
----------
  385581
(1 row)

root@[fd00:1122:3344:116::3]:32221/omicron> select count(*) from omicron.public.audit_log where time_completed is null;
  count
---------
      2
(1 row)

root@[fd00:1122:3344:116::3]:32221/omicron> select time_started, operation_id from omicron.public.audit_log where time_completed is null;
          time_started          | operation_id
--------------------------------+---------------
  2026-03-02 23:16:32.159074+00 | login_saml
  2025-10-18 15:01:21.671874+00 | login_saml
(2 rows)
```

File: nexus/examples/config.toml [hunk 6]
```diff
@@ -175,6 +175,9 @@ trust_quorum.period_secs = 60
 attached_subnet_manager.period_secs = 60
 session_cleanup.period_secs = 300
 session_cleanup.max_delete_per_activation = 10000
+audit_log_timeout_incomplete.period_secs = 600
+audit_log_timeout_incomplete.timeout_secs = 14400
+audit_log_timeout_incomplete.max_update_per_activation = 1000
```
Comment (david-crespo) [inline nexus/examples/config.toml]: I wonder if it's even necessary to make these tunable in the config as opposed to hard coded in the task definition. I guess it's nice to be able to change them without making a code change, but will we really have to?

File: nexus/db-queries/src/db/datastore/audit_log.rs [hunk 7]
```diff
@@ -371,4 +429,104 @@ mod tests {
...
+            .await
+            .expect("could not set time_started");
+    }
+
+    /// A late completion of an already-timed-out entry should be a no-op.
+    /// Once an entry is timed out and visible in the audit log, it's part
+    /// of the immutable record. Overwriting it would change its timestamp
+    /// and violate the guarantee that the past doesn't change.
+    #[tokio::test]
+    async fn test_audit_log_timeout_then_late_completion() {
```
Comment (david-crespo) [inline nexus/db-queries/src/db/datastore/audit_log.rs:469]: I think this test belongs here rather than the timeout task because it's really about what `datastore.audit_log_entry_complete()` does with an already timed out row. I got rid of the other tests that were redundant with the one in the task file, though.

File: nexus/examples/config.toml (hunk 6 above)
Comment (hawkw) [reply nexus/examples/config.toml]: :woman_shrugging: i don't really care about being able to tune these in the config, but it's fine to leave them since you've already done it?

File: nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs [hunk 8]
```diff
@@ -28,29 +28,16 @@ impl AuditLogTimeoutIncomplete {
...
-                    cutoff: Utc::now(),
-                    max_timed_out_per_activation: self
-                        .max_timed_out_per_activation,
-                    error: Some(msg),
-                };
-            }
-        };
-
-        let cutoff = Utc::now() - timeout_delta;
+        let cutoff = Utc::now() - self.timeout;
```
Comment (hawkw) [inline nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs]: should this fail if it's out of range?

File: nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs [hunk 9]
```diff
@@ -0,0 +1,291 @@
...
+
+impl AuditLogTimeoutIncomplete {
+    pub fn new(
+        datastore: Arc<DataStore>,
+        timeout: Duration,
+        max_timed_out_per_activation: u32,
+    ) -> Self {
+        let Ok(timeout) = TimeDelta::from_std(timeout) else {
+            panic!(
+                "invalid timeout {timeout:?} \
```
Comment (hawkw) [inline nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs]: it would be nice if we said the name of the config file key here, rather than just "invalid timeout"

File: nexus/db-queries/src/db/datastore/audit_log.rs [hunk 10]
```diff
@@ -115,23 +123,73 @@ impl DataStore {
...
+    ) -> Result<usize, omicron_common::api::external::Error> {
+        use nexus_db_schema::schema::audit_log;
+        opctx.authorize(authz::Action::CreateChild, &authz::AUDIT_LOG).await?;
+
+        // Diesel's ValidSubselect doesn't allow a subquery from the same
+        // table being updated, so we alias audit_log for the subquery.
+        let audit_log_sub =
+            diesel::alias!(nexus_db_schema::schema::audit_log as audit_log_sub);
+
+        let subquery = audit_log_sub
```
Comment (hawkw) [inline nexus/db-queries/src/db/datastore/audit_log.rs]: i might give this a more semantically meaningful name --- it's selecting the timed-out rows to update, right?

File: nexus/db-queries/src/db/datastore/audit_log.rs [hunk 11]
```diff
@@ -106,7 +107,14 @@ impl DataStore {
...
 
-    // set duration and result on an existing entry
+    /// Complete an audit log entry with the request's outcome.
+    ///
+    /// The `time_completed IS NULL` filter is critical: once an entry has been
+    /// completed — whether by the normal request path or by the background
+    /// timeout task — it is part of the immutable audit log. Overwriting it
+    /// would change its `time_completed` timestamp, shifting its position in
+    /// the `(time_completed, id)` pagination order and violating the guarantee
+    /// that past query results are stable.
```
Comment (hawkw) [inline nexus/db-queries/src/db/datastore/audit_log.rs]: this doesn't feel like API docs to me --- i think it should go in the place where you're actually setting that filter?

File: nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs (hunk 8 above)
Comment (david-crespo) [reply nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs]: By out of range, do you mean overflow? In a247d5423aeee47245f2b56e55e79391768fa855 I used `checked_sub_signed` and `expect()`, but it seems like an overflow would have panicked anyway, just with a slightly less direct error message.

File: nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs [hunk 12]
```diff
@@ -42,7 +43,9 @@ impl AuditLogTimeoutIncomplete {
         &mut self,
         opctx: &OpContext,
     ) -> AuditLogTimeoutIncompleteStatus {
-        let cutoff = Utc::now() - self.timeout;
+        let cutoff = Utc::now()
+            .checked_sub_signed(self.timeout)
+            .expect("now - timeout overflowed (timeout_secs is too large)");
```
Comment (hawkw) [inline nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs:48]: hm, should we panic the whole nexus here, or just fail the activation? is the implication that the assert when we construct the background task should stop this from happening, because i don't think it will (if NTP is extremely un-synced i guess)

File: nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs (hunk 8 above)
Comment (hawkw) [reply nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs]: I was thinking more that if the subtraction overflows, maybe we should return an error and just not do anything, instead of a sploding. :woman_shrugging:

File: .claude/skills/add-background-task/SKILL.md [hunk 13]
```diff
@@ -0,0 +1,97 @@
...
+
+### 2. Task implementation (`nexus/src/app/background/tasks/<name>.rs`)
+
+Create the task module. The struct holds whatever state it needs (typically `Arc<DataStore>` plus config). Implement `BackgroundTask::activate` by delegating to an `async fn actually_activate(&mut self, opctx) -> YourStatus` method, then serialize the status to `serde_json::Value`. The `actually_activate` pattern makes unit testing easy without going through the trait.
+
+Logging conventions: `debug` when there's nothing to do, `info` when routine work was done, `warn` when the work done indicates something is wrong (e.g., cleaning up after a crash), `error` on failure. Log errors as structured fields with the `; &err` slog syntax (which uses the `SlogInlineError` trait), not by interpolating into the message string. For the error string in the status struct, use `InlineErrorChain::new(&err).to_string()` (from `slog_error_chain`) to capture the full cause chain. Status error strings should not repeat the task name — omdb already shows which task you're looking at.
```
Comment (hawkw) [inline .claude/skills/add-background-task/SKILL.md:28]: Some of this (the stuff about slog error chains) feels like maybe something `slog` should always be instructed to do, not just in bg tasks? If there's another place to put that advice that will cause claude to use it any time it writes code in this repo, that could be a good idea.

File: .claude/skills/add-background-task/SKILL.md [hunk 14]
```diff
@@ -0,0 +1,97 @@
...
+
+These are the touch points for adding a new background task. Follow them in order.
+
+### 1. Status type (`nexus/types/src/internal_api/background.rs`)
+
+Define a struct for the task's activation status. Derive `Clone, Debug, Deserialize, Serialize, PartialEq, Eq`. For errors, use `Option<String>` if the task can only fail in one way per activation, or `Vec<String>` if it accumulates multiple independent errors. Match what similar tasks do.
+
+### 2. Task implementation (`nexus/src/app/background/tasks/<name>.rs`)
+
+Create the task module. The struct holds whatever state it needs (typically `Arc<DataStore>` plus config). Implement `BackgroundTask::activate` by delegating to an `async fn actually_activate(&mut self, opctx) -> YourStatus` method, then serialize the status to `serde_json::Value`. The `actually_activate` pattern makes unit testing easy without going through the trait.
```
Comment (hawkw) [inline .claude/skills/add-background-task/SKILL.md]: i _absolutely adore_ the fact that the stupid eliza-ism of `actually_activate()` is now being blasted directly into Claude's brain for all of eternity :)

File: .claude/skills/add-background-task/SKILL.md [hunk 15]
```diff
@@ -0,0 +1,97 @@
...
+
+### 9. Datastore method (if needed)
+
+If the task needs a new query, add it in the appropriate `nexus/db-queries/src/db/datastore/` file. Prefer the Diesel typed DSL over raw SQL (`diesel::sql_query`) for queries and test helpers. Only fall back to raw SQL when the DSL genuinely can't express the query.
+
+If the task modifies rows that other code paths also modify, think about races: what happens if both run concurrently on the same row? Both paths should typically guard their writes so only one succeeds.
+
+### 10. omdb output (`dev-tools/omdb/src/bin/omdb/nexus.rs`)
+
+Add a `print_task_<name>` function and wire it into the match in `print_task_details` (alphabetical order). Import the status type. Use the `const_max_len` + `WIDTH` pattern to align columns:
```
Comment (hawkw) [inline .claude/skills/add-background-task/SKILL.md:75]: Wow _another_ thing I did that one time has now been determined to be a Best Practice that the robot should do! This _almost_ makes me feel okay about being replaced! :D

File: .claude/skills/add-background-task/SKILL.md (hunk 14 above)
Comment (hawkw) [reply .claude/skills/add-background-task/SKILL.md]: Also, perhaps we should tell it that sometimes I've found it's sometimes better to pass an `&mut WhateverStatus` _into_ `actually_activate()` --- in particular, I like to do this when I'm doing something that can complete partially, and then return an error. This way, you can record whatever has completed into the status, and then bail out using `?` later, but the status has still recorded whatever you already did.

File: nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs (hunk 12 above)
Comment (hawkw) [reply nexus/src/app/background/tasks/audit_log_timeout_incomplete.rs:48]: for the record i think this is highly unlikely regardless and i think i'm probably just being annoying about it at this point

File: .claude/skills/add-background-task/SKILL.md (hunk 13 above)
Comment (david-crespo) [reply .claude/skills/add-background-task/SKILL.md:28]: A checked-in `CLAUDE.md` for the repo would be a good spot for that. I've held off making one because the work people do in here is so varied that it's hard to write down truly general guidelines.

Comment (hawkw) [reply .claude/skills/add-background-task/SKILL.md:28]: yeah. i feel like there is a lot of stuff that _everyone_ would want it to know, such like "don't use the logger incorrectly" and "remember to run `cargo xtask clippy` instead of some other thing" and "if you run the tests using `cargo test` rather than `cargo nextest`, most of them will not work"
