### PR TITLE
Verify UUIDs before performing switch port settings queries

### LINKED ISSUE #6462: need to validate bgp config UUID when adding/setting bgp peer
I was using a4x2 with:
- omicron 02303a6f03b19b8476fc4bc4a65d6b4e29585c6c
- Oxide CLI from branch in https://github.com/oxidecomputer/oxide.rs/pull/795 commit `98f000bfc68b375e49888ff6946ffa988092084e` with merge from https://github.com/oxidecomputer/oxide.rs/pull/808 commit `457db93dc13a09d45df09597dd0a3c1becd0b086`, resolved merge conflicts by hand.

I tried to add/set (add has been renamed to set) a bgp peer that I already deleted previously (so the bgp peer did not exist at the time), but at add/set time I supplied a bad UUID for the `--bgp-config` flag value, where the UUID supplied had the last digit increased by 1 from the real UUID value.  It accepted the bad value with no complaints.
```
$ oxide system networking bgp peer set --rack 2d1fe615-0fd9-485d-8898-cd024883d222 --switch switch1 --port qsfp0 --addr 169.254.40.1 --bgp-config c722f444-9e03-4c07-8a58-89ed53c43dd6
```

This command then panicked when trying to show the bgp peers (and static route) for `switch1/qsfp0`:
```
$ oxide system networking switch-port-settings show
switch0/qsfp0
=============
Autoneg  Fec   Speed
false    None  Speed100G

Address          Lot            VLAN
169.254.10.2/30  initial-infra  None
169.254.30.2/30  initial-infra  None

BGP Peer      Config   Export          Import          Communities  Connect Retry  Delay Open  Enforce First AS  Hold Time  Idle Hold Time  Keepalive  Local Pref  Md5 Auth  Min TTL  MED   Remote ASN  VLAN
169.254.10.1  as65547  [no filtering]  [no filtering]  []           3              3           false             6          0               2          None        None      None     None  None        None
169.254.30.1  as65547  [no filtering]  [no filtering]  []           3              3           false             6          0               2          None        None      None     None  None        None

Destination  Nexthop  Vlan  Preference

switch1/qsfp0
=============
Autoneg  Fec   Speed
false    None  Speed100G

Address          Lot            VLAN
169.254.20.2/30  initial-infra  None
169.254.40.2/30  initial-infra  None

thread 'tokio-runtime-worker' panicked at cli/src/cmd_net.rs:1292:61:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at cli/src/main.rs:109:10:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(129), ...)
```

The current workaround is to just overwrite with correct UUID.
```
$ oxide system networking bgp peer set --rack 2d1fe615-0fd9-485d-8898-cd024883d222 --switch switch1 --port qsfp0 --addr 169.254.40.1 --bgp-config c722f444-9e03-4c07-8a58-89ed53c43dd5
```

Output is ok after the workaround:
```
$ oxide system networking switch-port-settings show
switch0/qsfp0
=============
Autoneg  Fec   Speed
false    None  Speed100G

Address          Lot            VLAN
169.254.10.2/30  initial-infra  None
169.254.30.2/30  initial-infra  None

BGP Peer      Config   Export          Import          Communities  Connect Retry  Delay Open  Enforce First AS  Hold Time  Idle Hold Time  Keepalive  Local Pref  Md5 Auth  Min TTL  MED   Remote ASN  VLAN
169.254.10.1  as65547  [no filtering]  [no filtering]  []           3              3           false             6          0               2          None        None      None     None  None        None
169.254.30.1  as65547  [no filtering]  [no filtering]  []           3              3           false             6          0               2          None        None      None     None  None        None

Destination  Nexthop  Vlan  Preference

switch1/qsfp0
=============
Autoneg  Fec   Speed
false    None  Speed100G

Address          Lot            VLAN
169.254.20.2/30  initial-infra  None
169.254.40.2/30  initial-infra  None

BGP Peer      Config   Export          Import          Communities  Connect Retry  Delay Open  Enforce First AS  Hold Time  Idle Hold Time  Keepalive  Local Pref  Md5 Auth  Min TTL  MED   Remote ASN  VLAN
169.254.20.1  as65547  [no filtering]  [no filtering]  []           3              3           false             6          3               2          None        None      None     None  None        None

Destination  Nexthop          Vlan  Preference
240.0.0.0/4  169.254.30.1/32  0     10
```

### PR DESCRIPTION
**Pull request by internet-diglett**
In #6462, it was noted that if you provided a bad uuid for a BGP config when setting a BGP peer, the api would accept it without reporting and error, which would consequently break subsequent interactions that relied on BGP configuration data.

This was due to us not validating the uuid before applying subsequent updates to the switch port configuration tables. This PR adds UUID validation to all transactions in the switch port configuration database queries.

Testing
---

We now return an error when an invalid bgp config id is provided:

```
oxide --profile a4x2 system networking bgp peer set --rack d44a1d52-1586-4627-863d-7e7553d393dd --switch switch1 --port qsfp0 --addr 169.254.40.1 --bgp-config c722f444-9e03-4c07-8a58-89ed53c43dd6

Error Response: status: 400 Bad Request; headers: {"content-type": "application/json", "x-request-id": "bc9d158e-be15-457c-8334-ea8111095ad7", "content-length": "129", "date": "Thu, 06 Mar 2025 05:05:44 GMT"}; value: Error { error_code: Some("InvalidRequest"), message: "BGP config not found", request_id: "bc9d158e-be15-457c-8334-ea8111095ad7" }
```

Related
--
Closes #6462

### CODE REVIEW

**Comment by internet-diglett** [comment]
@elaine-oxide I tested this fix following the steps you listed in #6462

File: nexus/db-queries/src/db/datastore/switch_port.rs [hunk 1]
```diff
@@ -1527,10 +1550,23 @@ async fn do_switch_port_settings_delete(
     use db::schema::switch_port_settings;
     use db::schema::switch_port_settings::dsl as port_settings_dsl;
     let id = match selector {
-        NameOrId::Id(id) => *id,
+        // TODO: perform lookup here
```
Comment (elaine-oxide) [inline nexus/db-queries/src/db/datastore/switch_port.rs:1553]: Do we still need this?

File: nexus/db-queries/src/db/datastore/switch_port.rs [hunk 2]
```diff
@@ -1134,7 +1134,6 @@ async fn do_switch_port_settings_create(
     err: OptionalError<SwitchPortSettingsCreateError>,
```
Comment (elaine-oxide) [inline nexus/db-queries/src/db/datastore/switch_port.rs:1134]: Is line 406 ok?  Just checking for consistency for occurrences of the pattern `NameOrId::Id(id) =>`.

**Review by elaine-oxide — COMMENTED** [review]
I don't see anything self-inconsistent.  See comments.

File: nexus/db-queries/src/db/datastore/switch_port.rs (hunk 2 above)
Comment (internet-diglett) [reply nexus/db-queries/src/db/datastore/switch_port.rs:1134]: We should probably change that one too

Comment (internet-diglett) [reply nexus/db-queries/src/db/datastore/switch_port.rs:1150]: fixed

File: nexus/db-queries/src/db/datastore/switch_port.rs (hunk 1 above)
Comment (internet-diglett) [reply nexus/db-queries/src/db/datastore/switch_port.rs]: no, removed

**Review by elaine-oxide — COMMENTED** [review]
Latest commit looks self-consistent to me. :)

**Review by smklein — APPROVED** [review]
