### PR TITLE
Don't block Nexus startup on successful IP allowlist plumbing

### LINKED ISSUE #1791: Handle multiple failures in sled-agent firewall rule requests
When firewall rules are sent to multiple sleds, only a single error is currently handled (as of PR #1636). We should have some form of long-running, retry-style error handling in case something goes wrong on more than one sled.

_Originally raised by @bnaecker in https://github.com/oxidecomputer/omicron/pull/1636#discussion_r987211916_

### PR DESCRIPTION
**Pull request by bnaecker**
- Remove the default firewall rule for Nexus that allows HTTP(S).
- Add data migration that removes the rule from existing systems.
- Make IP allowlist plumbing best-effort on Nexus startup. This prevents blocking the Nexus external API servers from starting up if we fail to reach any sled. Instead, we rely on OPTE's builtin default-deny firewall rule to keep the API servers unreachable until the allowlist plumbing is done. That _could_ happen right away, if the sled-agents are reachable, but it might not happen until another background task run. But all the Nexus instances running on reachable sleds will be available when it does run.
- Return all errors while propagating firewall rules to sleds. Fixes #1791. Log these during Nexus external server startup, and in the background task, and also return them in the OMDB task details.

### CODE REVIEW

**Comment by bnaecker** [comment]
Fixes https://github.com/oxidecomputer/customer-support/issues/972

**Comment by bnaecker** [comment]
I tested this a bit on `dublin`. I deployed the commit 7ed790c1a423ac2fe0e9552d0d2daaddca2773dc using `rkadm`. The first thing we note is that it "works", in the sense that the OPTE firewall rule actually reflects the IP allowlist:

```
2F8JEXDK # zoneadm list | grep nexus
oxz_nexus_b7f7dca6-e9ce-4933-aea9-9bbff3636900
2F8JEXDK # zlogin oxz_nexus_b7f7dca6-e9ce-4933-aea9-9bbff3636900 dladm
LINK        CLASS     MTU    STATE    BRIDGE     OVER
opte0       misc      1500   up       --         --
oxControlService14 vnic 9000 up       --         ?
2F8JEXDK # opteadm dump-layer -p opte0 firewall
Port opte0 - Layer firewall
======================================================================
Inbound Flows
----------------------------------------------------------------------
PROTO  SRC IP  SPORT/TY  DST IP  DPORT  HITS  ACTION

Outbound Flows
----------------------------------------------------------------------
PROTO  SRC IP  SPORT/TY  DST IP  DPORT  HITS  ACTION

Inbound Rules
----------------------------------------------------------------------
ID    PRI    HITS  PREDICATES                               ACTION
1155  65534  0     inner.ip.proto=TCP                       "Stateful Allow"
                   inner.ulp.dst=80,=443

1154  65534  0     inner.icmp.type=time exceeded            "Stateful Allow"
1153  65534  0     inner.icmp.type=message redirect         "Stateful Allow"
1152  65534  0     inner.icmp.type=destination unreachable  "Stateful Allow"
                   inner.icmp.code∈(3..=4)

DEF   --     0     --                                       "deny"

Outbound Rules
----------------------------------------------------------------------
ID   PRI  HITS  PREDICATES  ACTION
DEF  --   0     --          "stateful allow"

```

So the OPTE FW has a default-deny rule, then rule 1155 is our injected IP allowlist, letting Nexus receive HTTP(S) traffic from anywhere. The old default VPC firewall rule for Nexus inbound traffic isn't in the database anymore:

```
root@oxz_switch1:~# omdb -w db sql
note: database URL not specified.  Will search DNS.
note: (override with --db-url or OMDB_DB_URL)
note: using DNS from system config (typically /etc/resolv.conf)
note: (if this is not right, use --dns-server to specify an alternate DNS server)
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB OSS v22.1.22-64-g86fdbfca06 (x86_64-pc-solaris2.11, built 2026/03/18 01:49:10, go1.22.11) (same version as client)
# Cluster ID: 86d73345-4b3b-4ede-a315-ffd61b4b9bfc
#
# Enter \? for a brief introduction.
#
root@[fd95:2333:df54:104::3]:32221/omicron> select name, filter_hosts, filter_ports, filter_protocols from vpc_firewall_rule where vpc_id = '001de000-074c-4000-8000-000000000000' and direction = 'inbound';
          name         | filter_hosts | filter_ports |       filter_protocols
-----------------------+--------------+--------------+--------------------------------
  nexus-icmp           | NULL         | NULL         | {"icmp:3,3-4",icmp:5,icmp:11}
  external-dns-inbound | NULL         | {53}         | {udp}
  nexus-icmp           | NULL         | NULL         | {"icmp:3,3-4",icmp:5,icmp:11}
  external-dns-inbound | NULL         | {53}         | {udp}
  external-dns-inbound | NULL         | {53}         | {udp}
  nexus-icmp           | NULL         | NULL         | {"icmp:3,3-4",icmp:5,icmp:11}
(6 rows)


Time: 2ms total (execution 1ms / network 1ms)
```

So the basic setup of this commit works, removing the default rule and injecting the rule based on the allow list instead. Next I'm going to test the main point of this fix, whether it blocks Nexus startup if any one of the sleds isn't reachable.

**Comment by bnaecker** [comment]
Ok, I used the repro steps listed in the customer support ticket. I logged into sled 17 and stopped its sled-agent:

```
root@oxz_switch1:~# pilot host exec -c 'zoneadm list | grep nexus || true' 14-18
14  2F8JEXDK           ok: oxz_nexus_b7f7dca6-e9ce-4933-aea9-9bbff3636900
15  BRM27230037        ok:
16  BRM23230018        ok: oxz_nexus_47d20796-db47-419d-a3ca-c4f7b2a01868
17  BRM23230010        ok: oxz_nexus_52025930-a214-4119-96bd-b3060b3bd531
root@oxz_switch1:~# pilot host login 17

    #####
   ##   ##
  ##   # ##  ##   ##
  ##  #  ##   ## ##     Oxide Computer Company
  ## #   ##    ###      Engineering
   ##   ##    ## ##
    #####    ##   ##    Compute Sled

BRM23230010 # pgrep sled-agent
657
BRM23230010 # svcadm disable sled-agent
BRM23230010 # logout
```

Then I restarted the Nexus SMF service on _another_ sled:

```
root@oxz_switch1:~# pilot host login 14

    #####
   ##   ##
  ##   # ##  ##   ##
  ##  #  ##   ## ##     Oxide Computer Company
  ## #   ##    ###      Engineering
   ##   ##    ## ##
    #####    ##   ##    Compute Sled

2F8JEXDK # zlogin oxz_nexus_b7f7dca6-e9ce-4933-aea9-9bbff3636900
[Connected to zone 'oxz_nexus_b7f7dca6-e9ce-4933-aea9-9bbff3636900' pts/3]
Last login: Wed Apr 22 22:07:49 on pts/3
The illumos Project     helios-2.0.23894        April 2026
root@oxz_nexus_b7f7dca6:~# svcs nexus
STATE          STIME    FMRI
online         20:49:13 svc:/oxide/nexus:default
root@oxz_nexus_b7f7dca6:~# svcadm restart nexus
```

I confirmed that Nexus correctly _attempted_ the allowlist plumbing, but that it did not block the service from continuing:

```
root@oxz_nexus_b7f7dca6:~# grep allowlist $(svcs -L nexus)
{"msg":"failed to push initial IP allowlist to sled-agent; background task will retry","v":0,"name":"nexus","level":50,"time":"2026-04-22T22:34:08.876708788Z","hostname":"oxz_nexus_b7f7dca6-e9ce-4933-aea9-9bbff3636900","pid":3791,"component":"nexus","component":"ServerContext","name":"b7f7dca6-e9ce-4933-aea9-9bbff3636900","file":"nexus/src/app/allow_list.rs:175","error":"InternalError { internal_message: \"Communication Error: error sending request for url (http://[fd95:2333:df54:103::1]:12345/vpc/001de000-074c-4000-8000-000000000000/firewall/rules)\" }","sled_id":"1c1688fe-87c1-415e-b649-502c2dc705f0"}
root@oxz_nexus_b7f7dca6:~# tail -F $(svcs -L nexus) | looker
22:34:12.666Z DEBG b7f7dca6-e9ce-4933-aea9-9bbff3636900 (ServerContext): client response
    background_task = inventory_collection
    gateway_url = http://[fd95:2333:df54:104::2]:12225
    result = Ok(Response { url: "http://[fd95:2333:df54:104::2]:12225/sp/sled/15/component/sp/caboose?firmware_slot=1", status: 200, headers: {"content-type": "application/json", "x-request-id": "eca46e89-4c1d-49a7-8a41-c707643ae7c5", "content-length": "138", "date": "Wed, 22 Apr 2026 22:34:12 GMT"} })
22:34:12.666Z DEBG b7f7dca6-e9ce-4933-aea9-9bbff3636900 (ServerContext): client request
    background_task = inventory_collection
    body = None
    gateway_url = http://[fd95:2333:df54:104::2]:12225
    method = GET
    uri = http://[fd95:2333:df54:104::2]:12225/sp/sled/15/component/rot/caboose?firmware_slot=0
22:34:12.923Z DEBG b7f7dca6-e9ce-4933-aea9-9bbff3636900 (ServerContext): client response
    background_task = inventory_collection
    gateway_url = http://[fd95:2333:df54:104::2]:12225
    result = Ok(Response { url: "http://[fd95:2333:df54:104::2]:12225/sp/sled/15/component/rot/caboose?firmware_slot=0", status: 200, headers: {"content-type": "application/json", "x-request-id": "d98ce250-7175-454b-a345-48db77045520", "content-length": "206", "date": "Wed, 22 Apr 2026 22:34:12 GMT"} })
22:34:12.924Z DEBG b7f7dca6-e9ce-4933-aea9-9bbff3636900 (ServerContext): client request
    background_task = inventory_collection
    body = None
    gateway_url = http://[fd95:2333:df54:104::2]:12225
    method = GET
    uri = http://[fd95:2333:df54:104::2]:12225/sp/sled/15/component/rot/caboose?firmware_slot=1
^C
```

Those log messages are later than the first message about failing the allowlist plumbing, so Nexus has correctly started. We can also see that Nexus ran the background task that's supposed to correct this:

```
root@oxz_switch1:~# omdb nexus background-tasks show service_firewall_rule_propagation
note: Nexus URL not specified.  Will pick one from DNS.
note: using DNS from system config (typically /etc/resolv.conf)
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using Nexus URL http://[fd95:2333:df54:102::4]:12232
task: "service_firewall_rule_propagation"
  configured period: every 5m
  currently executing: no
  last completed activation: iter 22, triggered by a periodic timer firing
    started at 2026-04-22T22:34:17.410Z (75s ago) and ran for 330ms
    failed to push rules to 1 sled(s):
        sled 1c1688fe-87c1-415e-b649-502c2dc705f0: Internal Error: Communication Error: error sending request for url (http://[fd95:2333:df54:103::1]:12345/vpc/001de000-074c-4000-8000-000000000000/firewall/rules)

```

Then I re-enabled the sled-agent from the first step, activated the task, and saw that it successfully ran to plumb the service firewall rules:

```
BRM23230010 # svcadm enable sled-agent
BRM23230010 # logout
root@oxz_switch1:~# omdb nexus background-tasks show service_firewall_rule_propagation
note: Nexus URL not specified.  Will pick one from DNS.
note: using DNS from system config (typically /etc/resolv.conf)
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using Nexus URL http://[fd95:2333:df54:102::4]:12232
task: "service_firewall_rule_propagation"
  configured period: every 5m
  currently executing: no
  last completed activation: iter 22, triggered by a periodic timer firing
    started at 2026-04-22T22:34:17.410Z (215s ago) and ran for 330ms
    failed to push rules to 1 sled(s):
        sled 1c1688fe-87c1-415e-b649-502c2dc705f0: Internal Error: Communication Error: error sending request for url (http://[fd95:2333:df54:103::1]:12345/vpc/001de000-074c-4000-8000-000000000000/firewall/rules)

root@oxz_switch1:~# omdb nexus background-tasks
print information about background tasks

Usage: omdb nexus background-tasks [OPTIONS] <COMMAND>

Commands:
  doc           Show documentation about background tasks
  list          Print a summary of the status of all background tasks
  show          Print human-readable summary of the status of each background task
  print-report  Print an event report for a background task if available
  activate      Activate one or more background tasks
  help          Print this message or the help of the given subcommand(s)

Options:
      --log-level <LOG_LEVEL>  log level filter [env: LOG_LEVEL=] [default: warn]
      --color <COLOR>          Color output [default: auto] [possible values: auto, always, never]
  -h, --help                   Print help

Connection Options:
      --nexus-internal-url <NEXUS_INTERNAL_URL>  URL of the Nexus internal lockstep API [env: OMDB_NEXUS_URL=]
      --dns-server <DNS_SERVER>                  [env: OMDB_DNS_SERVER=]

Safety Options:
  -w, --destructive  Allow potentially-destructive subcommands
root@oxz_switch1:~# omdb nexus background-tasks activate service_firewall_rule_propagation
note: Nexus URL not specified.  Will pick one from DNS.
note: using DNS from system config (typically /etc/resolv.conf)
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using Nexus URL http://[fd95:2333:df54:102::4]:12232
Error: This command is potentially destructive. Pass the `-w` / `--destructive` flag to allow it.
root@oxz_switch1:~# omdb -w nexus background-tasks activate service_firewall_rule_propagation
note: Nexus URL not specified.  Will pick one from DNS.
note: using DNS from system config (typically /etc/resolv.conf)
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using Nexus URL http://[fd95:2333:df54:102::4]:12232
activated background tasks: service_firewall_rule_propagation
root@oxz_switch1:~# omdb nexus background-tasks show service_firewall_rule_propagation
note: Nexus URL not specified.  Will pick one from DNS.
note: using DNS from system config (typically /etc/resolv.conf)
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using Nexus URL http://[fd95:2333:df54:102::4]:12232
task: "service_firewall_rule_propagation"
  configured period: every 5m
  currently executing: no
  last completed activation: iter 23, triggered by an explicit signal
    started at 2026-04-22T22:38:14.411Z (6s ago) and ran for 243ms

```

File: nexus/networking/src/firewall_rules.rs [hunk 1]
```diff
@@ -43,6 +71,13 @@ pub async fn vpc_list_firewall_rules(
     Ok(rules)
 }
 
+/// Resolve a set of VPC firewall rules into the form expected by sled-agents.
+///
+/// This function does not inject any Nexus-specific allow rules (i.e., the
+/// inbound-allow rule derived from the IP allowlist). Callers that are
+/// propagating rules for the services VPC must inject that rule themselves
+/// before calling this function; see [`plumb_service_firewall_rules`]. All
+/// other current call sites operate on customer VPCs and are unaffected.
```
Comment (mergeconflict) [inline nexus/networking/src/firewall_rules.rs]: We should probably `debug_assert!` that the caller has included the synthetic inbound-allow rule in `rules`.

Can we do something like:
```rs
  debug_assert!(
      vpc.id() != *SERVICES_VPC_ID
          || rules.iter().any(|r| r.name().as_str() == "nexus-inbound"),                                                                                                                                                                                              
      "..."
  ); 
```

File: nexus/networking/src/firewall_rules.rs [hunk 2]
```diff
@@ -21,17 +21,45 @@ use omicron_common::api::external::AllowedSourceIps;
...
+impl fmt::Display for ServiceFirewallRulesError {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        match self {
+            ServiceFirewallRulesError::Lookup(e) => {
+                write!(f, "failed to look up or resolve firewall rules: {e}")
+            }
+            ServiceFirewallRulesError::SledPush(failures) => {
+                write!(
+                    f,
+                    "failed to push firewall rules to {} sled(s)",
```
Comment (mergeconflict) [inline nexus/networking/src/firewall_rules.rs]: Would it be worth anything to include the sled IDs in here, or do you think the count is enough for this?

File: nexus/src/lib.rs [hunk 3]
```diff
@@ -189,10 +189,12 @@ impl Server {
...
-        // While we've started our internal server, we need to wait until we've
-        // definitely implemented our source IP allowlist for making requests to
-        // the external server we're about to start.
-        apictx.context.nexus.await_ip_allowlist_plumbing().await;
+        // Make a best-effort attempt to push the IP allowlist as firewall rules
+        // to sled-agents before starting the external server. Because OPTE has
+        // a default-deny policy, Nexus will be unreachable until this succeeds;
+        // the background task that propagates service firewall rules will keep
+        // retrying if this attempt fails.
+        apictx.context.nexus.attempt_ip_allowlist_plumbing().await;
```
Comment (mergeconflict) [inline nexus/src/lib.rs]: Is there a way to write a test where we spin up Nexus with an unreachable sled and observe that it starts?

File: nexus/db-fixed-data/src/vpc_firewall_rule.rs [hunk 4]
```diff
@@ -34,43 +34,6 @@ pub static DNS_VPC_FW_RULE: LazyLock<VpcFirewallRuleUpdate> =
         priority: VpcFirewallRulePriority(65534),
     });
 
-/// The name for the built-in VPC firewall rule for Nexus.
-pub const NEXUS_VPC_FW_RULE_NAME: &str = "nexus-inbound";
```
Comment (mergeconflict) [inline nexus/db-fixed-data/src/vpc_firewall_rule.rs:38]: Nit: we could still use this instead of hardcoding "nexus-inbound" in a bunch of spots.

File: nexus/networking/src/firewall_rules.rs [hunk 5]
```diff
@@ -531,25 +506,55 @@ pub async fn plumb_service_firewall_rules(
...
+                    first: 443.try_into().unwrap(),
+                    last: 443.try_into().unwrap(),
+                },
+            ]),
+        },
+        action: external::VpcFirewallRuleAction::Allow,
+        priority: external::VpcFirewallRulePriority(65534),
+    };
+    db::model::VpcFirewallRule::new(Uuid::new_v4(), *SERVICES_VPC_ID, &update)
+        .map_err(|e| Error::internal_error(&e.to_string()))
```
Comment (mergeconflict) [inline nexus/networking/src/firewall_rules.rs:621]: Claude found a minor bug here-ish. `VpcFirewallRule::new` will return an error if the number of hosts exceeds 256:

https://github.com/oxidecomputer/omicron/blob/979bc71872558269eeb61fbf89cf7ad896a69b10/nexus/db-model/src/vpc_firewall_rule.rs#L263-L265

We populate our hosts list from `allowed_ips: AllowedSourceIps`, which I think is capped at 1000 when users submit them:

https://github.com/oxidecomputer/omicron/blob/979bc71872558269eeb61fbf89cf7ad896a69b10/nexus/src/app/allow_list.rs#L39

So I think we need to resolve the disagreement between those limits, or users will see an internal error when they provide too many allowed source IPs.

File: nexus/src/app/vpc.rs [hunk 6]
```diff
@@ -328,7 +329,7 @@ impl super::Nexus {
                 error!(
                     self.log,
                     "failed to update sled-agents with new ICMP status";
-                    "error" => format!("{message}: {e:?}"),
+                    "error" => ?e,
```
Comment (mergeconflict) [inline nexus/src/app/vpc.rs]: Intentionally discarding the message here?

File: nexus/src/app/background/tasks/service_firewall_rules.rs [hunk 7]
```diff
@@ -42,30 +42,56 @@ impl BackgroundTask for ServiceRulePropagator {
...
+                )) => {
+                    for (sled_id, e) in &failures {
+                        error!(
+                            log,
+                            "failed to push service firewall rules to \
+                            sled-agent";
+                            "sled_id" => %sled_id,
+                            "error" => ?e,
+                        );
+                    }
```
Comment (mergeconflict) [inline nexus/src/app/background/tasks/service_firewall_rules.rs]: Nit: this might be spammy, it'll log up to 32 errors every time the background task runs. Is that ok?

File: nexus/networking/src/firewall_rules.rs (hunk 1 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: I agree with the goal, but does returning an error seem like enough?

File: nexus/src/lib.rs (hunk 3 above)
Comment (bnaecker) [reply nexus/src/lib.rs]: I couldn't think of a good way, so I did the manual test described above. I disabled one of the sled-agents hosting a Nexus instance, and then restarted a different Nexus. It printed an error about this attempt failing, but then continued on starting up as expected.

It might be possible to write an integration test that works like this, but I'm not sure.

File: nexus/networking/src/firewall_rules.rs (hunk 5 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs:621]: Good catch. We could either break the allowlist into 32-host-sized chunks; reduce the allowlist length; or increase the FW rule length. Reducing seems risky, but since this limits have been here for a long time and no customer deployment has hit this, I suspect we are _probably_ safe. I'm not sure what the right call is there.

File: nexus/src/app/vpc.rs (hunk 6 above)
Comment (bnaecker) [reply nexus/src/app/vpc.rs]: I was, since the display impl of the error type now includes a message. But I see now that the messages are a little different. I'll add it back.

File: nexus/src/app/background/tasks/service_firewall_rules.rs (hunk 7 above)
Comment (bnaecker) [reply nexus/src/app/background/tasks/service_firewall_rules.rs]: I think it's probably fine? It seems better than not logging it, IMO. We get the _last_ status with the background task output, but not the less-recent ones.

File: nexus/db-fixed-data/src/vpc_firewall_rule.rs (hunk 4 above)
Comment (bnaecker) [reply nexus/db-fixed-data/src/vpc_firewall_rule.rs:38]: I'm keeping this, but moving it to another module. It's not really about the DB anymore.

File: nexus/networking/src/firewall_rules.rs (hunk 2 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: We can do that

File: nexus/networking/src/firewall_rules.rs (hunk 5 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs:621]: I'm going to split the allowlist up into different rules. I was wrong, it's not 32-hosts at a time, its 256. So we have at most 4 rules to implement the allowlist, which is not much.

Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs:621]: Done in 5ef127304

File: nexus/networking/src/firewall_rules.rs (hunk 2 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: Done in 5ef127304

File: nexus/db-fixed-data/src/vpc_firewall_rule.rs (hunk 4 above)
Comment (bnaecker) [reply nexus/db-fixed-data/src/vpc_firewall_rule.rs:38]: Done in 5ef127304

File: nexus/src/app/vpc.rs (hunk 6 above)
Comment (bnaecker) [reply nexus/src/app/vpc.rs]: Done in 5ef127304

File: nexus/networking/src/firewall_rules.rs (hunk 1 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: I've added a check in c1cd64c97. This returns an error rather than panicking.

**Review by mergeconflict — APPROVED** [review]

File: dev-tools/omdb/src/bin/omdb/nexus.rs [hunk 8]
```diff
@@ -2809,18 +2809,38 @@ fn print_task_session_cleanup(details: &serde_json::Value) {
 }
 
 fn print_task_service_firewall_rule_propagation(details: &serde_json::Value) {
-    match serde_json::from_value::<serde_json::Value>(details.clone()) {
+    #[derive(Deserialize)]
+    struct SledPushError {
```
Comment (jgallagher) [inline dev-tools/omdb/src/bin/omdb/nexus.rs]: Instead of defining these structs here and using `json!({ ... })` that happens to match in the bg task, could we move these structs to `nexus/types/src/internal_api/background.rs` and use them both here and in the bg task? (I think we have a mix of these styles in this file; `print_task_blueprint_planner()` is one example that uses the pattern I'm describing here.)

File: nexus/reconfigurator/execution/src/lib.rs [hunk 9]
```diff
@@ -486,7 +486,11 @@ fn register_plumb_firewall_rules_step<'a>(
                     &opctx.log,
                 )
                 .await
-                .context("failed to plumb service firewall rules to sleds");
+                .map_err(|e| {
+                    anyhow::anyhow!(
+                        "failed to plumb service firewall rules to sleds: {e}"
```
Comment (jgallagher) [inline nexus/reconfigurator/execution/src/lib.rs]: This change isn't correct. `.context()` correctly added another layer of error source; embedding `{e}` in the format string will _lose_ any inner error sources. This goes through `map_err_to_step_warning()` which already does the right thing and logs the entire error chain.

File: nexus/networking/src/firewall_rules.rs [hunk 10]
```diff
@@ -21,17 +21,53 @@ use omicron_common::api::external::AllowedSourceIps;
...
 use slog::info;
-use slog::warn;
 use std::collections::{HashMap, HashSet};
+use std::fmt;
 use std::net::IpAddr;
+use uuid::Uuid;
+
+/// Error returned when attempting to propagate service firewall rules to
+/// sled-agents.
+#[derive(Debug)]
```
Comment (jgallagher) [inline nexus/networking/src/firewall_rules.rs]: This should implement `std::error::Error` so we can treat it as an error in terms of `anyhow` and logging. Could this be

```rust
#[derive(Debug, thiserror::Error)]
pub enum ServiceFirewallRulesError {
    /// Failed to look up or resolve firewall rules (e.g., a database error).
    #[error("failed to look up or resolve firewall rules")]
    Lookup(#[source] Error),
    /// Firewall rules were resolved but some sled-agents could not be reached.
    #[error("{}", summarize_sled_push_errors(.0))]
    SledPush(Vec<(SledUuid, Error)>),
}

fn summarize_sled_push_errors(errors: &[(SledUuid, Error)]) -> String {
    // ... build the "failed to push firewall rules to N sled(s): [sled_ids]" string ..
}
```

(and then we wouldn't need an explicit `fmt::Display` impl, since `thiserror` would do it for us)

File: nexus/networking/src/firewall_rules.rs [hunk 11]
```diff
@@ -21,17 +21,53 @@ use omicron_common::api::external::AllowedSourceIps;
...
+pub enum ServiceFirewallRulesError {
+    /// Failed to look up or resolve firewall rules (e.g., a database error).
+    Lookup(Error),
+    /// Firewall rules were resolved but some sled-agents could not be reached.
+    SledPush(Vec<(SledUuid, Error)>),
```
Comment (jgallagher) [inline nexus/networking/src/firewall_rules.rs]: Should this be `BTreeMap<SledUuid, Error>` instead of a vec? (I assume a single sled can only show up once?)

File: nexus/reconfigurator/execution/src/lib.rs (hunk 9 above)
Comment (jgallagher) [reply nexus/reconfigurator/execution/src/lib.rs]: Edit: I see, this is here because `e` is no longer actually an `Error`. We should fix that and then revert this change.

File: nexus/networking/src/firewall_rules.rs [hunk 12]
```diff
@@ -43,13 +79,36 @@ pub async fn vpc_list_firewall_rules(
     Ok(rules)
 }
 
+/// Resolve a set of VPC firewall rules into the form expected by sled-agents.
+///
+/// This function does not inject any Nexus-specific allow rules (i.e., the
+/// inbound-allow rule derived from the IP allowlist). Callers that are
+/// propagating rules for the services VPC must inject that rule themselves
+/// before calling this function; see [`plumb_service_firewall_rules`]. An error
+/// is returned if this not the case.
```
Comment (jgallagher) [inline nexus/networking/src/firewall_rules.rs]: This comment makes me nervous, or makes me feel like we've gone of the rails somewhere. Looking at the immediate callers of this function, neither appears to supplement the rules its passing with anything:

* `send_sled_agents_firewall_rules()` later in this file passes the rules it receives unsupplemented
* [`Nexus::resolve_firewall_rules_for_sled_agent()`](https://github.com/oxidecomputer/omicron/blob/8c724b387e2ba1c2c3f3b37c6f81ad967b2c1fe3/nexus/src/app/vpc.rs#L275) passes the rules it receives unsupplemented

Do we need to propagate this warning comment out to those, and their callers, etc.? It looks like the Nexus one is called with rules that are [directly looked up from the db](https://github.com/oxidecomputer/omicron/blob/8c724b387e2ba1c2c3f3b37c6f81ad967b2c1fe3/nexus/src/app/instance.rs#L1533-L1538), but I guess from context that's okay because the VPC there is never the services VPC?

I'm not sure what to do about this exactly, but it seems overly fragile. Will noodle on it.

File: nexus/networking/src/firewall_rules.rs [hunk 13]
```diff
@@ -492,36 +472,55 @@ pub async fn send_sled_agents_firewall_rules(
...
-                      "vpc_id" => %vpc.id(),
-                      "error" => %e);
-            return Err(e);
+            sled_failures.push((sled.id(), e));
         }
     }
+    if !sled_failures.is_empty() {
+        return Err(ServiceFirewallRulesError::SledPush(sled_failures));
+    }
     info!(log, "updated firewall rules on {} sleds", vpc_to_sleds.len());
```
Comment (jgallagher) [inline nexus/networking/src/firewall_rules.rs]: Should we log this before checking `!sled_failures.is_empty()`, since we might have updated the firewall rules on _some_ sleds even if not all? (And/or emit a slightly different log message if we had partial or total failure?) Maybe something like

```rust
if sled_failures.is_empty() {
    info!(log, "updated firewall rules on {} sleds", vpc_to_sleds.len());
    Ok(())
} else {
    warn!(
        log, "failed to update firewall rules on all sleds";
        "sleds-successfully-updated" => vpc_to_sleds.len() - sled_failures.len(),
        "sleds-failed-to-update" => sled_failures.len(),
    );
    Err(ServiceFirewallRulesError::SledPush(sled_failures))
}
```

File: nexus/networking/src/firewall_rules.rs [hunk 14]
```diff
@@ -531,25 +530,108 @@ pub async fn plumb_service_firewall_rules(
...
+/// The base name for the VPC firewall rules for Nexus implementing the IP allowlist.
+pub const NEXUS_VPC_FW_RULE_NAME: &str = "nexus-inbound";
+
+/// Maximum number of entries in the IP allowlist.
+///
+/// This is enforced at the API layer in `allow_list_upsert` (which imports
+/// this constant). It must be kept consistent with
+/// `MAX_NEXUS_INBOUND_RULES * VPC_FIREWALL_RULE_MAX_FILTER_LEN`; see the
+/// static assertion below.
+pub const MAX_ALLOWLIST_LENGTH: usize = 1000;
```
Comment (jgallagher) [inline nexus/networking/src/firewall_rules.rs]: Given the comment, why is this not 1024 (i.e., exactly `MAX_NEXUS_INBOUND_RULES * VPC_FIREWALL_RULE_MAX_FILTER_LEN`)?

File: nexus/networking/src/firewall_rules.rs [hunk 15]
```diff
@@ -531,25 +530,108 @@ pub async fn plumb_service_firewall_rules(
...
+            .collect(),
+    }
+}
+
+fn make_one_nexus_inbound_rule(
+    name: &str,
+    hosts: Option<Vec<external::VpcFirewallRuleHostFilter>>,
+) -> Result<db::model::VpcFirewallRule, Error> {
+    let update = external::VpcFirewallRuleUpdate {
+        name: name.parse().expect("nexus-inbound rule names are always valid"),
```
Comment (jgallagher) [inline nexus/networking/src/firewall_rules.rs]: Nit - we should make this function take a `Name` and put the `.parse().expect()` in the caller where it's obvious that it's a valid name.

File: nexus/networking/src/firewall_rules.rs [hunk 16]
```diff
@@ -531,25 +530,108 @@ pub async fn plumb_service_firewall_rules(
...
+/// entries each. When the allowlist is `Any`, a single rule named
+/// `nexus-inbound` with no host filter is returned.
+fn make_nexus_allowlist_rules(
+    allowed_ips: AllowedSourceIps,
+) -> Result<Vec<db::model::VpcFirewallRule>, Error> {
+    match allowed_ips {
+        AllowedSourceIps::Any => {
+            Ok(vec![make_one_nexus_inbound_rule(NEXUS_VPC_FW_RULE_NAME, None)?])
+        }
+        AllowedSourceIps::List(list) => list
```
Comment (jgallagher) [inline nexus/networking/src/firewall_rules.rs]: Should we check that `list.len() <= MAX_ALLOWLIST_LEN`?

File: nexus/networking/src/firewall_rules.rs (hunk 12 above)
Comment (jgallagher) [reply nexus/networking/src/firewall_rules.rs]: An idea that won't work but I wanted to write down in case there's something here: what if we made this function private, and added a public `resolve_instance_firewall_rules_for_sled_agent()` that (a) fails if passed the services VPC then (b) calls through to this now-private function? Where this doesn't work is that we'd also want to make `send_sled_agents_firewall_rules()` private, because it also calls this function, and that is called by at least the VPC create saga. Maybe that one could also have a public "only used for non-service-VPCs" interface? But this is getting really messy. :(

File: nexus/src/app/background/tasks/service_firewall_rules.rs [hunk 17]
```diff
@@ -42,30 +42,56 @@ impl BackgroundTask for ServiceRulePropagator {
...
+                    );
+                    serde_json::json!({})
+                }
+                Err(nexus_networking::ServiceFirewallRulesError::Lookup(e)) => {
+                    error!(
+                        log,
+                        "failed to look up or resolve service firewall rules";
+                        "error" => ?e,
+                    );
+                    serde_json::json!({"lookup_error": e.to_string()})
```
Comment (jgallagher) [inline nexus/src/app/background/tasks/service_firewall_rules.rs]: We should use `InlineErrorChain` for both logging and string conversion here, to avoid losing the full chain:


```suggestion
                    let e = InlineErrorChain::new(&e);
                    error!(
                        log,
                        "failed to look up or resolve service firewall rules";
                        &e,
                    );
                    serde_json::json!({"lookup_error": e.to_string()})
```

(same issue in the `SledPush` arm below)

File: nexus/src/app/allow_list.rs [hunk 18]
```diff
@@ -139,34 +138,46 @@ impl super::Nexus {
...
+        {
+            Ok(()) => {
+                info!(self.log, "plumbed initial IP allowlist");
+            }
+            Err(nexus_networking::ServiceFirewallRulesError::Lookup(e)) => {
+                error!(
+                    self.log,
+                    "failed to look up initial IP allowlist rules; \
+                    background task will retry";
+                    "error" => ?e,
```
Comment (jgallagher) [inline nexus/src/app/allow_list.rs]:
```suggestion
                    InlineErrorChain::new(&e),
```

File: nexus/src/app/allow_list.rs [hunk 19]
```diff
@@ -139,34 +138,46 @@ impl super::Nexus {
...
+            )) => {
+                for (sled_id, e) in &failures {
                     error!(
                         self.log,
-                        "failed to plumb initial IP allowlist";
-                        "error" => ?e
+                        "failed to push initial IP allowlist to sled-agent; \
+                        background task will retry";
+                        "sled_id" => %sled_id,
+                        "error" => ?e,
```
Comment (jgallagher) [inline nexus/src/app/allow_list.rs]:
```suggestion
                        InlineErrorChain::new(&e),
```

File: nexus/src/app/vpc.rs [hunk 20]
```diff
@@ -263,6 +263,7 @@ impl super::Nexus {
             &self.log,
         )
         .await
+        .map_err(|e| Error::internal_error(&e.to_string()))
```
Comment (jgallagher) [inline nexus/src/app/vpc.rs]:
```suggestion
        .map_err(|e| Error::internal_error(InlineErrorChain::new(&e).to_string()))
```

File: nexus/src/lib.rs [hunk 21]
```diff
@@ -189,10 +189,12 @@ impl Server {
         let opctx = apictx.context.nexus.opctx_for_service_balancer();
         apictx.context.nexus.await_rack_initialization(&opctx).await;
 
-        // While we've started our internal server, we need to wait until we've
-        // definitely implemented our source IP allowlist for making requests to
-        // the external server we're about to start.
-        apictx.context.nexus.await_ip_allowlist_plumbing().await;
+        // Make a best-effort attempt to push the IP allowlist as firewall rules
```
Comment (jgallagher) [inline nexus/src/lib.rs:192]: Could we activate the bg task here instead of needing a function specifically for "try this once"?

File: nexus/networking/src/firewall_rules.rs (hunk 16 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: That's done in the API handler, but no real harm in doing it again.

File: nexus/networking/src/firewall_rules.rs (hunk 14 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: Only to avoid changing something else that doesn't need to. Will update.

File: dev-tools/omdb/src/bin/omdb/nexus.rs (hunk 8 above)
Comment (bnaecker) [reply dev-tools/omdb/src/bin/omdb/nexus.rs]: Done in 96352f9fa

File: nexus/reconfigurator/execution/src/lib.rs (hunk 9 above)
Comment (bnaecker) [reply nexus/reconfigurator/execution/src/lib.rs]: Done in 96352f9fa

File: nexus/networking/src/firewall_rules.rs (hunk 10 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: Done in 96352f9fa

File: nexus/networking/src/firewall_rules.rs (hunk 11 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: Done in 96352f9fa

File: nexus/networking/src/firewall_rules.rs (hunk 13 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: Done in 96352f9fa

File: nexus/networking/src/firewall_rules.rs (hunk 14 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: Done in 96352f9fa

File: nexus/networking/src/firewall_rules.rs (hunk 15 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: Done in 96352f9fa

File: nexus/networking/src/firewall_rules.rs (hunk 16 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: Done in 96352f9fa

File: nexus/src/app/background/tasks/service_firewall_rules.rs (hunk 17 above)
Comment (bnaecker) [reply nexus/src/app/background/tasks/service_firewall_rules.rs]: Done in 96352f9fa

File: nexus/src/app/allow_list.rs (hunk 18 above)
Comment (bnaecker) [reply nexus/src/app/allow_list.rs]: Done in 96352f9fa

File: nexus/src/app/allow_list.rs (hunk 19 above)
Comment (bnaecker) [reply nexus/src/app/allow_list.rs]: Done in 96352f9fa

File: nexus/src/app/vpc.rs (hunk 20 above)
Comment (bnaecker) [reply nexus/src/app/vpc.rs]: Done in 96352f9fa

File: nexus/src/lib.rs (hunk 21 above)
Comment (bnaecker) [reply nexus/src/lib.rs:192]: Done in 96352f9fa

File: nexus/networking/src/firewall_rules.rs (hunk 12 above)
Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: One thing that might work is to push the addition of the rules for the allowlist down, rather than up. Suppose we did the work of looking up the allowlist and constructing the rule for it inside `send_sled_agents_firewall_rules()` rather than in the caller?

Comment (jgallagher) [reply nexus/networking/src/firewall_rules.rs]: Yeah, that might be the right path. I don't want to hold this up over a super-gnarly-to-untangle problem, necessarily; do you think pushing the rules down that way is easy-ish to try / see if it looks good?

Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: I think it's pretty easy. We'd move the block that computes the rules from the allowlist from `plumb_service_firewall_rules()` down into `send_sled_agents_firewall_rules()`. That already has all the datastore / opctx stuff it would need, since it has to resolve the rules from the database in any case. I'll give it a whirl, thanks for the suggestion to improve this.

Comment (bnaecker) [reply nexus/networking/src/firewall_rules.rs]: Done in b7ba55c45, let me know what you think.

**Review by jgallagher — APPROVED** [review]
Changes LGTM, thanks! I'm not sure if enough has changed since you tested that it warrants redoing that; happy to defer to your judgment.

**Comment by bnaecker** [comment]
Thanks @jgallagher. I'll take it for another lap on one of the racklets. Appreciate your input!

**Comment by bnaecker** [comment]
Ok, I did the same repro steps once more on `madrid`:

- install b7ba55c45e8ce5a452cdea16c9a343e6bfbf58c4 with `rkadm`
- Nexus comes up completely, along with the rest of the control plane
- stop the sled-agent on sled 15
- restart Nexus on sled 14
- observe that the background task runs to completion, with an error message about not being able to reach the sled
- restart the sled-agent
- trigger the background task once more, which completes successfully

I'm going to fixup the merge conflicts and queue this to merge. Thanks all for the reviews!
