### PR TITLE
[nexus-types] test that PlanningReports can be roundtrip serialized

### LINKED ISSUE #9081: Test that `PlanningReport` can be serialized as JSON
While testing update on dublin, a Nexus instance went into maintenance after panicking multiple times with

```
thread 'tokio-runtime-worker' panicked at nexus/src/app/background/tasks/blueprint_planner.rs:295:31:
called `Result::unwrap()` on an `Err` value: Error("key must be a string", line: 0, column: 0)
```

and included this error log shortly before the panic:

```
{"msg":"could not serialize blueprint planning report","v":0,"name":"nexus","level":50,"time":"2025-09-24T18:19:01.819740006Z","hostname":"oxz_nexus_a4c68a8c-7e9a-45a4-8adc-88de59616d9d","pid":11682,"component":"datastore","component":"nexus","component":"ServerContext","name":"a4c68a8c-7e9a-45a4-8adc-88de59616d9d","file":"nexus/db-queries/src/db/datastore/deployment.rs:531","error":"key must be a string"}
```

#9080 fixes two maps that had non-string keys and removes the call to `json!()` that induced this panic, but does not add any test coverage for other maps I might've missed or that might be added in the future. @sunshowers suggested we add a proptest that generates arbitrary reports and confirms we can serialize them to JSON.

### PR DESCRIPTION
**Pull request by sunshowers**
This proptest would catch the issue detected in #9080.

Closes #9081.

### CODE REVIEW

File: nexus/types/src/deployment.rs [hunk 1]
```diff
@@ -1850,9 +1868,22 @@ pub struct PendingMgsUpdateHostPhase1Details {
...
+// through JSON.
+#[cfg(test)]
+fn socket_addr_v6_without_flowinfo()
+-> impl proptest::strategy::Strategy<Value = SocketAddrV6> {
+    use proptest::strategy::Strategy;
+
+    proptest::arbitrary::any::<(Ipv6Addr, u16, u32)>().prop_map(
+        |(addr, port, scope_id)| SocketAddrV6::new(addr, port, 0, scope_id),
+    )
+}
```
Comment (sunshowers) [inline nexus/types/src/deployment.rs:1930]: 😬

File: nexus/types/src/deployment.rs [hunk 2]
```diff
@@ -1528,13 +1535,19 @@ impl<'a> IntoIterator for &'a PendingMgsUpdates {
...
 )]
+#[cfg_attr(test, derive(test_strategy::Arbitrary))]
 pub struct PendingMgsUpdate {
     // identity of the baseboard
     /// id of the baseboard that we're going to update
     pub baseboard_id: Arc<BaseboardId>,
 
     // location of the baseboard (that we'd pass to MGS)
     /// what type of baseboard this is
+    #[cfg_attr(test, strategy(proptest::prop_oneof![
```
Comment (jgallagher) [inline nexus/types/src/deployment.rs]: Was there something preventing us from deriving `Arbitrary` for `SpType`?

File: nexus/types/src/deployment.rs (hunk 1 above)
Comment (jgallagher) [reply nexus/types/src/deployment.rs:1930]: ooof

**Review by jgallagher — APPROVED** [review]
Thanks! This looks like it was pretty tedious, but is way more robust than the path I started down.

File: nexus/types/src/deployment.rs (hunk 2 above)
Comment (sunshowers) [reply nexus/types/src/deployment.rs]: Ended up `replace`-ing the `SpType` in gateway-client in favor of the one in gateway-types: https://github.com/oxidecomputer/omicron/pull/9093

With that change, we can derive `Arbitrary` on `SpType`.
