### PR TITLE
[nexus] Having children shouldn't prevent reincarnation

### LINKED ISSUE #8178: test failed in CI: test_instance_failed_by_stop_request_does_not_reincarnate
This test failed on a CI run on **pull request #8174**:

https://github.com/oxidecomputer/omicron/pull/8174/checks?check_run_id=42323677841

Log showing the specific test failure:

https://buildomat.eng.oxide.computer/wg/0/details/01JVB1PD2FS2TGNJ8YWS5PJWKX/ehxX0N3vFukjWLFqMtKuXAvVc02rU1FAD1MPIHUXJrAteusu/01JVB1Q0B25QFZ2F0ZSSNR1559#S7266

Excerpt from the log showing the failure:

```
        FAIL [ 192.386s] omicron-nexus::test_all integration_tests::instances::test_instance_failed_by_stop_request_does_not_reincarnate
──── STDOUT:             omicron-nexus::test_all integration_tests::instances::test_instance_failed_by_stop_request_does_not_reincarnate

running 1 test
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: System }, version: Some(RouterVersion { router_id: 83e54225-6e48-443e-90e1-82e7fa9e3b36, version: 3 }), routes: {ResolvedVpcRoute { dest: V6(Ipv6Net { addr: ::, width: 0 }), target: InternetGateway(Instance(54e26dfe-249f-4bd3-a21f-0461c92e8a9f)) }, ResolvedVpcRoute { dest: V4(Ipv4Net { addr: 172.30.0.0, width: 22 }), target: VpcSubnet(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, ResolvedVpcRoute { dest: V4(Ipv4Net { addr: 0.0.0.0, width: 0 }), target: InternetGateway(Instance(54e26dfe-249f-4bd3-a21f-0461c92e8a9f)) }, ResolvedVpcRoute { dest: V6(Ipv6Net { addr: fd7a:5945:4de6::, width: 64 }), target: VpcSubnet(V6(Ipv6Net { addr: fd7a:5945:4de6::, width: 64 })) }} }
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
test integration_tests::instances::test_instance_failed_by_stop_request_does_not_reincarnate has been running for over 60 seconds
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(16322539), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
test integration_tests::instances::test_instance_failed_by_stop_request_does_not_reincarnate ... FAILED

failures:

failures:
    integration_tests::instances::test_instance_failed_by_stop_request_does_not_reincarnate

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 438 filtered out; finished in 192.00s

──── STDERR:             omicron-nexus::test_all integration_tests::instances::test_instance_failed_by_stop_request_does_not_reincarnate
log file: /var/tmp/omicron_tmp/test_all-94731d9e6db289ca-test_instance_failed_by_stop_request_does_not_reincarnate.23960.0.log
note: configured to log to "/var/tmp/omicron_tmp/test_all-94731d9e6db289ca-test_instance_failed_by_stop_request_does_not_reincarnate.23960.0.log"
DB URL: postgresql://root@[::1]:37220/omicron?sslmode=disable
DB address: [::1]:37220
log file: /var/tmp/omicron_tmp/test_all-94731d9e6db289ca-test_instance_failed_by_stop_request_does_not_reincarnate.23960.2.log
note: configured to log to "/var/tmp/omicron_tmp/test_all-94731d9e6db289ca-test_instance_failed_by_stop_request_does_not_reincarnate.23960.2.log"
[nexus/tests/integration_tests/instances.rs:1439:23] make_forgotten_instance(&cptestctx, instance_name,
InstanceAutoRestartPolicy::BestEffort,).await = a642b2b8-502d-4761-9190-01f5776645d3 (instance)
[nexus/tests/integration_tests/instances.rs:1458:5] instance_wait_for_state(client, instance_id, InstanceState::Failed).await = Instance {
    identity: IdentityMetadata {
        id: a642b2b8-502d-4761-9190-01f5776645d3,
        name: Name(
            "resurgam",
        ),
        description: "instance \"resurgam\"",
        time_created: 2025-05-15T23:55:01.319179Z,
        time_modified: 2025-05-15T23:55:09.802162Z,
    },
    project_id: 354efc7e-8c45-4d5e-b952-752f01b33dba,
    ncpus: InstanceCpuCount(
        4,
    ),
    memory: ByteCount(
        1073741824,
    ),
    hostname: "the-host",
    boot_disk_id: None,
    runtime: InstanceRuntimeState {
        run_state: Failed,
        time_run_state_updated: 2025-05-15T23:55:10.163327Z,
        time_last_auto_restarted: None,
    },
    auto_restart_status: InstanceAutoRestartStatus {
        enabled: true,
        policy: Some(
            BestEffort,
        ),
        cooldown_expiration: None,
    },
}
[nexus/tests/integration_tests/instances.rs:1464:5] nexus_test_utils::background::activate_background_task(&cptestctx.internal_client,
"instance_reincarnation",).await = BackgroundTask {
    current: Idle,
    description: "schedules start sagas for failed instances that can be automatically restarted",
    last: Completed(
        LastResultCompleted {
            details: Object {
                "changed_state": Array [],
                "disabled": Bool(false),
                "errors": Array [],
                "instances_found": Object {
                    "Failed": Number(0),
                    "SagaUnwound": Number(0),
                },
                "instances_reincarnated": Array [],
                "restart_errors": Array [],
            },
            elapsed: Duration {
                nanos: 131868255,
                secs: 0,
            },
            iteration: 2,
            reason: Signaled,
            start_time: 2025-05-15T23:55:11.040059501Z,
        },
    ),
    name: "instance_reincarnation",
    period: Duration {
        nanos: 0,
        secs: 600,
    },
}
[nexus/tests/integration_tests/instances.rs:1491:5] expect_instance_start_ok(client, instance_name).await = ()

thread 'integration_tests::instances::test_instance_failed_by_stop_request_does_not_reincarnate' panicked at nexus/tests/integration_tests/instances.rs:6913:19:
instance a642b2b8-502d-4761-9190-01f5776645d3 did not transition to Starting after 120s: timed out after 120.762367471s
stack backtrace:
   0: rust_begin_unwind
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:695:5
   1: core::panicking::panic_fmt
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:75:14
   2: {async_fn#0}
             at ./tests/integration_tests/instances.rs:6913:19
   3: {async_fn#0}
             at ./tests/integration_tests/instances.rs:6864:6
   4: {async_fn#0}
             at ./tests/integration_tests/instances.rs:1527:14
   5: {async_block#0}
             at ./tests/integration_tests/instances.rs:1430:1
   6: poll<&mut dyn core::future::future::Future<Output=()>>
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/future/future.rs:124:9
   7: poll<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/future/future.rs:124:9
   8: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/scheduler/current_thread/mod.rs:729:57
   9: with_budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/coop.rs:107:5
  10: budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/coop.rs:73:5
  11: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/scheduler/current_thread/mod.rs:729:25
  12: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/scheduler/current_thread/mod.rs:428:19
  13: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/scheduler/current_thread/mod.rs:728:36
  14: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/scheduler/current_thread/mod.rs:807:68
  15: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/context/scoped.rs:40:9
  16: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/context.rs:180:26
  17: try_with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>), tokio::runtime::scheduler::current_thread::{impl#8}::enter::{closure_env#0}<tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>, core::option::Option<()>>>, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>)>
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/thread/local.rs:310:12
  18: std::thread::local::LocalKey<T>::with
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/thread/local.rs:274:15
  19: tokio::runtime::context::set_scheduler
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/context.rs:180:9
  20: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/scheduler/current_thread/mod.rs:807:27
  21: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/scheduler/current_thread/mod.rs:716:19
  22: {closure#0}<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/scheduler/current_thread/mod.rs:196:28
  23: tokio::runtime::context::runtime::enter_runtime
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/context/runtime.rs:65:16
  24: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/scheduler/current_thread/mod.rs:184:9
  25: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/runtime.rs:368:47
  26: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
             at /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.1/src/runtime/runtime.rs:342:13
  27: test_instance_failed_by_stop_request_does_not_reincarnate
             at ./tests/integration_tests/instances.rs:1430:1
  28: test_all::integration_tests::instances::test_instance_failed_by_stop_request_does_not_reincarnate::{{closure}}
             at ./tests/integration_tests/instances.rs:1433:2
  29: core::ops::function::FnOnce::call_once
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/ops/function.rs:250:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
WARN: dropped CockroachInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
WARN: temporary directory leaked: "/var/tmp/omicron_tmp/.tmphUsj2Q"
	If you would like to access the database for debugging, run the following:

	# Run the database
	cargo xtask db-dev run --no-populate --store-dir "/var/tmp/omicron_tmp/.tmphUsj2Q/data"
	# Access the database. Note the port may change if you run multiple databases.
	cockroach sql --host=localhost:32221 --insecure
WARN: dropped ClickHouse process without cleaning it up first (there may still be a child process running (PID 23967) and a temporary directory leaked, /var/tmp/omicron_tmp/test_all-94731d9e6db289ca-test_instance_failed_by_stop_request_does_not_reincarnate.23960.1-clickhouse-3UYIoZ)
failed to clean up ClickHouse data dir:
- /var/tmp/omicron_tmp/test_all-94731d9e6db289ca-test_instance_failed_by_stop_request_does_not_reincarnate.23960.1-clickhouse-3UYIoZ: File exists (os error 17)
WARN: dropped DendriteInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
WARN: dendrite temporary directory leaked: /var/tmp/omicron_tmp/.tmpHd7ihX
WARN: dropped MgdInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
WARN: mgd temporary directory leaked: /var/tmp/omicron_tmp/.tmpwdfnTW

```

### PR DESCRIPTION
**Pull request by hawkw**
See https://github.com/oxidecomputer/omicron/issues/8178#issuecomment-2887234729

This was an attempt at fixing the test flake in #8178 that I made back in May of 2025. Unfortunately, I wasn't able to reproduce the flake, so I have no idea if this actually fixes it or not. But it seems like it could, maybe. Since we've seen the flake again, I'm opening a PR for it.

Basically, the idea here is that previously, we would only attempt to reincarnate an instance at the end of an `instance_update` saga in an `else` block, if we _don't_ then attempt to spawn a subsequent update saga to apply an additional update. This branch changes it so that the activation of the reincarnation task is conditional only on whether the instance is believed to be reincarnatable, rather than only doing that if there is no successor saga. I don't really remember why I thought this fixed the test flake, but it seems basically good in any case. 

**UPDATE**: Oh right, the reason that I thought this might fix it is that the child saga in the flake I saw previously didn't actually make any state changes, but we had to re-do the whole lock-y dance to find that out (https://github.com/oxidecomputer/omicron/issues/8178#issuecomment-2887813581). And then, because the child doesn't actually need to do anything, it doesn't run a "real" update saga and therefore doesn't get to the node that checks if the reincarnation task needs to be updated. And this is only a bug in tests and not in real life, because in real life, the background task runs periodically and will eventually notice the instance in need of reincarnation anyway.

So, yeah, I do think this probably fixes #8178.

### CODE REVIEW

File: nexus/src/app/sagas/instance_update/mod.rs [hunk 1]
```diff
@@ -1338,37 +1307,7 @@ async fn siu_chain_successor_saga(
...
-                    log,
-                    "instance update: instance will not reincarnate";
-                    "instance_id" => %instance_id,
-                    "auto_restart_config" => ?new_state.instance.auto_restart,
-                    "needs_reincarnation" => karmic_state.needs_reincarnation,
-                    "karmic_state" => ?karmic_state.can_reincarnate,
-                    "intended_state" => %new_state.instance.intended_state,
-                )
-            }
+            reincarnate_if_needed(osagactx, &new_state)
```
Comment (smklein) [inline nexus/src/app/sagas/instance_update/mod.rs:1310]: So: this is refactored, but this is functionally the same...

File: nexus/src/app/sagas/instance_update/start.rs [hunk 2]
```diff
@@ -302,6 +302,18 @@ async fn siu_fetch_state_and_start_real_saga(
...
+        // instance. A previous activation may have not been able to
+        // reincarnate this instance because we held the lock, so poking the
+        // reincarnation task here should help ensure it sees a failed instance
+        // in a timely manner.
+        //
+        // This doesn't matter a whole lot in production systems, where the task
+        // will activate periodically regardless, but it should make the tests
+        // less flakey, and hopefully also decrease the latency with which
+        // failed instances are reincarnated a bit, maybe?
+        super::reincarnate_if_needed(osagactx, &state);
```
Comment (smklein) [inline nexus/src/app/sagas/instance_update/start.rs:316]: ... and this is the new bit?

Kinda up-to-your-judgement how much to do "now" vs "later", but it would be really nice to have a regression test for this.

Even though this is coupled a bit with the background task system, it seems possible if we set the timeouts such that "normally the reincarnation background task never fires". Then, we could interleave instance operations, cause one to get locked out of reincarnation, observe this branch with a new saga, and see that the reincarnation bg task **did** get started (which would be the new behavior). Beyond that point, we wouldn't even need to check that it does anything meaningful, just that the bg task system kicked it.

IDK - would be nice to be able to validate these new behaviors, but I also understand if that's kinda an onerous testing request.

Comment (hawkw) [reply nexus/src/app/sagas/instance_update/start.rs:316]: > Even though this is coupled a bit with the background task system, it seems possible if we set the timeouts such that "normally the reincarnation background task never fires". Then, we could interleave instance operations, cause one to get locked out of reincarnation, observe this branch with a new saga, and see that the reincarnation bg task **did** get started (which would be the new behavior).

We actually already _do_ set a timeout that should prevent the reincarnation task from having periodic activations fire in tests:

https://github.com/oxidecomputer/omicron/blob/696a3f6a884ea2692f9bc973a03623e79aeb0fc6/nexus/tests/config.test.toml#L155-L164

I actually think that's _why_ the flake happens at all, I'm pretty sure it's not a real bug that would occur in production, because the periodic activation guards against it.

Comment (hawkw) [reply nexus/src/app/sagas/instance_update/start.rs:316]: I think I'm probably going to punt on trying to test this since it seems that last time I was looking at this, I didn't really manage to work out the precise interleaving that would have reproduced the flake, and I'd rather just merge this and hopefully stop it from happening again.

Comment (smklein) [reply nexus/src/app/sagas/instance_update/start.rs:316]: I hear ya on this - I would also consider it a "bug" if we had an artificial 30 seconds added between "instance could/should be reincarnated" and "it actually is re-incarnated". Not a bad bug, because of the eventuality of the background task! but still, one we could have a regression test against.

all that said, definitely don't want to get in the way of fixing a flake
