### PR TITLE
Fix external subnet creation error handling and enforce pool-silo linking

### LINKED ISSUE #9872: Incorrect error returned by external subnet creation when pool doesn't exist
I specified a non-existing pool and found the error returned misleading:
```
oxide external-subnet create --project angela --json-body ~/subnet-create-alt-pool.json 
error
Error Response: status: 400 Bad Request; headers: {"content-type": "application/json", "x-request-id": "1f5b18f7-ecaa-45f9-9b27-a43a98bb917b", "date": "Tue, 17 Feb 2026 23:16:27 GMT", "content-length": "165"}; value: Error { error_code: Some("InvalidRequest"), message: "All subnets are used in the Subnet Pool with name 'xxxx'", request_id: "1f5b18f7-ecaa-45f9-9b27-a43a98bb917b" }
```

### LINKED ISSUE #9873: 500 error returned by external subnet creation when there is a name conflict
I used a subnet name that already existed but the API returned 500 instead of a 409: 
```
oxide external-subnet create --project angela --json-body ~/subnet-create-auto.json 
error
Error Response: status: 500 Internal Server Error; headers: {"content-type": "application/json", "x-request-id": "be75e431-840f-4c50-b617-0ae954defb25", "date": "Tue, 17 Feb 2026 20:36:20 GMT", "content-length": "124"}; value: Error { error_code: Some("Internal"), message: "Internal Server Error", request_id: "be75e431-840f-4c50-b617-0ae954defb25" }
```

### PR DESCRIPTION
**Pull request by david-crespo**
Closes #9872
Closes #9873

This turned out to be a lot more interesting than I expected. Three bugs fixed:

1. The `ensure_silo_is_linked_to_pool` CTE was not `MATERIALIZED` and not referenced by any downstream CTE, so CockroachDB never evaluated it. This meant pool-silo linking was never enforced on the Auto/Explicit allocation path. Adding `MATERIALIZED` fixes both the nonexistent pool error (#9872, since a nonexistent pool is trivially not linked) and starts enforcing pool-silo linking for the first time on this path.

2. The sentinel value in the CTE was bound as a query parameter (`$N`) instead of being embedded directly in the SQL. CockroachDB error messages contain the literal placeholder, so `is_bool_parse_error` never matched.

3. The error decoder did not handle `DatabaseErrorKind::UniqueViolation`, so name conflicts fell through to `ErrorHandler::Server` (500). Now returns `ObjectAlreadyExists`.

Also fixes the error decoder to construct the 404 directly via `LookupType::into_not_found` instead of routing through `public_error_from_diesel`, which would return 500 for `DatabaseError` variants.

Updates all tests to use a helper that creates and links a pool in one call, matching the pattern used by IP pool tests.

### CODE REVIEW

File: nexus/tests/integration_tests/external_subnets.rs [hunk 1]
```diff
@@ -802,3 +813,134 @@ async fn detach_external_subnet(
...
+    };
+    let error = object_create_error(
+        client,
+        &external_subnets_url(PROJECT_NAME),
+        &create_params,
+        StatusCode::NOT_FOUND,
+    )
+    .await;
+    assert_eq!(error.error_code.as_deref(), Some("ObjectNotFound"));
+}
```
Comment (david-crespo) [inline nexus/tests/integration_tests/external_subnets.rs:946]: This test fails on main (201 instead of the expected 404). This is here to make sure our reliance out `MATERIALIZED` is not misplaced in the future.

File: nexus/db-queries/tests/output/insert_external_subnet_from_explicit_pool.sql [hunk 2]
```diff
@@ -16,7 +16,7 @@ WITH
               )
             ),
             'true',
-            '$3'
+            'pool-not-linked'
```
Comment (david-crespo) [inline nexus/db-queries/tests/output/insert_external_subnet_from_explicit_pool.sql:19]: I find Claude's explanation here persuasive. This hard-coding of `pool-not-linked` is not strictly necessary for fixing the problem of being able to allocate from an unlinked pool (`as MATERIALIZED` does that), but it is necessary for detecting that error in order to convert it properly from a 500 to a 404.

<details>
<summary>Claude's explanation</summary>

The sentinel string `REQUESTED_POOL_NOT_LINKED_TO_SILO_SENTINEL` ("pool-not-linked") was previously passed as a bind parameter (`.param().bind::<sql_types::Text, _>(...)`), which made it show up as `$3` in the generated SQL. The change inlines it as a SQL literal (`.sql(REQUESTED_POOL_NOT_LINKED_TO_SILO_SENTINEL)`).

The reason: when CockroachDB fails to parse the sentinel as a bool, the error message contains the literal text it tried to parse. If it's a bind parameter, the error message contains `$3`, not `pool-not-linked`. The error decoding logic (`is_bool_parse_error`) matches on the sentinel string in the error message, so with `$3` it wouldn't match and the error would fall through to a generic 500 instead of producing the intended "pool not linked" error.

This is the same bug pattern that the `external_subnet_create_unlinked_pool` test caught — on main without MATERIALIZED, the CTE was elided entirely, but even with MATERIALIZED, the sentinel-as-bind-param issue would have caused the error to be misclassified.

</details>

<details>
<summary>Codex's concurrence</summary>

The explanation is substantively correct.

`$3` showed up because the sentinel was previously emitted via `.param().bind(...)`, so Diesel rendered it as a positional placeholder in the SQL string it logs/expectorates; switching to `.sql(REQUESTED_POOL_NOT_LINKED_TO_SILO_SENTINEL)` inlines the actual text, so the expectorated SQL contains `'pool-not-linked'` instead.

The “why” is also right given the current decoder: `is_bool_parse_error()` does an exact string equality check against `could not parse "<sentinel>" as type bool: invalid bool value` (see `nexus/db-queries/src/db/queries/external_subnet.rs:1215`). If CockroachDB’s error message contains `"$3"` (placeholder) instead of `"pool-not-linked"`, it won’t match and the error will be treated as an internal server error.

On necessity: it’s not strictly necessary to prevent the unauthorized behavior (that’s the `MATERIALIZED`/forced-evaluation part), but it is necessary for the current “sentinel in bool-parse error message” mechanism to reliably classify the error as the intended NotFound instead of a 500. The only way to avoid inlining would be to change the classification approach (e.g., stop depending on the literal error message).

</details>
