### PR TITLE
Pick a non-expunged clone source

### LINKED ISSUE #7209: Read-only region clone attempting to contact expunged downstairs
The following region snapshot replacement is not making forward progress:

```
262313d2-72ef-482d-b750-1c9115d74d59:

                    started: 2024-12-05 01:33:05.919898 UTC
                      state: Allocating
            region snapshot: 3ec0e848-39de-495e-be0e-88241e11d0fb 2bf499e2-a4f4-4e2e-9977-875f4914a7ce 39618f4c-0040-4a8b-9faf-0391a560d960
              new region id: None
     in-progress steps left: 0
```

Looking at a corresponding `region-snapshot-replacement-start` saga invocation shows that the `new_region_ensure` node is failing:

```
d56b625d-1ada-4cd5-bde1-8318abbd951c | 2024-12-05T06:42:01.865Z |          |   5: region_snapshot_replacement_start.find_new_region         | succeeded     | "new_dataset_and_region" => [{"compression":null,"identity":{"id":"46d1afcc-cc3f-4b17-aafc-054dd4862d15","time_created":"2023-08-30T18:59:10.758515Z","time_modified":"2023-08-30T18:59:10.758515Z"},"ip":"fd00:1122:3344:106::5","kind":"Crucible","pool_id":"7f778610-7328-4554-98f6-b17f74f551c7","port":32345,"quota":null,"rcgen":1,"reservation":null,"size_used":341449900032,"time_deleted":null,"zone_name":null},{"block_size":512,"blocks_per_extent":131072,"dataset_id":"46d1afcc-cc3f-4b17-aafc-054dd4862d15","deleting":false,"extent_count":16,"identity":{"id":"b9a2d268-de4d-43d0-a8b8-69e1b2f47791","time_created":"2024-12-05T06:42:01.228607Z","time_modified":"2024-12-05T06:42:01.228607Z"},"port":null,"read_only":true,"volume_id":"9d6ff72d-fb95-42e2-9765-0ff3eb103636"}]
d56b625d-1ada-4cd5-bde1-8318abbd951c | 2024-12-05T06:42:01.871Z |          |   6: region_snapshot_replacement_start.new_region_ensure       | started       | 
d56b625d-1ada-4cd5-bde1-8318abbd951c | 2024-12-05T06:42:17.866Z |          |   6: region_snapshot_replacement_start.new_region_ensure       | failed        | "ensured_dataset_and_region" => {"ActionFailed":{"source_error":{"InternalError":{"internal_message":"Failed to create region, unexpected state: Failed"}}}}
```

This step is responsible for creating a new cloned read-only region that will be used to replace the region snapshot. It uses the region snapshot's region as the source of the clone, but if that region is on an expunged dataset then this clone will never succeed. Tracing through to the crucible agent logs shows this:

```
BRM42220006 # cat /pool/ext/cf14d1b9-b4db-4594-b3ab-a9957e770ce9/crypt/debug/oxz_crucible_46d1afcc-cc3f-4b17-aafc-054dd4862d15/oxide-crucible-agent:default.log.1733391340 | looker -o long | less

06:42:02.123Z INFO crucible: Connecting to [fd00:1122:3344:124::22]:23001 to obtain our extent files.
    task = clone

Error: Failed to get source region definition: Communication Error: error sending request for url (http://[fd00:1122:3344:124::22]:23001/region-info)

BRM42220006 # ping fd00:1122:3344:124::22
ping: sendto No route to host
```

This sled is gone:

```
root@[fd00:1122:3344:105::3]:32221/omicron> select serial_number,sled_policy from sled where ip::TEXT like '%fd00:1122:3344:124%';
  serial_number | sled_policy
----------------+--------------
  BRM23230018   | expunged
(1 row)
```

The fix for this is to choose any other region that shares the snapshot id which is not expunged. Each region snapshot that shares that snapshot id will be exactly the same and can be used as a clone source.

### PR DESCRIPTION
**Pull request by jmpesp**
When performing region snapshot replacement, the associated start saga chose the request's region snapshot as the clone source, but if that region snapshot was backed by an expunged dataset then it may be gone.

This commit adds logic to choose another clone source, either another region snapshot from the same snapshot, or one of the read-only regions for that snapshot.

Basic sanity tests were added for ensuring that region replacements and region snapshot replacements resulting from expungement can occur. It was an oversight not to originally include these! Rn order to support these new sanity tests, the simulated pantry has to fake activating volumes in the background. This commit also refactors the simulated Pantry to have one Mutex around an "inner" struct instead of many Mutexes.

Fixes #7209

### CODE REVIEW

File: nexus/src/app/sagas/region_snapshot_replacement_start.rs [hunk 1]
```diff
@@ -265,6 +270,145 @@ async fn rsrss_set_saga_id_undo(
...
+        .map_err(ActionError::action_failed)?;
+
+    let clone_source = if request_dataset_on_in_service_physical_disk {
+        // If the request region snapshot's dataset has not been expunged,
+        // it can be used
+        CloneSource::RegionSnapshot {
+            dataset_id: params.request.old_dataset_id.into(),
+            region_id: params.request.old_region_id,
+        }
+    } else {
```
Comment (leftwo) [inline nexus/src/app/sagas/region_snapshot_replacement_start.rs:308]: So, if I'm following correclty, we land here with an expected source (`request.old_dataset_id, `request.old_region_id`) But we need to verify that it's not expunged yet, right?

File: nexus/src/app/sagas/region_snapshot_replacement_start.rs [hunk 2]
```diff
@@ -265,6 +270,145 @@ async fn rsrss_set_saga_id_undo(
...
+        info!(
+            log,
+            "request region snapshot dataset expunged, finding another";
+            "snapshot_id" => %params.request.old_snapshot_id,
+            "dataset_id" => %params.request.old_dataset_id,
+        );
+
+        // Select another region snapshot that's part of this snapshot - they
+        // will all have identical contents.
```
Comment (leftwo) [inline nexus/src/app/sagas/region_snapshot_replacement_start.rs:317]: Do I understand where we are correctly here:

We have a snapshot with a failed downstairs we want to replace.
We have chosen another downstairs target to clone from, but we then discovered that source was on an expunged disk?
So now we are going to try and get that third (final) downstairs as a source?

**Review by leftwo — COMMENTED** [review]
I have some questions to be sure I'm following along here.

File: nexus/db-queries/src/db/datastore/region_snapshot.rs [hunk 3]
```diff
@@ -120,4 +120,40 @@ impl DataStore {
             .await
             .map_err(|e| public_error_from_diesel(e, ErrorHandler::Server))
     }
+
+    /// Find region snapshots not on expunged disks that match a snapshot id
+    pub async fn find_non_expunged_region_snapshots(
```
[the remark this answers is not in the document]
Comment (jmpesp) [reply nexus/db-queries/src/db/datastore/region_snapshot.rs:125]: Yeah, the inverse of this would be finding all expunged region snapshots, which something like the region snapshot replacement start background task does do. But I'm not sure about including both

File: nexus/db-queries/src/db/datastore/region.rs [hunk 4]
```diff
@@ -548,6 +548,42 @@ impl DataStore {
 
         Ok(records)
     }
+
+    /// Find regions not on expunged disks that match a volume id
+    pub async fn find_non_expunged_regions(
```
[the remark this answers is not in the document]
Comment (jmpesp) [reply nexus/db-queries/src/db/datastore/region.rs:553]: > For the region who will be created using this source, we do care that it's (if possible) on a sled that does not have any of the other downstairs, but that's not something we care about here, correct?

Yeah, that'd be the concern of the region allocation that occurs later in this saga :)

File: nexus/src/app/sagas/region_snapshot_replacement_start.rs (hunk 2 above)
Comment (jmpesp) [reply nexus/src/app/sagas/region_snapshot_replacement_start.rs:317]: Exactly yeah!

File: nexus/src/app/sagas/region_snapshot_replacement_start.rs (hunk 1 above)
Comment (jmpesp) [reply nexus/src/app/sagas/region_snapshot_replacement_start.rs]: Yep, though this function changed a bit as a result of our call :)

File: nexus/src/app/sagas/region_snapshot_replacement_start.rs [hunk 5]
```diff
@@ -265,6 +270,147 @@ async fn rsrss_set_saga_id_undo(
...
+}
+
+async fn rsrss_get_clone_source(
+    sagactx: NexusActionContext,
+) -> Result<CloneSource, ActionError> {
+    let params = sagactx.saga_params::<Params>()?;
+    let osagactx = sagactx.user_data();
+    let log = osagactx.log();
+
+    // If the downstairs we're cloning from is on an expunged dataset, the clone
```
Comment (leftwo) [inline nexus/src/app/sagas/region_snapshot_replacement_start.rs:286]: just update this comment to what we discussed over chat

**Review by leftwo — APPROVED** [review]
🚀

**Review by leftwo — APPROVED** [review]
Still ship it!
