### PR TITLE
[sled-agent] Unbreak handling of Propolis error codes

### LINKED ISSUE #3209: sled agent should terminate Propolis zones when Propolis indicates a previously-started VM has gone missing
An instance on rack2 appeared to be stuck because:
- propolis-server panicked
- the propolis-server service was restarted by SMF (its restarter is `svc:/system/svc/restarter:default`)
- sled-agent failed to notice that propolis-server had panicked (#3206), and the instance was still marked as running
- a new propolis-server ran, and requests from the serial console in the web console continued, but there was no instance, so the console seemed to hang

It isn't clear to me that restarting propolis-server is the right thing to do here. We should consider having the service go into maintenance and not restart when that happens.

Related: #2825

### LINKED ISSUE #3238: sled agent and Nexus frequently flatten errors into 500 Internal Server Error
Sled agent has a relatively rich set of internal error types, but at the Dropshot HTTP error boundary, it converts almost all of them to 500 errors:

https://github.com/oxidecomputer/omicron/blob/cab09253e6e6e27761d1ef99f8087f86ccad2e8b/sled-agent/src/sled_agent.rs#L102-L137

This makes it hard for callers to reason about the cause or permanence of any of these errors. This was a pebble in the shoe of PR #2892 and is coming up again in #3230 (sled agent is making a call to Nexus whose response depends in part on calls back down into sled agent, and there's no way to be sure about the permanence of any errors returned from Nexus in that path because all errors are getting flattened into a single error code).

There are similar paths through Nexus that flatten errors this way that the fix for #3230 will have to take into account:

- Updating instance state can update the instance's Dendrite configuration: https://github.com/oxidecomputer/omicron/blob/cab09253e6e6e27761d1ef99f8087f86ccad2e8b/nexus/src/app/instance.rs#L1138-L1144
- `instance_ensure_dpd_config` calls `dpd_client.ensure_nat_entry` and maps all errors to 500s: https://github.com/oxidecomputer/omicron/blob/cab09253e6e6e27761d1ef99f8087f86ccad2e8b/nexus/src/app/instance.rs#L1243-L1259
- `ensure_nat_entry` calls Dendrite daemon routines that can (I presume) produce transient failures (e.g. transient communication failures), e.g.: https://github.com/oxidecomputer/omicron/blob/cab09253e6e6e27761d1ef99f8087f86ccad2e8b/dpd-client/src/lib.rs#L111-L127

Revisiting absolutely every single error conversion in sled agent and Nexus all at once is probably a non-starter, but we can likely start by improving sled agent's internal-error-to-Dropshot-error conversion and look for opportunities to remove other error-flattening cases as they arise.

### PR DESCRIPTION
**Pull request by hawkw**
At present, sled-agent's handling of the error codes used by Propolis to
indicate that it has crashed and been restarted is woefully incorrect.
In particular, there are two cases where such an error may be
encountered by a sled-agent:

1. When attempting to ask the VMM to change state (e.g. reboot or stop
   the instance)
2. When hitting Propolis' `instance-state-monitor` API endpoint to
   proactively check the VM's current state

Neither of these are handled correctly today,

In the first case, if a sled-agent operation on behalf of Nexus
encounters a client error from Propolis, it will forward that error code
to Nexus...but, _Nexus_ only moves instances to `Failed` in the face of
sled-agent's `410 NO_SUCH_INSTANCE`, and _not_ [if it sees the
`NoInstance` error code from Propolis][1], which means that the ghosts
left behind by crashed and restarted Propolii still won't be moved to
`Failed`. Agh. Furthermore, in that case, sled-agent itself will not
perform the necessary cleanup actions to deal with the now-defunct
Propolis zone (e.g. collecting a zone bundle and then destroying the
zone).

In the second case, where we hit the instance-state-monitor endpoint and
get back a `NoInstance` error, things are equally dire. The
`InstanceMonitorRunner` task, which is responsible for polling the state
monitor endpoint, will just bail out on receipt of any error from
Propolis:
https://github.com/oxidecomputer/omicron/blob/888f6a1eae91e5e7091f2e174dec7a8ee5bd04b5/sled-agent/src/instance.rs#L253-L289

We would _expect_ this to drop the send-side of the channel it uses to
communicate with the `InstanceRunner`, closing the channel, and hitting
this select, which would correctly mark the VMM as failed and do what we
want, despite eating the actual error message from propolis:
https://github.com/oxidecomputer/omicron/blob/888f6a1eae91e5e7091f2e174dec7a8ee5bd04b5/sled-agent/src/instance.rs#L388-L394

HOWEVER, as the comment points out, the `InstanceRunner` is _also_
holding its own clone of the channel sender, keeping us from ever
hitting that case:
https://github.com/oxidecomputer/omicron/blob/888f6a1eae91e5e7091f2e174dec7a8ee5bd04b5/sled-agent/src/instance.rs#L308-L309

AFAICT, this means we'll just totally give up on monitoring the instance
as soon as we hit any error here, which seems...quite bad. I *think*
that this actually means that when a Propolis process crashes
unexpectedly, we'll get an error when the TCP connection closes, bail
out, and then _never try hitting the instance monitor endpoint ever
again_[^1]. So, we won't notice that the Propolis is actually out to
lunch until we try to ask it to change state. **This Is Not Great!**

This commit fixes both of these cases, by making sled-agent actually
handle Propolis' error codes correctly. I've added a dependency on the
`propolis_api_types` crate, which is where the error code lives, and
some code in sled-agent to attempt to parse these codes when receiving
an error response from the Propolis client. Now, when we try to PUT a
new state to the instance, we'll look at the error code that comes back,
mark it as `Failed` if the error indicates that we should do so, and
publish the `Failed` VMM state to Nexus before tearing down the zone.
The `InstanceMonitorTask` now behaves similarly, and I've changed it to
retry all other errors with a backoff, rather than just bailing out
immediately on receipt fo the first error.

I've manually tested this on `london` as discussed here:
https://github.com/oxidecomputer/omicron/pull/6726#issuecomment-2384012654

Unfortunately, it's hard to do any kind of automated testing of this
with the current test situation, as none of this code is exercised by
the simulated sled-agent.

Fixes #3209
Fixes #3238

[^1]: Although I've not actually verified that this is what happens.

[1]:
    https://github.com/oxidecomputer/propolis/blob/516dabe473cecdc3baea1db98a80441968c144cf/crates/propolis-api-types/src/lib.rs#L434-L441

### CODE REVIEW

**Comment by hawkw** [comment]
[`helios-deploy` CI failure](https://github.com/oxidecomputer/omicron/runs/30870016717) looks like timesync badness again: https://buildomat.eng.oxide.computer/wg/0/artefact/01J91ZNH8EG1FZF6P13HVDW7G2/X6nkLZG8fI0eo7zJjaGBT4LAQIcZnulGhaqf5r2iUSG3dbkZ/01J91ZP39V6PYJ5TB4FNYY2JE0/01J922ZA9WCDEF1DX5JBHGGR8X/oxide-sled-agent:default.log?format=x-bunyan#L915

Will restart that and see if it's still busted.

File: sled-agent/src/instance.rs [hunk 1]
```diff
@@ -385,6 +433,34 @@ impl InstanceRunner {
                                 warn!(self.log, "InstanceRunner failed to send to InstanceMonitorRunner");
                             }
                         },
+                         Some(InstanceMonitorRequest { update: Error(code), tx }) => {
+                            // TODO(eliza): this is kinda jank but Propolis
+                            // currently could return the same error when the
+                            // instance has not been ensured and when it's still
+                            // coming up, which is sad. I'm not sure whether
+                            // that happens IRL or not --- investigate this.
+                            let reaction = if has_ever_seen_a_good_state {
```
Comment (hawkw) [inline sled-agent/src/instance.rs:442]: This extra junk is because I noticed that Propolis' instance-state-monitor endpoint will presently return the `NoInstance` error on both `VmError::NotCreated` _and_ `VmError::WaitingToInitialize`:

https://github.com/oxidecomputer/propolis/blob/11371b0f3743f8df5b047dc0edc2699f4bdf3927/bin/propolis-server/src/lib/server.rs#L397-L399

This gave me some anxiety about sled-agent potentially deciding that a Propolis has "died" while it's actually still waiting to be born, although I'm not sure whether we would actually see the `WaitingToInitialize` error there in practice or not. I think the proper thing to do would be to change that behavior in Propolis, but I wanted to get something working in sled-agent regardless.

File: sled-agent/src/instance.rs [hunk 2]
```diff
@@ -385,6 +433,34 @@ impl InstanceRunner {
...
+                                info!(
+                                    self.log,
+                                    "Error code from Propolis after instance initialized, assuming it's gone";
+                                    "error" => ?code,
+                                );
+                                self.terminate(true).await;
+                                self.publish_state_to_nexus().await;
```
Comment (hawkw) [inline sled-agent/src/instance.rs:449]: This is probably why we sent the failed state to nexus twice in my [manual testing](https://github.com/oxidecomputer/omicron/pull/6726#issuecomment-2384012654), so I think it can be removed.

File: sled-agent/src/instance.rs (hunk 1 above)
Comment (hawkw) [reply sled-agent/src/instance.rs:442]: after actually looking in Propolis, it looks like the `Vm::state_watcher()` function will never actually return `VmError::WaitingToInitialize`; it will only return `VmError::NotCreated`: 
https://github.com/oxidecomputer/propolis/blob/11371b0f3743f8df5b047dc0edc2699f4bdf3927/bin/propolis-server/src/lib/vm/mod.rs#L353-L364

So, hitting the state-monitor endpoint should just return a `Starting` VMM state in that case, which is good. I still don't like that the method _can_ return any of the error types, though, even though it doesn't currently --- I'll go try to clean that up on the Propolis side.

Comment (hawkw) [reply sled-agent/src/instance.rs:442]: Okay, https://github.com/oxidecomputer/propolis/pull/771 will make the propolis side way less scary. But I think this code can also just be removed as propolis' current behavior is also correct.

**Comment by hawkw** [comment]
I'm going to redo my manual testing from https://github.com/oxidecomputer/omicron/pull/6726#issuecomment-2384012654 with the latest changes from b59cfc1102d1fa4e9eb40a0c996a0cae651ecd4e, but I'm pretty sure that it'll still work. Figured it was worth making sure, though.

File: sled-agent/src/instance.rs [hunk 3]
```diff
@@ -960,6 +1041,29 @@ impl InstanceRunner {
...
+    log: &slog::Logger,
+    error: &PropolisClientError,
+) -> Option<PropolisErrorCode> {
+    // Is this a structured error response from the Propolis server?
+    let propolis_client::Error::ErrorResponse(ref rv) = &error else {
+        return None;
+    };
+
+    let code = rv.error_code.as_deref()?;
+    match code.parse::<PropolisErrorCode>() {
```
Comment (ahl) [inline sled-agent/src/instance.rs:1054]: This is interesting. It suggest we might want a structured error response from dropshot if we're interested in taking discrete actions depending on those values.

File: Cargo.toml [hunk 4]
```diff
@@ -512,6 +512,9 @@ proc-macro2 = "1.0"
 progenitor = "0.8.0"
 progenitor-client = "0.8.0"
 bhyve_api = { git = "https://github.com/oxidecomputer/propolis", rev = "fae5334bcad5e864794332c6fed5e6bb9ec88831" }
+# TODO(eliza): `propolis-client` should maybe re-export the needed types from
```
Comment (ahl) [inline Cargo.toml:515]: Perhaps this is a note to yourself as you self-review, but I'd suggest either do that in propolis and then implement this fix, or don't and leave out this note.

Regardless, I think a better approach would be to (somehow) include the `ErrorCode` type in the `propolis-server.json` file so that we had a generated type for it. i.e. rather than adding a new dependency into the tree.

File: sled-agent/src/instance.rs [hunk 5]
```diff
@@ -248,51 +253,92 @@ enum InstanceRequest {
...
+                        "retry_in" => ?delay,
+                        "generation" => generation,
+                    );
+                },
+            )
+            .await?;
+
+            // Update the state generation for the next poll.
+            if let InstanceMonitorUpdate::State(ref state) = update {
+                generation = state.r#gen + 1;
```
Comment (ahl) [inline sled-agent/src/instance.rs:280]: oh no, is this now required or are you futureproofing against the `gen` keyword?

**Review by ahl — COMMENTED** [review]
I'd suggest @pfmooney take a look.

Perhaps something like https://github.com/oxidecomputer/dropshot/issues/39 would better allow propolis to communicate actionable errors.

**Review by gjcolombo — APPROVED** [review]

File: sled-agent/src/instance.rs [hunk 6]
```diff
@@ -1358,7 +1462,28 @@ impl InstanceRunner {
...
+                    ) => {
+                        error!(self.log,
+                            "Propolis error code indicates VMM failure";
+                            "code" => ?code,
+                        );
+                        self.terminate(true).await;
+                        // We've transitioned to `Failed`, so just return the
+                        // failed state normally. We return early here instead
+                        // of falling through because we don't want to overwrite
+                        // that with the published VMM state determined above.
```
Comment (smklein) [inline sled-agent/src/instance.rs:1479]: Nitpick, could we be more clear about what "that" is here? `self.state`?

File: Cargo.toml [hunk 7]
```diff
@@ -512,6 +512,9 @@ proc-macro2 = "1.0"
...
+# this crate?
```
Comment (smklein) [inline Cargo.toml:516]: Yeah, this makes sense to me, they seem pretty tightly coupled

File: sled-agent/src/instance.rs [hunk 8]
```diff
@@ -130,6 +131,10 @@ pub enum Error {
     Terminating,
 }
 
+// Make this less gross.
```
Comment (smklein) [inline sled-agent/src/instance.rs:134]: I might delete this comment, unless you have something more actionable in mind -- this is pretty standard for progenitor error types, right?

**Review by smklein — APPROVED** [review]

File: sled-agent/src/instance.rs (hunk 3 above)
Comment (hawkw) [reply sled-agent/src/instance.rs:1054]: Yeah, I stumbled across oxidecomputer/dropshot#39 (which you referenced above) and the related oxidecomputer/dropshot#41 way back when I originally added these error codes to Propolis (see https://github.com/oxidecomputer/propolis/pull/649#discussion_r1499913263), and I think having a first-class mechanism for structured serializable/deserializable error code types in Dropshot/Progenitor would have made all of this much nicer. 

I don't want to hold up the short term fix for sled-agent totally failing to handle these errors on getting that into Dropshot, but it's definitely the better long-term solution.

File: sled-agent/src/instance.rs (hunk 5 above)
Comment (hawkw) [reply sled-agent/src/instance.rs:280]: This is just futureproofing --- we're still on Rust 2021. I believe the suggestion from [RFD 500](https://rfd.shared.oxide.computer/rfd/0500#gen) was that any new code use `generation` and that anyone changing code that uses `gen` was encouraged to update it, so I've been trying to make a habit of that.

File: Cargo.toml (hunk 4 above)
Comment (hawkw) [reply Cargo.toml]: Oh, that's a good suggestion, I'll look into figuring out how to add it to the OpenAPI document even though it doesn't actually appear in any of the OpenAPI endpoints directly. 

That said, I'd prefer to do that in a separate change as I think fixing the currently broken behavior is urgent enough that I'd like to land this PR as soon as possible, to make sure it gets in for the release. I've removed the comment for now, and then I'll try to get this into the generated client and come back and remove then dep.

Comment (hawkw) [reply Cargo.toml]: AFAICT, adding schemas for additional types to a Dropshot-generated OpenAPI document will probably require re-parsing the JSON, sticking the new schema in the correct place, and re-serializing it. I'm not really sure if it's worth the effort to do that just for this one case when we could, alternatively, spend that time actually changing Dropshot to allow specifying error body types more generally (e.g. oxidecomputer/dropshot#39, oxidecomputer/dropshot#41)?

File: sled-agent/src/instance.rs (hunk 8 above)
Comment (ahl) [reply sled-agent/src/instance.rs]: Agreed; progenitor is great.

File: Cargo.toml (hunk 4 above)
Comment (hawkw) [reply Cargo.toml]: Opened https://github.com/oxidecomputer/propolis/issues/775 to track this.

**Comment by hawkw** [comment]
Okay, I've re-tested this after the Dogfood update to c50cf019cd9be35f98266a7f4acacab0236b3a3d, and it definitely still works --- if I restart a `propolis_server` process, the instance gets reincarnated pretty much immediately:

```console
#
# in the switch zone, inspecting my newly created test instance
#
root@oxz_switch0:~# omdb db instance info cb44ae27-befb-424a-b9f1-087ac9d0c898
note: database URL not specified.  Will search DNS.
note: (override with --db-url or OMDB_DB_URL)
note: using DNS server for subnet fd00:1122:3344::/48
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using database URL postgresql://root@[fd00:1122:3344:109::3]:32221,[fd00:1122:3344:105::3]:32221,[fd00:1122:3344:10b::3]:32221,[fd00:1122:3344:107::3]:32221,[fd00:1122:3344:108::3]:32221/omicron?sslmode=disable
note: database schema version matches expected (107.0.0)

== INSTANCE ====================================================================
                        ID: cb44ae27-befb-424a-b9f1-087ac9d0c898
                project ID: 50d839b4-2d18-49c0-94cf-7d6883e00178
                      name: test-instance-please-ignore
               description: let's see what happens when propolis crashes
                created at: 2024-10-02 21:10:26.781544 UTC
          last modified at: 2024-10-02 21:10:26.781544 UTC

== CONFIGURATION ===============================================================
                     vCPUs: 2
                    memory: 8 GiB
                  hostname: test-instance-please-ignore
                 boot disk: None
              auto-restart:
                  InstanceAutoRestart {
                      policy: None,
                      cooldown: None,
                  }

== RUNTIME STATE ===============================================================
               nexus state: Vmm
(i)     external API state: Running
           last updated at: 2024-10-02T21:10:26.781544Z (generation 3)
       needs reincarnation: false
             karmic status: bound to saṃsāra
      last reincarnated at: None
             active VMM ID: Some(89437bf4-da6b-441d-bc9c-c9344b6893e3)
             target VMM ID: None
              migration ID: None
              updater lock: UNLOCKED at generation: 1

         active VMM record:
             Vmm {
                 id: 89437bf4-da6b-441d-bc9c-c9344b6893e3,
                 time_created: 2024-10-02T21:10:30.927858Z,
                 time_deleted: None,
                 instance_id: cb44ae27-befb-424a-b9f1-087ac9d0c898,
                 sled_id: 5f6720b8-8a31-45f8-8c94-8e699218f28b,
                 propolis_ip: V6(
                     Ipv6Network {
                         addr: fd00:1122:3344:109::1:4f6,
                         prefix: 128,
                     },
                 ),
                 propolis_port: SqlU16(
                     12400,
                 ),
                 runtime: VmmRuntimeState {
                     time_state_updated: 2024-10-02T21:10:41.851556Z,
                     gen: Generation(
                         Generation(
                             4,
                         ),
                     ),
                     state: Running,
                 },
             }
#
# log into the instance's sled and restart its propolis-server
#
root@oxz_switch0:~# pilot host login BRM42220017

    #####
   ##   ##
  ##   # ##  ##   ##
  ##  #  ##   ## ##     Oxide Computer Company
  ## #   ##    ###      Engineering
   ##   ##    ## ##
    #####    ##   ##    Gimlet

BRM42220017 # zlogin oxz_propolis-server_89437bf4-da6b-441d-bc9c-c9344b6893e3
[Connected to zone 'oxz_propolis-server_89437bf4-da6b-441d-bc9c-c9344b6893e3' pts/3]
root@oxz_propolis:~# svcadm restart svc:/system/illumos/propolis-server:default
root@oxz_propolis:~#
[Connection to zone 'oxz_propolis-server_89437bf4-da6b-441d-bc9c-c9344b6893e3' pts/3 closed]
BRM42220017 # exit
#
# instance is restarted successfully!
#
root@oxz_switch0:~# omdb db instance info cb44ae27-befb-424a-b9f1-087ac9d0c898
note: database URL not specified.  Will search DNS.
note: (override with --db-url or OMDB_DB_URL)
note: using DNS server for subnet fd00:1122:3344::/48
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using database URL postgresql://root@[fd00:1122:3344:109::3]:32221,[fd00:1122:3344:105::3]:32221,[fd00:1122:3344:10b::3]:32221,[fd00:1122:3344:107::3]:32221,[fd00:1122:3344:108::3]:32221/omicron?sslmode=disable
note: database schema version matches expected (107.0.0)

== INSTANCE ====================================================================
                        ID: cb44ae27-befb-424a-b9f1-087ac9d0c898
                project ID: 50d839b4-2d18-49c0-94cf-7d6883e00178
                      name: test-instance-please-ignore
               description: let's see what happens when propolis crashes
                created at: 2024-10-02 21:10:26.781544 UTC
          last modified at: 2024-10-02 21:10:26.781544 UTC

== CONFIGURATION ===============================================================
                     vCPUs: 2
                    memory: 8 GiB
                  hostname: test-instance-please-ignore
                 boot disk: None
              auto-restart:
                  InstanceAutoRestart {
                      policy: None,
                      cooldown: None,
                  }

== RUNTIME STATE ===============================================================
               nexus state: Vmm
(i)     external API state: Starting
           last updated at: 2024-10-02T21:14:44.002990Z (generation 5)
       needs reincarnation: false
/!\          karmic status: cooling down (TimeDelta { secs: 3589, nanos: 929383990 } remaining)
      last reincarnated at: Some(2024-10-02T21:14:45.996494Z)
             active VMM ID: Some(9111dfe7-0d55-4c6b-a72c-1f35ba9b5fc2)
             target VMM ID: None
              migration ID: None
              updater lock: UNLOCKED at generation: 4

         active VMM record:
             Vmm {
                 id: 9111dfe7-0d55-4c6b-a72c-1f35ba9b5fc2,
                 time_created: 2024-10-02T21:14:45.918847Z,
                 time_deleted: None,
                 instance_id: cb44ae27-befb-424a-b9f1-087ac9d0c898,
                 sled_id: f15774c1-b8e5-434f-a493-ec43f96cba06,
                 propolis_ip: V6(
                     Ipv6Network {
                         addr: fd00:1122:3344:105::1:5d5,
                         prefix: 128,
                     },
                 ),
                 propolis_port: SqlU16(
                     12400,
                 ),
                 runtime: VmmRuntimeState {
                     time_state_updated: 2024-10-02T21:14:46.684417Z,
                     gen: Generation(
                         Generation(
                             2,
                         ),
                     ),
                     state: Starting,
                 },
             }
root@oxz_switch0:~#
```
