### PR TITLE
Fix `omdb db disks info`

### LINKED ISSUE #9624: Allow omdb to work with different disk types
With the disk type schema change, `omdb db disks` no longer understands how to get the disk info:
```
root@oxz_switch0:~# omdb db disks info fff17edb-b345-42de-9a16-8f52fc6d42ea
Error: Object (of type ById(fff17edb-b345-42de-9a16-8f52fc6d42ea)) not found: disk
```

### PR DESCRIPTION
**Pull request by jmpesp**
`omdb db disks info` started failing due to a `LookupPath` check preventing the omdb OpContext from looking up arbitrary disks. Fix this by looking up the disk directly in the database in omdb, then splitting the existing `disk_get` into a version that accepts the Disk model directly.

Fixes #9624

### CODE REVIEW

File: nexus/db-queries/src/db/datastore/disk.rs [hunk 1]
```diff
@@ -310,6 +313,21 @@ impl DataStore {
...
             LookupPath::new(opctx, self).disk_id(disk_id).fetch().await?;
 
+        self.disk_get_with_model(opctx, disk).await
+    }
+
+    /// Return a `datastore::Disk` given a `model::Disk`
+    ///
+    /// Prefer to use `disk_get` instead: this version of the function bypasses
+    /// the LookupPath induced permissions check and is (currently) only called
+    /// from omdb.
```
Comment (hawkw) [inline nexus/db-queries/src/db/datastore/disk.rs]: maybe worth explicitly saying that nothing in Nexus should use this?

**Review by hawkw — APPROVED** [review]
seems reasonable to me!

File: nexus/db-queries/src/db/datastore/disk.rs (hunk 1 above)
Comment (jmpesp) [reply nexus/db-queries/src/db/datastore/disk.rs]: 089d95541 has some stronger language here
