### PR TITLE
set_target_release: Fail if setting target release to a pruned TUF repo

### LINKED ISSUE #9114: must not be able to set target release to a pruned release
This problem will be introduced by the ongoing work on pruning (#9109, #9107) and should be fixed before R17 release.

### PR DESCRIPTION
**Pull request by jgallagher**
Fixes #9114.

### CODE REVIEW

File: nexus/db-queries/src/db/datastore/target_release.rs [hunk 1]
```diff
@@ -262,4 +374,103 @@ mod test {
...
+        let err = InlineErrorChain::new(&err).to_string();
+        assert!(
+            err.contains("violates unique constraint"),
+            "unexpected error: {err}"
+        );
+
+        // Attempt to make repo2 the target release. This should fail with a
+        // reasonable error message (it's been pruned).
+        let err = datastore
+            .target_release_insert(
```
Comment (smklein) [inline nexus/db-queries/src/db/datastore/target_release.rs:431]: `target_release_insert` a UUID that does not exist?

Would it still claim to be pruned?

File: nexus/db-queries/src/db/datastore/target_release.rs [hunk 2]
```diff
@@ -77,12 +84,52 @@ impl DataStore {
...
+                    // target release.
+                    Ok(target_release)
+                }
+                None => {
+                    // Insertion succeeded but didn't return any rows: this is
+                    // how `insert_target_release_query` indicates that the
+                    // referenced repo is pruned.
+                    Err(Error::invalid_request(format!(
+                        "cannot make TUF repo {tuf_repo_id} the \
+                         target release: it has been pruned from the system"
```
Comment (smklein) [inline nexus/db-queries/src/db/datastore/target_release.rs:168]: Should this say "it does not exist or has been pruned from the system"?

Comment (jgallagher) [reply nexus/db-queries/src/db/datastore/target_release.rs:168]: I don't think so (and to your other comment, I omitted a test for this same reasoning); arguably, I should just remove the comments about nonexisted IDs. We have a strongly-typed `TufRepoId` UUID here, which _should_ mean something else has already confirmed that this ID is a real TUF repo. If we used hard foreign keys, we'd have one that would catch this, but in general we don't use them and rely on strongly-typed-UUIDs + doing the right thing.

In terms of this error message: it can only bubble out of the `target_release_update` external API. The input from the operator to that endpoint is a system version, not a UUID. The handler has to map that system version to a (known, good, existing) TUF repo ID before calling this function, so it should already be handling returning a reasonable message for "that repo doesn't exist".

Comment (smklein) [reply nexus/db-queries/src/db/datastore/target_release.rs:168]: > We have a strongly-typed `TufRepoId` UUID here, which _should_ mean something else has already confirmed that this ID is a real TUF repo.

Is there something about TUF repos that adds this property? This isn't true for most of our public APIs, which accept arbitrary user input, convert to strongly-typed UUIDs, and use them elsewhere.

AFAIK the "strongly-typed" aspect implies "this is a UUID which should only refer to Tuf Repos, as a type", not "this is a UUID which refers to a **real** TUF repo that is guaranteed to exist"

Comment (smklein) [reply nexus/db-queries/src/db/datastore/target_release.rs:168]: Ah, responded too quickly, perhaps. I see you're saying "based on how the caller uses this API right now, we expect this UUID to exist". Fair enough, but I think that's distinct from the properties guaranteed by the type system here.

Comment (jgallagher) [reply nexus/db-queries/src/db/datastore/target_release.rs:168]: > Is there something about TUF repos that adds this property? This isn't true for most of our public APIs, which accept arbitrary user input, convert to strongly-typed UUIDs, and use them elsewhere.

Yeah, as I said above we don't accept a UUID here at all:

> In terms of this error message: it can only bubble out of the target_release_update external API. The input from the operator to that endpoint is a system version, not a UUID. The handler has to map that system version to a (known, good, existing) TUF repo ID before calling this function, so it should already be handling returning a reasonable message for "that repo doesn't exist".

Comment (jgallagher) [reply nexus/db-queries/src/db/datastore/target_release.rs:168]: > Fair enough, but I think that's distinct from the properties guaranteed by the type system here.

Yeah, you're right. I still think it's not particularly useful to separate these cases? But if you disagree I can see if there's a way we can distinguish.

I'm also going to push up a change that switches this back to diesel - I realized after writing it by hand it's not bad at all there since this isn't a true CTE.

File: nexus/db-queries/src/db/datastore/target_release.rs [hunk 3]
```diff
@@ -77,12 +79,104 @@ impl DataStore {
...
+            // error message if we get back no rows.
+            let result = insert_into(dsl::target_release)
+                .values(selection)
+                .returning(TargetRelease::as_returning())
+                .get_result_async(&*conn)
+                .await
+                .optional()
+                .map_err(|e| {
+                    public_error_from_diesel(e, ErrorHandler::Server)
+                })?;
```
Comment (davepacheco) [inline nexus/db-queries/src/db/datastore/target_release.rs:155]: This is probably the same as it was before, but does this do something reasonable if the INSERT fails for some other reason (like the generation number was already inserted)?

Comment (jgallagher) [reply nexus/db-queries/src/db/datastore/target_release.rs:155]: Yeah, I added a test for exactly that case, which still causes the insertion to _fail_ with the same error it did before. The `.optional()` here only lets us handle "insert succeeded but returned 0 rows", which I believe can only be caused by the repo being pruned (the error we expect) or we got passed a UUID that isn't in the `tuf_repo` table at all (which would be a mistake somewhere else, and would only result in us claiming that the nonexistent repo was pruned instead of more clearly saying it doesn't exist).
