### PR TITLE
Drop OPTE port lock earlier

### LINKED ISSUE #10280: Failing to set external IPs can deadlock the OPTE port manager
It's possible that this call:

https://github.com/oxidecomputer/omicron/blob/0ef430324bbcc83b8fe3c733ce7629f2fd4faf93/illumos-utils/src/opte/port_manager.rs#L446

will deadlock the OPTE port manager. The following sequence of events can get you here (credit to @jgallagher):

1. we acquire the port lock on line 417
2. we create a PortTicket on line 418
3. if we bail out because of an error on 446, we'll drop the PortTicket before dropping the ports lock guard
4. but PortTicket's drop impl [also tries to acquire the lock via release_inner](https://github.com/oxidecomputer/omicron/blob/0ef430324bbcc83b8fe3c733ce7629f2fd4faf93/illumos-utils/src/opte/port_manager.rs#L1146)

We need to catch the error here; drop the lock guard; then propagate the error. This would let the drop impl for the port ticket to acquire it. There may be a better approach here too. This section of code has caused a few issues in the past, though thankfully none for a few years. We might want to reconsider a better architecture than the shared lock, acquired implicitly in the drop impl.

### PR DESCRIPTION
**Pull request by bnaecker**
Fixes a possible deadlock in the OPTE port manager. When failing to add external IPs for a new port, we both the `PortTicket` and a lock guard around the mananger's mapping of all ports. Unforunately, we do that in the wrong order: `PortTicket` first, which attempts to take that same lock in its drop implementation. This drops the port lock earlier, to avoid a deadlock.

Fixes #10280

### CODE REVIEW

File: illumos-utils/src/opte/port_manager.rs [hunk 1]
```diff
@@ -432,6 +432,12 @@ impl PortManager {
                 nic.kind,
             );
 
+            // NOTE: We may add external IPs below, which can fail. If that
+            // does, we drop the `ticket` on the way out of this block. That
+            // attempts to acquire this lock, in order to remove itself on drop.
+            // We need to drop the lock before that, to avoid a deadlock.
+            drop(ports);
```
Comment (jgallagher) [inline illumos-utils/src/opte/port_manager.rs]: Instead of having to explicitly drop this, could we scope the lock down to just the insert? I.e., don't take an explicit `let muts port = ...` guard at all, and change line 427 to

```rust
let old = self.inner.ports.lock().unwrap().insert(...);
````

which acquires the guard, does the insert, then immediately drops the guard?

I'd probably keep your comment but "lock reduced to the one operation we need it" seems nice.

Comment (bnaecker) [reply illumos-utils/src/opte/port_manager.rs]: Done in 440b37b2f

**Review by jgallagher — APPROVED** [review]

**Review by FelixMcFelix — APPROVED** [review]
Looks good; thanks for the quick turnaround!
