### PR TITLE
[nexus] Allow stopping `Failed` instances

### LINKED ISSUE #2825: Failed instances should be allowed to stop and restart
Currently Nexus accepts no attempts to change the state of a Failed instance: https://github.com/oxidecomputer/omicron/blob/ee0aac053f178980d0c2d0e6c40bea38688961f9/nexus/src/app/instance.rs#L395-L416

There are plenty of reasons an instance could move to the Failed state (e.g. a failure to start the VM in Propolis, a heartbeat failure like those discussed in #2727, etc.). A VM user needs to be able to stop and attempt to restart a failed instance.

(Note that, on the Propolis end, once an instance has failed, it can't be restarted--the Propolis zone needs to be destroyed and recreated.)

### LINKED ISSUE #6640: [nexus] want to allow stopping `Failed` instances
PR #6503 changed Nexus to attempt to automatically restart instances  which are in the `Failed` state. Now that we do this, we should probably change the allowable instance state transitions to permit a user to stop an instance that is `Failed`, as a way to say "stop trying to restart this instance" (as `Stopped` instances are not restarted).

This would have slightly different semantics from changing the instance's auto-restart policy using a future instance-reconfigure API. Stopping a `Failed` instance would mean "stop trying to restart this now; if it is later started and then transitions to `Failed` again, continue using whatever its auto-restart policy is", while changing the  auto-restart policy would mean "don't try to automatically restart this even if it's eventually restarted again".[^1]

If we do this, we should _definitely_ also make `SagaUnwound` instances appear as `Failed` rather than `Stopped`, as I  discussed in https://github.com/oxidecomputer/omicron/issues/6638#issuecomment-2369169065.

[^1]: Unless, of course, the user changes the auto-restart policy _again_.

### PR DESCRIPTION
**Pull request by hawkw**
PR #6503 changed Nexus to attempt to automatically restart instances which are in the `Failed` state. Now that we do this, we should probably change the allowable instance state transitions to permit a user to stop an instance that is `Failed`, as a way to say "stop trying to restart this instance" (as `Stopped` instances are not restarted). This branch changes `Nexus::instance_request_state` and
`select_instance_change_action` to permit stopping a `Failed` instance.

Fixes #6640
Fixes #2825, along with #6455 (which allowed restarting `Failed` instances).

### CODE REVIEW

File: nexus/src/app/instance.rs [hunk 1]
```diff
@@ -898,6 +925,24 @@ impl super::Nexus {
...
+                    .datastore()
+                    .instance_update_runtime(&instance_id, &new_runtime)
+                    .await
+                    .map_err(InstanceStateChangeError::Other)?;
+                if !changed {
+                    // TODO(eliza): perhaps we should refetch the instance here
+                    // and return Ok if it was in the desired state...
+                    Err(InstanceStateChangeError::Other(Error::conflict(
+                        "instance changed state before it could be updated",
+                    )))
```
Comment (hawkw) [inline nexus/src/app/instance.rs:941]: i don't love this error message but couldn't come up with something better --- any suggestions?

**Comment by hawkw** [comment]
@david-crespo I was just about to leave a comment letting you know about this change, but it looks like you were way ahead of me with oxidecomputer/console#2468. Nice :)

**Comment by david-crespo** [comment]
My email inbox is a nightmare but I am up to date

**Comment by hawkw** [comment]
The [CI failure](https://github.com/oxidecomputer/omicron/pull/6652/checks?check_run_id=30600027898) is due to an [unexpected Tokio task cancellation in `test_omdb_success_cases`](https://buildomat.eng.oxide.computer/wg/0/details/01J8JH1GHTE595MAF5YBTA8BS6/3ybl2B1ZPCoj5D0UfV5BgvmfQpYqlpYGkOVlmy3dpaUvVN5L/01J8JH2AVHD7EAR6AT7ZG8WS72#S5595), which is a known test flake --- see #6505. I'm going to restart that run.

File: nexus/src/app/instance.rs [hunk 2]
```diff
@@ -811,13 +815,36 @@ impl super::Nexus {
                                 still being created"
                                 ))
                 }
+                // Failed instances may transition to Stopped by just changing
+                // the Nexus state in the database to NoVmm.
+                //
+                // An instance's effective state will never be Failed while it
+                // is linked with a VMM. If the instance has an active VMM which
```
Comment (gjcolombo) [inline nexus/src/app/instance.rs:822]: optional: could note here that this is also enforced by database constraint

File: nexus/src/app/instance.rs [hunk 3]
```diff
@@ -811,13 +815,36 @@ impl super::Nexus {
...
+                        nexus_state: db::model::InstanceState::NoVmm,
+                        ..prev_runtime.clone()
+                    }));
+                }
                 // If the instance has no sled beacuse it's been destroyed or
                 // has fallen over, reject the state change.
-                //
-                // TODO(#2825): Failed instances should be allowed to stop, but
-                // this requires a special action because there is no sled to
-                // send the request to.
```
Comment (gjcolombo) [inline nexus/src/app/instance.rs:820]: yesssssss

File: nexus/src/app/instance.rs (hunk 1 above)
Comment (gjcolombo) [reply nexus/src/app/instance.rs:941]: This one's tricky because we don't really want the error to start talking about details like "generation numbers" or "optimistic concurrency control," but it's hard to explain what's really happening without bringing those concepts in. Would being more verbose help? For example:

> The instance was previously in a state that allowed the requested state change, but the instance's state changed before the request could be completed.

Comment (hawkw) [reply nexus/src/app/instance.rs]: I changed it to use that, thanks for the suggestion!
