### PR TITLE
fix: use lazy argument evaluation to handle errors

### LINKED ISSUE #9051: sled agent fails on startup looking for non-existent config-rss.toml
I believe that right now, sled agent on most real systems will fail on startup with:

```
[ Sep 19 15:47:38 Method "start" exited with status 0. ]
sled-agent: Failed to read config from /opt/oxide/sled-agent/pkg/config-rss.toml: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
[ Sep 19 15:47:38 Stopping because all processes in service exited. ]
[ Sep 19 15:47:38 Executing stop method (:kill). ]
[ Sep 19 15:47:38 Restarting too quickly, changing state to maintenance. ]
```

Details coming.  I think this was introduced yesterday in #9016 here:
https://github.com/oxidecomputer/omicron/pull/9016/files#diff-47887367c1e0816a1e9405c9e748d167c55abd5743fd02c55246ff0bd76e9ff9

Per @jgallagher, that `then_some` wants to be using `then` with a closure.  As written, even if the file doesn't exist, it attempts to parse it and then bails out with the error.

### PR DESCRIPTION
**Pull request by dancrossnyc**
An instance of `.then_some` on a bool should have been `.then`. The former evaluates its arguments eagerly, so runs _regardless of the value of the bool_, while the latter does so lazily, which was the desired behavior.

In testing, all of our configurations had the file we were testing the presence of before reading.  But other folks do not.

Fixes #9051

### CODE REVIEW

File: sled-agent/src/bin/sled-agent.rs [hunk 1]
```diff
@@ -62,7 +62,7 @@ async fn do_run() -> Result<(), CmdError> {
                 rss_config_path.push("config-rss.toml");
                 rss_config_path
             };
-            let rss_config = rss_config_path.exists().then_some({
+            let rss_config = rss_config_path.exists().then(|| {
                 let rss_config =
                     RackInitializeRequest::from_file(rss_config_path)
                         .map_err(|e| CmdError::Failure(anyhow!(e)))?;
```
Comment (jgallagher) [inline sled-agent/src/bin/sled-agent.rs:68]: I'm not sure this compiles - does this mean `rss_config` is now an `Option<Result<...>>`?

Comment (dancrossnyc) [reply sled-agent/src/bin/sled-agent.rs:68]: Ugh. Of course. :-(

**Review by jgallagher — APPROVED** [review]

File: sled-agent/src/bin/sled-agent.rs (hunk 1 above)
Comment (dancrossnyc) [reply sled-agent/src/bin/sled-agent.rs:68]: Actually, it didn't mean that; `then_some` was already returning an `Option<RackInitializeRequestParams>`; the `Result` was being destructured by the `?` on line 68.  But you can't (conveniently) use `?` in a closure, so it did fail to compile.

It's possible one could omit the `?` and try to play games with `.transpose` or `.ok` or some combination of things like that, but I don't think the result would be comprehensible.  My conclusion is that none of the slick methods on `bool` are really useful here, so I just switched it back to an `if` expression.

Comment (dancrossnyc) [reply sled-agent/src/bin/sled-agent.rs:68]: > Actually, it didn't mean that; `then_some` was already returning an `Option<RackInitializeRequestParams>`; the `Result` was being destructured by the `?` on line 68. But you can't (conveniently) use `?` in a closure, so it did fail to compile.
> 
> It's possible one could omit the `?` and try to play games with `.transpose` or `.ok` or some combination of things like that, but I don't think the result would be comprehensible. My conclusion is that none of the slick methods on `bool` are really applicable here, so I just switched it back to an `if` expression.
