### PR TITLE
Properly check prior instance/vmm states when starting an instance

### LINKED ISSUE #6274: `Nexus::instance_start` doesn't check that the target instance is fully created
This was seen in stress testing of PR #5749. That PR seems to hit the problem more often than main does, for reasons we're still investigating, but it looks like it's also a bug on current main so I'm filing a separate issue for it.

This is a regression I introduced in #4194. `Nexus::instance_start` previously rejected attempts to start a Creating instance: https://github.com/oxidecomputer/omicron/blob/79fee6a2c9f0099fb9cca6effbb862fd75c0a4e4/nexus/src/app/instance.rs#L483-L520

In 4194 I changed this path so that it checks the state of the instance's *VMM* but does not pay attention to the state of the *instance*: https://github.com/oxidecomputer/omicron/blob/acbaf4370b876bd8f27b71bbf41fd12abafc09dc/nexus/src/app/instance.rs#L533-L581

The `if let Some(vmm)` clause should have an `else` that checks to make sure that the instance is actually in a state where it's ready to be started (i.e. it should be in `NoVmm`).

At first glance the impact of this seems pretty limited: to hit it, you need to create an instance, then try to start it by name before the create saga is finished. The result that we're seeing is that the start request 500s; the other possible result, I think, is that the VM will start without all the virtual hardware you might expect, which you can recover from by stopping and restarting the instance.

### PR DESCRIPTION
**Pull request by gjcolombo**
Fix the following instance start dispositions:

- an instance with no active VMM can only be started if it's in the "NoVmm" instance state
- an instance with a migrating active VMM has been started, so allow start to succeed for idempotency
- an instance with a SagaUnwound active VMM is allowed to be started again (the new start saga's VMM supplants the old VMM)

Add some unit tests to cover these cases.

Fixes #6274.

### CODE REVIEW

File: nexus/src/app/instance.rs [hunk 1]
```diff
@@ -2186,18 +2166,114 @@ pub(crate) async fn notify_instance_updated(
...
+    instance: &DbInstance,
+    vmm: &Option<DbVmm>,
+) -> Result<InstanceStartDisposition, Error> {
+    // If the instance has an active VMM, there's nothing to start, but this
+    // disposition of this call (succeed for idempotency vs. fail with an
+    // error describing the conflict) depends on the state that VMM is in.
+    //
+    // If the instance doesn't have an active VMM, see if the instance state
+    // permits it to start.
+    if let Some(vmm) = vmm {
```
Comment (hawkw) [inline nexus/src/app/instance.rs:2182]: I briefly wondered about whether the `if` where each branch is a `match` ought to be combined into one big `match (vmm.runtime.state, instance.runtime.nexus_state)`, but honestly, I'm not sure which is clearer...

File: nexus/src/app/instance.rs [hunk 2]
```diff
@@ -2186,18 +2166,114 @@ pub(crate) async fn notify_instance_updated(
...
+                debug!(log, "asked to start an active instance";
+                           "instance_id" => %instance.id());
+
+                Ok(InstanceStartDisposition::AlreadyStarted)
+            }
+            // If a previous start saga failed and left behind a VMM in the
+            // SagaUnwound state, allow a new start saga to try to overwrite
+            // it.
+            DbVmmState::SagaUnwound => {
+                debug!(log, "instance's last VMM's start saga unwound";
```
Comment (hawkw) [inline nexus/src/app/instance.rs:2199]: nitpicky: perhaps this log message should specifically indicate that it's okay to start the instance?

File: nexus/src/app/instance.rs [hunk 3]
```diff
@@ -2290,4 +2366,91 @@ mod tests {
...
+        let mut vmm = Some(vmm);
+        vmm.as_mut().unwrap().runtime.state = DbVmmState::Starting;
+        assert!(instance_start_allowed(&logctx.log, &instance, &vmm).is_ok());
+        vmm.as_mut().unwrap().runtime.state = DbVmmState::Running;
+        assert!(instance_start_allowed(&logctx.log, &instance, &vmm).is_ok());
+        vmm.as_mut().unwrap().runtime.state = DbVmmState::Rebooting;
+        assert!(instance_start_allowed(&logctx.log, &instance, &vmm).is_ok());
+        vmm.as_mut().unwrap().runtime.state = DbVmmState::Migrating;
+        assert!(instance_start_allowed(&logctx.log, &instance, &vmm).is_ok());
+    }
```
Comment (hawkw) [inline nexus/src/app/instance.rs:2455]: thanks for adding these tests, i really appreciate this.

File: nexus/src/app/instance.rs [hunk 4]
```diff
@@ -2290,4 +2366,91 @@ mod tests {
...
+        instance.runtime_state.propolis_id = Some(vmm.id);
+        let mut vmm = Some(vmm);
+        vmm.as_mut().unwrap().runtime.state = DbVmmState::Starting;
+        assert!(instance_start_allowed(&logctx.log, &instance, &vmm).is_ok());
+        vmm.as_mut().unwrap().runtime.state = DbVmmState::Running;
+        assert!(instance_start_allowed(&logctx.log, &instance, &vmm).is_ok());
+        vmm.as_mut().unwrap().runtime.state = DbVmmState::Rebooting;
+        assert!(instance_start_allowed(&logctx.log, &instance, &vmm).is_ok());
+        vmm.as_mut().unwrap().runtime.state = DbVmmState::Migrating;
+        assert!(instance_start_allowed(&logctx.log, &instance, &vmm).is_ok());
```
Comment (hawkw) [inline nexus/src/app/instance.rs:2454]: nitpicky: the unwraps here are a bit weird, but I guess that's a consequence of `instance_start_allowed` taking `&Option<Vmm>` rather than `Option<&Vmm>` --- if we changed it to take the latter and passed `vmm.as_ref()` when calling it elsewhere, we wouldnt need the unwraps. but, maybe not worth torturing the interface used in real code to make the tests nicer...

File: nexus/src/app/instance.rs [hunk 5]
```diff
@@ -2186,18 +2166,114 @@ pub(crate) async fn notify_instance_updated(
     }
 }
 
+/// Determines the disposition of a request to start an instance given its state
+/// (and its current VMM's state, if it has one) in the database.
+fn instance_start_allowed(
+    log: &slog::Logger,
+    instance: &DbInstance,
+    vmm: &Option<DbVmm>,
```
Comment (hawkw) [inline nexus/src/app/instance.rs:2174]: nitpicky: i kinda wonder if this ought to take `&InstanceAndActiveVmm` instead of `&Instance, &Vmm`, because that kind of enforces the invariant that you should call it with an instance and _its active VMM_ rather than any random VMM?

OTTOH, that probably makes the tests annoyinger.

**Review by hawkw — APPROVED** [review]

File: nexus/src/app/instance.rs (hunk 5 above)
Comment (gjcolombo) [reply nexus/src/app/instance.rs:2174]: I was worried about this when I started writing the tests, but it actually turns out not to be so bad, and it gets rid of some of the `unwrap()` nonsense you mentioned in the previous comment. Will push a fix for this shortly.

File: nexus/src/app/instance.rs (hunk 3 above)
Comment (gjcolombo) [reply nexus/src/app/instance.rs:2455]: My pleasure!

File: nexus/src/app/instance.rs (hunk 1 above)
Comment (gjcolombo) [reply nexus/src/app/instance.rs:2181]: I also think this is a push (particularly if much of this routine is about to get replaced with a call to `effective_state` anyway) so have left it as-is.
