### PR TITLE
[fm] only you can prevent inventory collection time travel

### LINKED ISSUE #10260: FM: can we prevent inventory collection time travel?
When a FM sitrep is committed to the `fm_sitrep_history`, we check that the parent sitrep ID is the current sitrep when committing the new one, and fail the commit if it is not. However, the parent sitrep is not the only input; the inventory collection loaded by the Nexus that produced the sitrep is also an important input. Currently, there is nothing that prevents a sitrep from being produced by a Nexus that is still operating on an *older inventory collection* than the one that was the input to the current sitrep, which could result in time travel/flapping, as I discussed in [RFD 603](https://rfd.shared.oxide.computer/rfd/0603#_inventory):

> [Flapping](https://rfd.shared.oxide.computer/rfd/0603#_flapping) is a potential concern here. Suppose one Nexus has loaded the latest inventory collection, while another is still operating with an earlier view of the inventory. If the first Nexus generates a sitrep based on the actual latest inventory, and the second Nexus sees that sitrep and notes that the inventory does not match the one that it considers the "latest", it may decide to generate a new sitrep. The second Nexus' diagnosis engines may incorrectly believe that the system has gone from the state represented by the inventory in the current sitrep to the inventory it believes is current, when in actuality, the opposite has happened. This "time travel" leads to Nexus imagining that changes in inventory have occurred which do not reflect reality, potentially causing incorrect diagnoses, imagined alerts, and so on. To prevent this, we may have to make the CTE for inserting a current sitrep into the sitrep history (described in ["Creating Sitreps"](https://rfd.shared.oxide.computer/rfd/0603#_creating_sitreps)) check that the inventory collection ID in the new sitrep has a timestamp greater than the inventory collection ID in the current sitrep.
>
> Another concern with using data from the inventory in the sitrep is that old inventory collections are deleted very aggressively. Only the four most recent inventory collections are kept at any given time. Depending on the frequency of inventory collections relative to sitrep generation, this may mean that the inventory collection that was input to the current sitrep may no longer exist by the time that a new sitrep is generated. Thus, it may be necessary to ensure that the sitrep can be interpreted without actually accessing data from the inventory that was current when it was generated. Any data from inventory necesary for a subsequent diagnosis phase to understand the current sitrep would need to be stored within the sitrep’s records. The inventory collection ID stored in the sitrep may only be used to compare whether the inventory collection is the same or different from the current one, and whether it is newer or older (as described in the previous paragraph). When checking if the inventory collection ID in a new sitrep is newer than the current one to prevent flapping, we can safely assume that if an inventory collection ID no longer exists in the inv_collection table, it must be older.

Sitreps carry with them the ID of the inventory collection that was an input to the sitrep.  I _think_ we should hopefully be able to guard against inventory collection time travel within the [`DataStore::insert_sitrep_version_query`](https://github.com/oxidecomputer/omicron/blob/65ac833cea36f0f4eceb3876ac3ac5f49dff92bf/nexus/db-queries/src/db/datastore/fm.rs#L970) by doing the following:
- Selecting the `inv_collection_id` fields from the parent sitrep and the sitrep being inserted
- `LEFT JOIN`ing with `inv_collection` on those IDs
  - We would use a `LEFT JOIN` here because inventory collections are garbage collected, and either collection may no longer exist in the db. In that case, we can safely always assume that a deleted collection is older than a not-deleted one.
- Failing the CTE if the sitrep being inserted's inventory collection is older than the current sitrep's inventory collection, determined based on the timestamps of the inventory collection records.

I think we would want a different error type to be returned than `ParentNotCurrent` in this situation, so that we can distinguish between when we are behind on loading the current sitrep and when we are behind on loading the inventory, and activate the inventory loader task if it's the inventory that's behind.

### PR DESCRIPTION
**Pull request by hawkw**
Depends on #10258.

As described in #10260 (and [§8.2 RFD 603]), **only _you_ can prevent inventory collection time travel**: because each Nexus that might participate in FM analysis has its own copy of the inventory which it considers to be current (loaded by its `inventory_load` background task). Since we must allow for the possibility of a particular Nexus being arbitrarily behind, we can easily imagine a scenario where a Nexus attempts to perform FM analysis and generate a sitrep while operating on a copy of the inventory that is actually *older* than the inventory that was used to produce the current sitrep. If this happens, we might incorrectly think that the state of the system has _changed_ from the state in the current sitrep, while actually, we are just operating on an outdated understanding. This branch fixes that.

In #10260, I proposed addressing this by making the CTE that inserts a sitrep into the sitrep history only succeed if the inventory collection UUID in that sitrep's metadata is newer than the one in the current sitrep's metadata. This would probably have worked, but putting that check in the already somewhat hairy CTE was not actually necessary.  Instead, we can just perform this check *before* actually doing any analysis, which feels a lot nicer. In order to do this, it was necessary to add a query to just go and fetch only the timestamps from an inventory by its UUID, which was not a huge deal. I think it is plausible that the "is strictly newer than" check for inventory collections may be useful elsewhere as well.

Fixes #10260 

[§8.3 RFD 603]: https://rfd.shared.oxide.computer/rfd/0603#_inventory

### CODE REVIEW

File: nexus/src/app/background/tasks/fm_analysis.rs [hunk 1]
```diff
@@ -304,3 +375,269 @@ impl FmAnalysis {
...
+            match &result.outcome {
+                status::Outcome::InventoryStale { parent_inv, loaded_inv } => {
+                    assert_eq!(parent_inv.id, newer.id);
+                    assert_eq!(loaded_inv.id, older.id);
+                }
+                other => panic!("expected InventoryStale, got {other:?}"),
+            }
+        }
+
+        // If the parent sitrep's inventory collection is strictly newer than
```
Comment (mergeconflict) [inline nexus/src/app/background/tasks/fm_analysis.rs]: Do you mean "if the _loaded_ inventory collection ..."?

File: nexus/types/src/inventory.rs [hunk 2]
```diff
@@ -61,6 +61,33 @@ mod display;
...
+impl CollectionMetadata {
+    /// Returns `true` if this collection is strictly newer than `other`.
+    ///
+    /// A collection is strictly newer if it *started* after `other` *ended*.
+    /// This means there is no overlap in time between the two collections:
+    /// everything observed by `self` was observed after everything observed
+    /// by `other`.
+    pub fn is_strictly_newer_than(&self, other: &CollectionMetadata) -> bool {
+        self.time_started > other.time_done
+    }
```
Comment (mergeconflict) [inline nexus/types/src/inventory.rs]: Is there any potential concern about collections that take a long time? Like if collection A is slow for whatever reason and happens to overlap with collection B, then `actually_activate` says we can't use B and have to wait for a later collection.

**Review by mergeconflict — APPROVED** [review]

File: nexus/src/app/background/tasks/fm_analysis.rs [hunk 3]
```diff
@@ -113,6 +106,84 @@ impl FmAnalysis {
...
+                        },
+                    };
+                }
+                // Otherwise, the loaded inventory collection is newer than the
+                // one in the parent sitrep. This is the case if
+                // `inventory_collection_read_metadata` returns `None`, since if
+                // the parent sitrep's inventory collection has been garbage
+                // collected, it is definitely older than the loaded one.
+                Ok(_) => {}
+                Err(error) => {
```
Comment (davepacheco) [inline nexus/src/app/background/tasks/fm_analysis.rs]: What if the current sitrep's inventory collection has been deleted?  Would this not cause FM to just stop?

What do you think of (instead of all of this) storing in the sitrep, alongside the inventory collection uuid, the timestamp that you care about?  Then you can do this check without hitting the database at all and even if the collection has been deleted.

---

I don't think there's anything wrong with adding this check per se and it might be the best option.  But I'm worried that whatever depends on this is implicitly depending on synchronized distributed time for correctness, which we've generally avoided.  I think it's always safe to assume that if some inventory collection is older than some other one, you can just skip it and wait for the next one (though it might be several minutes).  But it's possible (though unlikely) that a newer-timestamped inventory collection contains data points that were from before some earlier-timestamped inventory collection.

Comment (hawkw) [reply nexus/src/app/background/tasks/fm_analysis.rs]: > What if the current sitrep's inventory collection has been deleted? Would this not cause FM to just stop?

Do you mean the inventory collection of the current sitrep (the parent of the new sitrep), or the inventory collection that this Nexus has loaded and is about to use as the input to the next one? If the current sitrep's inventory has been deleted, the `inventory_collection_read_metadata` query will return `None` and we will proceed with analysis, rather than returning a `NotFound` error that makes analysis stop forever.

With all that said, I think your suggestion that we just make the sitrep store the inventory collection's timestamps rather than hitting the DB again to look it up feels both simpler and less potentially sketchy, so I think I'll change it to do that instead of querying the db for the metadata record.

---

Regarding your other point, I'm also concerned about the staleness of individual data points in the inventory and I'm not totally sure how to handle that. But I think this check is still worth having to ensure that the inventory loader is not arbitrarily behind?

Comment (davepacheco) [reply nexus/src/app/background/tasks/fm_analysis.rs]: Yeah, that's fine.

To handle the case of stale data points I think we'd need more fine-grained ordering closer to the source of the data.  Suppose we could assign to each startup of sled agent a monotonically increasing id.  (It's not obvious to me how we'd do this, but I feel like it should be manageable.)  Then it could report this with its inventory, you could store it with the sitrep, and FM could avoid taking action on the data in the inventory _for that sled_ if it's looking at older data for this sled.

This seems like a great candidate for punting on for a while.  It seems like a lot of work to improve a very unlikely case.

File: nexus/types/src/inventory.rs (hunk 2 above)
Comment (smklein) [reply nexus/types/src/inventory.rs]: This seems like a feature of this PR, not a bug! if they're overlapping, it's possible that the "mostly newer" inventory has pieces that are older than the "mostly older" collection, which could result in time travel.

(I think that if inventory drags on for longer, and multiple nexuses are doing it concurrently, the risk here of time travel increases. So the strictly-newer-than check seems really handy!)

Comment (mergeconflict) [reply nexus/types/src/inventory.rs]: Oh it's definitely intentional, I was mostly pondering if there might be a liveness issue if the situation persists (e.g. C overlaps with B, then D overlaps with C, etc.). But no, I think I was wrong; we always compare against the committed sitrep.

**Comment by hawkw** [comment]
Okay, I've updated this change to store a `next_inv_min_time_started` in the sitrep metadata record in CRDB, rather than trying to refetch the inventory collection every time (as @davepacheco suggested in https://github.com/oxidecomputer/omicron/pull/10266#discussion_r3081021553) --- would love another look from @mergeconflict and/or @smklein when you guys have a chance!

File: schema/crdb/fm-sitrep-next-inv-min-time-started/up2.sql
Comment (mergeconflict) [inline schema/crdb/fm-sitrep-next-inv-min-time-started/up2.sql:1]: `s/next_inv_min_start_time/next_inv_min_time_started/g`

File: nexus/types/src/internal_api/background.rs [hunk 4]
```diff
@@ -921,20 +921,27 @@ pub struct FmAnalysisStatus {
...
 
     #[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
     #[allow(clippy::large_enum_variant)]
     pub enum Outcome {
-        /// Fault management analysis was not performed as no inventory
+        /// Fault management analysis was not performed, as no inventory
         /// collection has been loaded.
         WaitingForInventory,
 
+        WaitingForNewerInventory {
```
Comment (mergeconflict) [inline nexus/types/src/internal_api/background.rs:942]: Nit: doc comment here?

File: nexus/src/app/background/tasks/fm_analysis.rs [hunk 5]
```diff
@@ -304,3 +330,244 @@ impl FmAnalysis {
...
+            let result = task.actually_activate(opctx).await;
+            assert_eq!(result.inv_collection_id, Some(overlapping.id));
+            match &result.outcome {
+                status::Outcome::WaitingForNewerInventory {
+                    parent_inv_id,
+                    next_inv_min_time_started,
+                    input_inv_time_started,
+                } => {
+                    assert_eq!(*parent_inv_id, newer.id);
+                    assert_eq!(*next_inv_min_time_started, newer.time_done,);
```
Comment (mergeconflict) [inline nexus/src/app/background/tasks/fm_analysis.rs]: should this be `older.id` and `older.time_done`?

File: nexus/fm/src/analysis_input.rs
Comment (mergeconflict) [inline nexus/fm/src/analysis_input.rs]: FWIW, Claude thinks this should be `inv_collection_id: inv.id` to avoid tripping the staleness check.

**Review by mergeconflict — APPROVED** [review]

File: schema/crdb/fm-sitrep-next-inv-min-time-started/up2.sql
Comment (hawkw) [reply schema/crdb/fm-sitrep-next-inv-min-time-started/up2.sql:1]: gah, whoops...i didn't get a lot of sleep last night.

File: nexus/src/app/background/tasks/fm_analysis.rs [hunk 6]
```diff
@@ -304,3 +330,249 @@ impl FmAnalysis {
...
+            assert_eq!(result.inv_collection_id, Some(older.id));
+            match &result.outcome {
+                status::Outcome::WaitingForNewerInventory {
+                    parent_inv_id,
+                    next_inv_min_time_started,
+                    input_inv_time_started,
+                } => {
+                    assert_eq!(*parent_inv_id, newer.id);
+                    assert_eq!(*next_inv_min_time_started, newer.time_done,);
+                    assert_eq!(*input_inv_time_started, older.time_started,);
```
Comment (smklein) [inline nexus/src/app/background/tasks/fm_analysis.rs:448]: Because we're comparing timestamps - these aren't round-tripping to the database, are they?

(Just asking to avoid flake a la https://github.com/oxidecomputer/omicron/issues/10274 )

File: nexus/src/app/background/tasks/fm_analysis.rs [hunk 7]
```diff
@@ -304,3 +330,249 @@ impl FmAnalysis {
...
+                    &result.outcome,
+                    status::Outcome::WaitingForNewerInventory { .. }
+                ),
+                "expected analysis to proceed with same inventory \
+                 collection ID, got: {:?}",
+                result.outcome,
+            );
+        }
+
+        // If our "currently loaded" inventory collection overlaps with the
```
Comment (smklein) [inline nexus/src/app/background/tasks/fm_analysis.rs:537]: Great tests!

**Review by smklein — APPROVED** [review]

File: nexus/src/app/background/tasks/fm_analysis.rs (hunk 6 above)
Comment (hawkw) [reply nexus/src/app/background/tasks/fm_analysis.rs:448]: Nope! Because the current inventory and current sitrep inputs to this task are loaded by the `inv_loader` and `sitrep_loader`, we're operating on in memory state rather than loading them from the DB, and none of this stuff roundtrips through CRDB in this test. Good question though!
