### PR TITLE
Fix flaky oximeter-collector agent tests

### LINKED ISSUE #8636: test failed in CI: `test_self_stat_collection_count`
This test failed on a CI run on #8627:

https://github.com/oxidecomputer/omicron/pull/8627/checks?check_run_id=46208988376

Log showing the specific test failure:

https://buildomat.eng.oxide.computer/wg/0/details/01K0CYCJ10M4HYQ5TJDRNFFTRX/GkU4qFcnvjiE6MOKLpiGpI1Yu5sJbshKlC1KNbKPVprBXJyB/01K0CYDK2VDM6GQS0Z5CQYYQYW

Excerpt from the log showing the failure:

```
7923	2025-07-17T21:06:32.078Z	  stdout ───
7924	2025-07-17T21:06:32.078Z	
7925	2025-07-17T21:06:32.078Z	    running 1 test
7926	2025-07-17T21:06:32.078Z	    test agent::tests::test_self_stat_collection_count ... FAILED
7927	2025-07-17T21:06:32.078Z	
7928	2025-07-17T21:06:32.078Z	    failures:
7929	2025-07-17T21:06:32.078Z	
7930	2025-07-17T21:06:32.078Z	    failures:
7931	2025-07-17T21:06:32.078Z	        agent::tests::test_self_stat_collection_count
7932	2025-07-17T21:06:32.078Z	
7933	2025-07-17T21:06:32.078Z	    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 7 filtered out; finished in 1.86s
7934	2025-07-17T21:06:32.078Z	    
7935	2025-07-17T21:06:32.078Z	  stderr ───
7936	2025-07-17T21:06:32.079Z	    log file: /var/tmp/omicron_tmp/oximeter_collector-ce92baab1eaac757-test_self_stat_collection_count.4000.0.log
7937	2025-07-17T21:06:32.079Z	    note: configured to log to "/var/tmp/omicron_tmp/oximeter_collector-ce92baab1eaac757-test_self_stat_collection_count.4000.0.log"
7938	2025-07-17T21:06:32.079Z	
7939	2025-07-17T21:06:32.079Z	    thread 'agent::tests::test_self_stat_collection_count' panicked at oximeter/collector/src/agent.rs:844:9:
7940	2025-07-17T21:06:32.079Z	    assertion failed: stats.failed_collections.is_empty()
```

We previously had this test flaking in #4657 but it looks like this is a different assert failing, so figured it was worth a new issue rather than reopening.

### PR DESCRIPTION
**Pull request by mergeconflict**
Fixes #8636 (and likely the same root cause as #7255 and #7220).

Three agent tests have been reported as flaky on loaded CI machines: `test_self_stat_collection_count` (#8636, #4657), `test_self_stat_error_counter` (#7255), and `verify_producer_details` (#7220). A fourth, `test_self_stat_unreachable_counter`, uses the same pattern and was likely susceptible too.

They all shared the same approach: pause tokio time, advance by a fixed `TEST_WAIT_PERIOD`, then assert. On slow machines, the collection task couldn't keep up with the timer: its bounded channel (capacity 1) would overflow when the next tick fired before the previous collection finished, recording spurious `CollectionsInProgress` failures.

The fix introduces `advance_n_collections()`, which advances paused time in small increments (`TICK_INTERVAL`), using a watch channel to wait for each collection to complete before moving on to the next. This guarantees the channel is drained before the next timer tick fires, so collections never overlap.

Because collections can no longer overlap, `test_self_stat_error_counter` gets substantially simpler: the old code had to tolerate both `CollectionsInProgress` and `500` failure reasons (summing across them) and allowed `+1` slack between the server-side and task-side counts. Now it can assert exactly `N_COLLECTIONS` errors of a single type and exact count equality.

`test_updated_producer_is_still_collected_from` also gets a more precise wait loop after re-registration: instead of advancing time by a fixed amount and hoping a collection happened, it watches for the server-side `collection_count` to confirm an actual collection from the new server (as opposed to just a producer info update from re-registration).

Also adds `CollectionTaskHandle::details_watcher()` (`#[cfg(test)]`) to expose the watch receiver.

### CODE REVIEW

File: oximeter/collector/src/agent.rs [hunk 1]
```diff
@@ -803,16 +821,14 @@ mod tests {
...
+        // collections. We wait on the condition rather than advancing for a
+        // fixed duration to avoid overflowing the collection task's bounded
+        // request channel on slow/loaded machines.
         tokio::time::pause();
-        let now = Instant::now();
-        while now.elapsed() < TEST_WAIT_PERIOD {
-            tokio::time::advance(TICK_INTERVAL).await;
-        }
+        let target = N_COLLECTIONS as usize;
+        advance_until(|| collection_count.load(Ordering::SeqCst) >= target)
```
Comment (jgallagher) [inline oximeter/collector/src/agent.rs]: Sorry, I'm not following how this change addresses the theory in the PR description. If we think

> the root cause was that the collection task's bounded channel (capacity 1) would overflow when the timer fired before the previous collection completed, recording spurious FailedCollection entries.

what's stopping that from still happening with these changes? We haven't changed how we step the timer, only changed when we decide to stop doing so. But if the task is overloaded, won't we still get spurious `FailedCollection` entries?

Edit: Is there a way to induce the behavior you think is happening (e.g., by adding sleeps or CPU spinloops or something at judicious spots within the collection task)?

Comment (mergeconflict) [reply oximeter/collector/src/agent.rs]: Yeah, after a night's sleep, I think I was being dumb and this doesn't actually work.

What I really wanted was to use something like a `tokio::sync::Notify` to wait until the channel is actually emptied, but that wasn't going to work with `tokio::time::{pause, advance}`. The way I understand these tests, the use of controlled, simulated time is important because they're about collection intervals... There's probably a way to do this properly still.

Comment (mergeconflict) [reply oximeter/collector/src/agent.rs]: Ok, I think I've got something better now in 7c2eade.

File: oximeter/collector/src/agent.rs [hunk 2]
```diff
@@ -702,11 +703,60 @@ mod tests {
...
+        collector: &OximeterAgent,
+        id: Uuid,
+        n: u64,
+    ) {
+        const TIMEOUT: Duration = Duration::from_secs(60);
+        let mut details_rx = details_watcher(collector, id);
+        // Mark current state as seen so has_changed() only reflects
+        // new updates from this point forward.
+        details_rx.borrow_and_update();
+        tokio::time::pause();
```
Comment (bnaecker) [inline oximeter/collector/src/agent.rs:748]: Do we want to resume time at the end of this function?

File: oximeter/collector/src/agent.rs [hunk 3]
```diff
@@ -702,11 +703,60 @@ mod tests {
...
+            // Advance time until this collection completes.
+            loop {
+                assert!(
+                    start.elapsed() < TIMEOUT,
+                    "timed out waiting for collection {i} after \
+                    {:?} of simulated time",
+                    start.elapsed(),
+                );
+                tokio::time::advance(TICK_INTERVAL).await;
+                if details_rx.has_changed().unwrap_or(false) {
```
Comment (bnaecker) [inline oximeter/collector/src/agent.rs]: Do we really want `unwrap_or()`? If the other side is closed, don't we want to panic here? Or will the test abort anyway in that case?

File: oximeter/collector/src/agent.rs [hunk 4]
```diff
@@ -936,72 +977,41 @@ mod tests {
...
-        // our collection task side, so we allow the server count to be greater
-        // than our own. But since the collection task is single-threaded, it
-        // cannot ever be more than _one_ greater than our count, since we
-        // should increment that counter before making another request to the
-        // server.
         let server_count = collection_count.load(Ordering::SeqCst);
         assert!(
-            count == server_count || count + 1 == server_count,
+            error_count as usize == server_count
+                || error_count as usize + 1 == server_count,
```
Comment (bnaecker) [inline oximeter/collector/src/agent.rs]: Is this +1 still needed now? We've advanced exactly N collections, and I don't see another await point in here for an additional collection to fire.

File: oximeter/collector/src/agent.rs [hunk 5]
```diff
@@ -1163,10 +1170,28 @@ mod tests {
...
+        // update_producer_info notification from re-registration too.
+        let n_before = details_rx.borrow().n_collections;
+        let start = Instant::now();
+        loop {
+            assert!(
+                start.elapsed() < Duration::from_secs(60),
+                "timed out waiting for collection from re-registered producer",
+            );
             tokio::time::advance(TICK_INTERVAL).await;
+            if details_rx.has_changed().unwrap_or(false) {
```
Comment (bnaecker) [inline oximeter/collector/src/agent.rs]: Same comment here, `unwrap_or()` doesn't seem quite right to me.

File: oximeter/collector/src/agent.rs [hunk 6]
```diff
@@ -1163,10 +1170,28 @@ mod tests {
...
+                let details = details_rx.borrow_and_update().clone();
```
Comment (bnaecker) [inline oximeter/collector/src/agent.rs]: Is this `clone()` load-bearing? I'm not picky about the performance implications, just making sure I get the semantics here.

File: oximeter/collector/src/agent.rs [hunk 7]
```diff
@@ -1163,10 +1170,28 @@ mod tests {
...
+                // Only break once a new collection has actually completed
+                // (not just a producer info update).
+                if details.n_collections > n_before
```
Comment (bnaecker) [inline oximeter/collector/src/agent.rs]: I this check for the number of collections necessary? IIUC, we're trying to distinguish a collection from the producer info update. But the latter doesn't change the `collection_count`, so why isn't the second half of this condition enough?

File: oximeter/collector/src/agent.rs (hunk 2 above)
Comment (mergeconflict) [reply oximeter/collector/src/agent.rs:748]: Nope, one of the callers needs time to still be paused, added a comment in 2d2e237.

File: oximeter/collector/src/agent.rs (hunk 3 above)
Comment (mergeconflict) [reply oximeter/collector/src/agent.rs]: Yeah, we should panic. Added in 2d2e237.

File: oximeter/collector/src/agent.rs (hunk 4 above)
Comment (mergeconflict) [reply oximeter/collector/src/agent.rs]: You're right, we can do without it now, thanks!

File: oximeter/collector/src/agent.rs (hunk 2 above)
Comment (bnaecker) [reply oximeter/collector/src/agent.rs:748]: Comment looks helpful, thanks. It might be better to require the caller to manage pausing / resuming time as they need, rather than doing half of that implicitly. You could call `tokio::time::advance()` with a super tiny duration to force a panic if the caller doesn't pause time themselves.

File: oximeter/collector/src/agent.rs (hunk 6 above)
Comment (mergeconflict) [reply oximeter/collector/src/agent.rs]: Nope, it wasn't necessary at all.

File: oximeter/collector/src/agent.rs (hunk 7 above)
Comment (mergeconflict) [reply oximeter/collector/src/agent.rs]: Yep, you're right, it's sufficient to just check that the collection_count is non-zero. This is what I get for vibe coding.

File: oximeter/collector/src/agent.rs (hunk 5 above)
Comment (mergeconflict) [reply oximeter/collector/src/agent.rs]: Fixed

File: oximeter/collector/src/agent.rs (hunk 2 above)
Comment (mergeconflict) [reply oximeter/collector/src/agent.rs:748]: I thought about that, but figured it would just be adding an extra footgun for callers.
