### PR TITLE
Expunge and Decommission disks in planner

### LINKED ISSUE #6999: many Reconfigurator execution steps are fatal that shouldn't be
Right now, failure at many blueprint execution steps causes all of execution to stop.  That feels like the conservative thing to do, but it's not necessarily.  When fixing a broken system requires Reconfigurator to proceed despite some failures, this choice is problematic.  This came up in a colo incident a few weeks ago where we wanted to use Reconfigurator to repair the system by deploying a second Oximeter zone.  In trying to do so, execution failed because it couldn't deploy datasets to a sled agent that was known to be broken (and unrelated to the problem we were trying to repair).  There's no reason that failure to deploy datasets to one sled should prevent Reconfigurator from trying to deploy zones to a _different_ sled.  Arguably, it's wrong to say that failing to deploy datasets to a sled should prevent us from trying to deploy zones to the _same_ sled.  After all, it's totally possible that we successfully deployed datasets during a previous execution, or that there are no new datasets to be created there.  We could instead leave it to the sled agent to check this dependency, failing the zones request if it's missing some dataset that needs to be there.

In today's update call I proposed a pattern where:

- we build the individual execution operations such that when they have strict dependencies like this, the request fails cleanly when the dependency is not satisfied (i.e., `PUT /omicron-zones` should fail if the body refers to datasets that haven't been configured).
- having done that, it's generally safe to call these operations even if their dependencies haven't succeeded; this allows Reconfigurator execution to _always_ try to do these operations rather than skipping them if some dependent operation seems to have failed

The conclusion was that this is directionally a good pattern, but it's not clear how unsafe it would be to just ignore these dependencies today.  So the proposal here is:

- build new operations using this pattern where possible
- for existing operations, evaluate them to determine if we _can_ do things this way and convert them where possible

### LINKED ISSUE #7098: Decommissioning expunged disks should happen in planner
Currently, we decommission expunged disks [during reconfigurator execution](https://github.com/oxidecomputer/omicron/blob/d9153ff0fcbb47afbaaabbac5d5dd9706eb19ede/nexus/reconfigurator/execution/src/lib.rs#L497-L522). This expungement step is tied to a [previous step](https://github.com/oxidecomputer/omicron/blob/d9153ff0fcbb47afbaaabbac5d5dd9706eb19ede/nexus/reconfigurator/execution/src/lib.rs#L269-L293) in the executor that ensures that any expunged disks no longer exist on the given sled. 

Unfortunately, this coupling prevents us from making all execution steps independent and skippable as a solution to #6999.
We can resolve this issue by decommissioning disks in the planner, rather than in the executor as we do with [sled decommissioning](https://github.com/oxidecomputer/omicron/blob/main/nexus/reconfigurator/planning/src/planner.rs#L109)

### LINKED ISSUE #7502: DataStore::physical_disk_update_policy() doesn't update time_modified
While investigating #7501, we found a disk that claimed to be expunged 11 months ago:

```
root@[fd00:1122:3344:105::3]:32221/omicron> select * from physical_disk where serial = 'A084A5EE';
                   id                  |         time_created          |         time_modified         | time_deleted | rcgen | vendor |  serial  |      model      | variant |               sled_id                | disk_policy |   disk_state
---------------------------------------+-------------------------------+-------------------------------+--------------+-------+--------+----------+-----------------+---------+--------------------------------------+-------------+-----------------
  0bffef3c-56b1-4b01-b897-161bbf766bea | 2023-08-30 18:57:23.655377+00 | 2024-03-27 21:18:20.906665+00 | NULL         |     1 | 1b96   | A084A5EE | WUS4C6432DSP3X3 | u2      | 0c7011f7-a4bf-4daf-90cc-1c2410103300 | expunged    | decommissioned
(1 row)
```

but subsequent digging found that it was actually expunged a few days ago:

```
2025-02-03 07:04:17.560Z DEBG 20b100d0-84c3-4119-aa9b-0c632b0b6a3a/11421 (dropshot_internal) on oxz_nexus_20b100d0-84c3-4119-aa9b-0c632b0b6a3a: authorize result
    action = Modify
    actor = Some(Actor::UserBuiltin { user_builtin_id: 001de000-05e4-4000-8000-000000000002, .. })
    actor_id = 001de000-05e4-4000-8000-000000000002
    authenticated = true
    local_addr = [fd00:1122:3344:104::3]:12221
    method = POST
    remote_addr = [fd00:1122:3344:108::2]:34294
    req_id = c2350d2d-86b1-4232-b3f4-b5a139d2c4f9
    resource = PhysicalDisk { parent: Fleet, key: 0bffef3c-56b1-4b01-b897-161bbf766bea (physical_disk), lookup_type: ById(0bffef3c-56b1-4b01-b897-161bbf766bea) }
    result = Ok(())
    uri = /physical-disk/expunge
2025-02-03 07:04:17.612Z INFO 20b100d0-84c3-4119-aa9b-0c632b0b6a3a/11421 (dropshot_internal) on oxz_nexus_20b100d0-84c3-4119-aa9b-0c632b0b6a3a: request completed
    file = /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dropshot-0.15.1/src/server.rs:867
    latency_us = 73067
    local_addr = [fd00:1122:3344:104::3]:12221
    method = POST
    remote_addr = [fd00:1122:3344:108::2]:34294
    req_id = c2350d2d-86b1-4232-b3f4-b5a139d2c4f9
    response_code = 204
    uri = /physical-disk/expunge
```

`physical_disk_update_policy()` [only updates `disk_policy`](https://github.com/oxidecomputer/omicron/blob/6dbd67387aa103e6071ad686e9145f5086fcfaef/nexus/db-queries/src/db/datastore/physical_disk.rs#L158-L166); it should also update `time_modified`.

### PR DESCRIPTION
**Pull request by andrewjstone**
This PR partially fixes #6999,  and fixes #7098 and #7502.

A few significant changes are made in this PR:

 1.  Where possible execution steps no longer error out and cause
the executor itself to early return without running all steps. Instead a
`StepWarning` is returned for each step that contains errors and the executor
runs every step.
 2. Some fallible steps have become decoupled in that they do not rely on
each other and can safely run independently. This was mostly true, except for
the bulk of the work in this PR which ensures that when a a disk is expunged, it
is not immediately decommissioned unless the sled is also expunged. The planner
waits to see that the expungement has been observed by a sled-agent on an active
sled with an expunged disk before it marks it decommissioned.
 3. The executor only decommissions physical disks if their disposition is expunged and they are `ready_for_cleanup` in the blueprint. This completes the feedback loop
between planning, inventory collection, and execution. Previously disk
decommissioning was done for *all* expunged disks. This was racy in
that a separate nexus may have expunged a disk that was not yet ready
to be decommissioned, and it would be picked up in the decommissioning
step of the first nexus's executor. There is more information in the
following [commit comments](https://github.com/oxidecomputer/omicron/commit/3ee1546af757e9f7c396794057ca83cac68fac67#commitcomment-149432816).
4. A Disposition field have been added to the table output for disks.

Steps 1 and 2 above partially resolve #6999 and resolve #7502. While I was modifying the datastore
to implement step 3 I also updated the `modified_time` of the physical disks
table for necessary transactions. This fixes #7502.

This PR also fixes a planner bug where we only check the planning input for
decommissioned disks even if there was a change in the parent blueprint, but no
corresponding change to the planning input.

### CODE REVIEW

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs [hunk 1]
```diff
@@ -1087,16 +1081,113 @@ impl<'a> BlueprintBuilder<'a> {
...
+            {
+                // Do we have any expunged disks in the parent blueprint?
+                //
+                // SAFETY: We check that we have a parent blueprint in the
+                // condition immediately above.
+                let config = self
+                    .parent_blueprint
+                    .blueprint_disks
+                    .get(&sled_id)
+                    .unwrap();
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/blueprint_builder/builder.rs:1177]: I think we could get rid of this `.unwrap()` and maybe also drop a level of indentation by keeping the full config when we look it up the first time. Would need to restore the comments, but something like:

```rust
        if sled_details.policy == SledPolicy::Expunged {
            // ... same as above ...
        } else if let Some(parent_bp_config) =
            self.parent_blueprint.blueprint_disks.get(&sled_id)
        {
            let seen_generation = self
                .collection
                .sled_agents
                .get(&sled_id)
                .map(|sa| sa.omicron_physical_disks_generation);
            if seen_generation == Some(parent_bp_config.generation) {
                for disk in &parent_bp_config.disks {
                    if disk.disposition
                        == BlueprintPhysicalDiskDisposition::Expunged
                    {
                        editor.decommission_disk(&disk.id).map_err(|err| {
                            Error::SledEditError { sled_id, err }
                        })?;
                    }
                }
            }
        }
```

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs [hunk 2]
```diff
@@ -2140,12 +2231,12 @@ pub mod test {
         // The example blueprint should have internal NTP zones on all the
         // existing sleds, plus Crucible zones on all pools.  So if we ensure
         // all these zones exist, we should see no change.
-        for (sled_id, sled_resources) in
-            example.input.all_sled_resources(SledFilter::Commissioned)
+        for (sled_id, sled_details) in
+            example.input.all_sleds(SledFilter::Commissioned)
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/blueprint_builder/builder.rs:2235]: Why did we switch from `all_sled_resources` here? It doesn't look like we use any of the non-resource details. (Same comment on some of the other similar changes below)

File: nexus/reconfigurator/planning/src/planner.rs [hunk 3]
```diff
@@ -148,6 +161,22 @@ impl<'a> Planner<'a> {
...
+                if *sled_state == SledState::Decommissioned {
+                    continue;
+                }
+            }
+
+            // Decommission any disks that need it
+            //
+            // This call must live here so that we don't try to decommission disks
+            // on an already decommissioned sled. That violates editor invariants,
+            // as the planner should not be trying to edit sleds that have been pulled.
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/planner.rs:177]: Nit - I'd be specific here, since once we have trust quorum decommissioning won't require physical removal.

```suggestion
            // as the planner should not be trying to edit sleds that have been decommissioned.
```

File: nexus/reconfigurator/planning/src/planner.rs [hunk 4]
```diff
@@ -1803,6 +1833,206 @@ mod test {
...
+                disk.disposition,
+                BlueprintPhysicalDiskDisposition::InService
+            );
+            assert_eq!(disk.state, PhysicalDiskState::Active);
+        }
+
+        let mut builder = input.into_builder();
+
+        // Let's expunge a disk. It's disposition should change to `Expunged`
+        // but it's state should remain active.
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/planner.rs:1874]:
```suggestion
        // Let's expunge a disk. Its disposition should change to `Expunged`
        // but its state should remain active.
```

File: nexus/reconfigurator/planning/src/planner.rs [hunk 5]
```diff
@@ -1803,6 +1833,206 @@ mod test {
...
+                    disk.disposition,
+                    BlueprintPhysicalDiskDisposition::InService
+                );
+            }
+            assert_eq!(disk.state, PhysicalDiskState::Active);
+            println!("{disk:?}");
+        }
+
+        // We haven't updated the inventory, so no changes should be made
+        assert_planning_makes_no_changes(
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/planner.rs:1931]: This helper method is misnamed :( This only creates a _builder_ and ensures that doesn't make any changes; it doesn't go through full planning. If I change this to run planning instead, the test fails, but I think that's not the fault of this PR:

```
 MODIFIED SLEDS:

  sled 08b956ec-858e-41d4-9a52-2762ed593f78 (active):

    physical disks at generation 3:
    ---------------------------------------------------------------------------------------------
    vendor        model        serial                                        disposition   state
    ---------------------------------------------------------------------------------------------
    fake-vendor   fake-model   serial-0dd065e6-8a48-4755-aeb3-81d26f4e4982   expunged      active
    fake-vendor   fake-model   serial-0f30cb79-704c-4253-b3aa-5256ccf827f8   in service    active
    fake-vendor   fake-model   serial-3343a70d-37ad-4f89-a52c-2f2c1276f25c   in service    active
    fake-vendor   fake-model   serial-4cce2789-3630-4a06-97c3-db989b3a859c   in service    active
    fake-vendor   fake-model   serial-8d88e7cf-1c70-44a6-9e49-aa46b023dd75   in service    active
    fake-vendor   fake-model   serial-a66ed8b6-2d09-487f-8f67-208b47ae8479   in service    active
    fake-vendor   fake-model   serial-b75d5788-427e-4dd1-8576-1e79ab332f0d   in service    active
    fake-vendor   fake-model   serial-c8c33965-be2f-42cb-bed0-dbf93b9f3c14   in service    active
    fake-vendor   fake-model   serial-e718f8d6-5219-46bb-9722-0291de2ceeb5   in service    active
    fake-vendor   fake-model   serial-e9dbf16d-6973-4405-9600-3cc11372b30c   in service    active


    datasets generation 3 -> 4:
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    dataset name                                                                                                   dataset id                             disposition   quota     reservation   compression
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crucible                                                              2b8f25b7-f61c-4dfe-9dd8-9436eaabffca   expunged      none      none          off
    oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crucible                                                              e5617c91-b140-406d-9caf-27e9e2f101f5   in service    none      none          off
    oxp_3343a70d-37ad-4f89-a52c-2f2c1276f25c/crucible                                                              41cabbdc-c121-4756-a271-49fc711698b2   in service    none      none          off
    oxp_4cce2789-3630-4a06-97c3-db989b3a859c/crucible                                                              dd48c434-217e-4e2c-8953-d25dee1a9835   in service    none      none          off
    oxp_8d88e7cf-1c70-44a6-9e49-aa46b023dd75/crucible                                                              77f76ec3-0b44-4279-8c44-559cd7bd57ee   in service    none      none          off
    oxp_a66ed8b6-2d09-487f-8f67-208b47ae8479/crucible                                                              879f664e-0944-43b5-b36f-bcbc1a430375   in service    none      none          off
    oxp_b75d5788-427e-4dd1-8576-1e79ab332f0d/crucible                                                              a3c7bde7-6091-453b-8161-b3b9a206c75d   in service    none      none          off
    oxp_c8c33965-be2f-42cb-bed0-dbf93b9f3c14/crucible                                                              9c4cf6fe-a6a1-4b4b-8de4-d1021457d26e   in service    none      none          off
    oxp_e718f8d6-5219-46bb-9722-0291de2ceeb5/crucible                                                              1b5c1a3d-b023-4381-a552-708da17147f5   in service    none      none          off
    oxp_e9dbf16d-6973-4405-9600-3cc11372b30c/crucible                                                              40d3edd8-1c03-40a9-b78d-c7ee9093a1f2   in service    none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/clickhouse                                                      ca0f9499-7578-4144-a5bc-743e5e1949ab   expunged      none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/internal_dns                                                    8958b784-2e7f-483a-886d-07ffb58c661b   expunged      none      none          off
    oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/internal_dns                                                    752f25d7-6bb5-44ad-bf92-52d82f6469a6   in service    none      none          off
    oxp_3343a70d-37ad-4f89-a52c-2f2c1276f25c/crypt/internal_dns                                                    73414a28-6322-4f19-aa5a-5a41b39a50fd   in service    none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/zone                                                            13d3bd12-1716-4cd8-a4b2-a7a8f1d5cda8   expunged      none      none          off
    oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/zone                                                            c5cfcd2f-d7a3-4d93-9a2d-bff3a3fa0040   in service    none      none          off
    oxp_3343a70d-37ad-4f89-a52c-2f2c1276f25c/crypt/zone                                                            94531636-4c00-45d7-8635-121a004d3371   in service    none      none          off
    oxp_4cce2789-3630-4a06-97c3-db989b3a859c/crypt/zone                                                            399e8a70-455a-451d-876f-c2d8e3848db3   in service    none      none          off
    oxp_8d88e7cf-1c70-44a6-9e49-aa46b023dd75/crypt/zone                                                            7d0acf2d-64d7-4155-a0a3-b27df0e84e16   in service    none      none          off
    oxp_a66ed8b6-2d09-487f-8f67-208b47ae8479/crypt/zone                                                            8a5751bc-6cba-4cbc-8ebe-fec5b0ca19bb   in service    none      none          off
    oxp_b75d5788-427e-4dd1-8576-1e79ab332f0d/crypt/zone                                                            e7f13d82-178b-4657-9e6f-a8a03fb9fa8f   in service    none      none          off
    oxp_c8c33965-be2f-42cb-bed0-dbf93b9f3c14/crypt/zone                                                            72a32326-04ba-4e43-ad7c-0d5c523dce5c   in service    none      none          off
    oxp_e718f8d6-5219-46bb-9722-0291de2ceeb5/crypt/zone                                                            e25b2666-1d38-48c5-9b74-ff982d80ed91   in service    none      none          off
    oxp_e9dbf16d-6973-4405-9600-3cc11372b30c/crypt/zone                                                            ea358245-ddec-4410-b90f-c250ddb13060   in service    none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/zone/oxz_clickhouse_a84b8933-9b31-4bbf-81b1-151ad7b3fec6        126b2d8e-9205-4035-9951-eaf286e2a8a6   expunged      none      none          off
    oxp_b75d5788-427e-4dd1-8576-1e79ab332f0d/crypt/zone/oxz_crucible_09ad74cc-4cdf-4caf-b6da-a036833b960b          141de87f-85d6-453d-8c50-edc8dd38da7e   in service    none      none          off
    oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/zone/oxz_crucible_0c51734b-6dac-4a77-814c-234dd98fa994          7ec5fdd2-ab19-4427-abc3-281fc32d5813   in service    none      none          off
    oxp_3343a70d-37ad-4f89-a52c-2f2c1276f25c/crypt/zone/oxz_crucible_2d2227e4-1daf-4a9b-8441-06310860ace1          88b1f479-4634-48f4-a17c-bda634e6a631   in service    none      none          off
    oxp_c8c33965-be2f-42cb-bed0-dbf93b9f3c14/crypt/zone/oxz_crucible_3e5eff07-4fbf-40c3-ba23-a19fcef1d3d9          bc58cb40-fd54-4acf-85bd-d5928f5a3ce9   in service    none      none          off
    oxp_e9dbf16d-6973-4405-9600-3cc11372b30c/crypt/zone/oxz_crucible_4ee7b57a-99d5-42af-bd4a-1c2bddeec449          880d97c7-8429-4047-8b66-20145ada6553   in service    none      none          off
    oxp_a66ed8b6-2d09-487f-8f67-208b47ae8479/crypt/zone/oxz_crucible_5ca3817f-8fcd-4f4e-9859-1ac8997eeb90          893a3b7a-959a-47fe-90a3-7dd984f78d0d   in service    none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/zone/oxz_crucible_8ee7e76f-8de1-4e16-9ee2-c2134cef60af          5931d852-6cda-4ef5-bd6c-9ed37bdff50f   expunged      none      none          off
    oxp_e718f8d6-5219-46bb-9722-0291de2ceeb5/crypt/zone/oxz_crucible_cf764a28-c721-40d1-ba60-2d2c70af507e          e2be5471-11a1-4e0d-b03b-79474c59dae3   in service    none      none          off
    oxp_8d88e7cf-1c70-44a6-9e49-aa46b023dd75/crypt/zone/oxz_crucible_e386f27a-b18d-4932-bc01-690441c11c63          92c107a3-b4a3-49b9-b712-608f186b1fee   in service    none      none          off
    oxp_4cce2789-3630-4a06-97c3-db989b3a859c/crypt/zone/oxz_crucible_eb6709cc-762f-429d-8fd2-100189365c84          7669123d-bf76-4aff-907f-909b8138f8e4   in service    none      none          off
    oxp_3343a70d-37ad-4f89-a52c-2f2c1276f25c/crypt/zone/oxz_crucible_pantry_228f58f7-51f8-4ec7-b444-b6321455b8c2   833ea9da-6f36-41e6-8da1-1ffd104c6e2f   in service    none      none          off
    oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/zone/oxz_crucible_pantry_ab599159-4618-4ca2-9307-770c762eb0af   d54bb7ae-3145-4cf5-b6fc-6f9e90881d3a   in service    none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/zone/oxz_crucible_pantry_ed5e9223-e0d2-4797-a85b-0781ed74dd77   76ccdfea-c51c-431f-9059-328eed76e144   expunged      none      none          off
    oxp_3343a70d-37ad-4f89-a52c-2f2c1276f25c/crypt/zone/oxz_internal_dns_0a63f376-cb07-405e-8dec-66c2fa0b4d17      c1554fe1-2060-46f8-8d77-3b39245080bc   in service    none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/zone/oxz_internal_dns_15094518-59c3-48e4-b198-2f05ba3ed0f0      6e179041-e490-4b33-8515-609f305bc61e   expunged      none      none          off
    oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/zone/oxz_internal_dns_a3055eda-0e3d-4d06-9c77-25412f1d6cb7      88c93bad-b6e7-490b-be50-c945a5ae73e3   in service    none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/zone/oxz_nexus_91244e29-6a1e-49cf-b41c-77126bdbe7bf             2ab66a63-d29f-4ab8-9509-29734e7a19b5   expunged      none      none          off
    oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/zone/oxz_ntp_638fb3d1-b326-4d9b-ad0b-b888171f85d6               68c398ae-0d90-42cd-9c19-8dba63dfc12e   in service    none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/zone/oxz_ntp_eead5cc3-c090-4618-96e4-6f29d1f23d3f               90d14546-b49e-4014-aedf-35f17978092d   expunged      none      none          off
    oxp_0dd065e6-8a48-4755-aeb3-81d26f4e4982/crypt/debug                                                           5f004291-d974-45a4-b71f-f67f4d4f5fa7   expunged      100 GiB   none          gzip-9
    oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/debug                                                           863b47d2-6dc6-47eb-ae39-8ae36bb1c192   in service    100 GiB   none          gzip-9
    oxp_3343a70d-37ad-4f89-a52c-2f2c1276f25c/crypt/debug                                                           f85a73fa-4868-4f8a-8df1-0d2d2374f5ee   in service    100 GiB   none          gzip-9
    oxp_4cce2789-3630-4a06-97c3-db989b3a859c/crypt/debug                                                           23b97f04-9efa-48a1-89ab-0b449007f844   in service    100 GiB   none          gzip-9
    oxp_8d88e7cf-1c70-44a6-9e49-aa46b023dd75/crypt/debug                                                           9360f803-1a7d-4b57-8d01-5aa8a0701322   in service    100 GiB   none          gzip-9
    oxp_a66ed8b6-2d09-487f-8f67-208b47ae8479/crypt/debug                                                           356a0d06-54cd-46c6-8daf-b433d8cecfeb   in service    100 GiB   none          gzip-9
    oxp_b75d5788-427e-4dd1-8576-1e79ab332f0d/crypt/debug                                                           1e5b4a92-89a0-4bec-beb8-0ff72a9f1813   in service    100 GiB   none          gzip-9
    oxp_c8c33965-be2f-42cb-bed0-dbf93b9f3c14/crypt/debug                                                           a0ff9718-3c53-46f8-ba29-ba0b91a5aa95   in service    100 GiB   none          gzip-9
    oxp_e718f8d6-5219-46bb-9722-0291de2ceeb5/crypt/debug                                                           12bcfcaa-c8bc-49ce-a18a-da1d4d911daa   in service    100 GiB   none          gzip-9
    oxp_e9dbf16d-6973-4405-9600-3cc11372b30c/crypt/debug                                                           40162115-8d5a-4977-a022-1d0cd463cf69   in service    100 GiB   none          gzip-9
+   oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/clickhouse                                                      9387e6b0-db2e-4c49-86cd-afa289642107   in service    none      none          off
+   oxp_4cce2789-3630-4a06-97c3-db989b3a859c/crypt/internal_dns                                                    6ab587eb-b62c-4cbb-a1d9-992d1c537176   in service    none      none          off
+   oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/zone/oxz_clickhouse_f850e110-0d27-44e2-a276-1bbfeaa30da7        a34633b1-437e-46be-ad76-0a1c69e6dfb2   in service    none      none          off
+   oxp_4cce2789-3630-4a06-97c3-db989b3a859c/crypt/zone/oxz_crucible_pantry_fb77ad85-0128-4489-8b95-c402b20c39f1   384dae50-3c88-402d-8431-28c633d680d6   in service    none      none          off
+   oxp_4cce2789-3630-4a06-97c3-db989b3a859c/crypt/zone/oxz_internal_dns_55c9056b-bab4-421f-88b3-caded01f5d45      bf4735dd-c4d2-496b-bade-f063aeef9cf3   in service    none      none          off
+   oxp_0f30cb79-704c-4253-b3aa-5256ccf827f8/crypt/zone/oxz_nexus_9b8bff27-7752-401c-926f-92f1d2c6347f             aa8ca3e8-5bc6-4d96-b0d8-18da3f555e67   in service    none      none          off


    omicron zones generation 3 -> 4:
    ---------------------------------------------------------------------------------------------
    zone type         zone id                                disposition   underlay IP
    ---------------------------------------------------------------------------------------------
    clickhouse        a84b8933-9b31-4bbf-81b1-151ad7b3fec6   expunged      fd00:1122:3344:101::23
    crucible          09ad74cc-4cdf-4caf-b6da-a036833b960b   in service    fd00:1122:3344:101::2d
    crucible          0c51734b-6dac-4a77-814c-234dd98fa994   in service    fd00:1122:3344:101::28
    crucible          2d2227e4-1daf-4a9b-8441-06310860ace1   in service    fd00:1122:3344:101::29
    crucible          3e5eff07-4fbf-40c3-ba23-a19fcef1d3d9   in service    fd00:1122:3344:101::2e
    crucible          4ee7b57a-99d5-42af-bd4a-1c2bddeec449   in service    fd00:1122:3344:101::30
    crucible          5ca3817f-8fcd-4f4e-9859-1ac8997eeb90   in service    fd00:1122:3344:101::2c
    crucible          8ee7e76f-8de1-4e16-9ee2-c2134cef60af   expunged      fd00:1122:3344:101::27
    crucible          cf764a28-c721-40d1-ba60-2d2c70af507e   in service    fd00:1122:3344:101::2f
    crucible          e386f27a-b18d-4932-bc01-690441c11c63   in service    fd00:1122:3344:101::2b
    crucible          eb6709cc-762f-429d-8fd2-100189365c84   in service    fd00:1122:3344:101::2a
    crucible_pantry   228f58f7-51f8-4ec7-b444-b6321455b8c2   in service    fd00:1122:3344:101::26
    crucible_pantry   ab599159-4618-4ca2-9307-770c762eb0af   in service    fd00:1122:3344:101::25
    crucible_pantry   ed5e9223-e0d2-4797-a85b-0781ed74dd77   expunged      fd00:1122:3344:101::24
    internal_dns      0a63f376-cb07-405e-8dec-66c2fa0b4d17   in service    fd00:1122:3344:3::1
    internal_dns      15094518-59c3-48e4-b198-2f05ba3ed0f0   expunged      fd00:1122:3344:1::1
    internal_dns      a3055eda-0e3d-4d06-9c77-25412f1d6cb7   in service    fd00:1122:3344:2::1
    internal_ntp      638fb3d1-b326-4d9b-ad0b-b888171f85d6   in service    fd00:1122:3344:101::31
    internal_ntp      eead5cc3-c090-4618-96e4-6f29d1f23d3f   expunged      fd00:1122:3344:101::21
    nexus             91244e29-6a1e-49cf-b41c-77126bdbe7bf   expunged      fd00:1122:3344:101::22
+   clickhouse        f850e110-0d27-44e2-a276-1bbfeaa30da7   in service    fd00:1122:3344:101::32
+   crucible_pantry   fb77ad85-0128-4489-8b95-c402b20c39f1   in service    fd00:1122:3344:101::33
+   internal_dns      55c9056b-bab4-421f-88b3-caded01f5d45   in service    fd00:1122:3344:1::1
+   nexus             9b8bff27-7752-401c-926f-92f1d2c6347f   in service    fd00:1122:3344:101::34
```

This is restoring all the policy-required services that were expunged when going from blueprint 1 -> 2. I think the planner should have replaced these _in_ blueprint 2, right? If it expunges a disk, which expunges a zone, it should then replace those zones if required by the policy?

I don't see how this could have been caused by this PR. I'm inclined to leave this as-is, but file an issue and one of us can take a look at (a) fixing `assert_planning_makes_no_changes()` to actually run the planner and (b) addressing whatever is going wrong here. (I'm slightly worried other tests might fail in similar ways!)

File: nexus/reconfigurator/planning/src/planner.rs [hunk 6]
```diff
@@ -2121,21 +2351,29 @@ mod test {
         };
         println!("1 -> 2: marked non-provisionable {nonprovisionable_sled_id}");
         let expunged_sled_id = {
-            let (sled_id, details) = sleds_iter.next().expect("no sleds");
-            details.policy = SledPolicy::Expunged;
+            let (sled_id, _) = sleds_iter.next().expect("no sleds");
+            // We need to call builde.expunge, but can't while iterating; we defer
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/planner.rs:2355]:
```suggestion
            // We need to call builder.expunge_sled(), but can't while iterating; we defer
```

File: nexus/reconfigurator/planning/tests/output/planner_decommissions_sleds_bp2.txt [hunk 7]
```diff
@@ -82,31 +122,6 @@ parent:    516e80a3-b362-4fac-bd3c-4559717120dd
     nexus             294379f6-502c-465b-b32d-771c415a38af   in service    fd00:1122:3344:102::22
 
 
-
-!a1b477db-b629-48eb-911d-1ccdafca75b9
-WARNING: Zones exist without physical disks!
```
[the remark this answers is not in the document]
Comment (andrewjstone) [reply nexus/reconfigurator/planning/tests/output/planner_decommissions_sleds_bp2.txt:87]: Yes, yes it is!

File: nexus/reconfigurator/planning/src/planner.rs (hunk 5 above)
Comment (jgallagher) [reply nexus/reconfigurator/planning/src/planner.rs:1931]: Fixed in #7512

File: nexus/reconfigurator/execution/src/lib.rs [hunk 8]
```diff
@@ -230,14 +245,13 @@ fn register_zone_external_networking_step<'a>(
...
+                let res = datastore
                     .blueprint_ensure_external_networking_resources(
                         &opctx, blueprint,
                     )
                     .await
-                    .map_err(|err| anyhow!(err))?;
-
-                StepSuccess::new(()).into()
+                    .map_err(|err| anyhow!(err));
+                result_to_step_result(res)
```
[the remark this answers is not in the document]
Comment (andrewjstone) [reply nexus/reconfigurator/execution/src/lib.rs]: Done in de4a0805309651eea73e6c8bab1e256afbaf992d. I left it in this PR for now.

File: nexus/db-queries/src/db/datastore/physical_disk.rs [hunk 9]
```diff
@@ -282,18 +284,23 @@ impl DataStore {
     }
 
     /// Decommissions all expunged disks.
```
[the remark this answers is not in the document]
Comment (andrewjstone) [reply nexus/db-queries/src/db/datastore/physical_disk.rs]: Fixed in de4a0805309651eea73e6c8bab1e256afbaf992d

File: nexus/reconfigurator/execution/src/omicron_physical_disks.rs [hunk 10]
```diff
@@ -94,38 +95,50 @@ pub(crate) async fn deploy_disks(
...
+        .filter_map(|(sled_id, disk_id)| async move {
+            let log = opctx.log.new(slog::o!(
+                "sled_id" => sled_id.to_string(),
+                "disk_id" => disk_id.to_string(),
+            ));
+
+            match datastore.physical_disk_decommission(&opctx, disk_id).await {
+                Err(error) => {
+                    warn!(log, "failed to decommission expunged disk";
+                "error" => #%error);
```
[the remark this answers is not in the document]
Comment (andrewjstone) [reply nexus/reconfigurator/execution/src/omicron_physical_disks.rs]: ugh. Fixed in de4a0805309651eea73e6c8bab1e256afbaf992d

File: nexus/reconfigurator/planning/src/blueprint_editor/sled_editor/disks.rs [hunk 11]
```diff
@@ -116,6 +138,32 @@ impl DisksEditor {
...
+                        id: *disk_id,
+                    });
+                }
+                config.state = PhysicalDiskState::Decommissioned;
+                self.counts.decommissioned += 1;
+            }
+            PhysicalDiskState::Decommissioned => {}
+        }
+
+        Ok(())
```
[the remark this answers is not in the document]
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_editor/sled_editor/disks.rs]: I added the bool, but didn't plumb it all the way through to `record_operation`. It looks like sled decommissioning also hasn't done that, so maybe this could be done together in another PR.

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs (hunk 1 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_builder/builder.rs]: Great suggestion! Done in de4a0805309651eea73e6c8bab1e256afbaf992d

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs (hunk 2 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_builder/builder.rs]: Good eye. I *think* this was leftover from an old commit before I had started reworking diffs. Reverted in de4a0805309651eea73e6c8bab1e256afbaf992d.

File: nexus/reconfigurator/planning/src/planner.rs (hunk 3 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/planner.rs]: Good eye. Done in de4a0805309651eea73e6c8bab1e256afbaf992d.

File: nexus/reconfigurator/planning/src/planner.rs (hunk 4 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/planner.rs]: Fixed in de4a0805309651eea73e6c8bab1e256afbaf992d

File: nexus/reconfigurator/planning/src/planner.rs (hunk 6 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/planner.rs]: Fixed in de4a0805309651eea73e6c8bab1e256afbaf992d

File: nexus/reconfigurator/planning/src/blueprint_editor/sled_editor/disks.rs [hunk 12]
```diff
@@ -116,6 +138,32 @@ impl DisksEditor {
...
+        let config = self.disks.get_mut(disk_id).ok_or_else(|| {
+            DisksEditError::DecommissionNonexistentDisk { id: *disk_id }
+        })?;
+
+        match config.state {
+            PhysicalDiskState::Active => {
+                if config.disposition
+                    != BlueprintPhysicalDiskDisposition::Expunged
+                {
+                    return Err(DisksEditError::DecommissionInServiceDisk {
```
[the remark this answers is not in the document]
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_editor/sled_editor/disks.rs]: Agreed. Done in de4a0805309651eea73e6c8bab1e256afbaf992d

File: nexus/types/src/deployment.rs [hunk 13]
```diff
@@ -936,25 +974,33 @@ impl BlueprintPhysicalDiskDisposition {
...
+    }
+}
+
 /// Information about an Omicron physical disk as recorded in a bluerprint.
 #[derive(
     Clone, Debug, Deserialize, Serialize, JsonSchema, PartialEq, Eq, Diffable,
 )]
 pub struct BlueprintPhysicalDiskConfig {
     pub disposition: BlueprintPhysicalDiskDisposition,
+    pub state: PhysicalDiskState,
```
Comment (jgallagher) [inline nexus/types/src/deployment.rs:1003]: We chatted a bit last week about how to solve #7527, which I think is very similar to this PR in practice (the planner needs to note in the blueprint that expunged zones have transitioned to a state where we know via inventory that the sled where it was running will not start running it again). Mechanically, @davepacheco suggested that instead of a separate `state` field like this (which introduces the illegal combo `(Disposition::InServed, State::Decommissioned)` that has to be handled at runtime), we could put fields into the disposition (e.g., `BlueprintPhysicalDiskDisposition::Expunged { decommissioned: bool }`).

I can't remember if we talked about that and decided to go with `state` instead? I might try the embed-a-bool version for zones and see if I run into problems. I guess while I'm there it could also include the generation in which the zone became expunged, to make the planner's job slightly easier (it could check "is inventory generation >= generation when expunged" instead of having to check "is inventory generation == parent blueprint generation" which is sufficient but more restrictive).

Comment (jgallagher) [reply nexus/types/src/deployment.rs:1003]: #7558 is a stab at what this would look like for zones. I think I prefer it to a separate state? But would like other opinions.

Comment (andrewjstone) [reply nexus/types/src/deployment.rs:1003]: We chatted about this today in update watercooler and @jgallagher and I chatted more afterwards. We agreed to the direction taken in #7558 and I'm going to do the same thing here - namely get rid of the state and add fields to the disk disposition.

File: nexus/db-model/src/schema_versions.rs [hunk 14]
```diff
@@ -29,6 +29,7 @@ static KNOWN_VERSIONS: Lazy<Vec<KnownVersion>> = Lazy::new(|| {
         // |  leaving the first copy as an example for the next person.
         // v
         // KnownVersion::new(next_int, "unique-dirname-with-the-sql-files"),
+        KnownVersion::new(125, "bp-physical-disk-state"),
```
Comment (jgallagher) [inline nexus/db-model/src/schema_versions.rs:32]: Probably need a different name for this migration (and definitely need different `upX.sql` implementations)

File: nexus/db-queries/src/db/datastore/physical_disk.rs [hunk 15]
```diff
@@ -282,18 +284,23 @@ impl DataStore {
...
-            .physical_disk_filter(DiskFilter::ExpungedButActive)
-            .set(dsl::disk_state.eq(PhysicalDiskState::Decommissioned))
+            .filter(dsl::disk_policy.eq(PhysicalDiskPolicy::Expunged))
+            .set((
+                dsl::disk_state.eq(PhysicalDiskState::Decommissioned),
+                dsl::time_modified.eq(now),
+            ))
             .execute_async(conn)
             .await
             .map_err(|e| public_error_from_diesel(e, ErrorHandler::Server))?;
```
[the remark this answers is not in the document]
Comment (jgallagher) [reply nexus/db-queries/src/db/datastore/physical_disk.rs:306]: Bump on these questions

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs [hunk 16]
```diff
@@ -899,12 +903,12 @@ impl<'a> BlueprintBuilder<'a> {
         let mut num_zones_expunged = 0;
 
         let mut disks_to_expunge = Vec::new();
-        for disk in editor.disks(DiskFilter::All) {
+        for disk in editor.disks(BlueprintPhysicalDiskDisposition::any) {
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/blueprint_builder/builder.rs:906]: Could this be 

```suggestion
        for disk in editor.disks(BlueprintPhysicalDiskDisposition::is_in_service) {
```

instead of needing a `match` within the loop?

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs [hunk 17]
```diff
@@ -1097,16 +1089,95 @@ impl<'a> BlueprintBuilder<'a> {
...
+        // physically or via trust-quorum.
+        if sled_details.policy == SledPolicy::Expunged {
+            for (_, disk) in sled_details.resources.all_disks(DiskFilter::All) {
                 editor
-                    .expunge_disk(&disk_id)
+                    .decommission_disk(&disk.disk_id)
                     .map_err(|err| Error::SledEditError { sled_id, err })?;
             }
+        } else if let Some(parent_bp_config) =
+            self.parent_blueprint.blueprint_disks.get(&sled_id)
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/blueprint_builder/builder.rs:1151]: Do we still need to look at the parent blueprint now that we have `as_of_generation`? I think it's okay to look at our current disks (since if we just expunged them, the `as_of_generation` is guaranteed to be higher than anything that could be in inventory).

File: nexus/reconfigurator/planning/src/blueprint_editor/sled_editor/disks.rs [hunk 18]
```diff
@@ -104,18 +148,63 @@ impl DisksEditor {
...
+            BlueprintPhysicalDiskDisposition::Expunged {
+                ready_for_cleanup: false,
+                as_of_generation,
+            } => {
+                config.disposition =
+                    BlueprintPhysicalDiskDisposition::Expunged {
+                        ready_for_cleanup: true,
+                        as_of_generation,
+                    };
+                self.counts.decommissioned += 1;
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/blueprint_editor/sled_editor/disks.rs:194]: Hmm, will changing `counts` here cause us to bump the generation on the `PhysicalDisksConfig` we emit? That doesn't seem right. Could we return `true` here without modifying `counts`? (At that point maybe `counts` doesn't need the new `decommissioned` field?)

File: nexus/types/src/deployment.rs [hunk 19]
```diff
@@ -926,25 +951,71 @@ pub enum BlueprintPhysicalDiskDisposition {
...
 
     /// The physical disk is permanently gone.
-    Expunged,
+    Expunged {
+        /// Generation of the parent config in which this disk became expunged.
+        as_of_generation: Generation,
+
+        /// True if Reconfiguration knows that this disk has been expunged.
+        ///
+        /// In the current implementation, this means:
```
Comment (jgallagher) [inline nexus/types/src/deployment.rs:960]: Nit - maybe

```suggestion
        /// In the current implementation, this means either:
```

File: nexus/types/src/deployment.rs (hunk 13 above)
Comment (andrewjstone) [reply nexus/types/src/deployment.rs]: This was done in 7be692dbbe7936b29d3367f81957a3690b5b7ef5

File: nexus/db-model/src/schema_versions.rs (hunk 14 above)
Comment (andrewjstone) [reply nexus/db-model/src/schema_versions.rs]: For sure. Done in e2e2cd5016481ca8d89349f361afba78d8d1af07

File: nexus/reconfigurator/planning/src/blueprint_editor/sled_editor/disks.rs (hunk 18 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_editor/sled_editor/disks.rs]: Good call, this is what we just discussed wrt your upcoming changes. I added a relevant comment in a test for this as well. Done in 55a65f8d01ed8e54a7ade5b84eeae83a937956dd

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs (hunk 17 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_builder/builder.rs]: Great catch. Fixed in 55a65f8d01ed8e54a7ade5b84eeae83a937956dd.

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs (hunk 16 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_builder/builder.rs]: Derp. Done in 55a65f8d01ed8e54a7ade5b84eeae83a937956dd. Note that I had to keep the clone into a Vec because of the mutable borrow on `editor` inside the loop. Same for another change in the same commit.

File: nexus/types/src/deployment.rs (hunk 19 above)
Comment (andrewjstone) [reply nexus/types/src/deployment.rs]: Done in 55a65f8d01ed8e54a7ade5b84eeae83a937956dd

**Comment by andrewjstone** [comment]
@jgallagher I think this is ready for a re-review. I'll give it a test on a4x2 tomorrow as well.

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs [hunk 20]
```diff
@@ -1098,16 +1076,97 @@ impl<'a> BlueprintBuilder<'a> {
...
+                .collect();
+            for disk in expunged_disks {
+                if let BlueprintPhysicalDiskDisposition::Expunged {
+                    as_of_generation,
+                    ..
+                } = disk.disposition
+                {
+                    // Has the sled agent seen this disk's expungement yet as
+                    // reflected in inventory?
+                    if seen_generation >= Some(as_of_generation) {
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/blueprint_builder/builder.rs:1160]: This is correct but potentially comparing `None >= Some(as_of_generation)` feels icky. Is there a way we could make `seen_generation` non-optional by the time we get here, since if we didn't see this sled in the inventory collection we can't do anything? Could we make the else on line 1137 an `else if let Some(seen_generation) = ...`?

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs [hunk 21]
```diff
@@ -1098,16 +1076,97 @@ impl<'a> BlueprintBuilder<'a> {
...
+                .collection
+                .sled_agents
+                .get(&sled_id)
+                .map(|sa| sa.omicron_physical_disks_generation);
+
+            // Do we have any expunged disks?
+            let expunged_disks: Vec<_> = editor
+                .disks(BlueprintPhysicalDiskDisposition::is_expunged)
+                .cloned()
+                .collect();
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/blueprint_builder/builder.rs:1151]: Small style nit - feel free to ignore. Would it be slightly cleaner to check `seen_condition` as we're building up this Vec, and then make the loop below that calls `decommission_disk` unconditional? A light argument: once we've expunged a disk, as written this vec will be nonempty on every future planning iteration, even after we've already decommissioned the disk. If we instead filtered here, something like

```rust
let disks_to_decommission: Vec<_> = editor
    .disks(|disposition| match disposition {
        BlueprintPhysicalDiskDisposition::Expunged { ready_for_cleanup, .. } => !ready_for_cleanup,
        BlueprintPhysicalDiskDisposition::InService => false,
    })
    .cloned()
    .collect();
```

then this vec would be empty on planning runs after we've decommissioned any expunged disks.

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs [hunk 22]
```diff
@@ -1098,16 +1076,97 @@ impl<'a> BlueprintBuilder<'a> {
...
+    ///   *this* planner pass.
+    ///
+    ///   However, if the sled is still in service, we must wait for any
+    ///   disks expunged in this planner pass to be seen by the sled-agent and
+    ///   reflected in inventory before we can decommission them. Since any
+    ///   modifications made in this planner pass have not yet been sent to the
+    ///   sled-agents, we only check for expunged sleds in the parent_blueprint.
+    ///
+    ///
+    /// Called by the planner in the `do_plan_decommission()` stage of planning
```
Comment (jgallagher) [inline nexus/reconfigurator/planning/src/blueprint_builder/builder.rs:1109]: Should this method be in the planner instead? "Compare inventory and make changes" vaguely feels to me like it's a planner thing, and the builder should only expose whatever's needed for the "make changes" bit.

If that seems right, I think I'd make two suggestions:

* Move the "decommission disks for expunged sleds" logic into `BlueprintBuilder::expunge_sled()`, which already does everything else needed for expunging an entire sled.
* Add a `BlueprintBuilder::decommision_disks()` method that the planner could call in the `seen_generation >= as_of_generation` case.

(This mostly comes from comparing this branch against my first draft of doing all this same work for zones.)

File: nexus/types/src/deployment.rs [hunk 23]
```diff
@@ -869,7 +895,6 @@ pub enum BlueprintDatasetFilter {
     JsonSchema,
     Deserialize,
     Serialize,
-    EnumIter,
     Diffable,
 )]
 #[serde(rename_all = "snake_case")]
```
Comment (jgallagher) [inline nexus/types/src/deployment.rs:900]: I think this needs a 

```suggestion
#[serde(tag = "kind", rename_all = "snake_case")]
```

to fix the OpenAPI test failure complaint.

**Review by jgallagher — APPROVED** [review]
LGTM, mostly just some style and organization nits around planner vs builder.

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs (hunk 21 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_builder/builder.rs:1151]: I thought about doing this, but didn't take into account how much cheaper this would make things in the common case. I''ll do this. Thanks!

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs (hunk 22 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_builder/builder.rs:1109]: Very good point. I think I was cribbing too much off of names like `sled_add_disks` while not fully considering the planner builder split. Will do.

File: nexus/types/src/deployment.rs (hunk 23 above)
Comment (andrewjstone) [reply nexus/types/src/deployment.rs]: Fixed in [2531105](https://github.com/oxidecomputer/omicron/pull/7286/commits/2531105c56870e196236ad82cc9aad24829c148f).

Thanks!

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs (hunk 22 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_builder/builder.rs]: Done in [2531105](https://github.com/oxidecomputer/omicron/pull/7286/commits/2531105c56870e196236ad82cc9aad24829c148f).

The code is much clearer, thanks!

File: nexus/reconfigurator/planning/src/blueprint_builder/builder.rs (hunk 21 above)
Comment (andrewjstone) [reply nexus/reconfigurator/planning/src/blueprint_builder/builder.rs]: Done in [2531105](https://github.com/oxidecomputer/omicron/pull/7286/commits/2531105c56870e196236ad82cc9aad24829c148f).

**Comment by andrewjstone** [comment]
Testing on a4x2 successful. I can expunge a disk and generate blueprints and watch it expunge and decommission a disk with as well as expunge zones on that disk. I also expunged a sled and watched it expunge all disks and zones and relocate services.
