### PR TITLE
always move uploaded TUF repos to the replication task

### LINKED ISSUE #9140: always hand over uploaded TUF repos to the artifact replication task
Re-uploading a TUF repo is idempotent with regards to the database, but the artifacts are dropped if the repo is already listed in the database:

https://github.com/oxidecomputer/omicron/blob/4d5bdc6d348b27761348d763c4085f060bcefc18/nexus/src/app/update.rs#L66-L74

If artifacts are lost from replication (most likely due to a Nexus crash/restart) there would be no way to reintroduce those artifacts, other than by manually injecting them into the update dataset. By removing this conditional operators can fix this.

### PR DESCRIPTION
**Pull request by iliana**
Fixes #9140.

### CODE REVIEW

File: nexus/src/app/update.rs [hunk 1]
```diff
@@ -93,29 +92,28 @@ impl super::Nexus {
...
+        // was already uploaded, the artifacts should immediately be dropped by
+        // the task.)
+        self.tuf_artifact_replication_tx
+            .send(artifacts_with_plan)
+            .await
+            .map_err(|err| {
+                // In theory this should never happen; `Sender::send`
+                // returns an error only if the receiver has hung up, and
+                // the receiver should live for as long as Nexus does (it
+                // belongs to the background task driver).
```
Comment (sunshowers) [inline nexus/src/app/update.rs]: (This can happen during shutdown, where the order Tokio tasks are torn down in is undefined)

Comment (sunshowers) [reply nexus/src/app/update.rs]: How about changing it to:

> This error can only happen while Nexus's Tokio runtime is shutting down; `Sender::send` returns an error only if the receiver has hung up, and the receiver should live for as long as Nexus does (it belongs to the background task driver.)
>
> In the unlikely event that it _does_ happen within this narrow window, the impact is that the database has recorded a repository for which we no longer have the artifacts. The fix would be to reupload the repository.

**Review by sunshowers — APPROVED** [review]
