### PR TITLE
Make VPC Subnet insertion query idempotent

### LINKED ISSUE #6069: vpc_create saga failed after recovery: "subnet" node not idempotent
While testing #6063, I kicked off a whole bunch of `project-create` sagas, each of which contains a `vpc-create` subsaga.  I restarted Nexus while a bunch of them were running.  On startup, Nexus recovered 31 sagas, but 3 of them failed with this error logged:

```
18:32:32.664Z ERRO 333518da-5601-43e8-b9bd-f675571c5797 (ServerContext): failed to create default VPC Subnet, IP address range '172.30.0.0/22' overlaps with existing
    background_task = saga_recovery
    file = nexus/src/app/sagas/vpc_create.rs:374
    ipv4_block = Ipv4Net { addr: 172.30.0.0, width: 22 }
    ipv6_block = Ipv6Net { addr: fd25:a89f:414b::, width: 64 }
    saga_id = 919ea676-a9fb-451d-9775-b3613447d874
    saga_name = project-create
    subnet_id = 5f4c24ed-2995-42b3-a220-27cbf1293d27
    vpc_id = e884754e-223a-4540-a674-9aa44fa2669e
```

The ultimately failed like this:

```
18:32:33.259Z ERRO 333518da-5601-43e8-b9bd-f675571c5797 (ServerContext): saga finished
    action_error_node_name = "subnet"
    action_error_source = ActionFailed { source_error: Object {"InternalError": Object {"internal_message": String("Failed to create default VPC Subnet, found overlapping IP address ranges")}} }
    file = /home/dap/.cargo/registry/src/index.crates.io-6f17d22bba15001f/steno-0.4.1/src/sec.rs:1039
    result = failure
    saga_id = 919ea676-a9fb-451d-9775-b3613447d874
    saga_name = project-create
    sec_id = 333518da-5601-43e8-b9bd-f675571c5797
    undo_error = PermanentFailure { source_error: Object {"message": String("undo action attempt 1: Invalid Request: VPC cannot be deleted while VPC Subnets exist")} }
    undo_error_node_name = "vpc"
```

The action is implemented by [`svc_create_subnet`](https://github.com/oxidecomputer/omicron/blob/fe60eb9c20b105c023e68d27cdb6605e4211fe2c/nexus/src/app/sagas/vpc_create.rs#L361-L370), which basically just makes one datastore call to [`vpc_create_subnet()`](https://github.com/oxidecomputer/omicron/blob/fe60eb9c20b105c023e68d27cdb6605e4211fe2c/nexus/db-queries/src/db/datastore/vpc.rs#L819), which calls [`vpc_create_subnet_raw()`](https://github.com/oxidecomputer/omicron/blob/fe60eb9c20b105c023e68d27cdb6605e4211fe2c/nexus/db-queries/src/db/datastore/vpc.rs#L833), which does an [`INSERT`]:
https://github.com/oxidecomputer/omicron/blob/fe60eb9c20b105c023e68d27cdb6605e4211fe2c/nexus/db-queries/src/db/datastore/vpc.rs#L844-L849

That INSERT is designed to fail if the subnet overlaps with an existing one.

This is not idempotent because if we successfully insert it, then Nexus crashes, this operation will fail (in the way we saw above, I think).

---

Another problem reflected in the log is that these three sagas failed again when unwinding, at the `vpc` node, because they tried to delete the VPC but it still had a subnet under it (presumably from the first execution of the "subnet" node).  I believe this is _not_ a second bug.  The "vpc" action can safely assume that the "subnet" action either never started or else that it ran successfully at least once _and_ had its undo action run successfully at least once.  Either way, there'd be no subnet in the database when undoing the "vpc" node.  I don't think Steno did the wrong thing, either.  From its local state, it knew the action had started, but wasn't sure if it finished.  The correct behavior in that case is to run it again.  If that fails, it would undo the stuff _before_ it, just as it would have without a crash.  (Steno never runs undo actions for actions that themselves failed.)

---

There's potentially a second problem here which is that we have tests for action idempotency and I'd have expected them to catch this.  I'm not sure why they didn't.

### PR DESCRIPTION
**Pull request by bnaecker**
- Fixes #6069
- Add an additional CTE to the existing VPC Subnet insertion query which detects a re-insertion of the same row, and ignores conflicts on that ID. It also verifies that the contents of the IP address blocks are the same, in that case.
- Add regression test and handle new error variant where needed

### CODE REVIEW

File: nexus/db-queries/src/db/queries/vpc_subnet.rs [hunk 1]
```diff
@@ -549,4 +715,140 @@ mod test {
...
+        let with_new_ipv6_block =
+            VpcSubnet { ipv6_block: other_ipv6_block.into(), ..row.clone() };
+        let with_new_both = VpcSubnet {
+            ipv4_block: other_ipv4_block.into(),
+            ipv6_block: other_ipv6_block.into(),
+            ..row.clone()
+        };
+        let expected_err =
+            SubnetError::same_id_with_different_block(row.identity.id);
+        for each in [with_new_ipv4_block, with_new_ipv6_block, with_new_both] {
```
Comment (smklein) [inline nexus/db-queries/src/db/queries/vpc_subnet.rs:838]: Great test, love to see all three of these cases covered

File: nexus/db-queries/src/db/queries/vpc_subnet.rs [hunk 2]
```diff
@@ -549,4 +715,140 @@ mod test {
...
+                    < 1_000,
+                "VPC Subnet rows should be equal",
+            );
+            assert!(
+                (left.identity.time_created - right.identity.time_created)
+                    .num_nanoseconds()
+                    .unwrap()
+                    < 1_000,
+                "VPC Subnet rows should be equal",
+            );
```
Comment (smklein) [inline nexus/db-queries/src/db/queries/vpc_subnet.rs:784]: oof, looks like they aren't even truncating, but *rounding* to the nearest microsecond. I think what you have here is fine, but historically I have ignored a lot of "timestamp comparisons" in tests for this reason. That said, I suppose this is a more extensive check!

File: nexus/db-queries/src/db/queries/vpc_subnet.rs [hunk 3]
```diff
@@ -88,11 +122,64 @@ impl SubnetError {
...
+/// Generate a subquery that either selects an exact record by ID, or generates
+/// an error, if the record does not have the same IP block as the input.
+///
+/// ```sql
+/// SELECT
+///     CAST(IF(ipv*_block = <ip>, <ip_as_str>, 'different-ip-block') AS INET)
+/// FROM
+///     vpc_subnet
+/// WHERE
+///     id = <id> AND time_deleted IS NULL
```
Comment (smklein) [inline nexus/db-queries/src/db/queries/vpc_subnet.rs:140]: Not sure I'm actually requesting a change here, but:

The `time_deleted IS NULL` check here has me curious -- if someone did actually soft-delete a `vpc_subnet`, and then try to re-run this insertion query **using the same UUID**, would we *want* it to pass this check?

Maybe this doesn't matter, if the attempt to `INSERT` this record again would always fail with a unique violation outside this CTE, but figured I'd ask, because I'm not sure how this particular case would manifest

**Review by smklein — APPROVED** [review]

File: nexus/db-queries/src/db/queries/vpc_subnet.rs (hunk 2 above)
Comment (bnaecker) [reply nexus/db-queries/src/db/queries/vpc_subnet.rs:784]: Yeah, I think ignoring them is OK in many cases too. I kinda wonder if we should provide some methods for comparisons that ignore or check the difference between two timestamps, say as part of deriving the `Identity` trait or similar. But not critical :)

File: nexus/db-queries/src/db/queries/vpc_subnet.rs (hunk 3 above)
Comment (bnaecker) [reply nexus/db-queries/src/db/queries/vpc_subnet.rs:140]: Hmm, a good question. First, I agree it seems unlikely, since it would require the exact same ID as a deleted record. But I also think we'd see this query "work", but not actually insert the new record! That seems bad.

Here's the flow, I think:

- A caller inserts a VPC Subnet with the same ID as the soft-deleted one (the IP block doesn't matter, actually)
- This CTE returns NULL, because there isn't an **active** record that matches
- The other CTE returns the IP block of the new record to be inserted, because there's no **active** record in the VPC with an overlapping block.
- We would attempt to insert the record, which would raise the PK violation
- We _catch_ that and ignore it. But the row in the DB doesn't match the one we wanted to insert! For sure, the `time_deleted` value doesn't match, and it's also possible if that the other columns don't match either.

Comment (bnaecker) [reply nexus/db-queries/src/db/queries/vpc_subnet.rs:140]: So there's one option, based on something Dave proposed in a chat. We could actually back out these changes, and use the original implementation, with one catch. If we do fail the query in the original way, because there is an overlapping subnet already in the database, we could try to fetch a record with the PK of the provided argument. If that returns nothing, then the overlap was with a different subnet, and we fail the test as previously. If we do find such a record, we can compare it and either return a conflict or internal error if the data doesn't match, or return it if it does match.

It feels to me like this opens a race window, but I could be wrong about that.

Comment (bnaecker) [reply nexus/db-queries/src/db/queries/vpc_subnet.rs:140]: Ok, after much toil in the SQL shell, I think I have a way to write the query that will handle the following cases:

1. Active row, overlapping IP blocks, different PK -> **FAIL**
2. Active row, non-equal IP blocks, same PK -> **FAIL**
3. Active row, equal IP blocks, same PK -> **DO NOTHING**
4. Inactive row, no IP constraint, same PK -> **UPDATE**

Item (4) is what you brought up here: what happens if there's a previously-deleted row that happens to have the same PK? In the query in the last commit, we would attempt to insert the new data, catch the PK violation, and then return anyway. But the data in this case **may not match**, since we don't actually know what the existing record was, only that it had the same PK and was deleted.

I believe this catches all the cases we really want, including idempotent inserts (for the saga, the main point of this); failing if you happen to try to overwrite a live record with the same PK but different IP blocks; and catching the original intended behavior, inserting any record that overlaps with others in the same VPC.

Comment (bnaecker) [reply nexus/db-queries/src/db/queries/vpc_subnet.rs]: I've added the monstrosity in 462bfe634. I updated and expanded the tests a bit, and things seem to be working OK.

**Comment by bnaecker** [comment]
Alrighty, after much gnashing of teeth, 1b0b3bb26 has a reworked and simplified version. We now longer check anything about the contents of the existing row to determine if we should fail the query. It only (1) checks if another existing row has overlapping subnets, and (2) returns the inserted data or the row from the DB if it already exists.

File: nexus/db-queries/src/db/queries/vpc_subnet.rs [hunk 4]
```diff
@@ -7,407 +7,318 @@
...
+/// overlap AS MATERIALIZED (
+///     SELECT
+///         -- NOTE: This cast always fails, we just use _how_ it fails to
+///         -- learn which IP block overlaps.
+///         CAST(
+///             IF(
+///                 inet_contains_or_equals(ipv4_block, <ipv4_block>),
+///                'ipv4',
+///                 'ipv6'
+///             j)
```
Comment (smklein) [inline nexus/db-queries/src/db/queries/vpc_subnet.rs:49]:
```suggestion
///             )
```

File: nexus/db-queries/src/db/queries/vpc_subnet.rs [hunk 5]
```diff
@@ -7,407 +7,318 @@
...
-/// SELECT NULLIF(
-///     <ip>,
-///     push_select_overlapping_ip_range(<vpc_id>, <ip>)
+/// WITH
+/// -- This CTE generates a casting error if any live records, other than _this_
+/// -- record, have overlapping IP blocks of either family.
+/// overlap AS MATERIALIZED (
+///     SELECT
+///         -- NOTE: This cast always fails, we just use _how_ it fails to
+///         -- learn which IP block overlaps.
```
Comment (smklein) [inline nexus/db-queries/src/db/queries/vpc_subnet.rs:43]: Ah, because of the `WHERE` clause below? Clever. Might be worth an explicit call-out that we depend on that filter in this comment.

**Review by smklein — APPROVED** [review]

File: nexus/db-queries/src/db/queries/vpc_subnet.rs (hunk 5 above)
Comment (bnaecker) [reply nexus/db-queries/src/db/queries/vpc_subnet.rs:43]: Yeah, that's right. This cast is only called when there _is_ a record with a different PK that overlaps with one we're inserting. We would just like to know which block overlapped, to report a helpful error message. Will add more notes.

File: nexus/db-queries/src/db/queries/vpc_subnet.rs (hunk 4 above)
Comment (bnaecker) [reply nexus/db-queries/src/db/queries/vpc_subnet.rs]: Fixed in 11197cc0a

File: nexus/db-queries/src/db/queries/vpc_subnet.rs (hunk 5 above)
Comment (bnaecker) [reply nexus/db-queries/src/db/queries/vpc_subnet.rs]: Expanded the comment in 11197cc0a
