### PR TITLE
sled-agent: Better handling of internal DNS gz address and DDM advertisements

### LINKED ISSUE #7782: expunge of sled 16 left sled 14's global zone unable to communicate
After expunging sled 14 and then brining it back. sled 16 was expunged.

New blueprints were generated after expungement, and sled 14 was to receive an external NTP zone.
The process of applying this blueprint got stuck, and left things such that the global zone for 14 
could not contact other sleds in the rack.

From @rcgoodfellow in chat:
From a pure networking point of view: sled-agent assigned a rack level address before advertising that address via ddm, and then sourced traffic from that address, so peers have no route to respond over

### LINKED ISSUE #7785: sled-agent: Expunging an internal-dns zone doesn't remove its associated global zone address
When starting an internal-dns zone, sled-agent creates an address object in the global zone for routing: https://github.com/oxidecomputer/omicron/blob/d510d3b15d14793f8f4e8d27104813e84e2b7758/sled-agent/src/services.rs#L2324-L2342

It subsequently instructs DDM to advertise the prefix for that internal-dns address.

When an internal-dns zone is expunged (e.g., due to a failed disk), sled-agent will instruct DDM to withdraw the advertisement for that prefix. However, it does not delete the global zone address object it created. I think this could land us in the same spot as #7782 (for a different reason); i.e., we'd have an address in the gz that processes (including sled-agent itself!) could potentially use as a _source_ address for socket operations, but other sleds would have no way to route responses because DDM would no longer be advertising that prefix. This would be doubly confusing if another sled subsequently started an internal-dns zone reusing that same prefix, as we'd then have two sleds with the same address in their global zones, only one of which was advertising the prefix via DDM.

### PR DESCRIPTION
**Pull request by jgallagher**
Two changes in this PR to fix two closely-related bugs:

* Instead of waiting until after ensuring all zones have been destroyed/started to update the set of internal DNS prefixes we tell DDM to advertise, we now start advertising immediately after creating or deleting the gz address. Fixes #7782.
* When shutting down an internal DNS zone, delete the gz address we created when we started it. Fixes #7785.

I'm spinning this up on a4x2 and will do some testing around internal DNS expungement and addition before merging.

### CODE REVIEW

File: sled-agent/src/services.rs [hunk 1]
```diff
@@ -3659,20 +3664,29 @@ impl ServiceManager {
...
             error!(log, "Failed to stop zone {}: {e}", zone.name());
         }
+        if let Err(e) =
+            self.clean_up_after_zone_shutdown(&zone.config.zone).await
+        {
+            error!(
+                log,
+                "Failed to clean up after stopping zone {}", zone.name();
+                InlineErrorChain::new(&e),
+            );
```
Comment (jgallagher) [inline sled-agent/src/services.rs:3680]: This makes me nervous: if we fail to clean up, we never try again. But that's already true for everything else this function does; e.g., if we fail to stop the zone, we also never try again. I'm not sure if I'm making this demonstrably worse. I'm also not sure what other option we have prior to moving to a zones reconciler (which I'm still marching towards!).

File: sled-agent/src/services.rs [hunk 2]
```diff
@@ -3695,18 +3709,62 @@ impl ServiceManager {
...
+            .expect("internal DNS address object name is well-formed");
+            Zones::delete_address(None, &addrobj).map_err(|err| {
+                Error::ZoneCleanup {
+                    zone_name: zone.zone_name(),
+                    err: Box::new(err),
+                }
+            })?;
+
+            self.ddm_reconciler()
+                .remove_internal_dns_subnet(Ipv6Subnet::new(*gz_address));
```
Comment (jgallagher) [inline sled-agent/src/services.rs:3764]: I _think_ this ordering is correct? If we fail to delete the address, we probably (?) don't want to withdraw our advertisement for it? (FWIW this is why I also tried to make `delete_address()` idempotent.)

This compounds my concerns about `zone_bundle_and_try_remove()` above. If we expunge an internal DNS zone but fail to delete its address, we'll continue to have the address in our gz and continue to advertise the prefix, but will claim the zone is gone in inventory, which will allow reconfigurator to reuse that prefix for a new internal DNS zone on some other sled. :-1:

**Comment by jgallagher** [comment]
Testing notes from a4x2; this all looks like I'd hope. I tried a sequence of steps that might have replicated #7782, but I can't say for sure they would have (or even whether 7782 is deterministic). They definitely would have replicated #7785.

---

Initial state of sled g1 after RSS completed; we have an internal DNS zone, an `internaldns1` address object, and are advertising its prefix:

```
root@g1:~# zoneadm list | grep dns
oxz_internal_dns_52f9f383-b102-49c7-ae86-65d71aa36d01
root@g1:~# ipadm | grep dns
underlay0/internaldns1 static ok        fd00:1122:3344:2::2/64
root@g1:~# ddmadm get-originated
Prefix
fdb0:a840:2500:3::/64
fd00:1122:3344:102::/64
fd00:1122:3344:2::/64
```

---

I used `reconfigurator-cli` to expunge the internal DNS zone:

```
 MODIFIED SLEDS:

  sled 000d406f-8fc1-46c4-b414-52e093bc04c6 (active):

    physical disks at generation 2:
    ---------------------------------------------------------------------------
    vendor             model                serial                  disposition
    ---------------------------------------------------------------------------
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_0   in service
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_1   in service
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_2   in service
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_3   in service
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_4   in service


    datasets generation 1 -> 2:
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    dataset name                                                                                                   dataset id                             disposition    quota     reservation   compression
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/cockroachdb                                                     6aed522f-6494-45fa-8d5e-e94c99a9b4fd   in service     none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/cockroachdb                                                     2d56d1c7-1b8b-4fdf-b014-5bb1fda22d7c   in service     none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crucible                                                              bb957dae-c936-4bf4-b024-f6e3dfc80cc5   in service     none      none          off
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crucible                                                              336b4ba9-f23c-45c3-9aaf-b5cd3abe952c   in service     none      none          off
    oxp_445a5f7e-db6b-4625-83c6-2a2d2f852a0e/crucible                                                              95520b87-cf27-436d-b3a4-fb419ea2089c   in service     none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crucible                                                              2cc61ce4-54ce-459f-8ad1-b96fab7b9fc7   in service     none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crucible                                                              f57d107c-3482-41df-91b0-eccd14e43fb9   in service     none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/zone                                                            d5dc5726-dab4-4353-be7f-da350f5ce799   in service     none      none          off
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crypt/zone                                                            b4192da9-1043-438a-ae26-c4ec43378e96   in service     none      none          off
    oxp_445a5f7e-db6b-4625-83c6-2a2d2f852a0e/crypt/zone                                                            efe98e31-70f4-478c-b823-27a793827e70   in service     none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/zone                                                            4bfc554a-b76b-407c-9e68-0d851c2169d2   in service     none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone                                                            066eaebd-8c26-467c-bf75-912760009d1c   in service     none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/zone/oxz_cockroachdb_236f5359-a764-4c3f-88df-1ed32c084f21       938772c9-dc25-4041-a7e1-e26273f5b3d5   in service     none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone/oxz_cockroachdb_b4395571-3ff4-488d-9f79-65f56573ac3c       60e309d0-73e9-40a4-a87c-d0ffae5a4cad   in service     none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone/oxz_crucible_1916d2b6-3a92-444f-9dcd-1bc68259374a          b75d8f7f-b2ff-4cb0-bf48-203fc4cf5058   in service     none      none          off
    oxp_445a5f7e-db6b-4625-83c6-2a2d2f852a0e/crypt/zone/oxz_crucible_3a2587b7-0240-403b-a843-859c584ded1e          45e92cc3-091b-4c4d-bc64-cb8c0e16e510   in service     none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/zone/oxz_crucible_67a2e9f0-798f-4e27-894c-db0bd61eb385          8235a8de-494c-46b5-9b07-36a0d094ca25   in service     none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/zone/oxz_crucible_bb857622-4a5a-49ff-96c5-737bf0c8ad0f          5512f3bc-faf7-4723-8fe6-1784d7d06c9d   in service     none      none          off
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crypt/zone/oxz_crucible_bed8968d-d44e-48b2-acb6-8d1ac31a81e1          dd31545e-3695-446d-a6e1-09b2a6e2fc50   in service     none      none          off
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crypt/zone/oxz_crucible_pantry_3f04b022-cd5c-40fe-ab3d-74764076010a   c58a4a40-3200-473d-bef6-afdbdd78d716   in service     none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/zone/oxz_nexus_8e4ea4cc-cdc7-4792-b85c-c1eb11995b30             a32796b4-57dc-4fcf-86f1-1d26783d07d0   in service     none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/zone/oxz_ntp_468f7470-92b1-4ea1-8faf-4893b89dad53               cf0bb154-dfdd-437f-9f30-55479241e101   in service     none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone/oxz_oximeter_f6b33d34-25f0-488d-afb7-786189cebda2          8439e6bd-17eb-46b9-a513-4c5f666324c3   in service     none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/debug                                                           ecaa7e38-4c1d-41c7-993f-e594116bb300   in service     100 GiB   none          gzip-9
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crypt/debug                                                           116d4fd4-01b4-4bb5-a37b-eac10213a032   in service     100 GiB   none          gzip-9
    oxp_445a5f7e-db6b-4625-83c6-2a2d2f852a0e/crypt/debug                                                           3f05c265-a48d-4795-a6b2-0d3991385c66   in service     100 GiB   none          gzip-9
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/debug                                                           e983059a-28b0-4c46-94a8-e1abd0c7b494   in service     100 GiB   none          gzip-9
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/debug                                                           5fe4133b-0d50-4d1a-b972-720bd4c4cb5f   in service     100 GiB   none          gzip-9
*   oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/internal_dns                                                    51cf52d5-ed02-489f-8287-f09fcffeda44   - in service   none      none          off
     └─                                                                                                                                                   + expunged
*   oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone/oxz_internal_dns_52f9f383-b102-49c7-ae86-65d71aa36d01      185ee17c-f34c-483f-a0e2-86137bfd03cf   - in service   none      none          off
     └─                                                                                                                                                   + expunged


    omicron zones generation 5 -> 6:
    -----------------------------------------------------------------------------------------------------------------
    zone type         zone id                                image source      disposition      underlay IP
    -----------------------------------------------------------------------------------------------------------------
    boundary_ntp      468f7470-92b1-4ea1-8faf-4893b89dad53   install dataset   in service       fd00:1122:3344:102::d
    cockroach_db      236f5359-a764-4c3f-88df-1ed32c084f21   install dataset   in service       fd00:1122:3344:102::4
    cockroach_db      b4395571-3ff4-488d-9f79-65f56573ac3c   install dataset   in service       fd00:1122:3344:102::3
    crucible          1916d2b6-3a92-444f-9dcd-1bc68259374a   install dataset   in service       fd00:1122:3344:102::8
    crucible          3a2587b7-0240-403b-a843-859c584ded1e   install dataset   in service       fd00:1122:3344:102::c
    crucible          67a2e9f0-798f-4e27-894c-db0bd61eb385   install dataset   in service       fd00:1122:3344:102::9
    crucible          bb857622-4a5a-49ff-96c5-737bf0c8ad0f   install dataset   in service       fd00:1122:3344:102::a
    crucible          bed8968d-d44e-48b2-acb6-8d1ac31a81e1   install dataset   in service       fd00:1122:3344:102::b
    crucible_pantry   3f04b022-cd5c-40fe-ab3d-74764076010a   install dataset   in service       fd00:1122:3344:102::7
    nexus             8e4ea4cc-cdc7-4792-b85c-c1eb11995b30   install dataset   in service       fd00:1122:3344:102::5
    oximeter          f6b33d34-25f0-488d-afb7-786189cebda2   install dataset   in service       fd00:1122:3344:102::6
*   internal_dns      52f9f383-b102-49c7-ae86-65d71aa36d01   install dataset   - in service     fd00:1122:3344:2::1
     └─                                                                        + expunged ⏳
```

After blueprint execution, the zone, address, and prefix advertisement are gone, confirming #7785 is fixed:

```
root@g1:~# zoneadm list | grep dns
root@g1:~# ipadm | grep dns
root@g1:~# ddmadm get-originated
Prefix
fd00:1122:3344:102::/64
fdb0:a840:2500:3::/64
```

---

I then used reconfigurator-cli to produce a new blueprint that adds both an internal-dns zone and a Nexus zone to this sled. (I did this in two steps: `blueprint-plan` placed the new internal-dns zone on its own, since we were down to two, and then I used `blueprint-edit` to add a Nexus zone. I hand-edited the emitted JSON to tweak the `parent_blueprint_id` so Nexus would allow this new blueprint as a single step.) This was to emulate what @leftwo hit in #7782: trying to add an internal-dns zone and a zone that needs an OPTE port in one blueprint step. The blueprint diff:

```
 MODIFIED SLEDS:

  sled 000d406f-8fc1-46c4-b414-52e093bc04c6 (active):

    physical disks at generation 2:
    ---------------------------------------------------------------------------
    vendor             model                serial                  disposition
    ---------------------------------------------------------------------------
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_0   in service
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_1   in service
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_2   in service
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_3   in service
    synthetic-vendor   synthetic-model-U2   synthetic-serial-g1_4   in service


    datasets generation 2 -> 4:
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    dataset name                                                                                                   dataset id                             disposition   quota     reservation   compression
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/cockroachdb                                                     6aed522f-6494-45fa-8d5e-e94c99a9b4fd   in service    none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/cockroachdb                                                     2d56d1c7-1b8b-4fdf-b014-5bb1fda22d7c   in service    none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crucible                                                              bb957dae-c936-4bf4-b024-f6e3dfc80cc5   in service    none      none          off
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crucible                                                              336b4ba9-f23c-45c3-9aaf-b5cd3abe952c   in service    none      none          off
    oxp_445a5f7e-db6b-4625-83c6-2a2d2f852a0e/crucible                                                              95520b87-cf27-436d-b3a4-fb419ea2089c   in service    none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crucible                                                              2cc61ce4-54ce-459f-8ad1-b96fab7b9fc7   in service    none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crucible                                                              f57d107c-3482-41df-91b0-eccd14e43fb9   in service    none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/internal_dns                                                    51cf52d5-ed02-489f-8287-f09fcffeda44   expunged      none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/zone                                                            d5dc5726-dab4-4353-be7f-da350f5ce799   in service    none      none          off
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crypt/zone                                                            b4192da9-1043-438a-ae26-c4ec43378e96   in service    none      none          off
    oxp_445a5f7e-db6b-4625-83c6-2a2d2f852a0e/crypt/zone                                                            efe98e31-70f4-478c-b823-27a793827e70   in service    none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/zone                                                            4bfc554a-b76b-407c-9e68-0d851c2169d2   in service    none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone                                                            066eaebd-8c26-467c-bf75-912760009d1c   in service    none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/zone/oxz_cockroachdb_236f5359-a764-4c3f-88df-1ed32c084f21       938772c9-dc25-4041-a7e1-e26273f5b3d5   in service    none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone/oxz_cockroachdb_b4395571-3ff4-488d-9f79-65f56573ac3c       60e309d0-73e9-40a4-a87c-d0ffae5a4cad   in service    none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone/oxz_crucible_1916d2b6-3a92-444f-9dcd-1bc68259374a          b75d8f7f-b2ff-4cb0-bf48-203fc4cf5058   in service    none      none          off
    oxp_445a5f7e-db6b-4625-83c6-2a2d2f852a0e/crypt/zone/oxz_crucible_3a2587b7-0240-403b-a843-859c584ded1e          45e92cc3-091b-4c4d-bc64-cb8c0e16e510   in service    none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/zone/oxz_crucible_67a2e9f0-798f-4e27-894c-db0bd61eb385          8235a8de-494c-46b5-9b07-36a0d094ca25   in service    none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/zone/oxz_crucible_bb857622-4a5a-49ff-96c5-737bf0c8ad0f          5512f3bc-faf7-4723-8fe6-1784d7d06c9d   in service    none      none          off
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crypt/zone/oxz_crucible_bed8968d-d44e-48b2-acb6-8d1ac31a81e1          dd31545e-3695-446d-a6e1-09b2a6e2fc50   in service    none      none          off
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crypt/zone/oxz_crucible_pantry_3f04b022-cd5c-40fe-ab3d-74764076010a   c58a4a40-3200-473d-bef6-afdbdd78d716   in service    none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone/oxz_internal_dns_52f9f383-b102-49c7-ae86-65d71aa36d01      185ee17c-f34c-483f-a0e2-86137bfd03cf   expunged      none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/zone/oxz_nexus_8e4ea4cc-cdc7-4792-b85c-c1eb11995b30             a32796b4-57dc-4fcf-86f1-1d26783d07d0   in service    none      none          off
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/zone/oxz_ntp_468f7470-92b1-4ea1-8faf-4893b89dad53               cf0bb154-dfdd-437f-9f30-55479241e101   in service    none      none          off
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/zone/oxz_oximeter_f6b33d34-25f0-488d-afb7-786189cebda2          8439e6bd-17eb-46b9-a513-4c5f666324c3   in service    none      none          off
    oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/debug                                                           ecaa7e38-4c1d-41c7-993f-e594116bb300   in service    100 GiB   none          gzip-9
    oxp_424d4417-5755-4d43-beb8-5c8855064db3/crypt/debug                                                           116d4fd4-01b4-4bb5-a37b-eac10213a032   in service    100 GiB   none          gzip-9
    oxp_445a5f7e-db6b-4625-83c6-2a2d2f852a0e/crypt/debug                                                           3f05c265-a48d-4795-a6b2-0d3991385c66   in service    100 GiB   none          gzip-9
    oxp_b6ecbd78-2ffd-4e17-aed5-7880c7470af0/crypt/debug                                                           e983059a-28b0-4c46-94a8-e1abd0c7b494   in service    100 GiB   none          gzip-9
    oxp_d8b776d7-81f9-4632-a35d-6b3b02e2e0a5/crypt/debug                                                           5fe4133b-0d50-4d1a-b972-720bd4c4cb5f   in service    100 GiB   none          gzip-9
+   oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/internal_dns                                                    c82ba629-ec5f-4380-ad1e-41d47c35db23   in service    none      none          off
+   oxp_2a10f27d-6748-4dfa-85f0-67ee208b9e22/crypt/zone/oxz_internal_dns_b6867037-332f-4273-9002-6c603285fae5      f168b779-edf2-4c54-9eae-8e29cd443a0d   in service    none      none          off
+   oxp_424d4417-5755-4d43-beb8-5c8855064db3/crypt/zone/oxz_nexus_22214b6e-ed39-494a-be29-b0605148b511             9757f245-84b9-4729-be6d-1d338136fa34   in service    none      none          off


    omicron zones generation 6 -> 8:
    ------------------------------------------------------------------------------------------------------------------
    zone type         zone id                                image source      disposition      underlay IP
    ------------------------------------------------------------------------------------------------------------------
    boundary_ntp      468f7470-92b1-4ea1-8faf-4893b89dad53   install dataset   in service       fd00:1122:3344:102::d
    cockroach_db      236f5359-a764-4c3f-88df-1ed32c084f21   install dataset   in service       fd00:1122:3344:102::4
    cockroach_db      b4395571-3ff4-488d-9f79-65f56573ac3c   install dataset   in service       fd00:1122:3344:102::3
    crucible          1916d2b6-3a92-444f-9dcd-1bc68259374a   install dataset   in service       fd00:1122:3344:102::8
    crucible          3a2587b7-0240-403b-a843-859c584ded1e   install dataset   in service       fd00:1122:3344:102::c
    crucible          67a2e9f0-798f-4e27-894c-db0bd61eb385   install dataset   in service       fd00:1122:3344:102::9
    crucible          bb857622-4a5a-49ff-96c5-737bf0c8ad0f   install dataset   in service       fd00:1122:3344:102::a
    crucible          bed8968d-d44e-48b2-acb6-8d1ac31a81e1   install dataset   in service       fd00:1122:3344:102::b
    crucible_pantry   3f04b022-cd5c-40fe-ab3d-74764076010a   install dataset   in service       fd00:1122:3344:102::7
    nexus             8e4ea4cc-cdc7-4792-b85c-c1eb11995b30   install dataset   in service       fd00:1122:3344:102::5
    oximeter          f6b33d34-25f0-488d-afb7-786189cebda2   install dataset   in service       fd00:1122:3344:102::6
*   internal_dns      52f9f383-b102-49c7-ae86-65d71aa36d01   install dataset   - expunged ⏳     fd00:1122:3344:2::1
     └─                                                                        + expunged ✓
+   internal_dns      b6867037-332f-4273-9002-6c603285fae5   install dataset   in service       fd00:1122:3344:2::1
+   nexus             22214b6e-ed39-494a-be29-b0605148b511   install dataset   in service       fd00:1122:3344:102::21
```

After blueprint execution, we had both new zones, the new internaldns address object, and were once again advertising the DNS prefix:

```
root@g1:~# zoneadm list | egrep 'dns|nexus'
oxz_nexus_8e4ea4cc-cdc7-4792-b85c-c1eb11995b30
oxz_internal_dns_b6867037-332f-4273-9002-6c603285fae5
oxz_nexus_22214b6e-ed39-494a-be29-b0605148b511
root@g1:~# ipadm | grep dns
underlay0/internaldns0 static ok        fd00:1122:3344:2::2/64
root@g1:~# ddmadm get-originated
Prefix
fd00:1122:3344:102::/64
fdb0:a840:2500:3::/64
fd00:1122:3344:2::/64
```

File: illumos-utils/src/zone.rs [hunk 3]
```diff
@@ -879,4 +897,20 @@ mod tests {
...
         }
     }
+
+    // This test validates that we correctly detect an attempt to delete an
+    // address that does not exist and return `Ok(())`.
+    #[cfg(target_os = "illumos")]
+    #[test]
+    fn delete_nonexistent_address() {
+        // We'll pick a name that hopefully no system actually has...
+        let addr = AddrObject::new("nonsense", "shouldnotexist").unwrap();
```
Comment (andrewjstone) [inline illumos-utils/src/zone.rs:907]: Coincidentally these are the two names of my children.

File: sled-agent/src/services.rs (hunk 2 above)
Comment (andrewjstone) [reply sled-agent/src/services.rs:3764]: > I think this ordering is correct? If we fail to delete the address, we probably (?) don't want to withdraw our advertisement for it? (FWIW this is why I also tried to make delete_address() idempotent.)

I think this is correct. We should never fail to delete an address, although I saw it happen a long time ago via `ipadm` due to a race condition in illumos. I can't seem to dig up the issue though.

> This compounds my concerns about zone_bundle_and_try_remove() above. If we expunge an internal DNS zone but fail to delete its address, we'll continue to have the address in our gz and continue to advertise the prefix, but will claim the zone is gone in inventory, which will allow reconfigurator to reuse that prefix for a new internal DNS zone on some other sled. 👎

This seems more problematic to me. We always expect zone shutdown to work, and if it doesn't shutdown we don't really want traffic flowing to/from it, right? Would it be a problem if we swapped the cleanup with the zone shutdown? 

The core problem really is just that none of these are atomic, and retrying isn't necessarily likely to make shutdown/deletion work suddenly. Not sure there's a good way around that.

**Review by andrewjstone — APPROVED** [review]
This PR fixes an existing bug and I think it should go in. Up to you @jgallagher if you think we should swap the ordering of zone shutdown and ip address/route withdrawal. CC @davepacheco @rcgoodfellow

File: sled-agent/src/services.rs (hunk 2 above)
Comment (jgallagher) [reply sled-agent/src/services.rs:3764]: > We always expect zone shutdown to work, and if it doesn't shutdown we don't really want traffic flowing to/from it, right? Would it be a problem if we swapped the cleanup with the zone shutdown?

I'm not sure we're worried about the same problem. At the moment we always try to shut down the zone (once) and always try to clean up after the zone (once). Either of those failing does not affect attempting the other.

My concern was that within this cleanup function, we're ordered as

```rust
Zones::delete_address(...)?;
ddm.remove_internal_dns_subnet();
```

If the `delete_address` call fails, we won't stop advertising. I'll claim that's "local-to-this-sled correct" in light of #7782: if we still have the address but fail to advertise it, we may send packets using it as a source address, and other sleds won't be able to route responses to us. But it's problematic from a Reconfigurator point of view if zone shutdown _succeeded_; inventory will claim the zone is gone even though we didn't finish our local cleanup.

I don't think we have a good way to handle this case given the current structure. I'm inclined to move forward with this and try to address it with the upcoming reconciler work (which already will need to be able to report a richer set of partial failure/success than we can today).

Comment (andrewjstone) [reply sled-agent/src/services.rs:3764]: > I'm not sure we're worried about the same problem. At the moment we always try to shut down the zone (once) and always try to clean up after the zone (once). Either of those failing does not affect attempting the other.

This was a secondary concern of mine separate from the ordering of the calls in the cleanup function which I agree looks correct. We don't have a good way to solve for a failure of `delete_address`.

 I failed to notice the zone shutdown and cleanup were unconditional calls. If they were not unconditional calls, and we re-ordered them such that we did cleanup first then if cleanup failed, we didn't shutdown the zone, that would prevent at least a re-use of the address if `delete_adress` failed. 

In any case, this does need a more holistic fix, so happy for you to move on.
