### PR TITLE
RSS: Don't proceed on partial failure setting up disks

### LINKED ISSUE #7708: RSS ignores partial failure when initializing disks
An a4x2 launch failed due to RSS getting stuck trying to deploy zones to one of the sleds. Looking at that sled, it had a transient error due to a timeout during the "disk initialization" phase of RSS. The logs for the first disk show:

```
16:09:39.411Z INFO SledAgent (StorageResources): Invoking Disk::new on an unmanaged disk
    file = sled-storage/src/resources.rs:419
...
16:09:39.634Z INFO SledAgent (StorageResources): Loading latest secret
    disk_id = DiskIdentity { vendor: "synthetic-vendor", model: "synthetic-model-U2", serial: "synthetic-serial-g3_0" }
    file = sled-storage/src/dataset.rs:241
16:09:44.789Z WARN SledAgent (StorageResources): Disk::new failed
    err = Dataset(KeyManager(SecretRetrieval(Bootstore("Fsm error: rack secret load timeout"))))
    file = sled-storage/src/resources.rs:429
16:09:44.789Z WARN SledAgent (StorageResources): Cannot parse disk
    err = KeyManager("KeyManager error: Failed to retrieve secret: Bootstore error: Fsm error: rack secret load timeout")
    file = sled-storage/src/resources.rs:362
```

while the remaining four disks all initialized fine; e.g., the second disk:

```
16:09:44.789Z INFO SledAgent (StorageResources): Invoking Disk::new on an unmanaged disk
    file = sled-storage/src/resources.rs:419
...
16:09:45.003Z INFO SledAgent (StorageResources): Loading latest secret
    disk_id = DiskIdentity { vendor: "synthetic-vendor", model: "synthetic-model-U2", serial: "synthetic-serial-g3_1" }
    file = sled-storage/src/dataset.rs:241
16:09:46.821Z INFO SledAgent (StorageResources): Loaded latest secret
    disk_id = DiskIdentity { vendor: "synthetic-vendor", model: "synthetic-model-U2", serial: "synthetic-serial-g3_1" }
    epoch = 1
    file = sled-storage/src/dataset.rs:243
...
16:09:47.189Z INFO SledAgent (StorageResources): Disk::new completed successfully
    disk_identity = DiskIdentity { vendor: "synthetic-vendor", model: "synthetic-model-U2", serial: "synthetic-serial-g3_1" }
    file = sled-storage/src/resources.rs:440
16:09:47.190Z INFO SledAgent (StorageResources): Disk management started successfully
    disk_identity = DiskIdentity { vendor: "synthetic-vendor", model: "synthetic-model-U2", serial: "synthetic-serial-g3_1" }
    file = sled-storage/src/resources.rs:357
```

sled-agent does return a vec of disk initialization results, but it's inside an HTTP OK. RSS currently treats any HTTP OK as success and only tries to handle HTTP errors: https://github.com/oxidecomputer/omicron/blob/8dadcfb7ef198843bf8845720ba602f518f33c1b/sled-agent/src/rack_setup/service.rs#L390-L395

RSS should inspect the HTTP OK and retry partial success.

### PR DESCRIPTION
**Pull request by jgallagher**
Fixes #7708.

I don't know how to intentionally reproduce this, but running this branch a4x2 I did hit it again; I saw these warnings in the RSS log:

```
18:55:26.442Z WARN SledAgent (RSS): failed to initialize Omicron storage
    error = Transient errors initializing disks: Retryable error initializing disk synthetic-vendor / synthetic-model-U2 / synthetic-serial-g1_3: Failed to access keys necessary to unlock storage. This error may be transient.
    file = sled-agent/src/rack_setup/service.rs:502
    retry_after = 79.359726ms
    sled_address = [fd00:1122:3344:102::1]:12345
18:55:27.047Z WARN SledAgent (RSS): failed to initialize Omicron storage
    error = Transient errors initializing disks: Retryable error initializing disk synthetic-vendor / synthetic-model-U2 / synthetic-serial-g3_2: Failed to access keys necessary to unlock storage. This error may be transient.
    file = sled-agent/src/rack_setup/service.rs:502
    retry_after = 114.775643ms
    sled_address = [fd00:1122:3344:103::1]:12345
18:55:27.076Z WARN SledAgent (RSS): failed to initialize Omicron storage
    error = Transient errors initializing disks: Retryable error initializing disk synthetic-vendor / synthetic-model-U2 / synthetic-serial-g0_2: Failed to access keys necessary to unlock storage. This error may be transient.
    file = sled-agent/src/rack_setup/service.rs:502
    retry_after = 104.205445ms
    sled_address = [fd00:1122:3344:101::1]:12345
```

but then RSS proceeded (presumably due to eventual success) and encountered no further errors.

### CODE REVIEW

File: common/src/disk.rs [hunk 1]
```diff
@@ -512,7 +512,7 @@ pub enum DiskManagementError {
 }
 
 impl DiskManagementError {
-    fn retryable(&self) -> bool {
+    pub fn retryable(&self) -> bool {
```
Comment (smklein) [inline common/src/disk.rs:515]: ha, handy this already existed for us!

**Review by smklein — APPROVED** [review]
