### PR TITLE
Reconfigurator: Teach planner about SNAT IPs

### LINKED ISSUE #6194: Blueprint planner can't handle SNAT IPs that differ only by port range
After running RSS on london, I tried to generate a new blueprint, and hit this error:

```
16:54:40.747Z INFO 1845f669-68e4-48da-bcdb-3fc37390afa6 (dropshot_internal): request completed
    error_message_external = Internal Server Error
    error_message_internal = error creating blueprint planner: duplicate external IP: Snat(OmicronZoneExternalSnatIp { id: 993088a2-e585-4a3b-a70f-fd39d9036aa5 (external_ip), snat_cfg: SourceNatConfig { ip: 172.20.27.5, first_port: 0, last_port: 16383 } })
    file = /home/build/.cargo/git/checkouts/dropshot-a4a923d29dccc492/0c0bae3/dropshot/src/server.rs:902
    latency_us = 139766
    local_addr = [fd00:1122:3344:104::5]:12221
    method = POST
    remote_addr = [fd00:1122:3344:102::2]:62070
    req_id = b00054de-ded4-4bf8-a222-1aac9020d0b1
    response_code = 500
    uri = /deployment/blueprints/regenerate
```

This is caused by:

1. The planner currently expects external IPs to be distinct: https://github.com/oxidecomputer/omicron/blob/35a504198b548d8dc8980489a1f28d523ec55001/nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs#L113-L116
2. #6037 fixed a longstanding bug in RSS where it would use distinct IPs for SNAT instead of reusing IPs until the port range is exhausted

I've already got this fixed as part of the reconfigurator boundary NTP zone work, but that's still a little ways from landing, so I'll pull the fix for this into its own PR shortly to fix main.

### PR DESCRIPTION
**Pull request by jgallagher**
Prior to this change, the planner expected all blueprints to have fully-exclusive external IP addresses. This isn't compatible with #6037, where RSS now hands out SNAT IPs with distinct port ranges but the same IP address.

A big chunk of this work is necessary to support boundary NTP zone planning, but that isn't included in this PR, so those bits are marked with `#[cfg(test)]`.

Fixes #6194.

### CODE REVIEW

File: nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs [hunk 1]
```diff
@@ -295,9 +304,218 @@ impl<T: Hash + Eq> Iterator for AvailableIterator<'_, T> {
...
+        &mut self,
+        external_ip: &OmicronZoneExternalIp,
+    ) -> anyhow::Result<()> {
+        match external_ip {
+            OmicronZoneExternalIp::Floating(ip) => {
+                let ip = ip.ip;
+                if self.used_snat_ips.contains_key(&ip)
+                    || !self.used_exclusive_ips.insert(ip)
+                {
+                    bail!("duplicate external IP: {external_ip:?}");
```
Comment (sunshowers) [inline nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs:340]: Is this something we'll ever hit beyond a logic error?

IIRC there was an error enum in this code where internal logic errors could be put -- could this use that enum to be explicit?

File: nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs [hunk 2]
```diff
@@ -295,9 +304,218 @@ impl<T: Hash + Eq> Iterator for AvailableIterator<'_, T> {
...
+    // a mismatched exclusiveness / SNAT-ness.
+    fn contains(
+        &self,
+        external_ip: &OmicronZoneExternalIp,
+    ) -> anyhow::Result<bool> {
+        match external_ip {
+            OmicronZoneExternalIp::Floating(ip) => {
+                let ip = ip.ip;
+                if self.used_snat_ips.contains_key(&ip) {
+                    bail!(
```
Comment (sunshowers) [inline nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs:372]: same comment here -- internal enum for logic error?

File: nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs [hunk 3]
```diff
@@ -295,9 +304,218 @@ impl<T: Hash + Eq> Iterator for AvailableIterator<'_, T> {
...
+
+        Err(Error::NoExternalServiceIpAvailable)
+    }
+}
+
+#[derive(
+    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, strum::EnumIter,
+)]
+#[cfg_attr(test, derive(test_strategy::Arbitrary))]
+enum SnatPortRange {
```
Comment (sunshowers) [inline nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs:448]: Oh hey, this is what we talked about at some point right?

File: nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs [hunk 4]
```diff
@@ -295,9 +304,218 @@ impl<T: Hash + Eq> Iterator for AvailableIterator<'_, T> {
...
+            SnatPortRange::Three => 2 * NUM_SOURCE_NAT_PORTS,
+            SnatPortRange::Four => 3 * NUM_SOURCE_NAT_PORTS,
+        };
+
+        // Parens are important here to avoid overflow on the last range!
+        let last = first + (NUM_SOURCE_NAT_PORTS - 1);
+
+        // By construction our (first, last) pair is aligned, so we can unwrap
+        // here. We'll use an explicit match to guard against `SourceNatConfig`
+        // gaining other kinds of validation we're currently not aware of.
```
Comment (sunshowers) [inline nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs:472]: Good idea!

**Review by sunshowers — APPROVED** [review]
Looks great!

File: nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs (hunk 3 above)
Comment (jgallagher) [reply nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs:448]: Almost - we talked about it in the bigger context of `omicron-common`; this is more of a local trial run of that idea. I think I like it, but it's not entirely frictionless.

File: nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs (hunk 1 above)
Comment (sunshowers) [reply nexus/reconfigurator/planning/src/blueprint_builder/external_networking.rs:340]: Ah if it's already the prevailing standard then this is okay. I'd say it's definitely worth doing at some point though, anyhow errors floating around just make me uncomfortable because of how untyped they are.
