### PR TITLE
cockroach-admin: Allow partial success parsing `cockroach node status --all` rows

### LINKED ISSUE #10068: cockroach-admin fails to report node status after other cockroach zones are expunged
Trying to develop a live test that would have caught #10025, I got london into a state where we were only getting cockroach status from 4 nodes, even though we had 5 online and healthy. The inventory report showed:

```
COCKROACH STATUS
    status from nodes: 2, 3, 4, 5
    ranges underreplicated: 0
    live nodes: 5
```

Logs from Nexus's inventory collector showed this failure trying to collect from the fifth node:

```
00:46:05.515Z WARN 9fab4d9c-10f7-4956-8c2d-18de75beac49 (ServerContext): Failed to fetch metrics from CockroachDB node
    error = Failed to get node ID from [fd3e:7225:64f1:101::3a]:32222
    file = cockroach-metrics/src/lib.rs:374
```

Going to that zone, trying to talk to the cockroach-admin server endpoints that involve parsing the output of `cockroach node status --all` were failing with errors that we've seen before (https://github.com/oxidecomputer/omicron/issues/8445#issuecomment-3005368549):

```
root@oxz_cockroachdb_0b9e7f01:~# curl -H 'api-version: 1.0.0' http://[fd3e:7225:64f1:101::3a]:32222/node/status
{
  "request_id": "a6d24ad7-b0e3-4b2e-9341-c4209b9fe247",
  "error_code": "Internal",
  "message": "failed to parse stdout \"id,address,sql_address,build,started_at,updated_at,locality,is_available,is_live,replicas_leaders,replicas_leaseholders,ranges,ranges_unavailable,ranges_underreplicated,live_bytes,key_bytes,value_bytes,intent_bytes,system_bytes,gossiped_replicas,is_decommissioning,membership,is_draining\\n1,NULL,NULL,NULL,NULL,2026-03-17 00:28:07.845312,NULL,false,false,50,50,244,0,0,232400764,76374197,322723215,0,166651,NULL,false,active,false\\n2,[fd3e:7225:64f1:102::3]:32221,[fd3e:7225:64f1:102::3]:32221,v22.1.22-46-g367bca413b,2026-03-16 19:20:59.488975,2026-03-17 00:49:12.573435,,true,true,48,48,244,0,0,505851138,114074028,651318542,0,707599,244,false,active,false\\n3,[fd3e:7225:64f1:104::3]:32221,[fd3e:7225:64f1:104::3]:32221,v22.1.22-46-g367bca413b,2026-03-16 19:21:00.330062,2026-03-17 00:49:12.320826,,true,true,49,49,244,0,0,505941788,114074052,651409236,0,707599,244,false,active,false\\n4,[fd3e:7225:64f1:103::3]:32221,[fd3e:7225:64f1:103::3]:32221,v22.1.22-46-g367bca413b,2026-03-16 19:21:00.432083,2026-03-17 00:49:12.422705,,true,true,48,48,244,0,0,505987858,114074293,651455102,0,707599,244,false,active,false\\n5,[fd3e:7225:64f1:104::4]:32221,[fd3e:7225:64f1:104::4]:32221,v22.1.22-46-g367bca413b,2026-03-16 19:21:00.683945,2026-03-17 00:49:12.67174,,true,true,45,45,244,0,0,505896463,114074052,651363911,0,707599,244,false,active,false\\n6,NULL,NULL,NULL,NULL,2026-03-17 00:28:07.845325,NULL,false,false,54,54,227,0,21,241750790,74592314,326610733,0,275612,NULL,false,active,false\\n7,NULL,NULL,NULL,NULL,2026-03-17 00:28:07.845326,NULL,false,false,54,54,244,0,0,274322449,84865180,370993320,0,433888,NULL,false,active,false\\n8,[fd3e:7225:64f1:101::33]:32221,[fd3e:7225:64f1:101::33]:32221,v22.1.22-46-g367bca413b,2026-03-16 22:13:14.330106,2026-03-17 00:28:07.845328,,false,false,54,54,244,0,0,465351282,99646220,595058198,0,647190,0,false,active,false\\n9,[fd3e:7225:64f1:101::3a]:32221,[fd3e:7225:64f1:101::3a]:32221,v22.1.22-46-g367bca413b,2026-03-17 00:26:13.672751,2026-03-17 00:49:15.258134,,true,true,54,54,244,0,0,505641887,114109608,651500710,0,707599,244,false,active,false\\n\", stderr \"\": failed to parse `cockroach node status` output: failed to parse node status row StringRecord([\"1\", \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"2026-03-17 00:28:07.845312\", \"NULL\", \"false\", \"false\", \"50\", \"50\", \"244\", \"0\", \"0\", \"232400764\", \"76374197\", \"322723215\", \"0\", \"166651\", \"NULL\", \"false\", \"active\", \"false\"]): CSV deserialize error: record 1 (line: 2, byte: 288): invalid socket address syntax"
}
```

For easier human output, the table formatted output of `node status --all` was:

```
  id |            address             |          sql_address           |          build          |         started_at         |         updated_at         | locality | is_available | is_live | replicas_leaders | replicas_leaseholders | ranges | ranges_unavailable | ranges_underreplicated | live_bytes | key_bytes | value_bytes | intent_bytes | system_bytes | gossiped_replicas | is_decommissioning | membership | is_draining
-----+--------------------------------+--------------------------------+-------------------------+----------------------------+----------------------------+----------+--------------+---------+------------------+-----------------------+--------+--------------------+------------------------+------------+-----------+-------------+--------------+--------------+-------------------+--------------------+------------+--------------
   1 | NULL                           | NULL                           | NULL                    | NULL                       | 2026-03-17 00:28:07.845312 |     NULL |        false |   false |               50 |                    50 |    244 |                  0 |                      0 |  232400764 |  76374197 |   322723215 |            0 |       166651 |       NULL        |              false |   active   |    false
   2 | [fd3e:7225:64f1:102::3]:32221  | [fd3e:7225:64f1:102::3]:32221  | v22.1.22-46-g367bca413b | 2026-03-16 19:20:59.488975 | 2026-03-17 00:51:54.582386 |          |         true |    true |               48 |                    48 |    244 |                  0 |                      0 |  509161972 | 115363708 |   655915927 |            0 |       707599 |        244        |              false |   active   |    false
   3 | [fd3e:7225:64f1:104::3]:32221  | [fd3e:7225:64f1:104::3]:32221  | v22.1.22-46-g367bca413b | 2026-03-16 19:21:00.330062 | 2026-03-17 00:51:54.320562 |          |         true |    true |               49 |                    49 |    244 |                  0 |                      0 |  509252622 | 115363803 |   656006721 |            0 |       707599 |        244        |              false |   active   |    false
   4 | [fd3e:7225:64f1:103::3]:32221  | [fd3e:7225:64f1:103::3]:32221  | v22.1.22-46-g367bca413b | 2026-03-16 19:21:00.432083 | 2026-03-17 00:51:54.420175 |          |         true |    true |               48 |                    48 |    244 |                  0 |                      0 |  509297947 | 115363803 |   656052046 |            0 |       707599 |        244        |              false |   active   |    false
   5 | [fd3e:7225:64f1:104::4]:32221  | [fd3e:7225:64f1:104::4]:32221  | v22.1.22-46-g367bca413b | 2026-03-16 19:21:00.683945 | 2026-03-17 00:51:54.671706 |          |         true |    true |               45 |                    45 |    244 |                  0 |                      0 |  509207297 | 115363803 |   655961396 |            0 |       707599 |        244        |              false |   active   |    false
   6 | NULL                           | NULL                           | NULL                    | NULL                       | 2026-03-17 00:28:07.845325 |     NULL |        false |   false |               54 |                    54 |    227 |                  0 |                     21 |  241750790 |  74592314 |   326610733 |            0 |       275612 |       NULL        |              false |   active   |    false
   7 | NULL                           | NULL                           | NULL                    | NULL                       | 2026-03-17 00:28:07.845326 |     NULL |        false |   false |               54 |                    54 |    244 |                  0 |                      0 |  274322449 |  84865180 |   370993320 |            0 |       433888 |       NULL        |              false |   active   |    false
   8 | [fd3e:7225:64f1:101::33]:32221 | [fd3e:7225:64f1:101::33]:32221 | v22.1.22-46-g367bca413b | 2026-03-16 22:13:14.330106 | 2026-03-17 00:28:07.845328 |          |        false |   false |               54 |                    54 |    244 |                  0 |                      0 |  465351282 |  99646220 |   595058198 |            0 |       647190 |         0         |              false |   active   |    false
   9 | [fd3e:7225:64f1:101::3a]:32221 | [fd3e:7225:64f1:101::3a]:32221 | v22.1.22-46-g367bca413b | 2026-03-17 00:26:13.672751 | 2026-03-17 00:51:52.766247 |          |         true |    true |               54 |                    54 |    244 |                  0 |                      0 |  509343272 | 115363911 |   656097570 |            0 |       707599 |        244        |              false |   active   |    false
```

Our parser will skip rows with a `membership` value of `decommissioned`, but none of these nodes are decommissioned - we then fail to parse `NULL` as a socket address. 

The cockroach-admin servers in _all_ the cockroach nodes were failing with this error when asked for `/node/status`. The inventory collector instead hits `/node/id` and then `/proxy/status/vars`. `/node/id` was succeeding on 4/5 nodes, but I believe this is only because cockroach-admin caches this value on first success (since the node ID of a running zone can never change) - if we were to restart the zones, I believe they'd all be failing and we'd get no inventory.

`/proxy/status/vars` was functional on all five nodes. Is there enough information there that we could remove the command line parsing entirely? Otherwise, I think we need to be more lenient on what we accept here - perhaps discard rows we fail to parse but report values for any we can, instead of failing the entire request?

### PR DESCRIPTION
**Pull request by jgallagher**
The `cockroach-admin` server runs `cockroach node status --all` both to find its local node ID and to service the `/node/status` endpoint. We have no production callers of the latter, but inventory relies on the former. We've previously seen that we can't get reasonable status from decommissioned nodes (in particular, we rely on socket addresses being present, and decommissioned nodes have `NULL` socket addresses) and so already skip rows from decommissioned nodes. However, in #10068 we saw similar invalid rows from not-yet-decommissioned nodes, which broke inventory collection.

This change relaxes our parsing: instead of bailing on any failure parsing a single row, we accumulate separate vecs of successfully parsed rows and failures parsing rows and return both. `cockroach-admin` logs the errors but otherwise ignores them. I don't love this but I _think_ it should be okay; a failure mode here is "we fail to parse any rows at all", but in practice the effect of having an empty vec of successfully-parsed rows is the same as failing the call entirely: we won't be able to find our local node ID or report any useful node status.

I think we'd be better off jettisoning this parsing entirely, if there's a way we could get at all this information from another source (either the prometheus endpoint we're already scraping, or maaaaaybe poking at files on disk, e.g., if there's a file that contains the local node ID?). But either of those would be larger changes, and this should unblock testing that bumped into the parsing issue.

Closes #10068.

### CODE REVIEW

File: cockroach-admin/types/versions/src/impls/node.rs [hunk 1]
```diff
@@ -45,16 +49,23 @@ pub enum DecommissionError {
...
-        // directly, because the `node status --all` flag to get all details
-        // also causes cockroach to emit statuses for decommissioned nodes,
-        // which report `NULL` for most fields. For now, we want to skip
-        // decommissioned nodes entirely, so we'll parse each record
-        // individually after checking first for whether it's decommissioned.
+        // We want to intentionally omit any decommissioned nodes: they
+        // shouldn't be returned as either `NodeStatus` rows _or_ parse errors.
+        // We expect them to produce parse errors (they report a socket address
+        // of `NULL`), so we'll check for decommissioned before attempting to
+        // parse.
```
Comment (smklein) [inline cockroach-admin/types/versions/src/impls/node.rs:68]: So, I'm totally on-board with this PR as it exists - makes sense to prevent a single parse error from stopping the whole status endpoint - but do we *want* to allow parsing NULL socket addresses as valid?

Put another way: It seems like "This is how CRDB works - the address field is actually an `Option`". Shouldn't we update our view of the `struct NodeStatus` to make some of these fields optional?

(basically: I think it's great to handle parse errors and continue going, but it also seems like we could / should avoid having parse errors, if we can!)

Comment (smklein) [reply cockroach-admin/types/versions/src/impls/node.rs:68]: I'm also okay punting this, if it immediately lets us unblock a wedged system. I suspect that "parsing these rows of expunged (but not decommissioned) nodes" might be more relevant later if we *do* want to do decommissioning down the line

Comment (jgallagher) [reply cockroach-admin/types/versions/src/impls/node.rs:68]: Hmm good question. I think when I originally wrote it like this, there were consumers that needed the IP address to be `Some(_)` to do anything useful, and a missing IP made the status entirely unusable. But maybe that's not true anymore (or maybe even if it is, it's not that bad). I'm inclined to land this and promote your comment here to a new issue.

**Comment by jgallagher** [comment]
> Re: your suggestion to possibly use Prometheus - wouldn't we still need to do similar parsing, just from a different source?

Ah yeah probably so. 

> (Not opposed to using it, just trying to understand your comment about "jettisoning this parsing entirely")

Shelling out and parsing CSV (or worse, [quasi-CSV-followed-by-arbitrary-messages](https://github.com/oxidecomputer/omicron/blob/9b5d906eb4682b44428b8dbc2cc64a61940f584b/cockroach-admin/types/versions/src/impls/node.rs#L208-L217)) feels awful. Maybe this is me just hoping there was a better source for all of this.

File: cockroach-admin/types/versions/src/impls/node.rs (hunk 1 above)
Comment (smklein) [reply cockroach-admin/types/versions/src/impls/node.rs:68]: > I'm inclined to land this and promote your comment here to a new issue.

Fully on-board with this plan!

**Comment by smklein** [comment]
> Shelling out and parsing CSV (or worse, [quasi-CSV-followed-by-arbitrary-messages](https://github.com/oxidecomputer/omicron/blob/9b5d906eb4682b44428b8dbc2cc64a61940f584b/cockroach-admin/types/versions/src/impls/node.rs#L208-L217)) feels awful. Maybe this is me just hoping there was a better source for all of this.

I get the hesitation, I just suspect a prometheus endpoint would have the same "null or not" issue we're facing here - and unless we change our in-memory struct representing the NodeStatus to cope with optionality, we'd probably fail to parse that too. (AKA: doesn't seem like the CSV formatting is the source of this parsing error)

File: cockroach-admin/types/versions/src/impls/node.rs (hunk 1 above)
Comment (jgallagher) [reply cockroach-admin/types/versions/src/impls/node.rs:68]: #10080
