### PR TITLE
Fix race between sled-agent and zone-setup service

### LINKED ISSUE #6149: Possible race between sled-agent and self-assembling switch zone
I've been having trouble deploying Omicron on my local Helios machine, using the a recent main (38575abf11e463993bdb953fc3ad3653cbf8a3b6 as of this writing). This is using the workflow "Bare-metal operating system" from `docs/how-to-run.adoc`. The behavior is sporadic, but here's what I've learned so far. I will fill in more details as I get them.

I generally see the first few zones being created: the switch zone, the internal DNS zones, and sometimes the NTP zone. At some point, things stall out. The zones don't fail, but the sled-agent makes no further progress creating new zones. I also see errors like this in the sled-agent log:

```
04:34:51.998Z ERRO SledAgent (HardwareMonitor): Failed to activate switch
    error = Failed to create address Static(V6(Ipv6Network { addr: fd00:1122:3344:101::2, prefix: 64 })) with name oxControlService0/omicron6 in oxz_switch: Zone execution error: Command [/usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlService0/omicron6] executed and failed with status: exit status: 1  stdout: \n  stderr: ipadm: Could not create address: Interface does not exist: Zone execution error: Command [/usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlService0/omicron6] executed and failed with status: exit status: 1  stdout: \n  stderr: ipadm: Could not create address: Interface does not exist: Command [/usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlService0/omicron6] executed and failed with status: exit status: 1  stdout: \n  stderr: ipadm: Could not create address: Interface does not exist
    file = sled-agent/src/hardware_monitor.rs:237
```

In most cases, I also see that MGS in the switch zone is not happy:

```
bnaecker@shale : ~/omicron $ pfexec svcs -Zx
svc:/oxide/mgs:default (Oxide Management Gateway Service)
  Zone: oxz_switch
 State: maintenance since July 24, 2024 at 04:49:31 AM UTC
Reason: Restarting too quickly.
   See: http://illumos.org/msg/SMF-8000-L5
   See: /zone/oxz_switch/root/var/svc/log/oxide-mgs:default.log
Impact: This service is not running.
```

Why is that process not running?

```
bnaecker@shale : ~/omicron $ pfexec zlogin oxz_switch 'tail $(svcs -L mgs)'
Jul 24 04:49:31.212 INFO received discovery response (not used for location), sp_port: One, interface: (direct socket handle), component: ManagementSwitch, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f, file: gateway/src/management_switch/location_map.rs:376
Jul 24 04:49:31.212 INFO received discovery response (used for location), pos: 1, sp_port: One, interface: (direct socket handle), component: ManagementSwitch, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f, file: gateway/src/management_switch/location_map.rs:367
Jul 24 04:49:31.212 INFO received discovery response (used for location), pos: 0, sp_port: One, interface: (direct socket handle), component: ManagementSwitch, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f, file: gateway/src/management_switch/location_map.rs:367
Jul 24 04:49:31.212 DEBG received location determination response, refined_locations: {"switch0"}, interface: (direct socket handle), component: ManagementSwitch, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f
Jul 24 04:49:31.212 DEBG registered endpoint, path: /ignition, method: GET, local_addr: [::1]:12225, component: dropshot, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f
Jul 24 04:49:31.212 DEBG registered endpoint, path: /ignition/{type}/{slot}, method: GET, local_addr: [::1]:12225, component: dropshot, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f
Jul 24 04:49:31.212 DEBG mgs: initializing http server listening at [fd00:1122:3344:101::2]:12225: error creating server listener: Cannot assign requested address (os error 126)
registered endpoint, path: /ignition/{type}/{slot}/{command}, method: POST, local_addr: [::1]:12225, component[ Jul 24 04:49:31 Stopping because all processes in service exited. ]
[ Jul 24 04:49:31 Executing stop method (:kill). ]
[ Jul 24 04:49:31 Restarting too quickly, changing state to maintenance. ]
```

It's a bit hard to read, but the last message with `DEBG` says that MGS could not bind to the requested address. That's the switch-zone's address on the underlay. In the past, that was created by the sled-agent using `zone_enter()` to run `ipadm` in the zone. With the changes to make the zone self-assembling, I'm not sure who is responsible for that yet.

Does that address exist?

```
bnaecker@shale : ~/omicron $ pfexec zlogin oxz_switch ipadm
ADDROBJ           TYPE     STATE        ADDR
lo0/v4            static   ok           127.0.0.1/8
lo0/v6            static   ok           ::1/128
tfportrear0_0/ll  addrconf ok           fe80::8846:60ff:fefc:dfc9%tfportrear0_0/10
oxBootstrap0/ll   addrconf ok           fe80::8:20ff:fe63:7251%oxBootstrap0/10
oxBootstrap0/bootstrap6 static ok       fdb0:18c0:4d87:4d6a::2/64
bnaecker@shale : ~/omicron $ pfexec zlogin oxz_switch dladm
LINK        CLASS     MTU    STATE    BRIDGE     OVER
tfportrear0_0 simnet  9000   up       --         ?
tfportqsfp0_0 simnet  9000   up       --         ?
oxBootstrap0 vnic     1500   up       --         ?
oxControlService0 vnic 9000  up       --         ?
```

No, neither the link-local nor the static underlay address exist in the zone, though the VNIC `oxControlService0` that is supposed to underly those does exist. That's good.

Does anyone ever create or operate on that address? Is it just never created, or somehow not plumbed correctly into or inside of the zone? Tracing this through `ipmgmtd` is a bit hard, but luckily we still shell out to `ipadm` for all or almost all of these operations. Let's see what's going on there, while I start the control plane:

```
bnaecker@shale : ~/helios $ pfexec dtrace -n 'proc:::exec-success /execname == "ipadm" && strstr(curpsinfo->pr_psargs, "oxControlService0") != NULL || strstr(curpsinfo->pr_psargs, "fd00:1122:3344:101::2") != NULL/ { printf("zone %d: '%s'\n", curpsinfo->pr_zoneid, curpsinfo->pr_psargs); }'
dtrace: description 'proc:::exec-success ' matched 1 probe
CPU     ID                    FUNCTION:NAME
 14  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6

  3  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm show-addr -p -o TYPE oxControlService0/ll

  8  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm create-addr -t -T addrconf oxControlService0/ll

  9  15105         exec_common:exec-success zone 138: bash -c /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 ox

  9  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlS

 22  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6

  1  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm delete-if oxControlService0

 17  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm create-if -t oxControlService0

  1  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv4 oxControlService0

 12  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv6 oxControlService0

```

It looks like the link-local and static underlay addresses are created, and then the underlying IP interface is deleted with `delete-if`! Just to confirm, that's coming from zone 138 which is indeed the switch zone:

```
bnaecker@shale : ~/omicron $ zoneadm list -p oxz_switch | grep oxz_switch
138:oxz_switch:running:/zone/oxz_switch:a3ddcd13-5f85-4e9d-bc72-658f2db7c3f5:omicron1:excl
```

So who's doing that? It's a bit hacky and ugly, but we can print the process tree when we intercept the `ipadm` commands we're interested in. I'm sure there's a better way to do this, but the following seems to show what's going on:

```
bnaecker@shale : ~/helios $ pfexec dtrace -x strsize=16k -wn 'proc:::exec-success /execname == "ipadm" && strstr(curpsinfo->pr_psargs, "oxControlService0") != NULL || strstr(curpsinfo->pr_psargs, "fd00:1122:3344:101::2") != NULL/ { stop(); printf("zone %d: \"%s\"\n", curpsinfo->pr_zoneid, curpsinfo->pr_psargs); system("ptree $(pgrep sled-agent)"); system("ptree -z %d %d", curpsinfo->pr_zoneid, curpsinfo->pr_pid); system("prun %d", pid); }'
dtrace: description 'proc:::exec-success ' matched 1 probe
dtrace: allowing destructive actions
CPU     ID                    FUNCTION:NAME
  2  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    2782   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm show-addr -p -o ADDR oxControlServi
      2789   /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6
2789   /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6

 12  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm show-addr -p -o TYPE oxControlService0/ll"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    2886   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm show-addr -p -o TYPE oxControlServi
      2893   /usr/sbin/ipadm show-addr -p -o TYPE oxControlService0/ll
    2974   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
2893   /usr/sbin/ipadm show-addr -p -o TYPE oxControlService0/ll

 20  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm create-addr -t -T addrconf oxControlService0/ll"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    2980   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T addrconf oxContro
      2981   /usr/sbin/ipadm create-addr -t -T addrconf oxControlService0/ll
2981   /usr/sbin/ipadm create-addr -t -T addrconf oxControlService0/ll

  7  15105         exec_common:exec-success zone 229: "bash -c /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 ox"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    3004   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:11
      3008   bash -c /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 ox
3008   bash -c /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 ox

  7  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlS"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    3004   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:11
      3008   /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlS
3008   /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlS

 12  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    3091   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm show-addr -p -o ADDR oxControlServi
      3092   /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6
3092   /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6

  5  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm delete-if oxControlService0"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    3156   /usr/bin/pfexec /usr/sbin/route add -inet6 default -inet6 fd00:1122:3344:101::1
1732   /lib/svc/bin/svc.startd
  3100   /opt/oxide/zone-setup-cli/bin/zone-setup common-networking -d oxControlService0
    3115   /usr/sbin/ipadm delete-if oxControlService0

  9  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm create-if -t oxControlService0"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    4152   /usr/sbin/svccfg -s svc:/oxide/mgd:default addpropvalue config/dns_servers astr
1732   /lib/svc/bin/svc.startd
  3100   /opt/oxide/zone-setup-cli/bin/zone-setup common-networking -d oxControlService0
    3168   /usr/sbin/ipadm create-if -t oxControlService0

  5  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv4 oxControlService0"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
1732   /lib/svc/bin/svc.startd
  3100   /opt/oxide/zone-setup-cli/bin/zone-setup common-networking -d oxControlService0
    4198   /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv4 oxControlService0

  2  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv6 oxControlService0"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
1732   /lib/svc/bin/svc.startd
  3100   /opt/oxide/zone-setup-cli/bin/zone-setup common-networking -d oxControlService0
    4740   /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv6 oxControlService0
```

Here's what I see:

1. The sled-agent appears to be using `zlogin` to create the link-local and underlay addresses.
2. The `zone-setup common-networking` command appears to be calling `delete-if` after this
3. The `zone-setup common-networking` command appears to be calling `create-if` again, and then setting the MTU on that interface.

Those latter two steps look like they're from here:

https://github.com/oxidecomputer/omicron/blob/38575abf11e463993bdb953fc3ad3653cbf8a3b6/zone-setup/src/bin/zone-setup.rs#L669

which calls into this:

https://github.com/oxidecomputer/omicron/blob/38575abf11e463993bdb953fc3ad3653cbf8a3b6/illumos-utils/src/ipadm.rs#L17-L31

So this sure looks like the zone-setup service and the sled-agent are racing. I do see this succeed about 1/3rd the time, and in that case, the zone-setup service `delete-if` call does in fact appear before the `sled-agent`'s call to `create-addr`. It looks like the sled-agent does still create the underlay address in the zone, here:

https://github.com/oxidecomputer/omicron/blob/38575abf11e463993bdb953fc3ad3653cbf8a3b6/sled-agent/src/services.rs#L3916-L3952

This needs to be coordinated with the zone-setup service, to prevent it deleting the interface under these addresses; or the zone-setup service needs to not delete those interfaces, and instead only _ensure_ they exist.

### PR DESCRIPTION
**Pull request by bnaecker**
- Fixes #6149
- Most zones run the `zone-network-setup` once, at startup, with their underlay addresses already provided by the sled-agent. That's not true for the switch zone, which starts with only a localhost address, and then is provided an underlay address by the sled-agent only after the bootstrapping process has proceededed further. However, the zone-setup-service previously deleted its IP interfaces prior to setting the underlay address on it, apparently as a workaround for https://github.com/oxidecomputer/stlouis/issues/435. That's fine for other zones, but that races with the sled-agent setting that underlay address later in the switch zone. It's possible for the zone-setup-service to delete the interface _after_ those addresses are set, which obviously prevents the rest of the control plane from deploying correctly. This fixes the issue by simply removing that call to `ipadm delete-if` in the zone-setup-service. The mentioned issue has been resolved, and the workaround is no longer needed.
- Move the `zone-network-setup` service depend on the network milestone, instead of multi-user. This just moves it earlier a bit in the dependency graph, though should not be strictly necessary. We might want to move the sled-agent's notion of "zone readiness" to depend on `multi-user` instead of `single-user` in the future, so this could help with that.
- Extract out a few constants, some whitespace cleanup

### CODE REVIEW

**Comment by bnaecker** [comment]
I've now run this a few dozen times on my machine, and not seen any of the races mentioned in the issue. Instead, tracing the `ipadm` calls always shows this:

```
bnaecker@shale : ~/omicron $ pfexec dtrace -n 'proc:::exec-success /execname == "ipadm" && strstr(curpsinfo->pr_psargs, "oxControlService0") != NULL || strstr(curpsinfo->pr_psargs, "fd00:1122:3344:101::2") != NULL/ { printf("zone %d: '%s'\n", curpsinfo->pr_zoneid, curpsinfo->pr_psargs); }'
dtrace: description 'proc:::exec-success ' matched 1 probe
CPU     ID                    FUNCTION:NAME
  3   2857         exec_common:exec-success zone 11: /usr/sbin/ipadm create-if -t oxControlService0

  2   2857         exec_common:exec-success zone 11: /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv4 oxControlService0

 15   2857         exec_common:exec-success zone 11: /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv6 oxControlService0

  4   2857         exec_common:exec-success zone 11: /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6

  0   2857         exec_common:exec-success zone 11: /usr/sbin/ipadm show-addr -p -o TYPE oxControlService0/ll

 15   2857         exec_common:exec-success zone 11: /usr/sbin/ipadm create-addr -t -T addrconf oxControlService0/ll

  2   2857         exec_common:exec-success zone 11: bash -c /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 ox

  2   2857         exec_common:exec-success zone 11: /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlS

  4   2857         exec_common:exec-success zone 11: /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6
```

That order is not strictly guaranteed, since there is still a window of concurrency between the sled-agent and the zone-setup tool. Note that this is _necessary_: the zone-setup tool attempts to create a default route, which will fail until the zone has an _underlay_ IPv6 address. That's created by the sled-agent. As `dpd` and `tfportd` are both dependent on the zone-setup service running to completion, we can't really avoid that AFAIK.

File: illumos-utils/src/addrobj.rs [hunk 1]
```diff
@@ -5,7 +5,17 @@
...
 /// The name provided to all link-local IPv6 addresses.
-pub const IPV6_LINK_LOCAL_NAME: &str = "ll";
+pub const IPV6_LINK_LOCAL_ADDROBJ_NAME: &str = "ll";
+
+/// The name provided to all static IPv6 underlay addresses.
+pub const IPV6_STATIC_ADDROBJ_NAME: &str = "omicron6";
+
+/// The name provided to all static IPv4 addresses, usually for public OPTE
+/// interfaces.
+pub const IPV4_STATIC_ADDROBJ_NAME: &str = "omicron6";
```
Comment (karencfv) [inline illumos-utils/src/addrobj.rs:15]: I believe this should be `omicron4` instead

```suggestion
pub const IPV4_STATIC_ADDROBJ_NAME: &str = "omicron4";
```

File: illumos-utils/src/addrobj.rs [hunk 2]
```diff
@@ -5,7 +5,17 @@
...
+
+/// The name provided to DHCP-configured addresses, of either family.
+pub const DHCP_ADDROBJ_NAME: &str = "omicron";
```
Comment (karencfv) [inline illumos-utils/src/addrobj.rs:18]: Nit: These constants are only used in `running_zone.rs`, perhaps they should be moved there for readability? Either way, I'm not too fussed about this, if you disagree feel free to ignore this comment :)

File: zone-setup/src/bin/zone-setup.rs [hunk 3]
```diff
@@ -232,7 +232,7 @@ async fn do_run() -> Result<(), CmdError> {
         )
         .subcommand(
             Command::new(CHRONY_SETUP_CMD)
-                .about("Sets up Chrony configuration for NTP zone") 
+                .about("Sets up Chrony configuration for NTP zone")
```
Comment (karencfv) [inline zone-setup/src/bin/zone-setup.rs:235]: Thanks for cleaning up all these small bits!

**Review by karencfv — COMMENTED** [review]
Thanks for finding the bug and providing a quick fix! Left a couple of comments, but otherwise looks good to me.

I'll leave the review of the manifest dependencies to @citrus-it though. He'll have a better grasp on that than me.

File: smf/zone-network-setup/manifest.xml [hunk 4]
```diff
@@ -6,21 +6,26 @@
...
   </dependency>
 
-  <dependency name='multi_user' grouping='require_all' restart_on='none'
-    type='service'>
-  <service_fmri value='svc:/milestone/multi-user:default' />
+  <!-- The zone-setup binary is not ready to run until its initial properties
+          have been set by the sled-agent, which happens after the
+          `manifest-import` service is running.
+  -->
+  <dependency name='zone-network-setup-manifest-import' type='service' grouping='require_all' restart_on='none'>
```
Comment (citrus-it) [inline smf/zone-network-setup/manifest.xml:19]:
```suggestion
  <dependency name='manifest-import' type='service' grouping='require_all' restart_on='none'>
```
nit, the name can just be `manifest-import` if you like, and that's the usual convention.
`<dependency/>` clauses are local to this service so the name only needs to be unique within it.
`<dependent/>` clauses, in contrast, are injected into the other (referenced) service as a dependency, and so need a more unique name.

File: smf/zone-network-setup/manifest.xml [hunk 5]
```diff
@@ -6,21 +6,26 @@
 <service name='oxide/zone-network-setup' type='service' version='1'>
   <create_default_instance enabled='true' />
 
-  <!-- Run after the operating system's svc:/network/physical service is done. -->
+  <!-- Run after the zone's networking stack is up. -->
   <dependency name='physical' grouping='require_all' restart_on='none'
```
Comment (citrus-it) [inline smf/zone-network-setup/manifest.xml:10]:
```suggestion
  <dependency name='network' grouping='require_all' restart_on='none'
```

**Review by citrus-it — COMMENTED** [review]
A couple of nits on the manifest, and I concur with @karencfv's comment on `IPV4_STATIC_ADDROBJ_NAME`.

File: illumos-utils/src/addrobj.rs (hunk 1 above)
Comment (bnaecker) [reply illumos-utils/src/addrobj.rs:15]: Yeah, good catch, thanks!

File: illumos-utils/src/addrobj.rs (hunk 2 above)
Comment (bnaecker) [reply illumos-utils/src/addrobj.rs:18]: We have the link-local addrobj suffix `ll` here already. Since these are also address-object naming conventions, I think it makes more sense to keep them here.

File: illumos-utils/src/addrobj.rs (hunk 1 above)
Comment (bnaecker) [reply illumos-utils/src/addrobj.rs]: Done in 6c93f59a4

File: smf/zone-network-setup/manifest.xml (hunk 4 above)
Comment (bnaecker) [reply smf/zone-network-setup/manifest.xml]: Done in 6c93f59a4

File: smf/zone-network-setup/manifest.xml (hunk 5 above)
Comment (bnaecker) [reply smf/zone-network-setup/manifest.xml]: Done in 6c93f59a4

**Review by citrus-it — APPROVED** [review]
