### PR TITLE
Send blueprint disks & datasets to simulated sled agent

### LINKED ISSUE #7081: nexus-test-utils: Populate disks and datasets in initial blueprint correctly
`nexus-test-utils` populates its initial blueprint's sleds' datasets and disks [based on the zones for that sled](https://github.com/oxidecomputer/omicron/blob/main/nexus/test-utils/src/lib.rs#L873-L904). However, these datasets and disks are just made up entirely on the spot, and have no correlation with the disks and datasets each simulated sled-agent will claim to have. This puts clients of this test setup code in an awkward position: they can't assume the blueprint they've been given is valid in the same way that a blueprint produced by the planner or real RSS is (i.e., that datasets/disks are populated in a valid way).

This may be somewhat tricky to untangle, depending on how much fidelity we care about. In real rack setup, RSS asks each sled-agent for its disks, then generates a plan and blueprint assigning zpools to each of those disks and zones/datasets to each of those zpools. In this test-utils path, though, we create a plan and blueprint before starting simulated sled-agents, which themselves then fabricate some number of disks. Ideally the simulated sled-agents would report disks that match the disks and datasets we populate in the test-utils blueprint.

Ideally we could use `BlueprintBuilder` here instead of creating a blueprint by hand; that may be hard or impossible given its current API, though.

### LINKED ISSUE #8222: cannot execute initial blueprint in simulated environment
Under `cargo xtask omicron-dev run-all`, I tried to execute the sole built-in blueprint, but it failed to execute:

```
$ omdb -w nexus blueprints target enable 184d8b69-bfdf-4b68-b8a7-f79412b40003
note: Nexus URL not specified.  Will pick one from DNS.
note: using Nexus URL http://[::1]:12221
set target blueprint 184d8b69-bfdf-4b68-b8a7-f79412b40003 to enabled

$ omdb nexus background-tasks show blueprint_executor
note: Nexus URL not specified.  Will pick one from DNS.
note: using Nexus URL http://[::1]:12221
task: "blueprint_executor"
  configured period: every 1m
  currently executing: no
  last completed activation: iter 24, triggered by a dependent task completing
    started at 2025-05-27T17:54:53.806Z (3s ago) and ran for 1603ms
    target blueprint: 184d8b69-bfdf-4b68-b8a7-f79412b40003                                                                                                                                                                                                                                                                                                                                                                                  
    execution:        enabled                                                                                                                                                                                                                                                                                                                                                                                                               
    status:           completed (14 steps)                                                                                                                                                                                                                                                                                                                                                                                                  
    warning:          at: Deploy single-node clickhouse cluster: failed to initialize single-node clickhouse database: Communication Error: error sending request for url (http://[::1]:8888/init)                                                                                                                                                                                                                                          
    warning:          at: Deploy sled configs: Failed to put OmicronSledConfig {                                                                                                                                                                                                                                                                                                                                                            
...                                                                                                                                                                                                                                                                                                                                                                  
                      } to sled b6d65341-167c-41df-9b5c-41cded99c229: Error Response: status: 400 Bad Request; headers: {"content-type": "application/json", "x-request-id": "d57fb89a-2c91-4cee-a7bd-c62511d50a0e", "content-length": "124", "date": "Tue, 27 May 2025 17:54:53 GMT"}; value: Error { error_code: None, message: "Generation number unchanged but data is different", request_id: "d57fb89a-2c91-4cee-a7bd-c62511d50a0e" } 
    error:            (none)                                                                                                                                                                                                                                                                                                                                                                                                                
```

I'll put the full error in a comment because it's too big for a GitHub issue description.

### PR DESCRIPTION
**Pull request by plotnick**
Fixes #7081, fixes #8222. Tracks disks and datasets added to the blueprint in `nexus-test-utils`, and sends them to the appropriate simulated sled-agents.

Also adds trivial but successful execution to the `test_blueprint_planner` introduced in #8287.

### CODE REVIEW

File: nexus/test-utils/src/lib.rs [hunk 1]
```diff
@@ -947,11 +952,13 @@ impl<'a, N: NexusServer> ControlPlaneTestContextBuilder<'a, N> {
...
                 }
 
+                self.blueprint_disks.insert(sled_id, disks.clone());
+                self.blueprint_datasets.insert(sled_id, datasets.clone());
                 blueprint_sleds.insert(
                     sled_id,
                     BlueprintSledConfig {
                         state: SledState::Active,
-                        sled_agent_generation: Generation::new().next(),
+                        sled_agent_generation: 4.into(),
```
Comment (davepacheco) [inline nexus/test-utils/src/lib.rs]: What's up with this number?  I feel like it could use a constant and comment.

File: nexus/test-utils/src/lib.rs [hunk 2]
```diff
@@ -1775,6 +1758,10 @@ async fn setup_with_config_impl<N: NexusServer>(
                             .boxed()
                     }),
                 ),
+                (
```
Comment (davepacheco) [inline nexus/test-utils/src/lib.rs]: I'm curious why this had to move to after starting Nexus.  This configuration mimics what RSS would normally do, right?  And that happens before Nexus starts.

File: nexus/test-utils/src/lib.rs [hunk 3]
```diff
@@ -1142,33 +1122,40 @@ impl<'a, N: NexusServer> ControlPlaneTestContextBuilder<'a, N> {
...
-            .await
-            .expect("Failed to write early networking config to bootstore");
+        macro_rules! from_clone {
+            ($source: expr) => {
+                $source.clone().into_iter().map(From::from).collect()
+            };
+        }
 
-        for sled_agent in self.sled_agents.iter().skip(1) {
+        let generation = Generation::from_u32(2);
```
Comment (davepacheco) [inline nexus/test-utils/src/lib.rs:1091]: Same -- where's this come from?

File: nexus/test-utils/src/lib.rs [hunk 4]
```diff
@@ -1142,33 +1122,40 @@ impl<'a, N: NexusServer> ControlPlaneTestContextBuilder<'a, N> {
...
+        let zones =
+            once(from_clone!(self.blueprint_zones)).chain(repeat(vec![]));
```
Comment (davepacheco) [inline nexus/test-utils/src/lib.rs]: Is this constructing a structure with non-empty zones for the first sled agent and no zones for the others?

**Review by davepacheco — COMMENTED** [review]
Cool!

File: nexus/test-utils/src/lib.rs (hunk 2 above)
Comment (plotnick) [reply nexus/test-utils/src/lib.rs]: I had the blueprint-builder recording the disks & datasets it creates, with the sled-agent picking them up later. But since you asked (thanks for asking!), I hacked on it some more and got it working the other way: in 4c1f2ab01, `sled_agent_config` now calls a new `make_sled_configs` method that computes what will be the blueprint's sled configs, and uses the disks & datasets from that. This lets sled-agent start before Nexus again, and the configs to still agree.

File: nexus/test-utils/src/lib.rs (hunk 4 above)
Comment (plotnick) [reply nexus/test-utils/src/lib.rs]: Yes, it's the same pattern used in the blueprint builder's `maybe_zones`. Commented in 4c1f2ab01.

File: nexus/test-utils/src/lib.rs (hunk 3 above)
Comment (plotnick) [reply nexus/test-utils/src/lib.rs:1091]: Thank you, updated and commented in 4c1f2ab01.

File: nexus/test-utils/src/lib.rs (hunk 1 above)
Comment (plotnick) [reply nexus/test-utils/src/lib.rs]: Thank you, there was a lot of experimentation with this, and it was not left at its minimum value for these configs. Lowered and commented in 4c1f2ab01.

File: nexus/test-utils/src/lib.rs [hunk 5]
```diff
@@ -904,114 +905,31 @@ impl<'a, N: NexusServer> ControlPlaneTestContextBuilder<'a, N> {
...
-                // Clickhouse clusters are not generated by RSS. One must run
-                // reconfigurator for that.
-                clickhouse_cluster_config: None,
-                oximeter_read_version: Generation::new(),
-                oximeter_read_mode: OximeterReadMode::SingleNode,
-                time_created: Utc::now(),
-                creator: "nexus-test-utils".to_string(),
-                comment: "initial test blueprint".to_string(),
-            }
+        // Construct an initial blueuprint that agrees with the sled-agents'
```
Comment (davepacheco) [inline nexus/test-utils/src/lib.rs]:
```suggestion
        // Construct an initial blueprint that agrees with the sled-agents'
```

File: nexus/test-utils/src/lib.rs [hunk 6]
```diff
@@ -1471,6 +1404,102 @@ impl<'a, N: NexusServer> ControlPlaneTestContextBuilder<'a, N> {
...
+
+        // The first sled agent is the only one that'll have configured
+        // blueprint zones, but the others all need to have disks.
+        let maybe_zones = once(Some(&self.blueprint_zones)).chain(repeat(None));
+
+        // The generation number that the sled-agents' configuration
+        // will have when this blueprint is executed:
+        //   1 = initial config
+        //   2 = config we deploy in `configure_sled_agents`
+        let sled_agent_generation = Generation::from_u32(3);
```
Comment (davepacheco) [inline nexus/test-utils/src/lib.rs]: Either I'm confused (definitely possible!) or there's a disconnect in the generation numbers here.

Here, `make_sled_configs()` produces `BlueprintSledConfig` objects for each sled with generation 3.
`configure_sled_agents()` sends requests to the sled agents with `OmicronSledConfig` objects derived from the `BlueprintSledConfig` object, but with generation 1 (L1088).
`start_nexus_internal()` uses the `BlueprintSledConfig` that was created by `make_sled_configs()` to construct an initial blueprint, so that winds up having generation *3*.

Since I think these all represent the same point in time (similar to the initial RSS blueprint), can we use the same generation number for both?  I think it should be generation 2 because I think we often (sometimes?) say that generation 1 is empty.  (I don't think this point actually affects anything though.)

File: nexus/test-utils/src/lib.rs (hunk 5 above)
Comment (plotnick) [reply nexus/test-utils/src/lib.rs]: Thanks, fixed in 13304d0ba.

File: nexus/test-utils/src/lib.rs (hunk 6 above)
Comment (plotnick) [reply nexus/test-utils/src/lib.rs]: Thank you, changed numbers and comments in 13304d0ba to agree that generation 2 is the sole post-initialization configuration.

**Review by davepacheco — APPROVED** [review]
