### PR TITLE
[crdb] set index backfill batch size to 5000, max-sql-memory to 256MiB

### LINKED ISSUE #9874: creating crdb indexes can fail on sufficiently large tables
Followup from https://github.com/oxidecomputer/omicron/issues/9866 -- see that issue for context.

With CockroachDB, if we take a table with a sufficiently large amount of data in it, and then create an index (in, e.g., a migration), it will fail with an out of memory error.

## Steps to reproduce

Run this reproduction script in Omicron (so that Omicron's copy of `cockroach` is in the PATH): https://gist.github.com/sunshowers/a5e690e8aa40df4ef00882b1e71e1f2e

This fails with:

```
[nexus1] ERROR: transaction committed but schema change aborted with error: (53200): failed to construct index entries during backfill: root: memory budget exceeded: 2437120 bytes requested, 132620137 currently allocated, 134217728 bytes in budget
[nexus1] SQLSTATE: XXA00
[nexus1] HINT: Consider increasing --max-sql-memory startup parameter.
[nexus1] --
[nexus1] Some of the non-DDL statements may have committed successfully, but some of the DDL statement(s) failed.
[nexus1] Manual inspection may be required to determine the actual state of the database.
[nexus1] --
[nexus1] See: https://github.com/cockroachdb/cockroach/issues/42061
[nexus1] Failed running "sql"
```

## What does "sufficiently large amount of data" mean?

TODO, still analyzing this. A quick summary is that for the example in the repro script above, 1.7M rows doesn't fail but 1.8M rows does.

### Reducing the batch size

For index backfills, [`bulkio.index_backfill.batch_size`](https://github.com/oxidecomputer/cockroach/blob/367bca413bc24e6213a45663fccd583cc726ba08/pkg/sql/backfill.go#L75-L84) controls how many rows are loaded in at once. The default value of this tunable is 50,000, and we don't alter it. Reducing the batch size sufficiently appears to get past this issue (TODO still need to verify this claim for real.)

https://github.com/cockroachdb/cockroach/pull/135563 uses a halving/backoff strategy for the batch size. But due to licensing issues we can't use it directly. If we decide to fix this in our fork of CockroachDB we'll need to reimplement this idea ourselves.

But we can also do this at the migration driver layer. For example, we can either conditionally (if the migration is a `CREATE INDEX` DDL) or unconditionally reduce the batch size to a smaller value of, say, 5000. That should get us past this issue.

### `--max-sql-memory`

The `--max-sql-memory` parameter is set on each node at startup time. By default it is 128 MiB, and we do not alter the default:

https://github.com/oxidecomputer/omicron/blob/79fac7deb9acd9272b867904da03f20076d09265/smf/cockroachdb/method_script.sh#L25-L33

Bumping this up to a larger value can help.

### PR DESCRIPTION
**Pull request by sunshowers**
Per the analysis in https://github.com/oxidecomputer/omicron-9874-findings.

An interesting note is that we didn't used to set max-sql-memory at all, which meant we were relying on the CockroachDB default. On Linux that was 25% of system memory, but on illumos the detection fell back to a default of 128 MiB. So developers on Linux would effectively have very different SQL memory limits from those on illumos. With this change, the two OSes now have similar behavior.

Fixes #9874.

### CODE REVIEW

File: cockroach-admin/src/cockroach_cli.rs [hunk 1]
```diff
@@ -586,6 +586,9 @@ mod tests {
                 .arg("[::1]:0")
                 .arg("--http-addr")
                 .arg("[::1]:0")
+                // See https://github.com/oxidecomputer/omicron-9874-findings for
+                // why we set the max SQL memory to be 256MiB.
+                .arg("--max-sql-memory=256MiB")
```
Comment (smklein) [inline cockroach-admin/src/cockroach_cli.rs:591]: This is more a note-to-self: I tweak this value in https://github.com/oxidecomputer/omicron/pull/9878 too, but only for testing to make reproductions more consistent. We should merge this carefully.

(I'm sure we can figure something out, just calling it out early)

File: nexus/tests/integration_tests/schema.rs [hunk 2]
```diff
@@ -822,11 +881,23 @@ async fn dbinit_equals_sum_of_all_up() {
...
     assert_eq!(observed_data, expected_data);
+
+    // Validate that cluster settings match.  This catches cases where
+    // dbinit.sql sets a cluster setting but migrations don't (or vice versa).
+    similar_asserts::assert_eq!(
+        observed_cluster_settings,
+        expected_cluster_settings,
+        "Cluster settings do not match between migrations and dbinit.sql. \
+         If dbinit.sql contains a SET CLUSTER SETTING statement, there must \
+         be a corresponding migration (and vice versa)."
```
Comment (smklein) [inline nexus/tests/integration_tests/schema.rs:898]: Real smart to include this as a check, good call!

File: nexus/db-model/src/schema_versions.rs [hunk 3]
```diff
@@ -566,11 +572,15 @@ impl std::fmt::Display for SchemaVersion {
     }
 }
 
+/// Pragma comment that marks a migration step as non-transactional.
+const NON_TRANSACTIONAL_PRAGMA: &str = "-- NON-TRANSACTIONAL";
```
Comment (smklein) [inline nexus/db-model/src/schema_versions.rs]: I hope no one complains that the `--NON-TRANSACTIONAL` flag isn't working, if they don't realize the `--` is syntax for SQL comments and we're checking the space here 😅 

(This is probably fine... but I am a little nervous that "almost correct" pragmas will silently do nothing)

**Review by smklein — APPROVED** [review]

File: cockroach-admin/src/cockroach_cli.rs (hunk 1 above)
Comment (sunshowers) [reply cockroach-admin/src/cockroach_cli.rs:591]: Oh good catch, I guess we should make the max sql memory an option on the cockroach command builder.

File: nexus/db-model/src/schema_versions.rs (hunk 3 above)
Comment (jgallagher) [reply nexus/db-model/src/schema_versions.rs]: It sure _looks_ like a comment in `up.sql` 😬 

I assume this is not something we expect to come up often, given it's the first time we've needed it. Would it be unreasonable to build a static list of migration files that are nontransactional instead of embedding a special marker in the file itself? Maybe kinda janky, but I'm imagining something like

```rust
static NON_TRANSACTIONAL_UPGRADE_STEPS: &[&str] = &[
    "index-backfill-batch-size/up.sql",
];
```

Comment (sunshowers) [reply nexus/db-model/src/schema_versions.rs]: > (This is probably fine... but I am a little nervous that "almost correct" pragmas will silently do nothing)

FWIW `SET CLUSTER SETTING` blows up quite loudly if in a (multi-statement) transaction.

> I assume this is not something we expect to come up often, given it's the first time we've needed it. Would it be unreasonable to build a static list of migration files that are nontransactional instead of embedding a special marker in the file itself? Maybe kinda janky, but I'm imagining something like

I considered that but felt that was slightly worse than embedding this knowledge locally in the file. I don't have a very strong preference here though.

File: cockroach-admin/src/cockroach_cli.rs (hunk 1 above)
Comment (sunshowers) [reply cockroach-admin/src/cockroach_cli.rs:591]: Done -- also added this to `cargo xtask db-dev run`

File: nexus/db-model/src/schema_versions.rs (hunk 3 above)
Comment (jgallagher) [reply nexus/db-model/src/schema_versions.rs]: > I considered that but felt that was slightly worse than embedding this knowledge locally in the file. I don't have a very strong preference here though.

I don't love the "static list" suggestion I made, but I more strongly dislike these two bits about embedding the knowledge locally in the file:

* We now have to check every schema migration step for a special magic comment (not worried about runtime overhead or anything; more the cognitive/complxity overhead - today we _just_ read the file, and that seems like a nice property to maintain as long as we can)
* It allows _any_ schema migration check to opt into non-transactional mode

The latter one bugs me more, I think? Maybe this is paranoia, but I'm worried about someone having some problem that they can address by opting out of transactions (but ought to address some other way), and code review missing it because the opt-out "flag" is a comment in a migration step, which I think is pretty easy to overlook.

Static list directly addresses the first of these, and maybe makes the second less likely? Hopefully a big scary comment on the static list plus a comment-per-entry works as a wakeup in PR review, and anyone stumbling across that list after changes are merged should be able to easily tell which migration steps have this opt-out and why.

Comment (smklein) [reply nexus/db-model/src/schema_versions.rs]: One downside of static lists, IMO:

- Someone writes a migration with steps "01.sql, 02.sql, 03.sql"
- They mark "02.sql" as "the one needing to be non-transactional"
- They realize they need another change before that, so they add it, and rename all the files
- Now the steps are "01.sql, 02.sql, 03.sql (this is the one which should be non-txn), 04.sql"
- The static list still points to 02.sql as the non-transactional one

I guess this is sorta my argument about the danger of non-locality of labelling

Comment (davepacheco) [reply nexus/db-model/src/schema_versions.rs]: Maybe bad idea: what about putting it in the filename somehow?  It's more local than a static list but doesn't involve sidebanding control information in a comment.  (The filename is still a sideband, but it feels less surprising that the filename could be semantically meaningful than a comment.)  On the flip side: it seems potentially less visible in code review.

Comment (smklein) [reply nexus/db-model/src/schema_versions.rs]: > Maybe bad idea: what about putting it in the filename somehow? It's more local than a static list but doesn't involve sidebanding control information in a comment. (The filename is still a sideband, but it feels less surprising that the filename could be semantically meaningful than a comment.) On the flip side: it seems potentially less visible in code review.

FWIW this is the approach I'm taking with https://github.com/oxidecomputer/omicron/pull/9878 - I'm auto-generating `NN.verify.sql` queries to live next to `NN.sql` files

Comment (sunshowers) [reply nexus/db-model/src/schema_versions.rs]: Hmm I would rather not encode this in the file name because this isn't an ancillary file the way `NN.verify.sql` is.

The solution @jgallagher and I came up with is on the update watercooler today is:

* rename `-- NON-TRANSACTIONAL` to `-- DANGER-NON-TRANSACTIONAL` -- make it semiotically [not a place of honor](https://en.wikipedia.org/wiki/Long-term_nuclear_waste_warning_messages)
* remove the documentation from the README, move it to a comment, with a clear warning sign

Thoughts?

Comment (smklein) [reply nexus/db-model/src/schema_versions.rs]: > Hmm I would rather not encode this in the file name because this isn't an ancillary file the way `NN.verify.sql` is.
> 
> The solution @jgallagher and I came up with is on the update watercooler today is:
> 
> * rename `-- NON-TRANSACTIONAL` to `-- DANGER-NON-TRANSACTIONAL` -- make it semiotically [not a place of honor](https://en.wikipedia.org/wiki/Long-term_nuclear_waste_warning_messages)
> * remove the documentation from the README, move it to a comment, with a clear warning sign
> 
> Thoughts?

I'd also be fine with this, especially given your note that you used this to update a cluster setting, and if we somehow beef this process and accidentally make the SQL statement happen in a txn, the migration would blow up in tests.

Comment (sunshowers) [reply nexus/db-model/src/schema_versions.rs]: Ok I just put up a change to encode this in the filename.

File: nexus/db-model/src/schema_versions.rs [hunk 4]
```diff
@@ -483,62 +496,60 @@ impl SchemaVersion {
...
+                     {}", single.path
                 );
             }
             _ => {
-                for (i, (up_number, path)) in up_sqls.iter().enumerate() {
+                for (i, parsed) in up_sqls.iter().enumerate() {
                     // We have 2 or more `up*.sql`; they should be numbered
                     // exactly 1..=up_sqls.len().
-                    if i as u64 + 1 != *up_number {
+                    if i as u64 + 1 != parsed.up_number {
```
Comment (smklein) [inline nexus/db-model/src/schema_versions.rs:525]: This is where we'd catch "a transactional + non-transactional SQL change both using the same number", right?

File: nexus/db-model/src/schema_versions.rs (hunk 3 above)
Comment (smklein) [reply nexus/db-model/src/schema_versions.rs]: https://github.com/oxidecomputer/omicron/pull/9889/commits/17d18fb1f7d2035b7df6f4e6a3257a920263c890 looks good to me; I also think it's reasonable to keep this out of the README given how sketchy non-transactional operations are.

File: nexus/db-model/src/schema_versions.rs (hunk 4 above)
Comment (sunshowers) [reply nexus/db-model/src/schema_versions.rs:525]: Yeah (and there's a test for this too)
