### PR TITLE
Properly check for expunged status during deletes

### LINKED ISSUE #10224: Unable to delete local disks on expunged sled
After hitting #10222, I tried out the sled expungement scenario on a racklet. The attempt to delete a local disk residing on the expunged sled hit a 500 error instead and transitioned to `faulted` state.
```
root@oxz_nexus_7797031c:~# grep InternalError /var/svc/log/oxide-nexus* | looker
05:17:39.130Z DEBG 7797031c-fa1b-45a8-a68d-a7f7a30eb4a2 (ServerContext): recording saga event
    event_type = Failed(ActionFailed { source_error: Object {"InternalError": Object {"internal_message": String("failed to delete local storage: failed at attempt 1: failed to determine whether remote server is gone: Internal Error: Sled 19d1543d-de66-44e4-b438-15aeef9978d4 is not in service")}} })
    node_id = 2
    saga_id = afd5e070-4187-4d55-ae55-0437eed60bc6
05:17:39.273Z WARN 7797031c-fa1b-45a8-a68d-a7f7a30eb4a2 (ServerContext): saga finished
    action_error_node_name = "delete_local_storage"
    action_error_source = ActionFailed { source_error: Object {"InternalError": Object {"internal_message": String("failed to delete local storage: failed at attempt 1: failed to determine whether remote server is gone: Internal Error: Sled 19d1543d-de66-44e4-b438-15aeef9978d4 is not in service")}} }
    file = /home/build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/steno-0.4.1/src/sec.rs:1044
    result = failure
    saga_id = afd5e070-4187-4d55-ae55-0437eed60bc6
    saga_name = disk-delete
    sec_id = 7797031c-fa1b-45a8-a68d-a7f7a30eb4a2
    undo_result = success
05:17:39.273Z INFO 7797031c-fa1b-45a8-a68d-a7f7a30eb4a2 (ServerContext): saga finished
    file = nexus/src/app/saga.rs:433
    saga_id = afd5e070-4187-4d55-ae55-0437eed60bc6
    saga_name = disk-delete
    saga_result = SagaResult { saga_id: afd5e070-4187-4d55-ae55-0437eed60bc6, saga_log: SagaLog { saga_id: afd5e070-4187-4d55-ae55-0437eed60bc6, unwinding: true, events: [N004 started, N004 succeeded, N000 started, N000 succeeded, N001 started, N001 succeeded, N002 started, N002 failed, N001 undo_started, N001 undo_finished, N000 undo_started, N000 undo_finished, N004 undo_started, N004 undo_finished], node_status: {0: UndoFinished, 1: UndoFinished, 2: Failed(ActionFailed { source_error: Object {"InternalError": Object {"internal_message": String("failed to delete local storage: failed at attempt 1: failed to determine whether remote server is gone: Internal Error: Sled 19d1543d-de66-44e4-b438-15aeef9978d4 is not in service")}} }), 4: UndoFinished} }, kind: Err(SagaResultErr { error_node_name: "delete_local_storage", error_source: ActionFailed { source_error: Object {"InternalError": Object {"internal_message": String("failed to delete local storage: failed at attempt 1: failed to determine whether remote server is gone: Internal Error: Sled 19d1543d-de66-44e4-b438-15aeef9978d4 is not in service")}} }, undo_failure: None }) }
```

The behavior has changed from r18 as the trust quorum expungement process involves taking the sled out of TQ first and regeneratinig the rack screts.

### PR DESCRIPTION
**Pull request by jmpesp**
When sending a delete request to a remote service during a saga, the usual pattern is to provide a "gone" check to bail out of the retry loop: if the remote service was impacted by an expunge then it's pointless to continue retrying a delete request, as something backing that service is gone.

There were TWO places not doing this correctly:

- when detaching a volume from a pantry
- when deleting local storage datasets

In these cases correct this by matching on the returned error of either `ProgenitorOperationRetry::run` or `retry_operation_while_indefinitely` (from progenitor-extras), and checking `e.is_gone`. If that matches then the saga can proceed.

Additionally, there are places where the gone check only checked if the sled was still in-service, but in reality needed to also check if the physical disk backing a zpool was expunged. Fix that too.

Also! The check functions bailed with an error if a sled or disk was not in-service, instead of returning a boolean. This meant that if a sled or disk was not in-service, the retry loop would exit with a `GoneCheckError` instead of a `Gone` value. This would not properly match for call sites that checked `is_gone` for a returned error, leading to saga unwinds that were ultimately not necessary. Change those functions to return a bool corresponding to whether or not the thing is in-service, and map that into a `GoneCheckResult` inside gone check functions.

Fixes #10224

### CODE REVIEW

File: nexus/db-queries/src/db/datastore/physical_disk.rs [hunk 1]
```diff
@@ -66,12 +66,22 @@ impl DataStore {
...
-                    )
-                    .await
-                    .map_err(|txn_error| txn_error.into_diesel(&err))?;
+                    let sled_in_service =
+                        Self::check_sled_in_service_on_connection(
+                            &conn,
+                            disk.sled_id(),
+                        )
+                        .await
+                        .map_err(|txn_error| txn_error.into_diesel(&err))?;
```
Comment (smklein) [inline nexus/db-queries/src/db/datastore/physical_disk.rs:75]: To confirm, this change is "functionally identical", right? just forced by the new signature of `check_sled_in_service_on_connection`?

(as in: old behavior if sled is not in service -> throw an error, and that's the new behavior too?)

File: nexus/src/app/sagas/common_storage.rs [hunk 2]
```diff
@@ -139,6 +139,10 @@ pub(crate) async fn call_pantry_attach_for_volume(
     let gone_check =
         || async { Ok(is_pantry_gone(nexus, pantry_address, log).await) };
 
+    // Do not match on `e.is_gone` here: if the Pantry is gone, then return an
+    // error. The attach may have succeeded for one of the previous calls but if
+    // the retry loop bails out after determining that the Pantry is gone, that
+    // attachment is now gone too.
```
Comment (smklein) [inline nexus/src/app/sagas/common_storage.rs:145]: I know you've scattered a bunch of these "Do not match on `is_gone`" comments through this PR, but I'm finding them a bit confusing.

It seems kinda like this is "obviously true" that:

- If you are trying to allocate a resource on top of some service X
- ... and "X" is removed from existence, which throws an error
- ... you should **not** match on that error and say "allocation succeeded" anyway

Similarly, the other commentary about unwinding seems true, but more a property of "how we're using sagas" than the specifics of this call site, if that makes sense?

I guess, put another way: the situation where we do:

1. Try to delete a resource
2. Special-case the error to say "if the resource is already gone", return success anyway

Seems like it's the special-case that deserves commentary - not the other way around.

File: nexus/src/app/sagas/snapshot_create.rs [hunk 3]
```diff
@@ -889,6 +885,8 @@ async fn ssc_send_snapshot_request_to_sled_agent(
     )
     .await
     .map_err(|e| {
+        // Do not match on `e.is_gone` here: if the ensure fails due to the sled
```
Comment (smklein) [inline nexus/src/app/sagas/snapshot_create.rs:888]: See my note above; I would omit this comment.

File: nexus/src/app/sagas/instance_start.rs [hunk 4]
```diff
@@ -719,6 +739,9 @@ async fn sis_ensure_local_storage(
     )
     .await
     .map_err(|e| {
+        // Do not match on `e.is_gone` here: If the ensure retry loop bailed out
```
Comment (smklein) [inline nexus/src/app/sagas/instance_start.rs:742]: See my note above; I would omit this comment.

File: nexus/src/app/sagas/snapshot_create.rs [hunk 5]
```diff
@@ -863,14 +862,11 @@ async fn ssc_send_snapshot_request_to_sled_agent(
...
     };
-    // `check_sled_in_service` returns an error if the sled is no longer in
-    // service; if it succeeds, the sled is not gone.
+
+    // Bail out of the retry loop if the sled is gone.
     let gone_check = || async {
-        osagactx
-            .datastore()
-            .check_sled_in_service(&opctx, sled_id)
+        sled_out_of_service_gone_check(osagactx.datastore(), &opctx, sled_id)
```
Comment (smklein) [inline nexus/src/app/sagas/snapshot_create.rs:868]: This is "functionally identical", just using a slightly different API to accomplish the same thing, right?

File: nexus/src/app/sagas/disk_delete.rs [hunk 6]
```diff
@@ -274,15 +290,21 @@ async fn sdd_delete_local_storage(
...
-        saga_action_failed(Error::internal_error(&format!(
+    .await;
+
+    match result {
+        Ok(_) => Ok(()),
+
+        // In this case, if the particular disk hosting this local storage was
+        // expunged, or if the sled was expunged, then proceed with the rest of
+        // the saga.
+        Err(e) if e.is_gone() => Ok(()),
```
Comment (smklein) [inline nexus/src/app/sagas/disk_delete.rs:301]: Should this be:

```suggestion
        Err(e) if e.is_gone() || e.is_not_found() => Ok(()),
```

Does `local_storage_dataset_delete` return a 404 if called twice in a row?

File: nexus/src/app/sagas/common_storage.rs [hunk 7]
```diff
@@ -169,10 +173,18 @@ pub(crate) async fn call_pantry_detach(
...
+    match ProgenitorOperationRetry::new(detach_operation, gone_check)
         .run(log)
         .await
-        .map(|_response| ())
+    {
+        Ok(_) => Ok(()),
+
+        // The pantry is stateless: if it is gone, then the Volume was
+        // destroyed, and we can proceed as if it was detached.
+        Err(e) if e.is_gone() => Ok(()),
```
Comment (smklein) [inline nexus/src/app/sagas/common_storage.rs:184]: Should this be:


```suggestion
        Err(e) if e.is_gone() || e.is_not_found() => Ok(()),
```

Does `detach` return a 404 if called multiple times in a row?

**Comment by smklein** [comment]
I'm trying to review this carefully, but it looks like it's mixing together a bunch of small changes that overlap. I'm trying to be diligent here and make sure I understand what is fixing what.

> When sending a delete request to a remote service during a saga, the usual pattern is to provide a "gone" check to bail out of the retry loop: if the remote service was impacted by an expunge then it's pointless to continue retrying a delete request, as something backing that service is gone.
> 
> There were TWO places not doing this correctly:
> 
> * when detaching a volume from a pantry
> * when deleting local storage datasets

This is in:

- `call_pantry_detach` and
- `sdd_delete_local_storage`, correct?

And it's referring to the "match-on-error, do an extra gone-check to allow deletion to succeed anyway, rather than stopping the saga", correct?

> In these cases correct this by matching on the returned error of either `ProgenitorOperationRetry::run` or `retry_operation_while_indefinitely` (from progenitor-extras), and checking `e.is_gone`. If that matches then the saga can proceed.
> 
> Additionally, there are places where the gone check only checked if the sled was still in-service, but in reality needed to also check if the physical disk backing a zpool was expunged. Fix that too.

These are places in:

- `sdd_delete_local_storage` and
- `sis_ensure_local_storage`

**Comment by smklein** [comment]
One more thing:

As described in my comment above, we have the four big behavior changes in this PR:

2x "let the gone check return Ok()"
2x "check the zpool status in addition to the sled for the gone check"

It would be great to get test coverage for these! They're all behavior changes that should be controllable if we can set up the DB correctly, right?

File: nexus/db-queries/src/db/datastore/physical_disk.rs (hunk 1 above)
Comment (jmpesp) [reply nexus/db-queries/src/db/datastore/physical_disk.rs:75]: Correct - the `TransactionError::CustomError` returned right after this highlighted line is what happened previously, and is in fact checked by the `physical_disk_cannot_insert_to_expunged_sled` test

File: nexus/src/app/sagas/disk_delete.rs (hunk 6 above)
Comment (jmpesp) [reply nexus/src/app/sagas/disk_delete.rs:301]: It should be idempotent for DELETEs.

File: nexus/src/app/sagas/common_storage.rs (hunk 7 above)
Comment (jmpesp) [reply nexus/src/app/sagas/common_storage.rs:184]: Same, it should be idempotent for detach.

File: nexus/src/app/sagas/snapshot_create.rs (hunk 5 above)
Comment (jmpesp) [reply nexus/src/app/sagas/snapshot_create.rs:868]: It is accomplishing the same thing, _and_ also this is one of the bug fixes: previously, `check_sled_in_service` would return Ok(()) if a sled is in service, and an error if it isn't. This would bubble up as a GoneCheckError instead of a Gone, and code matching on `e.is_gone` wouldn't execute. Now it returns a Ok(true) if the sled is in service, an Ok(false) if it isn't, and an Err when there's a legit query error.

**Comment by jmpesp** [comment]
> I'm trying to review this carefully, but it looks like it's mixing together a bunch of small changes that overlap. I'm trying to be diligent here and make sure I understand what is fixing what.
> 
> > When sending a delete request to a remote service during a saga, the usual pattern is to provide a "gone" check to bail out of the retry loop: if the remote service was impacted by an expunge then it's pointless to continue retrying a delete request, as something backing that service is gone.
> > There were TWO places not doing this correctly:
> > 
> > * when detaching a volume from a pantry
> > * when deleting local storage datasets
> 
> This is in:
> 
>     * `call_pantry_detach` and
> 
>     * `sdd_delete_local_storage`, correct?
> 
> 
> And it's referring to the "match-on-error, do an extra gone-check to allow deletion to succeed anyway, rather than stopping the saga", correct?
>
> > In these cases correct this by matching on the returned error of either `ProgenitorOperationRetry::run` or `retry_operation_while_indefinitely` (from progenitor-extras), and checking `e.is_gone`. If that matches then the saga can proceed.

Correct!

> > Additionally, there are places where the gone check only checked if the sled was still in-service, but in reality needed to also check if the physical disk backing a zpool was expunged. Fix that too.
> 
> These are places in:
> 
>     * `sdd_delete_local_storage` and
> 
>     * `sis_ensure_local_storage`

Also correct! :)

File: nexus/src/app/sagas/common_storage.rs (hunk 2 above)
Comment (jmpesp) [reply nexus/src/app/sagas/common_storage.rs]: Yeah, agreed. This was too overzealous with the comments. Removed them in e558903d4

**Comment by jmpesp** [comment]
@smklein ready for re-review. note 82cee71ef3861608e199fed81805076a2a6723fb reverts the change mentioned in the PR message: current call sites for `call_pantry_detach` already handle the gone check.

**Review by smklein — APPROVED** [review]
