### PR TITLE
[wicketd] Refine preflight uplink DNS check

### LINKED ISSUE #4044: wicketd preflight uplink: Break up A / AAAA DNS querying
Currently, the `preflight uplink` check provided by wicketd uses [AsyncResolver::lookup_ip()](https://docs.rs/trust-dns-resolver/0.22.0/trust_dns_resolver/struct.AsyncResolver.html#method.lookup_ip) to query DNS servers. Internally, this uses the default lookup strategy, [LookupIpStrategy::Ipv4thenIpv6](https://docs.rs/trust-dns-resolver/0.22.0/src/trust_dns_resolver/config.rs.html#749-751). If _anything_ goes wrong with the IPv4 (A) lookup, [the error is silently discarded](https://docs.rs/trust-dns-resolver/0.22.0/src/trust_dns_resolver/lookup_ip.rs.html#438) and the result of the IPv6 (AAAA) lookup is returned.

Yesterday we saw an instance of preflight uplink consistently reporting "AAAA record not found" errors when performing lookups against the _first_ DNS server in the list provided. The name being queried only had A records, and they were served by all DNS servers. If we swapped the order of the DNS server list, it was consistently the first in the list that failed; if we added a dummy non-server IP as the first entry, it would fail (as expected), but then all the remaining (real) DNS servers succeeded. A `truss` capture shows several `sendto()` calls that were not followed by `recvfrom()`s:

```
/123:   sendto(28, .., 37, 32768, 0xFFFFF5FFCF7F1450, 16) = 37
/129:   sendto(28, .., 37, 32768, 0xFFFFF5FFCDFF1450, 16) = 37
/122:   sendto(28, .., 37, 32768, 0xFFFFF5FFCFBF1450, 16) = 37
/122:   sendto(28, .., 37, 32768, 0xFFFFF5FFCFBF1450, 16) = 37
/125:   sendto(28, .., 37, 32768, 0xFFFFF5FFCEFF1450, 16) = 37
/123:   recvfrom(28, .., 2048, 0, 0xFFFFF5FFCF7F1330, 0xFFFFF5FFCF7F146C) = 65
/125:   sendto(28, .., 42, 32768, 0xFFFFF5FFCEFF0B30, 16) = 42
/116:   recvfrom(28, .., 2048, 0, 0xFFFFF5FFD13F0A10, 0xFFFFF5FFD13F0B4C) = 102
/125:   sendto(28, .., 37, 32768, 0xFFFFF5FFCEFF1450, 16) = 37
/116:   recvfrom(28, .., 2048, 0, 0xFFFFF5FFD13F1330, 0xFFFFF5FFD13F146C) = 81
/125:   sendto(28, .., 37, 32768, 0xFFFFF5FFCEFF1450, 16) = 37
/123:   recvfrom(28, .., 2048, 0, 0xFFFFF5FFCF7F1330, 0xFFFFF5FFCF7F146C) = 81
```

Our theory is that _something_ in the networking stack is not fully set up when we start the DNS queries, so the initial A query times out. After that timeout, we issue the AAAA query, and the network is ready, but we get a "record not found" error (which is expected if we're querying for AAAA when only A exists). To confirm and improve this, we should:

1. Perform separate A and AAAA queries ourselves instead of letting `lookup_ip()` do it for us; this will allow us to report and inspect specific errors from either query
2. If the A query fails for I/O-related issues (timeout, network not reachable, etc. - we're not sure exactly what error we'd see here), we should retry up to some limit

### PR DESCRIPTION
**Pull request by jgallagher**
Prior to this change, we used trust-dns-resolver's [lookup_ip()](https://docs.rs/trust-dns-resolver/0.22.0/trust_dns_resolver/struct.AsyncResolver.html#method.lookup_ip) with default options for our preflight DNS checks, but this doesn't expose as much information as we want in failure cases. In particular, it will query for an A record, and if that fails for any reason at all (including I/O errors and timeouts), it will discard the error, query for an AAAA record, and return the result of that second query.

The substantial changes in this PR are:

* We set several of the options when creating our resolver to more closely match how we're using it (see `build_resolver()`). Particularly relevant, we disable retries (because we're going to retry ourselves).
* Instead of using `lookup_ip()`, we now use `ipv4_lookup()` (A query) and `ipv6_lookup()` (AAAA query) explicitly so we can see the results of each, and decide ourselves whether to proceed from A to AAAA. We do proceed if we get a `NoRecordsFound` from the A query, but do not proceed if there's any other error (which indicates a problem communicating with the server that would not be resolved by changing query types).

Running a `preflight uplink` check on madrid with two correct DNS servers (1.1.1.1, 9.9.9.9) and one nonexistent DNS server (192.168.100.100) and querying for one valid hostname (`ntp.eng.oxide.computer`) and one invalid hostname (`ntp2.eng.oxide.computer`) now produces this output:

```
⚠ Checking for external DNS connectivity (33.088334968s)
    DNS server 1.1.1.1 A query attempt 1: resolved ntp.eng.oxide.computer to 172.20.0.5
    DNS server 9.9.9.9 A query attempt 1: resolved ntp.eng.oxide.computer to 172.20.0.5
    DNS server 1.1.1.1 A query attempt 1: failed to look up ntp2.eng.oxide.computer: no record found for Query { name: Name("ntp2.eng.oxide.computer."), query_type: A, query_class: IN }
    DNS server 1.1.1.1 AAAA query attempt 1: failed to look up ntp2.eng.oxide.computer: no record found for Query { name: Name("ntp2.eng.oxide.computer."), query_type: AAAA, query_class: IN }
    DNS server 9.9.9.9 A query attempt 1: failed to look up ntp2.eng.oxide.computer: no record found for Query { name: Name("ntp2.eng.oxide.computer."), query_type: A, query_class: IN }
    DNS server 9.9.9.9 AAAA query attempt 1: failed to look up ntp2.eng.oxide.computer: no record found for Query { name: Name("ntp2.eng.oxide.computer."), query_type: AAAA, query_class: IN }
    DNS server 192.168.100.100 A query attempt 1: failed to look up ntp.eng.oxide.computer: request timed out
    DNS server 192.168.100.100 A query attempt 2: failed to look up ntp.eng.oxide.computer: request timed out
    DNS server 192.168.100.100 A query attempt 3: failed to look up ntp.eng.oxide.computer: request timed out
```

We can see the A and AAAA queries made to the valid servers when failing to resolve `ntp2.eng.oxide.computer`, and we can see the specific errors from the three attempts to query the nonexistent server; we never move on to querying it for AAAA records.

Fixes #4044.

### CODE REVIEW

File: wicketd/src/preflight_check/uplink.rs [hunk 1]
```diff
@@ -1050,56 +1037,250 @@ impl<'a> DnsLookupStep<'a> {
...
+                        .await;
+                    }
+                    self.messages.append(&mut query_results);
+                    return Ok(());
+                }
+                Err(err) => err,
+            };
+
+            match err.kind() {
+                // If `NoRecordsFound` is an acceptible end to this lookup,
```
Comment (andrewjstone) [inline wicketd/src/preflight_check/uplink.rs:1150]:
```suggestion
                // If `NoRecordsFound` is an acceptable end to this lookup,
```

**Review by andrewjstone — APPROVED** [review]
Great commit message!
