### PR TITLE
Do not retry indefinitely if service is gone

### LINKED ISSUE #4331: all disk deletes hang while Crucible downstairs is unreachable
When the `disk_delete` saga runs, one of its responsibilities is to clean up regions that are freed as a result of a volume being deleted (`svd_delete_freed_crucible_regions`). This uses the following query to find regions that need to be cleaned up:

```sql
select * from region
inner join volume on region.volume_id = volume.id
inner join dataset on region.dataset_id = dataset.id
left join region_snapshot on region_snapshot.region_id = region.id or region_snapshot.dataset_id = dataset.id
where (region_snapshot.volume_references = 0 or region_snapshot.volume_references is null)
and not volume.time_deleted is null;
```

The results of this looks something like (keys redacted):
```
                   id                  |         time_created          |         time_modified         |              dataset_id              |              volume_id               | block_size | blocks_per_extent | extent_count |                  id                  |         time_created         |        time_modified         |         time_deleted          | rcgen |                                                                                                                                                                                                                     data                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       resources_to_clean_up                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                  id                  |         time_created          |         time_modified         | time_deleted | rcgen |               pool_id                |          ip           | port  |   kind   |  size_used  | dataset_id | region_id | snapshot_id | snapshot_addr | volume_references
---------------------------------------+-------------------------------+-------------------------------+--------------------------------------+--------------------------------------+------------+-------------------+--------------+--------------------------------------+------------------------------+------------------------------+-------------------------------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+-------------------------------+-------------------------------+--------------+-------+--------------------------------------+-----------------------+-------+----------+-------------+------------+-----------+-------------+---------------+--------------------
  341e684e-c49a-412d-99b1-9a64ce33a6c9 | 2023-10-16 20:44:49.184976+00 | 2023-10-16 20:44:49.184976+00 | 2074a935-c0b3-4c4f-aae5-a29adae3e1ac | 1f86e688-937a-4e58-81f2-a30d697e92c0 |        512 |            131072 |          160 | 1f86e688-937a-4e58-81f2-a30d697e92c0 | 2023-10-16 20:44:50.00492+00 | 2023-10-16 20:44:50.00492+00 | 2023-10-23 17:00:21.299613+00 |     1 | {"type":"volume","block_size":512,"id":"1f86e688-937a-4e58-81f2-a30d697e92c0","sub_volumes":[{"type":"region","block_size":512,"blocks_per_extent":131072,"extent_count":160,"gen":1,"opts":{"id":"1f86e688-937a-4e58-81f2-a30d697e92c0","key":"............................................","lossy":false,"read_only":false,"target":["[fd00:1122:3344:112::8]:19001","[fd00:1122:3344:11b::7]:19000","[fd00:1122:3344:108::7]:19000"]}}]} | {"V1":{"datasets_and_regions":[[{"identity":{"id":"2074a935-c0b3-4c4f-aae5-a29adae3e1ac","time_created":"2023-09-02T13:09:09.879257Z","time_modified":"2023-09-02T13:09:09.879257Z"},"time_deleted":null,"rcgen":1,"pool_id":"ac663368-45fb-447c-811e-561c68e37bdd","ip":"fd00:1122:3344:112::8","port":32345,"kind":"Crucible","size_used":21474836480},{"identity":{"id":"341e684e-c49a-412d-99b1-9a64ce33a6c9","time_created":"2023-10-16T20:44:49.184976Z","time_modified":"2023-10-16T20:44:49.184976Z"},"dataset_id":"2074a935-c0b3-4c4f-aae5-a29adae3e1ac","volume_id":"1f86e688-937a-4e58-81f2-a30d697e92c0","block_size":512,"blocks_per_extent":131072,"extent_count":160}],[{"identity":{"id":"4b7a7052-f8e8-4196-8d6b-315943986ce6","time_created":"2023-09-02T13:09:09.879238Z","time_modified":"2023-09-02T13:09:09.879238Z"},"time_deleted":null,"rcgen":1,"pool_id":"a549421c-2f12-45cc-b691-202f0a9bfa8b","ip":"fd00:1122:3344:108::7","port":32345,"kind":"Crucible","size_used":10737418240},{"identity":{"id":"1c33fde1-34d1-4686-843d-9855c74f2e29","time_created":"2023-10-16T20:44:49.184976Z","time_modified":"2023-10-16T20:44:49.184976Z"},"dataset_id":"4b7a7052-f8e8-4196-8d6b-315943986ce6","volume_id":"1f86e688-937a-4e58-81f2-a30d697e92c0","block_size":512,"blocks_per_extent":131072,"extent_count":160}],[{"identity":{"id":"864fdb33-a36d-4bb0-96e6-a3b3b057ba8b","time_created":"2023-09-02T13:09:09.879256Z","time_modified":"2023-09-02T13:09:09.879256Z"},"time_deleted":null,"rcgen":1,"pool_id":"f59674a4-437e-4846-9abf-a71679082c82","ip":"fd00:1122:3344:11b::7","port":32345,"kind":"Crucible","size_used":21474836480},{"identity":{"id":"6a84deca-8b0f-475d-bbe2-1c684bfc0ec1","time_created":"2023-10-16T20:44:49.184976Z","time_modified":"2023-10-16T20:44:49.184976Z"},"dataset_id":"864fdb33-a36d-4bb0-96e6-a3b3b057ba8b","volume_id":"1f86e688-937a-4e58-81f2-a30d697e92c0","block_size":512,"blocks_per_extent":131072,"extent_count":160}]],"datasets_and_snapshots":[]}} | 2074a935-c0b3-4c4f-aae5-a29adae3e1ac | 2023-09-02 13:09:09.879257+00 | 2023-09-02 13:09:09.879257+00 | NULL         |     1 | ac663368-45fb-447c-811e-561c68e37bdd | fd00:1122:3344:112::8 | 32345 | crucible | 21474836480 | NULL       | NULL      | NULL        | NULL          |              NULL
  1c33fde1-34d1-4686-843d-9855c74f2e29 | 2023-10-16 20:44:49.184976+00 | 2023-10-16 20:44:49.184976+00 | 4b7a7052-f8e8-4196-8d6b-315943986ce6 | 1f86e688-937a-4e58-81f2-a30d697e92c0 |        512 |            131072 |          160 | 1f86e688-937a-4e58-81f2-a30d697e92c0 | 2023-10-16 20:44:50.00492+00 | 2023-10-16 20:44:50.00492+00 | 2023-10-23 17:00:21.299613+00 |     1 | {"type":"volume","block_size":512,"id":"1f86e688-937a-4e58-81f2-a30d697e92c0","sub_volumes":[{"type":"region","block_size":512,"blocks_per_extent":131072,"extent_count":160,"gen":1,"opts":{"id":"1f86e688-937a-4e58-81f2-a30d697e92c0","key":"............................................","lossy":false,"read_only":false,"target":["[fd00:1122:3344:112::8]:19001","[fd00:1122:3344:11b::7]:19000","[fd00:1122:3344:108::7]:19000"]}}]} | {"V1":{"datasets_and_regions":[[{"identity":{"id":"2074a935-c0b3-4c4f-aae5-a29adae3e1ac","time_created":"2023-09-02T13:09:09.879257Z","time_modified":"2023-09-02T13:09:09.879257Z"},"time_deleted":null,"rcgen":1,"pool_id":"ac663368-45fb-447c-811e-561c68e37bdd","ip":"fd00:1122:3344:112::8","port":32345,"kind":"Crucible","size_used":21474836480},{"identity":{"id":"341e684e-c49a-412d-99b1-9a64ce33a6c9","time_created":"2023-10-16T20:44:49.184976Z","time_modified":"2023-10-16T20:44:49.184976Z"},"dataset_id":"2074a935-c0b3-4c4f-aae5-a29adae3e1ac","volume_id":"1f86e688-937a-4e58-81f2-a30d697e92c0","block_size":512,"blocks_per_extent":131072,"extent_count":160}],[{"identity":{"id":"4b7a7052-f8e8-4196-8d6b-315943986ce6","time_created":"2023-09-02T13:09:09.879238Z","time_modified":"2023-09-02T13:09:09.879238Z"},"time_deleted":null,"rcgen":1,"pool_id":"a549421c-2f12-45cc-b691-202f0a9bfa8b","ip":"fd00:1122:3344:108::7","port":32345,"kind":"Crucible","size_used":10737418240},{"identity":{"id":"1c33fde1-34d1-4686-843d-9855c74f2e29","time_created":"2023-10-16T20:44:49.184976Z","time_modified":"2023-10-16T20:44:49.184976Z"},"dataset_id":"4b7a7052-f8e8-4196-8d6b-315943986ce6","volume_id":"1f86e688-937a-4e58-81f2-a30d697e92c0","block_size":512,"blocks_per_extent":131072,"extent_count":160}],[{"identity":{"id":"864fdb33-a36d-4bb0-96e6-a3b3b057ba8b","time_created":"2023-09-02T13:09:09.879256Z","time_modified":"2023-09-02T13:09:09.879256Z"},"time_deleted":null,"rcgen":1,"pool_id":"f59674a4-437e-4846-9abf-a71679082c82","ip":"fd00:1122:3344:11b::7","port":32345,"kind":"Crucible","size_used":21474836480},{"identity":{"id":"6a84deca-8b0f-475d-bbe2-1c684bfc0ec1","time_created":"2023-10-16T20:44:49.184976Z","time_modified":"2023-10-16T20:44:49.184976Z"},"dataset_id":"864fdb33-a36d-4bb0-96e6-a3b3b057ba8b","volume_id":"1f86e688-937a-4e58-81f2-a30d697e92c0","block_size":512,"blocks_per_extent":131072,"extent_count":160}]],"datasets_and_snapshots":[]}} | 4b7a7052-f8e8-4196-8d6b-315943986ce6 | 2023-09-02 13:09:09.879238+00 | 2023-09-02 13:09:09.879238+00 | NULL         |     1 | a549421c-2f12-45cc-b691-202f0a9bfa8b | fd00:1122:3344:108::7 | 32345 | crucible | 10737418240 | NULL       | NULL      | NULL        | NULL          |              NULL
  6a84deca-8b0f-475d-bbe2-1c684bfc0ec1 | 2023-10-16 20:44:49.184976+00 | 2023-10-16 20:44:49.184976+00 | 864fdb33-a36d-4bb0-96e6-a3b3b057ba8b | 1f86e688-937a-4e58-81f2-a30d697e92c0 |        512 |            131072 |          160 | 1f86e688-937a-4e58-81f2-a30d697e92c0 | 2023-10-16 20:44:50.00492+00 | 2023-10-16 20:44:50.00492+00 | 2023-10-23 17:00:21.299613+00 |     1 | {"type":"volume","block_size":512,"id":"1f86e688-937a-4e58-81f2-a30d697e92c0","sub_volumes":[{"type":"region","block_size":512,"blocks_per_extent":131072,"extent_count":160,"gen":1,"opts":{"id":"1f86e688-937a-4e58-81f2-a30d697e92c0","key":"............................................","lossy":false,"read_only":false,"target":["[fd00:1122:3344:112::8]:19001","[fd00:1122:3344:11b::7]:19000","[fd00:1122:3344:108::7]:19000"]}}]} | {"V1":{"datasets_and_regions":[[{"identity":{"id":"2074a935-c0b3-4c4f-aae5-a29adae3e1ac","time_created":"2023-09-02T13:09:09.879257Z","time_modified":"2023-09-02T13:09:09.879257Z"},"time_deleted":null,"rcgen":1,"pool_id":"ac663368-45fb-447c-811e-561c68e37bdd","ip":"fd00:1122:3344:112::8","port":32345,"kind":"Crucible","size_used":21474836480},{"identity":{"id":"341e684e-c49a-412d-99b1-9a64ce33a6c9","time_created":"2023-10-16T20:44:49.184976Z","time_modified":"2023-10-16T20:44:49.184976Z"},"dataset_id":"2074a935-c0b3-4c4f-aae5-a29adae3e1ac","volume_id":"1f86e688-937a-4e58-81f2-a30d697e92c0","block_size":512,"blocks_per_extent":131072,"extent_count":160}],[{"identity":{"id":"4b7a7052-f8e8-4196-8d6b-315943986ce6","time_created":"2023-09-02T13:09:09.879238Z","time_modified":"2023-09-02T13:09:09.879238Z"},"time_deleted":null,"rcgen":1,"pool_id":"a549421c-2f12-45cc-b691-202f0a9bfa8b","ip":"fd00:1122:3344:108::7","port":32345,"kind":"Crucible","size_used":10737418240},{"identity":{"id":"1c33fde1-34d1-4686-843d-9855c74f2e29","time_created":"2023-10-16T20:44:49.184976Z","time_modified":"2023-10-16T20:44:49.184976Z"},"dataset_id":"4b7a7052-f8e8-4196-8d6b-315943986ce6","volume_id":"1f86e688-937a-4e58-81f2-a30d697e92c0","block_size":512,"blocks_per_extent":131072,"extent_count":160}],[{"identity":{"id":"864fdb33-a36d-4bb0-96e6-a3b3b057ba8b","time_created":"2023-09-02T13:09:09.879256Z","time_modified":"2023-09-02T13:09:09.879256Z"},"time_deleted":null,"rcgen":1,"pool_id":"f59674a4-437e-4846-9abf-a71679082c82","ip":"fd00:1122:3344:11b::7","port":32345,"kind":"Crucible","size_used":21474836480},{"identity":{"id":"6a84deca-8b0f-475d-bbe2-1c684bfc0ec1","time_created":"2023-10-16T20:44:49.184976Z","time_modified":"2023-10-16T20:44:49.184976Z"},"dataset_id":"864fdb33-a36d-4bb0-96e6-a3b3b057ba8b","volume_id":"1f86e688-937a-4e58-81f2-a30d697e92c0","block_size":512,"blocks_per_extent":131072,"extent_count":160}]],"datasets_and_snapshots":[]}} | 864fdb33-a36d-4bb0-96e6-a3b3b057ba8b | 2023-09-02 13:09:09.879256+00 | 2023-09-02 13:09:09.879256+00 | NULL         |     1 | f59674a4-437e-4846-9abf-a71679082c82 | fd00:1122:3344:11b::7 | 32345 | crucible | 21474836480 | NULL       | NULL      | NULL        | NULL          |              NULL
```
One of the related datasets points to a sled that had been physically removed from the rack: `fd00:1122:3344:11b::7`. The regions returned from the query will then eventually reach `delete_crucible_region` which will attempt to delete the region in a `retry_until_known_result` loop. Given that the sled is no longer reachable, this saga gets stuck in a running state indefinitely.

Given that the above query looks for regions that have been freed for any reason (as opposed to actions that directly occurred in the containing saga), all future `disk_delete` saga will also find these regions and attempt to delete them. This essentially means that once a single disk delete hangs, all future delete operations will hang.

For the instance that we saw this, this ultimately was a result of data being leftover in CockroachDB when trying to clean up from removing sled 10.

### LINKED ISSUE #5022: When crucible is unreachable instance-create saga can not unwind
Feel free to close if this is a duplicate as I fell like this was discussed before, but I could not find the exact issue.

When creating an instance, if the `instance-create` saga requests a region from an unavailable crucible zone the saga will eventually fail with a timeout and attempt to clean up any regions that were created during the unwind. During this unwind it will again try to reach out to the region that timed out as it does not know if the timeout resulted in a region or not. If the region is fully unreachable and not coming back, the saga will be hang repeatedly trying to reach the zone:

```
21:43:09.252Z DEBG 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): authorize result
    action = Query
    actor = Some(Actor::SiloUser { silo_user_id: fe770c10-0ad3-4d15-96e5-1b7541aa1591, silo_id: 3274bfe0-2cef-4983-9315-740cf1e4ad19, .. })
    actor_id = fe770c10-0ad3-4d15-96e5-1b7541aa1591
    authenticated = true
    resource = Database
    result = Ok(())
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
    saga_node = SpaceAccount
21:43:09.261Z DEBG 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): recording saga event
    event_type = Succeeded(Null)
    node_id = 171
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
21:43:09.263Z DEBG 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): recording saga event
    event_type = Started
    node_id = 172
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
21:43:09.265Z DEBG 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): recording saga event
    event_type = Succeeded(Null)
    node_id = 172
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
21:43:09.267Z DEBG 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): recording saga event
    event_type = Started
    node_id = 173
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
21:43:09.383Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Region requested, not yet created. Retrying in 272.667089ms
    file = nexus/src/app/sagas/common_storage.rs:74
    region = 54f13fed-7e31-4580-b1a3-e4ff9ea05884
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:09.385Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Region requested, not yet created. Retrying in 223.878843ms
    file = nexus/src/app/sagas/common_storage.rs:74
    region = 1c6cf3ca-acc0-4d6b-a27d-e422feb6ac00
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:09.611Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Region requested, not yet created. Retrying in 423.714892ms
    file = nexus/src/app/sagas/common_storage.rs:74
    region = 1c6cf3ca-acc0-4d6b-a27d-e422feb6ac00
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:09.657Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Region requested, not yet created. Retrying in 402.61976ms
    file = nexus/src/app/sagas/common_storage.rs:74
    region = 54f13fed-7e31-4580-b1a3-e4ff9ea05884
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:10.036Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Region requested, not yet created. Retrying in 1.492108863s
    file = nexus/src/app/sagas/common_storage.rs:74
    region = 1c6cf3ca-acc0-4d6b-a27d-e422feb6ac00
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:10.061Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Region requested, not yet created. Retrying in 1.45481525s
    file = nexus/src/app/sagas/common_storage.rs:74
    region = 54f13fed-7e31-4580-b1a3-e4ff9ea05884
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:24.382Z DEBG 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): recording saga event
    event_type = Failed(ActionFailed { source_error: Object {"InternalError": Object {"internal_message": String("Communication Error: error sending request for url (http://[fd00:1122:3344:111::5]:32345/crucible/0/regions): operation timed out")}} })
    node_id = 173
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
21:43:24.385Z INFO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): update for saga cached state
    file = /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/steno-0.4.0/src/sec.rs:1332
    new_state = Unwinding
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    sec_id = 95ebe94d-0e68-421d-9260-c30bd7fe4bd6
21:43:24.385Z INFO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): updating state
    file = nexus/db-queries/src/db/sec_store.rs:72
    new_state = unwinding
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
21:43:24.401Z DEBG 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): recording saga event
    event_type = UndoStarted
    node_id = 172
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
21:43:24.404Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): sdc_regions_ensure_undo: Deleting crucible regions
    file = nexus/src/app/sagas/disk_create.rs:545
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:24.548Z INFO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Transient(region not deleted yet), trying again in 146.578465ms
    file = nexus/src/app/sagas/common_storage.rs:290
    region_id = 54f13fed-7e31-4580-b1a3-e4ff9ea05884
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:24.549Z INFO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Transient(region not deleted yet), trying again in 54.971078ms
    file = nexus/src/app/sagas/common_storage.rs:290
    region_id = 1c6cf3ca-acc0-4d6b-a27d-e422feb6ac00
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:24.606Z INFO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Transient(region not deleted yet), trying again in 136.157882ms
    file = nexus/src/app/sagas/common_storage.rs:290
    region_id = 1c6cf3ca-acc0-4d6b-a27d-e422feb6ac00
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:24.696Z INFO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Transient(region not deleted yet), trying again in 177.300212ms
    file = nexus/src/app/sagas/common_storage.rs:290
    region_id = 54f13fed-7e31-4580-b1a3-e4ff9ea05884
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:24.743Z INFO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): Transient(region not deleted yet), trying again in 192.446679ms
    file = nexus/src/app/sagas/common_storage.rs:290
    region_id = 1c6cf3ca-acc0-4d6b-a27d-e422feb6ac00
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:24.875Z INFO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): region deleted
    file = nexus/src/app/sagas/common_storage.rs:275
    region_id = 54f13fed-7e31-4580-b1a3-e4ff9ea05884
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:24.938Z INFO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): region deleted
    file = nexus/src/app/sagas/common_storage.rs:275
    region_id = 1c6cf3ca-acc0-4d6b-a27d-e422feb6ac00
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:39.516Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): saw transient communication error error sending request for url (http://[fd00:1122:3344:111::5]:32345/crucible/0/regions/71d2cb1c-2ca1-40d0-9f53-98a9b76df51a): operation timed out, retrying...
    file = nexus/src/app/sagas/mod.rs:358
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:39.516Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): failed external call (Communication Error: error sending request for url (http://[fd00:1122:3344:111::5]:32345/crucible/0/regions/71d2cb1c-2ca1-40d0-9f53-98a9b76df51a): operation timed out), will retry in 299.584333ms
    file = nexus/src/app/sagas/mod.rs:403
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
21:43:54.818Z WARN 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): saw transient communication error error sending request for url (http://[fd00:1122:3344:111::5]:32345/crucible/0/regions/71d2cb1c-2ca1-40d0-9f53-98a9b76df51a): operation timed out, retrying...
    file = nexus/src/app/sagas/mod.rs:358
    saga_id = daf91d7c-7928-418a-ae54-e58c4a31b3ab
    saga_name = instance-create
```

This looks to occur in the unwind of the `disk-create` sub-saga when it attempts to delete crucible regions. The delete will loop forever until it is able to access the requested region.

To an end user this is reported as an instance stuck in the `creating` state, even though it is guaranteed at this point to never to complete (i.e. is it trying to destroy itself as opposed to start up).

### PR DESCRIPTION
**Pull request by jmpesp**
If there's a call to an external service, saga execution cannot move forward until the result of that call is known, in the sense that Nexus received a result. If there are transient problems, Nexus must retry until a known result is returned.

This is problematic when the destination service is gone - Nexus will retry indefinitely, halting the saga execution. Worse, in the case of sagas calling the volume delete subsaga, subsequent calls that also call volume delete will also halt.

With the introduction of a physical disk policy, Nexus can know when to stop retrying a call - the destination service is gone, so the known result is an error.

This commit adds a `ProgenitorOperationRetry` object that takes an operation to retry plus a "gone" check, and checks each retry iteration if the destination is gone. If it is, then bail out, otherwise assume that any errors seen are transient.

Further work is required to deprecate the `retry_until_known_result` function, as retrying indefinitely is a bad pattern.

Fixes #4331
Fixes #5022

### CODE REVIEW

File: nexus/src/app/crucible.rs [hunk 1]
```diff
@@ -0,0 +1,1086 @@
...
+                        Error::Gone => {
+                            // Return Ok if the dataset's agent is gone, no
+                            // delete call is required.
+                            return Ok(());
+                        }
+
+                        _ => {
+                            Err(BackoffError::Permanent(WaitError::Permanent(e)))
+                        }
+                    }
```
Comment (hawkw) [inline nexus/src/app/crucible.rs:714]: nit: this could be flattened into:
```suggestion
                    // Return Ok if the dataset's agent is gone, no
                    // delete call is required.
                    Err(Error::Gone) => return Ok(()),
                    Err(e) => Err(BackoffError::Permanent(WaitError::Permanent(e))),
```

File: nexus/src/app/crucible.rs [hunk 2]
```diff
@@ -0,0 +1,1086 @@
...
+                        Error::Gone => {
+                            // Return Ok if the dataset's agent is gone, no
+                            // delete call is required.
+                            return Ok(());
+                        }
+
+                        _ => Err(BackoffError::Permanent(
+                            WaitError::Permanent(e),
+                        )),
+                    },
```
Comment (hawkw) [inline nexus/src/app/crucible.rs:857]:
```suggestion

                    // Return Ok if the dataset's agent is gone, no
                    // delete call is required.
                    Err(Error::Gone) => return Ok(()),
                    
                    Err(e) => Err(BackoffError::Permanent(
                         WaitError::Permanent(e),
                    )),
```

File: nexus/src/app/crucible.rs [hunk 3]
```diff
@@ -0,0 +1,1086 @@
...
+                        crucible_agent_client::Error::ErrorResponse(rv) => {
+                            match rv.status() {
+                                status if status.is_client_error() => {
+                                    Err(Error::invalid_request(&rv.message))
+                                }
+
+                                _ => {
+                                    Err(Error::internal_error(&rv.message))
+                                }
+                            }
```
Comment (hawkw) [inline nexus/src/app/crucible.rs:469]: similarly, this could be:nit, take it or leave  it: maybe:
```suggestion
                            if rv.status().is_client_error() => {
                                Err(Error::invalid_request(&rv.message))
                            } else {
                                Err(Error::internal_error(&rv.message))
                            }
```

**Review by hawkw — COMMENTED** [review]
some smallish style suggestions to hopefully make the nested matches a little more comprehensible --- feel free to ignore me if you don't like them :)

**Comment by jmpesp** [comment]
> some smallish style suggestions to hopefully make the nested matches a little more comprehensible --- feel free to ignore me if you don't like them :)

Quite the opposite, thanks for them! I find myself writing nested match code like this lately, so these suggestions help :)

File: common/src/progenitor_operation_retry.rs [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+
+                async move {
+                    match gone_check.await {
+                        Ok(dest_is_gone) => {
+                            if dest_is_gone {
+                                return Err(BackoffError::Permanent(
+                                    ProgenitorOperationRetryError::Gone
+                                ));
+                            }
+                        }
```
[the remark this answers is not in the document]
Comment (jmpesp) [reply common/src/progenitor_operation_retry.rs:86]: In this case, I prefer the more explicit style, but thanks :)

File: nexus/db-queries/src/db/datastore/dataset.rs [hunk 5]
```diff
@@ -180,6 +182,56 @@ impl DataStore {
 
         Ok(all_datasets)
     }
+
+    pub async fn dataset_on_in_service_physical_disk(
+        &self,
+        // opctx: &OpContext,
+        dataset_id: Uuid,
+    ) -> LookupResult<bool> {
+        //let conn = self.pool_connection_authorized(opctx).await?;
```
Comment (andrewjstone) [inline nexus/db-queries/src/db/datastore/dataset.rs:191]: Presumably you want to restore this before merging. What caused this change to be needed in the first place?

File: nexus/db-queries/src/db/datastore/dataset.rs [hunk 6]
```diff
@@ -180,6 +182,56 @@ impl DataStore {
 
         Ok(all_datasets)
     }
+
+    pub async fn dataset_on_in_service_physical_disk(
```
Comment (andrewjstone) [inline nexus/db-queries/src/db/datastore/dataset.rs:186]: `on_in` reads a little wonky to me. I thought it was a typo at first. Maybe something like `in_service_physical_disk_contains_dataset` would work?

File: nexus/src/app/crucible.rs [hunk 7]
```diff
@@ -0,0 +1,1051 @@
...
+#[derive(Debug, thiserror::Error)]
+enum WaitError {
+    #[error("Transient error: {0}")]
+    Transient(#[from] anyhow::Error),
+
+    #[error("Permanent error: {0}")]
+    Permanent(#[from] Error),
+}
+
+impl super::Nexus {
```
Comment (andrewjstone) [inline nexus/src/app/crucible.rs:40]: I think we really want to get away from having a shared nexus type with all functions hanging off it. This has already made it quite difficult to pass pieces into background tasks by themselves. I'm not sure we should worry about it in this PR, but eventually we are going to end up ripping all this out and turning it into it's own distinct type I believe. Maybe we should get ahead of that now and provide a `CrucibleAgentClient` type that takes specific parameters for what it needs. That may be easier said than done given the need to use the `datastore`, but I figured I'd bring it up for completness and to also get us thinking about how we move on past the chads hanging off Nexus.

CC @david-crespo @jgallagher @hawkw @davepacheco

File: nexus/src/app/crucible.rs [hunk 8]
```diff
@@ -0,0 +1,1051 @@
...
+            id: RegionId(region.id().to_string()),
+            encrypted: region.encrypted(),
+            cert_pem: None,
+            key_pem: None,
+            root_pem: None,
+            source: None,
+        };
+
+        let create_region = || async {
+            let region = match ProgenitorOperationRetry::new(
```
Comment (andrewjstone) [inline nexus/src/app/crucible.rs:97]: This is pretty nice!

File: nexus/src/app/crucible.rs [hunk 9]
```diff
@@ -0,0 +1,1051 @@
...
+                Err(e) => {
+                    error!(
+                        log,
+                        "region_create saw {:?}",
+                        e;
+                        "region_id" => %region.id(),
+                        "dataset_id" => %dataset_id,
+                    );
+
+                    match e {
```
Comment (andrewjstone) [inline nexus/src/app/crucible.rs:115]: It's really a bee in my bonnet that we have to do these matches every time, but I"m not sure how to avoid it.

File: common/src/progenitor_operation_retry.rs [hunk 10]
```diff
@@ -0,0 +1,158 @@
...
+{
+    pub fn new(operation: F, gone_check: BF) -> Self {
+        Self { operation, gone_check }
+    }
+
+    pub async fn run(
+        mut self,
+        log: &Logger,
+    ) -> Result<T, ProgenitorOperationRetryError<E>> {
+        retry_notify(
```
Comment (andrewjstone) [inline common/src/progenitor_operation_retry.rs:72]: It looks like when you call `run` inside the `create_region` future inside `ensure_region_in_dataset`, there is a [`retry_notify`](https://github.com/oxidecomputer/omicron/pull/5789/files#diff-93ab1121effeed1199aef2b1d99ea8a00da10b6998c21aba461d15269a1f9c44R179-R182) call around the `create_region` future. This creates two backoff loops rather than one, and seems like a really easy mistake to make. Instead, what if we didn't actually call retry instead of `run` here but relied on the outer retry loop. I think that would simplify this a lot as well, as now you wouldn't have to worry about the progenitor errors. The outer loop would call a future that only does the gone check once and returns an error, rather than looping.

File: nexus/src/app/crucible.rs [hunk 11]
```diff
@@ -0,0 +1,1051 @@
...
+            Err(e) => {
+                error!(
+                    log,
+                    "region_get_snapshots saw {:?}",
+                    e;
+                    "region_id" => %region_id,
+                    "dataset_id" => %dataset_id,
+                );
+
+                match e {
```
Comment (andrewjstone) [inline nexus/src/app/crucible.rs:305]: After seeing the third one of these, the bee in my bonnet is now a hornet with an anger issue. Is it possible to wrap these checks into a function and reuse it?

File: nexus/tests/integration_tests/disks.rs [hunk 12]
```diff
@@ -2458,6 +2461,80 @@ async fn test_region_allocation_after_delete(
...
+    let jh = tokio::spawn(async move {
+        NexusRequest::object_delete(&client, &disk_url)
+            .authn_as(AuthnMode::PrivilegedUser)
+            .execute()
+            .await
+            .expect("failed to delete disk")
+    });
+
+    // It won't finish until the dataset is expunged.
+    tokio::time::sleep(Duration::from_secs(3)).await;
```
Comment (andrewjstone) [inline nexus/tests/integration_tests/disks.rs:2507]: I know you need some heuristic to ensure something is not done, but I really find sleeps like this in tests to be problematic. Not only do they sometimes cause flakiness, but they also make tests take longer. 3 seconds here, 3 seconds there and pretty soon your talking real time.

My recommendation instead of a sleep is usually to put one side of a channel in the task and have the test task communicate with it to determine if a given state has been reached. That seems somewhat difficult in this case, as you are essentially checking to see if the call is hung. I'm not sure how to fix this, but I still don't like it!

File: nexus/src/app/crucible.rs [hunk 13]
```diff
@@ -0,0 +1,1051 @@
...
+            .collect::<Vec<Result<(), Error>>>()
+            .await
+            .into_iter()
+            .collect::<Result<Vec<_>, _>>()?;
+
+        Ok(())
+    }
+
+    /// Given a list of datasets and region snapshots, send DELETE calls to the
+    /// datasets corresponding Crucible Agent for each snapshot.
```
Comment (andrewjstone) [inline nexus/src/app/crucible.rs:1015]:
```suggestion
    /// dataset's corresponding Crucible Agent for each snapshot.
```

File: nexus/src/app/crucible.rs [hunk 14]
```diff
@@ -0,0 +1,1051 @@
...
+        // the appropriate state change.
+
+        self.request_crucible_region_delete(log, dataset, region_id).await?;
+
+        // Wait until the region is deleted
+
+        backoff::retry_notify(
+            backoff::retry_policy_internal_service_aggressive(),
+            || async {
+                let region = match self.maybe_get_crucible_region(
```
Comment (andrewjstone) [inline nexus/src/app/crucible.rs:584]: Maybe make a note that `self.maybe_get_crucible_region` will check for permanent errors and so we don't need to add a check to this loop.

File: nexus/src/app/crucible.rs [hunk 15]
```diff
@@ -0,0 +1,1051 @@
...
+            || async {
+                let response = match self
+                    .get_crucible_region_snapshots(log, dataset, region_id)
+                    .await
+                {
+                    Ok(v) => Ok(v),
+
+                    // Return Ok if the dataset's agent is gone, no
+                    // delete call is required.
+                    Err(Error::Gone) => return Ok(()),
```
Comment (andrewjstone) [inline nexus/src/app/crucible.rs:818]: I finally noticed here, that we don't log when something is gone. Should we add that logging to the `ProgenitorOperationRetry` code or leave it to the users. In the latter case, we should add a log here, as well as all other places `Gone` is returned.

**Review by andrewjstone — COMMENTED** [review]
James, Overall I like the solution. It maps to what we discussed wrt expunged. However, I left a few suggestions for architectural fixes that probably are worth at least a look.

File: common/src/lib.rs [hunk 16]
```diff
@@ -79,83 +80,40 @@ impl slog::KV for FileKv {
...
 /// Retry a progenitor client operation until a known result is returned.
 ///
-/// Saga execution relies on the outcome of an external call being known: since
-/// they are idempotent, reissue the external call until a known result comes
-/// back. Retry if a communication error is seen, or if another retryable error
-/// is seen.
-///
-/// Note that retrying is only valid if the call itself is idempotent.
+/// See [`ProgenitorOperationRetry`] for more information.
+// TODO mark this deprecated, `never_bail` is a bad idea
```
[the remark this answers is not in the document]
Comment (jmpesp) [reply common/src/lib.rs:91]: Nope! opened #5813

File: nexus/src/app/crucible.rs (hunk 7 above)
Comment (hawkw) [reply nexus/src/app/crucible.rs:40]: Yeah, I would really like to move away from this as much as we're able to...

File: common/src/lib.rs (hunk 16 above)
[the remark this answers is not in the document]
Comment (andrewjstone) [reply common/src/lib.rs:91]: Thanks!

File: nexus/src/app/crucible.rs (hunk 11 above)
Comment (jmpesp) [reply nexus/src/app/crucible.rs]: I hacked on this for longer than I thought before settling on something that I liked! See ff3915033

File: nexus/src/app/crucible.rs (hunk 9 above)
Comment (jmpesp) [reply nexus/src/app/crucible.rs]: See ff3915033 for some reuse :)

File: common/src/progenitor_operation_retry.rs (hunk 10 above)
Comment (jmpesp) [reply common/src/progenitor_operation_retry.rs:96]: In this case, the double backoff looping was intentional: the outer retry (in nexus/src/app/crucible.rs) is to poll until a desired state change, and the inner retry (in common/src/progenitor_operation_retry.rs) is to paper over transient network problems. I think I still like this separation, though I don't grok the simplification you're referring to yet. Going to hack around with this.

File: nexus/src/app/crucible.rs (hunk 8 above)
Comment (jmpesp) [reply nexus/src/app/crucible.rs:125]: :+1:

File: nexus/db-queries/src/db/datastore/dataset.rs (hunk 6 above)
Comment (jmpesp) [reply nexus/db-queries/src/db/datastore/dataset.rs]: yeah, this sucks. changed to `dataset_physical_disk_in_service` in 9e8fcc147

File: nexus/src/app/crucible.rs (hunk 15 above)
Comment (jmpesp) [reply nexus/src/app/crucible.rs]: Good point - I don't think `ProgenitorOperationRetry` is a good place for this because it doesn't have any visibility into _what_ is gone, just that the gone_check function returned true, so I've added it one layer up: see 0baa9c8e5

File: nexus/src/app/crucible.rs (hunk 7 above)
Comment (jmpesp) [reply nexus/src/app/crucible.rs:68]: Without a motivating case of sharing functionality with a background task I'm not sure I want to separate parts of this out yet. I'm definitely glad to do the work in the future that you're talking about.

File: nexus/db-queries/src/db/datastore/dataset.rs (hunk 5 above)
Comment (andrewjstone) [reply nexus/db-queries/src/db/datastore/dataset.rs]: Ok, that makes sense.

File: nexus/src/app/crucible.rs (hunk 7 above)
Comment (andrewjstone) [reply nexus/src/app/crucible.rs:68]: That works for me.

File: nexus/src/app/crucible.rs (hunk 9 above)
Comment (andrewjstone) [reply nexus/src/app/crucible.rs]: That is so much better. Thank you!

File: nexus/tests/integration_tests/disks.rs (hunk 12 above)
Comment (andrewjstone) [reply nexus/tests/integration_tests/disks.rs]: This looks like it changes the semantics of the test though. You now have a much more likely chance that that the spawned task hasn't even started to run yet, making the ` assert!(!jh.is_finished())` somewhat meaningless. I still think on balance gettting rid of the sleep is the right, call, so I'm fine with this. But. maybe make a note about why there is no sleep and what the goal of the test is.

File: nexus/src/app/crucible.rs (hunk 15 above)
Comment (andrewjstone) [reply nexus/src/app/crucible.rs]: Great! Thanks.

File: common/src/progenitor_operation_retry.rs (hunk 10 above)
Comment (andrewjstone) [reply common/src/progenitor_operation_retry.rs:96]: If this makes sense, and your hacking didn't yield anything, I'm fine leaving it as is for now.

File: nexus/db-queries/src/db/datastore/dataset.rs (hunk 6 above)
Comment (andrewjstone) [reply nexus/db-queries/src/db/datastore/dataset.rs]: Thanks.

**Review by andrewjstone — APPROVED** [review]
Thanks for all the hard work and cleanup @jmpesp!

File: nexus/src/app/crucible.rs (hunk 14 above)
Comment (jmpesp) [reply nexus/src/app/crucible.rs]: Sorry, I don't quite grok this comment - this section matches against `Err(e)`?

Comment (andrewjstone) [reply nexus/src/app/crucible.rs]: Could be outdated. In either case, I wasn't even clear enough for myself to remember what I was talking about. Feel free to ignore it.
