### PR TITLE
Fix flaky instance zone-boot timeout test

### LINKED ISSUE #6197: `test_instance_create_timeout_while_creating_zone` is flaky
The test `test_instance_create_timeout_while_creating_zone` attempts to verify what happens when zone-boot times out while creating an instance. Prior to b74d691, that was inadvertently relying on a DNS resolution request that would never succeed to "time out" the zone boot. In that commit, we removed that DNS resolution, revealing the problem in the test.

However, the test remains flaky. It's relying on Tokio's time facilities to pause / advance time far enough that the we time out the request to create an instance, but not far enough that the zone actually boots. That kind of control of time is always finicky, since it's often the case that time needs to be advanced in small jumps to allow the runtime to schedule and drive other tasks in the meantime. In this case, we can apparently just never call the `MockZones::boot()` method, presumably because the test succeeds and that task is torn down before it's called.

We should probably make the test work better by advancing time in small jumps, well beyond the expected timeout for the zone boot call itself.

_Originally posted by @hawkw in https://github.com/oxidecomputer/omicron/issues/5749#issuecomment-2259232654_

### PR DESCRIPTION
**Pull request by bnaecker**
- Fixes #6197
- Use a multi-threaded runtime for the test so we can literally sleep in the boot closure without blocking the test itself.

### CODE REVIEW

File: sled-agent/src/instance.rs [hunk 1]
```diff
@@ -2110,20 +2122,16 @@ mod tests {
...
-        tokio::time::advance(TIMEOUT_DURATION * 2).await;
-
-        tokio::time::resume();
-
+        // Timeout our future waiting for the instance-state-change at 1s. This
+        // is much shorter than the actual `TIMEOUT_DURATION`, but the test
+        // structure requires that we actually wait this period, since we cannot
+        // advance time manually in a multi-threaded runtime.
+        let timeout_fut = timeout(TIMEOUT, put_rx);
+        println!("Awaiting zone-boot timeout");
```
Comment (lifning) [inline sled-agent/src/instance.rs:2130]: (should these println's be going into logctx instead?)

Comment (bnaecker) [reply sled-agent/src/instance.rs:2130]: They can, yeah. I wanted to see them during runs with `--nocapture`, but I can move them over if that's preferred.

Comment (bnaecker) [reply sled-agent/src/instance.rs]: Moved in a0b73002c

**Review by lifning — APPROVED** [review]
