### PR TITLE
Reconfigurator: Don't talk to expunged sleds from executor

### LINKED ISSUE #5594: Reconfigurator: Executor should not try to talk to expunged sleds
As part of testing in https://github.com/oxidecomputer/omicron/issues/5480, we found that the executor still tries, and fails, to send `OmicronPhysicalDisksConfig` to expunged sleds. This causes the rest of the executor to not complete on the error and so zones don't get deploye.

### PR DESCRIPTION
**Pull request by andrewjstone**
We confirmed on a4x2 that Nexus gets deployed on the new sled with this change.

Fixes #5594

### CODE REVIEW

**Comment by sunshowers** [comment]
Makes a ton of sense, thanks for doing this!

File: nexus/reconfigurator/execution/src/omicron_zones.rs [hunk 1]
```diff
@@ -33,6 +34,16 @@ pub(crate) async fn deploy_zones(
             {
                 Some(sled) => sled,
                 None => {
+                    if config.zones.iter().all(|c| {
+                        c.disposition == BlueprintZoneDisposition::Expunged
```
Comment (jgallagher) [inline nexus/reconfigurator/execution/src/omicron_zones.rs:38]: Do you think we'll do this frequently enough it warrants something like `config.are_all_zones_expunged()`?

File: nexus/src/app/background/inventory_collection.rs [hunk 2]
```diff
@@ -180,7 +181,11 @@ impl<'a> nexus_inventory::SledAgentEnumerator for DbSledAgentEnumerator<'a> {
             while let Some(p) = paginator.next() {
                 let records_batch = self
                     .datastore
-                    .sled_list(&self.opctx, &p.current_pagparams())
+                    .sled_list(
+                        &self.opctx,
+                        &p.current_pagparams(),
+                        SledFilter::All,
```
Comment (jgallagher) [inline nexus/src/app/background/inventory_collection.rs:187]: No objection on this PR, but this might not be right in the limit. (Some discussion in chat after #5480 noted inventory collection timeouts trying to talk to expunged sleds.)

File: nexus/src/app/rack.rs [hunk 3]
```diff
@@ -737,7 +738,10 @@ impl super::Nexus {
         };
 
         debug!(self.log, "Listing sleds");
-        let sleds = self.db_datastore.sled_list(opctx, &pagparams).await?;
+        let sleds = self
+            .db_datastore
+            .sled_list(opctx, &pagparams, SledFilter::All)
```
Comment (jgallagher) [inline nexus/src/app/rack.rs:743]: Should this be `SledFilter::InService`? I think with `::All` we wouldn't allow re-initializing a previously-expunged sled (because we'd still see its baseboard here)

File: nexus/src/app/sled.rs [hunk 4]
```diff
@@ -115,7 +116,7 @@ impl super::Nexus {
         opctx: &OpContext,
         pagparams: &DataPageParams<'_, Uuid>,
     ) -> ListResultVec<db::model::Sled> {
-        self.db_datastore.sled_list(&opctx, pagparams).await
+        self.db_datastore.sled_list(&opctx, pagparams, SledFilter::All).await
```
Comment (jgallagher) [inline nexus/src/app/sled.rs:119]: I'm not sure where this is called, but from context I would have guessed this should be `::InService` (e.g., why would Nexus list expunged sleds?). Or maybe this method could take a filter as an argument?

**Review by jgallagher — APPROVED** [review]

File: nexus/src/app/rack.rs (hunk 3 above)
Comment (andrewjstone) [reply nexus/src/app/rack.rs:743]: I wasn't sure about this, but I'm pretty sure you are right. Good catch!

File: nexus/src/app/sled.rs (hunk 4 above)
Comment (andrewjstone) [reply nexus/src/app/sled.rs:119]: Hmm. I mainly was sticking with the existing functionality here, but I think you are correct. I'll change this.

File: nexus/src/app/background/inventory_collection.rs (hunk 2 above)
Comment (andrewjstone) [reply nexus/src/app/background/inventory_collection.rs:187]: Yeah, I think based on the level of discussion that should be left to a follow up.

File: nexus/reconfigurator/execution/src/omicron_zones.rs (hunk 1 above)
Comment (andrewjstone) [reply nexus/reconfigurator/execution/src/omicron_zones.rs]: I don't think it will be used that frequently, but I like the method better. Added in 8b07fa885bdf94ed2009e1bda4da5d34dd6b4c72

File: nexus/src/app/rack.rs (hunk 3 above)
Comment (andrewjstone) [reply nexus/src/app/rack.rs]: Fixed in 8b07fa885bdf94ed2009e1bda4da5d34dd6b4c72

File: nexus/src/app/sled.rs (hunk 4 above)
Comment (andrewjstone) [reply nexus/src/app/sled.rs]: Fixed in 8b07fa885bdf94ed2009e1bda4da5d34dd6b4c72
