### PR TITLE
[nexus] retry indefinitely in `siu_lock_instance()`

### LINKED ISSUE #10166: a well-timed sequence of a Nexus crash and transient db error can leave an instance locked by a failed update saga forever
@davepacheco points out to me that the code in the `instance_update` start saga's `siu_lock_instance()` , here:

https://github.com/oxidecomputer/omicron/blob/d7c3b00d743bcc9212b222a74ae27cc970b1ee2c/nexus/src/app/sagas/instance_update/start.rs#L111-L112

can fall victim to a particularly bad sequence of events that results in the saga unwinding while leaving the instance record locked.

Suppose that:

1. A Nexus starts executing this action, successfully locks the instance record, and then crashes _before_ marking the saga node as having completed.
2. Subsequently, a new Nexus resumes executing the saga and runs this action again. It hits a query failure trying to lock the instance records, and unwinds.
3. Because the saga node has not _completed_, [its undo action, which releases the lock](https://github.com/oxidecomputer/omicron/blob/d7c3b00d743bcc9212b222a74ae27cc970b1ee2c/nexus/src/app/sagas/instance_update/start.rs#L116-L139), is not executed.

This leaves the instance record locked forever by the now-failed update saga. While these things happening in the correct sequence at the right times should hopefully be fairly unlikely (and we haven't observed this in real life as far as I know), this puts the instance in a state where Oxide support will have to manually wiggle the lock open to get it unstuck, which is quite sad and should be fixed.

Some potential solutions to this include:

1. Make `siu_lock_instance()` retry errors that _don't_ indicate the instance is already locked indefinitely. The infinite retry is probably fine to do, since if the database doesn't eventually reappear, we won't be able to unwind, either.
2. Have the action try indefinitely to _release_ the lock when encountering a db error, before it fails the saga. This would also fix the deadlock, but also "wastes" us having locked the instance, which is a bit sadder.
3. Dave points out that we might want to add a thing to `steno` to allow some actions to run their undo action when _that_ action fails. People often incorrectly think this is what steno already does, and there are cases (like this one) where it might be useful. But, it could also be a potential footgun. 🤷‍♀️

### PR DESCRIPTION
**Pull request by hawkw**
As described in #10166, a particularly unlucky sequence of events can
result a second execution of the instance-update saga's
`siu_lock_instance()` failing and unwinding while the instance is locked
by that saga, resulting in the instance record being locked forever (or,
until a human being manually picks the lock).

This occurs because that action [will currently fail][1] if the query
that tries to lock the instance record in the database fails with an
error that *does not* indicate that another saga has locked the
instance. However, the saga node may execute multiple times in the event
of a Nexus crash, so when this node executes, it is possible that the
saga is *already* holding the lock but the current execution of the node
is unaware of this.

Suppose that:

1. A Nexus starts executing this action, successfully locks the instance
   record, and then crashes *before* marking the saga node as having
   completed.
2. Subsequently, a new Nexus resumes executing the saga and runs this
   action again. It hits a query failure trying to lock the instance
   records, and unwinds.
3. Because the saga node has not *completed*, [its undo action, which
   releases the lock][2], is not executed. Therefore, the instance is
   still locked.

This commit fixes the bug by changing `siu_lock_instance()` so that
database errors that do not positively indicate that the lock is held by
another saga are retried forever, rather than failing the action.

In #10166, we discussed a few potential solutions to this:

1. Retrying the lock operation forever, as implemented here,
2. Attempting to *release* the lock forever if the lock operation fails
   with a database error,
3. Changing `steno` so that we can have `siu_lock_instance()`'s
   `siu_lock_instance_undo()` unwinding action execute if
   `siu_lock_instance()` fails (which is essentially (2) with extra
   steps, since `siu_lock_instance_undo()` will retry releasing the lock
   forever...)

Of these options, retrying the lock operation felt like the best
solution to me, since they all involve retrying *something* forever, and
retrying the lock rather than the unlock means that we will keep moving
forwards with the *current* saga in the face of a transient DB error,
rather than locking the instance, unwinding, releasing the lock, and
having to start a new saga before the state update can make progress ---
which just involves a lot more steps. This way, we don't "waste" the
already-acquired lock if a transient error occurs after a Nexus crash
results in the node executing twice. The retry loop is based on [the one
we already have in the `unwind_instance_lock()` function][3], and will
complain increasingly loudly if we have been retrying for a long time,
or if the database error appears to be a client rather than server
error.

Fixes #10166

[1]:
    https://github.com/oxidecomputer/omicron/blob/d7c3b00d743bcc9212b222a74ae27cc970b1ee2c/nexus/src/app/sagas/instance_update/start.rs#L111-L112
[2]:
    https://github.com/oxidecomputer/omicron/blob/d7c3b00d743bcc9212b222a74ae27cc970b1ee2c/nexus/src/app/sagas/instance_update/start.rs#L116-L139
[3]:
    https://github.com/oxidecomputer/omicron/blob/d7c3b00d743bcc9212b222a74ae27cc970b1ee2c/nexus/src/app/sagas/instance_update/mod.rs#L1469-L1534

### CODE REVIEW

File: nexus/src/app/sagas/instance_update/start.rs [hunk 1]
```diff
@@ -89,28 +90,146 @@ async fn siu_lock_instance(
...
+    //    action again. It hits a query failure trying to lock the instance
+    //    record, returns an `ActionFailed` error, and unwinds.
+    // 3. Because the saga node has not *completed*, our undo action
+    //    (`siu_instance_lock_undo()`), will *not* execute, so the instance
+    //    record remains locked, but this saga has now failed, so no one will
+    //    ever unlock the instance.
+    //
+    // See https://github.com/oxidecomputer/omicron/issues/10166 for more
+    // details.
+    //
```
Comment (davepacheco) [inline nexus/src/app/sagas/instance_update/start.rs]: It might be worth saying: "this action MUST continue retrying the lock operation forever in order to satisfy the distributed saga requirement that executing this action be idempotent.  It's possible that a execution of this action *did* get the lock but crashed before succeeding.  An example of how that could go badly is ..."

I feel like connecting it to the constraints that sagas expect makes this feel more structurally right to a reader and not just some obscure corner case we had to deal with.

Personally I'd generally strike the reference to the issue since the comment stands alone and someone can find the issue in the git history if they really want to know.

File: nexus/src/app/sagas/instance_update/start.rs [hunk 2]
```diff
@@ -89,28 +90,146 @@ async fn siu_lock_instance(
...
+                    Err(backoff::BackoffError::transient(e))
+                }
+            }
+        },
+        |error, call_count, total_duration| {
+            let http_error = dropshot::HttpError::from(error.clone());
+            if http_error.status_code.is_client_error() {
+                // A "client error" here indicates that we probably sent a query
+                // to the database that will never succeed. This should
+                // hopefully never happen, and probably indicates indicate a
```
Comment (davepacheco) [inline nexus/src/app/sagas/instance_update/start.rs]:
```suggestion
                // hopefully never happen, and probably indicates a
```

File: nexus/src/app/sagas/instance_update/start.rs [hunk 3]
```diff
@@ -89,28 +90,146 @@ async fn siu_lock_instance(
...
+                // programmer error in the lock operation. However, if we don't
+                // keep retrying, the instance may remain locked forever, so
+                // we shall just keep seeing if it will ever succeed.
+                error!(
+                    osagactx.log(),
+                    "instance update: client error while trying to lock \
+                     instance (likely requires operator intervention), \
```
Comment (davepacheco) [inline nexus/src/app/sagas/instance_update/start.rs]:
```suggestion
                     instance (likely requires support intervention), \
```

**Review by davepacheco — APPROVED** [review]

File: nexus/src/app/sagas/instance_update/start.rs (hunk 1 above)
Comment (hawkw) [reply nexus/src/app/sagas/instance_update/start.rs]: Good suggestions, updated in https://github.com/oxidecomputer/omicron/pull/10177/commits/5c78acc4fb213ff568623a0f179ce622d2b514db
