### PR TITLE
Self assembling zones should set their own MTU

### LINKED ISSUE #3512: Sled-agent crashed after hitting `ipadm: set-ifprop: mtu: Interface does not exist`
Here is the relevant portion of the sled-agent log file:
```
21:38:19.879Z INFO SledAgent (InstanceManager): Publishing instance state update to Nexus
    instance_id = c59ec866-fb95-4267-b976-9de840a73157
    state = InstanceRuntimeState { run_state: Failed, sled_id: 80395ead-2a26-4718-9919-cda27cad128f, propolis_id: 7931d3fb-5a0f-4e8a-83ed-554b72a05750, dst
_propolis_id: None, propolis_addr: Some([fd00:1122:3344:102::22]:12400), migration_id: None, propolis_gen: Generation(1), ncpus: InstanceCpuCount(8), memor
y: ByteCount(17179869184), hostname: "vm-8c-16m", gen: Generation(3), time_updated: 2023-07-06T21:38:19.879282812Z }
21:38:19.935Z INFO SledAgent (dropshot (SledAgent)): request completed
    error_message_external = Internal Server Error
    error_message_internal = Zone booted, but running a command experienced an error: Error running command in zone 'oxz_propolis-server_7931d3fb-5a0f-4e8a
-83ed-554b72a05750': Command [/usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv6 oxControlInstance0] executed and failed with status: exit status: 1  stdout
: \n  stderr: ipadm: set-ifprop: mtu: Interface does not exist
    local_addr = [fd00:1122:3344:102::1]:12345
    method = PUT
    remote_addr = [fd00:1122:3344:102::3]:33463
    req_id = fa4defff-9059-4b36-ab2d-a0746a7d92db
    response_code = 500
    uri = /instances/c59ec866-fb95-4267-b976-9de840a73157/state
21:38:20.030Z INFO SledAgent (dropshot (SledAgent)): accepted connection
    local_addr = [fd00:1122:3344:102::1]:12345
    remote_addr = [fd00:1122:3344:102::3]:47155
21:38:20.030Z WARN SledAgent (InstanceManager): Halting and removing zone: oxz_propolis-server_7931d3fb-5a0f-4e8a-83ed-554b72a05750
    instance_id = c59ec866-fb95-4267-b976-9de840a73157
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: AdmError { op: Uninstall, zone: "oxz_propolis-server_7931d3fb-5a0f-
4e8a-83ed-554b72a05750", err: CommandOutput(CommandOutputError("exit code 1\nstdout:\n\nstderr:\nzoneadm: zone 'oxz_propolis-server_7931d3fb-5a0f-4e8a-83ed
-554b72a05750': uninstall operation is invalid for shutting_down zones.")) }', sled-agent/src/instance.rs:533:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The complete log file can be found at: catacomb.eng.oxide.computer:/data/staff/dogfood/jul-6/sled-agent-gc17.log

### PR DESCRIPTION
**Pull request by jmpesp**
Bump crucible rev to pick up:

- Self assembling zones must set their own MTU
- fix build break caused by merging oxidecomputer/crucible#801
- Issue extent flushes in parallel
- Add Logger Option to Volume construct method
- Update Rust crate libc to 0.2.147
- Update Rust crate percent-encoding to 2.3
- Retry jobs until they succeed
- Reorder select arms so pings can't be starved out
- Treat a skipped IO like an error IO for ACK results.
- Retry pantry requests
- Remove panics and asserts in dummy tests
- Update Rust crate csv to 1.2.2
- Update Rust crate reedline to 0.21.0
- Set open file resource limit to the max
- Update Rust crate ringbuffer to 0.14
- DTrace meet cmon
- Widen assert values to u128 to deal with u64::MAX
- Change size_to_validate from usize to u64
- Turn on live-repair test in CI
- Increase flush_timeout for some tests, collect cores
- Update to latest dropshot

Bump propolis rev to pick up:

- Self assembling zones must set their own MTU
- Bump crucible rev to latest
- Make the propolis zone self-assembling
- Flesh out more PIIX3-PM to suppress log gripes
- Bump crucible rev to latest
- Restructure PM-timer under PIIX3 device
- Fix inventory handling for nested child entities
- Centralize vmm-data interface into bhyve_api
- Clean up PCI device classes
- Update openssl dep to 0.10.55
- Allow propolis-standalone to use VMM reservoir
- only allow one request to reboot to be enqueued at a time

Nexus is currently setting the MTU inside self-assembling zones, but this goes against the idea that self-assembling zones perform their own configuration. Remove the code in `RunningZone::boot` that performs commands on self-assembling zones, and set the MTU of $DATALINK in the Clickhouse and CockroachDB method scripts.

Fixes #3512

### CODE REVIEW

File: illumos-utils/src/running_zone.rs [hunk 1]
```diff
@@ -372,78 +372,60 @@ impl RunningZone {
...
 
-        // Pull the zone ID.
+        // If the zone is self-assembling, then SMF service(s) inside the zone
+        // will be creating the listen address for the zone's service(s),
+        // setting the appropriate ifprop MTU, and so on. The idea behind
+        // self-assembling zones is that once they boot there should be *no*
+        // zlogin required.
+
+        // Use the zone ID in order to check if /var/svc/profile/site.xml
+        // exists.
```
Comment (smklein) [inline illumos-utils/src/running_zone.rs:382]: Thanks for making this explicit!

**Review by smklein — APPROVED** [review]
Thanks for doing this. I know it's a pain to update all these repos, but I really appreciate this, and I think we'll appreciate going in this direction more-and-more when we start implementing reconciliation after sled agent reboot.

File: smf/cockroachdb/method_script.sh [hunk 2]
```diff
@@ -17,6 +17,13 @@ if [[ $DATALINK == unknown ]] || [[ $GATEWAY == unknown ]]; then
     exit "$SMF_EXIT_ERR_CONFIG"
 fi
 
+# TODO remove when https://github.com/oxidecomputer/stlouis/issues/435 is addressed
+ipadm delete-if "$DATALINK" || true
+ipadm create-if -t "$DATALINK"
+
+ipadm set-ifprop -t -p mtu=9000 -m ipv4 "$DATALINK"
+ipadm set-ifprop -t -p mtu=9000 -m ipv6 "$DATALINK"
```
Comment (luqmana) [inline smf/cockroachdb/method_script.sh:25]: Was there a bug or something for why we needed to explicitly set the ip-level MTU instead of just relying on the link's MTU?

Comment (jmpesp) [reply smf/cockroachdb/method_script.sh:25]: It was more an assurance thing
