### PR TITLE
Single node clickhouse init

### LINKED ISSUE #6826: Need to initialize a fresh ClickHouse database without restarting Oximeter
With #6800, we can now expunge a running ClickHouse zone and the reconfigurator will replace it. With #6745, qorb can automatically look up and connect to that new zone, but insertions still fail because the `oximeter` database does not yet exist:

```
21:19:19.250Z WARN oximeter (oximeter-agent): failed to insert some results into metric DB: Error interacting with telemetry database: Query failed: Code: 81. DB::Exception: Database oximeter does not exist. (UNKNOWN_DATABASE) (version 23.8.7.1)
```

I don't know if a client can initialize a non-existent database in ClickHouse. If it can, we may be able to solve this on the client side; if not, we'll need some server-side initialization scheme. See also [this comment](https://github.com/oxidecomputer/omicron/pull/4149#discussion_r1338926865), where this issue came up previously.

### PR DESCRIPTION
**Pull request by plotnick**
Depends on #6894, replaces #6878, fixes #6826 on the server side.

Adds a new Dropshot server, `clickhouse-admin-single`, analogous to `clickhouse-admin-keeper` and `clickhouse-admin-server` (which were split off from `clickhouse-admin` in #6837). Its sole purpose is to initialize the single-node ClickHouse database with the current Oximeter schema. We use a single in-memory lock (a `tokio::sync::Mutex`) to serialize initialization requests. Multi-node ClickHouse clusters will need something analogous as a follow-up.

~~Still needs testing. My `a4x2` cluster is currently being uncooperative, and so this has not been through a successful "spin-up, expunge ClickHouse, regenerate" cycle. Also missing unit tests.~~

Tested on `a4x2` by expunging the ClickHouse zone in a new blueprint, setting that as the target and verifying that the zone is expunged, regenerating a new blueprint, setting that as the target and ensuring that the new zone is instantiated, and ensuring that Oximeter correctly stops inserting while the db is unavailable, but automatically resumes insertions once the new one is up & initialized.

~~The failing test `cockroachdb::test::test_ensure_preserve_downgrade_option` is caused by the fact that we don't currently spin up the new `clickhouse-admin-single` server in a test environment, so when a blueprint containing a ClickHouse zone is executed, the initialization step fails.~~ Thanks to @andrewjstone for fixing the last failing test (#7059).

### CODE REVIEW

File: nexus/reconfigurator/execution/src/clickhouse.rs [hunk 1]
```diff
@@ -152,6 +153,36 @@ pub(crate) async fn deploy_nodes(
...
+        let admin_addr = SocketAddr::V6(SocketAddrV6::new(
+            zone.underlay_address,
+            CLICKHOUSE_ADMIN_PORT,
+            0,
+            0,
+        ));
+        let admin_url = format!("http://{admin_addr}");
+        let log = opctx.log.new(slog::o!("admin_url" => admin_url.clone()));
+        let client = ClickhouseSingleClient::new(&admin_url, log.clone());
+        client.init_db().await.map(|_| ()).map_err(|e| {
```
Comment (plotnick) [inline nexus/reconfigurator/execution/src/clickhouse.rs:176]: It's unclear to me if this is the right place to try to do this initialization, since we'll presumably have just spun up the server. It might be better to wait until the single-node server appears in an inventory collection, like the multi-node server does. OTOH, it shouldn't take long to start an uninitialized database, so we might be able to get away with a small retry loop and some longish timeouts, which seems significantly simpler.

Comment (bnaecker) [reply nexus/reconfigurator/execution/src/clickhouse.rs:176]: You could `ping` the server and wait for that to succeed before trying this. The `init_db()` call also returns an error indicating the server isn't available, so you might be able to just retry this call itself. The SQL it applies is idempotent.

File: clickhouse-admin/src/http_entrypoints.rs [hunk 2]
```diff
@@ -110,3 +119,49 @@ impl ClickhouseAdminKeeperApi for ClickhouseAdminKeeperImpl {
...
+    type Context = Arc<SingleServerContext>;
+
+    async fn init_db(
+        rqctx: RequestContext<Self::Context>,
+    ) -> Result<HttpResponseUpdatedNoContent, HttpError> {
+        let log = &rqctx.log;
+        let ctx = rqctx.context();
+        let initialized = ctx.db_initialized();
+        let mut initialized = initialized.lock().await;
+        if !*initialized {
```
Comment (andrewjstone) [inline clickhouse-admin/src/http_entrypoints.rs:135]: What happens if we want to update the schema? Is there any harm in just letting initialization run through every time? It's supposed to be idempotent, right?

CC @bnaecker

**Review by andrewjstone — APPROVED** [review]
Looks great!

File: nexus/reconfigurator/execution/src/clickhouse.rs [hunk 3]
```diff
@@ -160,6 +161,38 @@ pub(crate) async fn deploy_nodes(
...
+        let admin_addr = SocketAddr::V6(SocketAddrV6::new(
+            zone.underlay_ip(),
+            CLICKHOUSE_ADMIN_PORT,
+            0,
+            0,
+        ));
+        let admin_url = format!("http://{admin_addr}");
+        let log = opctx.log.new(slog::o!("admin_url" => admin_url.clone()));
+        let client = ClickhouseSingleClient::new(&admin_url, log.clone());
+        if let Err(e) = client.init_db().await {
```
Comment (andrewjstone) [inline nexus/reconfigurator/execution/src/clickhouse.rs:184]: Ok, so I know that I made this change. But afterwards I've been messing with other execution steps and think we should instead return the error here and then convert it into a warning in the execution step. The benefit of doing it this way is that it shows up in the `background-task` as a warning in OMDB.  I'll put a comment next to where this should go.

File: nexus/reconfigurator/execution/src/lib.rs [hunk 4]
```diff
@@ -549,6 +555,27 @@ fn register_deploy_clickhouse_cluster_nodes_step<'a>(
...
+    registrar
+        .new_step(
+            ExecutionStepId::Ensure,
+            "Deploy single-node clickhouse cluster",
+            move |_cx| async move {
+                clickhouse::deploy_single_node(
+                    &opctx,
+                    &blueprint.blueprint_zones,
+                )
+                .await?;
```
Comment (andrewjstone) [inline nexus/reconfigurator/execution/src/lib.rs:572]: We should put the warning here. Instead of using `?` we should do the following:

```rust
  if let Err(e) = clickhouse::deploy_single_node(
                    &opctx,
                    &blueprint.blueprint_zones,
                )
                .await {
                       return StepWarning::new((), e.to_string()).into();
                }
```

File: clickhouse-admin/src/http_entrypoints.rs (hunk 2 above)
Comment (bnaecker) [reply clickhouse-admin/src/http_entrypoints.rs:135]: > It's supposed to be idempotent, right?

Yeah, schema updates are idempotent, and also a no-op if the version in the database is at least as high as that on the client side.

Comment (plotnick) [reply clickhouse-admin/src/http_entrypoints.rs:135]: We talked a little about this in an update meeting a few weeks ago; my understanding was that letting initialization run each time and therefore update the schema would represent a change to our current policy of _not_ performing automatic schema updates. This was one of the reasons for preferring a server-side approach rather than initializing the database on every client connection. I'm fine either way; it's a trivial change to the code, but a potentially less trivial change in policy.

File: clickhouse-admin/api/src/lib.rs [hunk 5]
```diff
@@ -116,3 +117,24 @@ pub trait ClickhouseAdminServerApi {
         rqctx: RequestContext<Self::Context>,
     ) -> Result<HttpResponseOk<Vec<DistributedDdlQueue>>, HttpError>;
 }
+
+/// API interface for our clickhouse-admin-single server
+///
+/// The single-node server is distinct from the both the multi-node servers
+/// and its keepers. The sole purpose of this API is to serialize database
+/// initialization requests from reconfigurator execution. Multi-node clusters
+/// must eventually implement a similar interface, but the implementation will
```
[the remark this answers is not in the document]
Comment (plotnick) [reply clickhouse-admin/api/src/lib.rs]: Good call, fixed in 2ddcbd96f.

File: nexus/reconfigurator/execution/src/clickhouse.rs (hunk 3 above)
Comment (plotnick) [reply nexus/reconfigurator/execution/src/clickhouse.rs]: Done in c6e98a516.

File: clickhouse-admin/src/http_entrypoints.rs (hunk 2 above)
Comment (andrewjstone) [reply clickhouse-admin/src/http_entrypoints.rs:135]: > We talked a little about this in an update meeting a few weeks ago; my understanding was that letting initialization run each time and therefore update the schema would represent a change to our current policy of _not_ performing automatic schema updates. This was one of the reasons for preferring a server-side approach rather than initializing the database on every client connection. I'm fine either way; it's a trivial change to the code, but a potentially less trivial change in policy.

Thanks for reminding me of that discussion Alex. However:

* Currently the schema version is being issued based on a constant in the code, so it won't be updated at all unless the code changes.
* If the admin server crashes or the sled is rebooted, the in-memory state will be lost and the schema will be re-initialized anyway.

I think what we'll want to do in a follow up is to make schema updates part of the planner, and then only execute them when the plan changes.

Comment (andrewjstone) [reply clickhouse-admin/src/http_entrypoints.rs:135]: Oh, and the API call should then take the schema version to update from the executor.

File: clickhouse-admin/src/lib.rs [hunk 6]
```diff
@@ -115,3 +114,38 @@ pub async fn start_keeper_admin_server(
...
+/// Start the dropshot server for `clickhouse-admin-single` which
+/// manages a single-node ClickHouse database.
+pub async fn start_single_admin_server(
+    clickhouse_cli: ClickhouseCli,
+    server_config: Config,
+) -> Result<HttpServer<Arc<SingleServerContext>>, StartError> {
+    let (drain, registration) = slog_dtrace::with_drain(
+        server_config
+            .log
+            .to_logger("clickhouse-admin-keeper")
```
Comment (karencfv) [inline clickhouse-admin/src/lib.rs:127]:
```suggestion
            .to_logger("clickhouse-admin-single")
```

File: clickhouse-admin/src/bin/clickhouse-admin-single.rs [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+enum Args {
+    /// Start the single-node ClickHouse admin server
+    Run {
+        /// Address on which this server should run
+        #[clap(long, short = 'a', action)]
+        http_address: SocketAddrV6,
+
+        /// Path to the server configuration file
+        #[clap(long, short, action)]
+        config: Utf8PathBuf,
```
Comment (karencfv) [inline clickhouse-admin/src/bin/clickhouse-admin-single.rs:29]: I think you can remove this flag. We won't be generating the config file with clickward

File: smf/clickhouse-admin-single/manifest.xml [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+  <service_fmri value='svc:/milestone/multi-user:default' />
+  </dependency>
+
+  <dependency name='zone_network_setup' grouping='require_all' restart_on='none'
+    type='service'>
+  <service_fmri value='svc:/oxide/zone-network-setup:default' />
+  </dependency>
+
+  <exec_method type='method' name='start'
+    exec='ctrun -l child -o noorphan,regent /opt/oxide/omicron-clickhouse-admin/bin/clickhouse-admin-single run --config /var/svc/manifest/site/clickhouse-admin-single/config.toml --http-address %{config/http_address} --listen-address %{config/ch_address} --binary-path %{config/ch_binary}  &amp;'
```
Comment (karencfv) [inline smf/clickhouse-admin-single/manifest.xml:20]: Same here. I think we can remove `--config /var/svc/manifest/site/clickhouse-admin-single/config.toml`

File: clickhouse-admin/src/http_entrypoints.rs (hunk 2 above)
Comment (plotnick) [reply clickhouse-admin/src/http_entrypoints.rs]: Ok, those are excellent points; you've convinced me. 012b6a1d6 does unconditional (but still serialized) database initialization. We'll have to take explicit versioning as a follow-up.

File: clickhouse-admin/src/lib.rs (hunk 6 above)
Comment (plotnick) [reply clickhouse-admin/src/lib.rs]: Nice catch, thanks!

File: clickhouse-admin/src/bin/clickhouse-admin-single.rs (hunk 7 above)
Comment (karencfv) [reply clickhouse-admin/src/bin/clickhouse-admin-single.rs:29]: aha! you're right nvm
