### PR TITLE
Fix sled-agent periodic polling for hardware changes

### LINKED ISSUE #9975: sled-agent is not monitoring for hardware changes
We discovered today while attempting to test RSS with a disk manually disconnected that sled-agent only polled devinfo once on startup; it should be polling every 5 seconds in this infinite loop: https://github.com/oxidecomputer/omicron/blob/145b2fa5656deb0a596ab54418b248fed069fe39/sled-hardware/src/illumos/mod.rs#L811-L828

This is a regression in R18 accidentally introduced by #9465, which changed `hardware_tracking_task` from a normal function to an async function:

```diff
- fn hardware_tracking_task(
+ async fn hardware_tracking_task(
```

This is not an asynchronous function, and the call site did not change: https://github.com/oxidecomputer/omicron/blob/145b2fa5656deb0a596ab54418b248fed069fe39/sled-hardware/src/illumos/mod.rs#L926-L928

When `hardware_tracking_task` was a synchronous function, this spawned a thread that called `hardware_tracking_task()` and went into the expected infinite loop. The call to `std::thread::spawn()` itself returned a `JoinHandle<()>`.

Changing `hardware_tracking_task` to an async function changed this behavior significantly: now this spawns a thread which calls `hardware_tracking_task()`, which returns a `Future` that, if polled, would go into the infinite (blocking) loop. However, it is never polled, so instead, the thread immediately drops the future and exits. The return value of the `std::thread::spawn()` is a `JoinHandle<impl Future<Output = ()>>` (for whatever unnamable type the compiler gives the future returned by `hardware_tracking_task()`.

Normally `clippy` warns about futures that aren't `.await`'d, but I _think_ that's not happening here because the future gets stashed into a `JoinHandle`, which clippy does _not_ warn about: it's common to discard `JoinHandle`s.

I'm not sure what the full ramifications are or whether this warrants a backport and a cut of an 18.2 release. Definite side effects are that sled-agent won't notice a disk being added at runtime (which isn't supported yet anyway) or a disk going away at runtime (which _should_ be supported - that's the exact thing we were originally trying to test). I'm more concerned that this could cause us to fail to start the switch zone. With this bug in place, `sled-agent` polls devinfo exactly once, right after it starts up. If the Tofino is not yet present but becomes present at some point after that, our lack of polling means we won't see it and therefore won't start the switch zone when it appears. That's a race between the OS and sled-agent, and I don't know whether it can really happen in practice (e.g., maybe other SMF services sled-agent depends on already ensure the Tofino is present, if it is?). @leftwo and @labbott both anecdotally report that they've had issues in the past month-ish on racklettes where an apparently-healthy system had a scrimlet missing a switch zone, but we'd need to catch it in action to confirm whether this issue is the root cause.

(Big thanks to @davepacheco whose on-the-fly dtrace'ing narrowed this problem down very quickly.)

### PR DESCRIPTION
**Pull request by jgallagher**
Closes #9975.

### CODE REVIEW

File: sled-hardware/src/illumos/mod.rs [hunk 1]
```diff
@@ -918,13 +918,15 @@ impl HardwareManager {
...
+        std::thread::spawn(move || {
+            monitor_tofino(log2, tx2);
+        });
 
         let log2 = log.clone();
         let inner2 = inner.clone();
         let tx2 = tx.clone();
         std::thread::spawn(move || {
-            hardware_tracking_task(log2, inner2, nonsled_observed_disks, tx2)
+            hardware_tracking_task(log2, inner2, nonsled_observed_disks, tx2);
```
Comment (jgallagher) [inline sled-hardware/src/illumos/mod.rs:929]: With the `;` here, if the function is `async` we get warnings about an unpolled future.
