### PR TITLE
[bootstore] Do not compare ephemeral ports

### LINKED ISSUE #3675: Boostore test flake: `schemes::v0::peer::tests::network_config`
Seen on main:

https://buildomat.eng.oxide.computer/wg/0/details/01H5F510PSMHWHCP1B11ZW3A27/GrsCKW6Cvb7h89UFyYjCsG8DONwcnfyrHmio1PYwmqEgoia4/01H5F51MNYK21HXRV2M0DPJJBA#S5685

```
5685	2023-07-16T11:26:54.939Z	test schemes::v0::peer::tests::network_config ... FAILED
5686	2023-07-16T11:26:54.961Z	
5687	2023-07-16T11:26:54.985Z	failures:
5688	2023-07-16T11:26:55.004Z	
5689	2023-07-16T11:26:55.227Z	---- schemes::v0::peer::tests::network_config stdout ----
5690	2023-07-16T11:26:55.246Z	thread 'schemes::v0::peer::tests::network_config' panicked at 'Network config not replicated', bootstore/src/schemes/v0/peer.rs:1267:21
5691	2023-07-16T11:26:55.253Z	stack backtrace:
5692	2023-07-16T11:26:55.257Z	   0: rust_begin_unwind
5693	2023-07-16T11:26:55.265Z	             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
5694	2023-07-16T11:26:55.271Z	   1: core::panicking::panic_fmt
5695	2023-07-16T11:26:55.273Z	             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
5696	2023-07-16T11:26:55.276Z	   2: bootstore::schemes::v0::peer::tests::network_config::{{closure}}
5697	2023-07-16T11:26:55.278Z	             at ./src/schemes/v0/peer.rs:1267:21
5698	2023-07-16T11:26:55.283Z	   3: <core::pin::Pin<P> as core::future::future::Future>::poll
5699	2023-07-16T11:26:55.291Z	             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:125:9
5700	2023-07-16T11:26:55.301Z	   4: <core::pin::Pin<P> as core::future::future::Future>::poll
5701	2023-07-16T11:26:55.305Z	             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:125:9
5702	2023-07-16T11:26:55.309Z	   5: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
5703	2023-07-16T11:26:55.312Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:651:57
5704	2023-07-16T11:26:55.315Z	   6: tokio::runtime::coop::with_budget
5705	2023-07-16T11:26:55.318Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
5706	2023-07-16T11:26:55.321Z	   7: tokio::runtime::coop::budget
5707	2023-07-16T11:26:55.325Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
5708	2023-07-16T11:26:55.330Z	   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
5709	2023-07-16T11:26:55.333Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:651:25
5710	2023-07-16T11:26:55.338Z	   9: tokio::runtime::scheduler::current_thread::Context::enter
5711	2023-07-16T11:26:55.344Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:410:19
5712	2023-07-16T11:26:55.349Z	  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
5713	2023-07-16T11:26:55.352Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:650:36
5714	2023-07-16T11:26:55.355Z	  11: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
5715	2023-07-16T11:26:55.366Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:68
5716	2023-07-16T11:26:55.378Z	  12: tokio::runtime::context::scoped::Scoped<T>::set
5717	2023-07-16T11:26:55.389Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/scoped.rs:40:9
5718	2023-07-16T11:26:55.397Z	  13: tokio::runtime::context::set_scheduler::{{closure}}
5719	2023-07-16T11:26:55.407Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:26
5720	2023-07-16T11:26:55.414Z	  14: std::thread::local::LocalKey<T>::try_with
5721	2023-07-16T11:26:55.428Z	             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
5722	2023-07-16T11:26:55.431Z	  15: std::thread::local::LocalKey<T>::with
5723	2023-07-16T11:26:55.435Z	             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
5724	2023-07-16T11:26:55.438Z	  16: tokio::runtime::context::set_scheduler
5725	2023-07-16T11:26:55.441Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:9
5726	2023-07-16T11:26:55.446Z	  17: tokio::runtime::scheduler::current_thread::CoreGuard::enter
5727	2023-07-16T11:26:55.451Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:27
5728	2023-07-16T11:26:55.456Z	  18: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
5729	2023-07-16T11:26:55.461Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:638:19
5730	2023-07-16T11:26:55.466Z	  19: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
5731	2023-07-16T11:26:55.469Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:175:28
5732	2023-07-16T11:26:55.472Z	  20: tokio::runtime::context::runtime::enter_runtime
5733	2023-07-16T11:26:55.475Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
5734	2023-07-16T11:26:55.480Z	  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
5735	2023-07-16T11:26:55.485Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:167:9
5736	2023-07-16T11:26:55.489Z	  22: tokio::runtime::runtime::Runtime::block_on
5737	2023-07-16T11:26:55.494Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:311:47
5738	2023-07-16T11:26:55.500Z	  23: bootstore::schemes::v0::peer::tests::network_config
5739	2023-07-16T11:26:55.505Z	             at ./src/schemes/v0/peer.rs:1379:9
5740	2023-07-16T11:26:55.509Z	  24: bootstore::schemes::v0::peer::tests::network_config::{{closure}}
5741	2023-07-16T11:26:55.513Z	             at ./src/schemes/v0/peer.rs:1216:31
5742	2023-07-16T11:26:55.515Z	  25: core::ops::function::FnOnce::call_once
5743	2023-07-16T11:26:55.518Z	             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
5744	2023-07-16T11:26:55.520Z	  26: core::ops::function::FnOnce::call_once
5745	2023-07-16T11:26:55.522Z	             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
5746	2023-07-16T11:26:55.525Z	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
5747	2023-07-16T11:26:55.527Z	
5748	2023-07-16T11:26:55.529Z	
5749	2023-07-16T11:26:55.532Z	failures:
5750	2023-07-16T11:26:55.538Z	    schemes::v0::peer::tests::network_config
5751	2023-07-16T11:26:55.541Z	error: test failed, to rerun pass `-p bootstore --lib`
5752	2023-07-16T11:26:55.543Z	
5753	2023-07-16T11:26:55.546Z	     Running `/work/oxidecomputer/omicron/target/debug/deps/v0_fsm_proptest_learner-0a26b1dac927e830`
5754	2023-07-16T11:26:55.548Z	test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.37s
5755	2023-07-16T11:26:55.551Z	
```

### PR DESCRIPTION
**Pull request by andrewjstone**
Don't compare ephemeral ports for peer connection invariant violation bugs. Wait until the handshake completes and the canonical (listening) port is received in the `Identify` message.

Fixes #3675

### CODE REVIEW

File: bootstore/src/schemes/v0/peer_networking.rs [hunk 1]
```diff
@@ -512,6 +512,38 @@ pub async fn spawn_accepted_connection_management_task(
             }
         };
 
+        // Connections are only supposed to come from peers with `ip:port`
+        // values that sort higher than the peer they are connecting to. We
+        // don't know the canonical port of the connecting peer until the
+        // handshake completes though as the connecting port is ephemeral.
+        // Therefore we do the check here.
+        //
+        // Note: We don't do the check in `perform_hanshake` because that method
```
Comment (andrewjstone) [inline bootstore/src/schemes/v0/peer_networking.rs:521]: damnit. typo

**Review by smklein — APPROVED** [review]
Thanks for the quick fix!

**Comment by andrewjstone** [comment]
> Thanks for the quick fix!

Thanks for reproducing and isolating the problem!
