### PR TITLE
Reconfigurator: Don't fail if we try to soft delete external networking rows that never existed

### LINKED ISSUE #10025: Reconfigurator: race between planner and executor during disk expungement led to executor perpetually failing
On a customer system today, while performing a sled expungement, the `blueprint_executor` task started failing on every invocation, reporting this error:

```
execution:        enabled
status:           failed at: Ensure external networking resources (step 1/15)
error:            step failed: Ensure external networking resources
  caused by:      Internal Error: unexpected database error: Record not found
```

The "ensuring external networking resources" is the step where we attempt to ensure that the external IP and service NIC rows in the non-reconfigurator CRDB tables are consistent with the blueprint. (We treat them as a form of rendezvous table, although they long predate that term and idea.) This is a two-step process with two substeps each:

1. For every expunged zone with an external IP:
    1. Soft delete its external IP by updating the relevant row (unless it's already been soft deleted, in which case do nothing)
    2. Soft delete its service NIC by updating the relevant row (again unless it's already been soft deleted)
2. For every in-service zone with an external IP:
    1. Ensure its external IP exists, creating it if necessary
    2. Ensure its service NIC exists, creating it if necessary

The datastore process for this is [here](https://github.com/oxidecomputer/omicron/blob/3d2d0c17002ef6291e1b4f88755ac7f7ba90dbd1/nexus/db-queries/src/db/datastore/deployment.rs#L2109-L2143).

The errors we were seeing were from attempting to soft delete external IPs. We did see these logs for some zones: https://github.com/oxidecomputer/omicron/blob/3d2d0c17002ef6291e1b4f88755ac7f7ba90dbd1/nexus/db-queries/src/db/datastore/deployment/external_networking.rs#L178-L182

but never made it to the point of ensuring new records existed, strongly implying we were failing to soft delete some particular zone's records.

Support grabbed both the Nexus logs and a Reconfigurator state file. The logs showed the zone ID of the last successful soft deletion (repeated on each iteration of the executor task). The loops here are ordered by sled ID first, zone ID second, so given the state file and the last successful soft delete, we were able to find both the zone ID of the zone we were presumably failing on and its associated external IP / service NIC details. We manually confirmed that the rows the blueprint claimed should exist did not:

```
> select * from external_ip where id = '$ZONE_EXTERNAL_IP_ID';
NO ROWS

> select * from service_network_interface where id = '$ZONE_NIC_ID';
NO ROWS
```

The planner/executor believe this should be impossible, hence the executor getting stuck. (This is one of the few executor steps that stops the entire task, under the assumption that if we can't ensure the networking tables are correct it may not be safe to start up zones; e.g. could we have multiple zones believing they're associated with the same external IP?)

Looking at the Reconfigurator state file, I believe the sequence that got us here was:

1. Before expunging the sled, we expunged each of that sled's disks, one at a time. (This is the documented procedure, and exists as a workaround for #8520.)
2. The 9th disk being expunged hosted a Nexus.
3. The planner run after expunging the 9th disk expunged the Nexus on that disk, then placed a new Nexus. It put it on the next disk that was going to be expunged. (At this time, both the disk and sled were still in-service, so this was a perfectly valid, albeit very unfortunate, placement.)
4. The 10th disk was expunged.
5. The planner run after expunging the 10th disk expunged the Nexus on that disk, which the planner run in step 3 had just created. It placed a new Nexus on another sled.

However, the executor _did not run_ in between the blueprint from step 3 being made the target and the blueprint from step 5 being made the target. Therefore, it never ensured the external IP / service NIC rows for the short-lived Nexus were created. Therefore, all subsequent executor runs from that point on are doomed: they're stuck trying to soft-delete rows that don't exist, because the only blueprint that would have caused them to be created was never executed.

### PR DESCRIPTION
**Pull request by jgallagher**
This fixes #10025; see it for much more background information. I'll deploy this branch to a racklette and repeat the reproduction steps and will report back here before merging. (I also plan to attempt to write some live tests that would catch this, but that will take a little longer.)

The queries we use to delete external IPs and vNICs used to return a `Result<bool, _>`, where `Ok(true)` meant "we did soft delete", `Ok(false)` meant "row exists but is already soft deleted", and "row not found at all" was an error. The lowest-level queries now return a `Result<SoftDeleteResult, _>`, where `SoftDeleteResult` can represent all three variants (did soft delete, was already soft deleted, row not found). It has a helper to squash itself back into a `Result<bool, _>` and treat row not found as an error, which is used by the higher-level methods to delete instance resources. Reconfigurator uses the lower-level methods directly, and chooses not to fail on "row not found".

### CODE REVIEW

File: nexus/db-queries/src/db/queries/network_interface.rs [hunk 1]
```diff
@@ -1729,16 +1659,16 @@ impl DeleteQuery {
...
-            (Some(_), None) => Ok(false),
+            (Some(_), None) => Ok(SoftDeleteResult::AlreadySoftDeleted),
             (None, Some(deleted)) => {
                 panic!(
                     "internal query error: \
                      deleted nonexisted interface {deleted}"
                 )
             }
-            (None, None) => Err(DieselError::NotFound),
+            (None, None) => Ok(SoftDeleteResult::NotFound),
```
Comment (jgallagher) [inline nexus/db-queries/src/db/queries/network_interface.rs:1671]: This branch is the one whose behavior we wanted to change, and it already existed but could never be taken given the way the query was written. The final clause of the CTE was:

```sql
SELECT
  found_interface.id, updated.id
FROM
  found_interface LEFT JOIN updated ON found_interface.id = updated.id
```

which would _not_ return `(NULL, NULL)` if the row wasn't found - it would return _no rows at all_, which means we'd bail out with a `DieselError::NotFound` up on line 1654 above and never get to this branch.

The edits below change this final clause to:

```sql
SELECT
  found_interface.id, updated.id
FROM
  interface
  LEFT JOIN found_interface ON interface.id = found_interface.id
  LEFT JOIN updated ON found_interface.id = updated.id
```

where `interface` is the existing query gadget to do some error checks; I gave its output row the name `id` so we could do easy left joins. We'll now return `NULL, NULL` if the row isn't found, which allows us to make it to this branch in the `match`.

File: nexus/db-queries/src/db/datastore/external_ip.rs [hunk 2]
```diff
@@ -1454,6 +1468,92 @@ mod tests {
...
+            .deallocate_external_ip_on_connection(&conn, bogus_id)
+            .await
+            .expect("bogus delete did nothing");
+        assert_eq!(
+            bogus_delete_result,
+            SoftDeleteResult::NotFound,
+            "bogus delete should not have found a matching row"
+        );
+
+        // Deallocate the first IP.
```
Comment (smklein) [inline nexus/db-queries/src/db/datastore/external_ip.rs]: This doesn't seem like it's happening here?

File: nexus/db-queries/src/db/queries/network_interface.rs [hunk 3]
```diff
@@ -1789,12 +1719,14 @@ impl QueryFragment<Pg> for DeleteQuery {
         out.push_sql(" AND ");
         out.push_identifier(dsl::time_deleted::NAME)?;
         out.push_sql(" IS NULL) <= 1, ");
-        out.push_bind_param::<sql_types::Text, String>(&self.parent_id_str)?;
+        out.push_bind_param::<sql_types::Text, String>(&self.interface_id_str)?;
```
Comment (smklein) [inline nexus/db-queries/src/db/queries/network_interface.rs:1722]: Was this a pre-existing bug? This is swapping the "parent_id" with the "interface_id" here?

File: nexus/db-queries/src/db/datastore/deployment/external_networking.rs [hunk 4]
```diff
@@ -175,10 +186,28 @@ impl DataStore {
...
+                }
+                SoftDeleteResult::NotFound => {
+                    // Attempting to delete a nonexistent interface should
+                    // succeed. This is unusual but not illegal. For example, we
+                    // could have a target blueprint that adds a service zone
+                    // with a NIC followed by a child target blueprint that
+                    // expunges that zone. If we never executed the first
+                    // blueprint, executing the second will attempt to delete a
+                    // NIC that was never created, and that should be fine.
+                    // (This happened in the field: omicron#10025.)
```
Comment (smklein) [inline nexus/db-queries/src/db/datastore/deployment/external_networking.rs:204]: (No action needed) I wanted to verify that we couldn't have a race condition where:

- Some slow Nexus is running the the "insert records" pathway
- A newer faster Nexus does this soft delete, sees nothing, moves on
- The old Nexus re-inserts these records

We guard against this because of a check in `blueprint_ensure_external_networking_resources_impl`, where we (in a transaction) verify the "supplied blueprint is still the current target".

This was load-bearing before, and remains load-bearing now!

File: nexus/db-queries/src/db/datastore/external_ip.rs (hunk 2 above)
Comment (jgallagher) [reply nexus/db-queries/src/db/datastore/external_ip.rs]: Whoops, copy-paste error. Thanks.

File: nexus/db-queries/src/db/queries/network_interface.rs (hunk 3 above)
Comment (jgallagher) [reply nexus/db-queries/src/db/queries/network_interface.rs:1722]: Ah, no, this wasn't a bug. Previously: the exact value here did not matter, except that it needed to be any valid UUID - this was only used as an error checking gadget. Now, we need it to specifically be the ID of the interface we're trying to delete, because we use it in the JOINs in the final SELECT clause.

File: nexus/db-queries/src/db/datastore/deployment/external_networking.rs (hunk 4 above)
Comment (jgallagher) [reply nexus/db-queries/src/db/datastore/deployment/external_networking.rs:204]: Yeah I would love to rework this to make it not necessary (e.g., with a more well-thought-out rendezvous table, probably with a generation number covering "the full external networking config of a blueprint"). But for now we keep the more strict check.

File: nexus/db-queries/src/db/queries/network_interface.rs (hunk 3 above)
Comment (smklein) [reply nexus/db-queries/src/db/queries/network_interface.rs:1722]: got it. And because it's a bind parameter flowing through a `CAST`, this basically just lets us re-use `interface.id` instead of re-passing the bind parameter later?

**Review by smklein — APPROVED** [review]

File: nexus/db-queries/src/db/queries/network_interface.rs (hunk 3 above)
Comment (jgallagher) [reply nexus/db-queries/src/db/queries/network_interface.rs:1722]: Yep, exactly. To pass it as another bind parameter later, I believe we'd have to introduce another subquery just for that; all the subqueries after this one (as written) return no rows at all if the interface ID doesn't exist, so there's nowhere to stick an extra bind parameter that will show up in the output.

**Comment by jgallagher** [comment]
Testing on london looks good. I repeated the reproduction steps from https://github.com/oxidecomputer/omicron/issues/10025#issuecomment-4041847071, and see both execution succeeding:

```
  last completed activation: iter 25, triggered by a dependent task completing
    started at 2026-03-16T19:37:18.472Z (0s ago) and ran for 467ms
    target blueprint: 2e1290e1-3829-42eb-a534-b215108c49f5
    execution:        enabled
    status:           completed (15 steps)
    error:            (none)
```

and the expected debug logs for trying to soft-delete nonexistent rows:

```
19:39:23.246Z DEBG 4ddb5ba2-551f-44a2-b01f-586f8b863375 (ServerContext): Skipped soft-deletion of Omicron zone external IP (external IP does not exist)
    action = deallocate-external-networking
    background_task = blueprint_executor
    comment =
    ip = Floating(OmicronZoneExternalFloatingIp { id: e83ff356-44b5-4362-bbd3-662ad98af5e7 (external_ip), ip: 172.20.27.2 })
    nic = NetworkInterface { id: 25f699ee-0437-436a-8dcd-73dbb450df4f, kind: Service { id: dafba4c0-cc23-457a-b696-f466593b7403 }, name: Name("nexus-dafba4c0-cc23-457a-b696-f466593b7403"), ip_config: V4(PrivateIpv4Config { ip: 172.30.2.5, subnet: Ipv4Net { addr: 172.30.2.0, width: 24 }, transit_ips: [] }), mac: MacAddr(MacAddr6([168, 64, 37, 255, 128, 0])), vni: Vni(100), primary: true, slot: 0 }
    zone_id = dafba4c0-cc23-457a-b696-f466593b7403
    zone_kind = nexus
19:39:23.251Z DEBG 4ddb5ba2-551f-44a2-b01f-586f8b863375 (ServerContext): Skipped soft-deletion of Omicron zone vNIC (vNIC does not exist)
    action = deallocate-external-networking
    background_task = blueprint_executor
    comment =
    ip = Floating(OmicronZoneExternalFloatingIp { id: e83ff356-44b5-4362-bbd3-662ad98af5e7 (external_ip), ip: 172.20.27.2 })
    nic = NetworkInterface { id: 25f699ee-0437-436a-8dcd-73dbb450df4f, kind: Service { id: dafba4c0-cc23-457a-b696-f466593b7403 }, name: Name("nexus-dafba4c0-cc23-457a-b696-f466593b7403"), ip_config: V4(PrivateIpv4Config { ip: 172.30.2.5, subnet: Ipv4Net { addr: 172.30.2.0, width: 24 }, transit_ips: [] }), mac: MacAddr(MacAddr6([168, 64, 37, 255, 128, 0])), vni: Vni(100), primary: true, slot: 0 }
    zone_id = dafba4c0-cc23-457a-b696-f466593b7403
    zone_kind = nexus
```
