### PR TITLE
Ignore missing zpools instead of bailing

### LINKED ISSUE #7963: omdb db zpool and crucible-dataset subcommands should ignore deleted zpools
I was trying to work around #7962 temporarily by manually setting the `time_deleted` field to non-NULL for a zpool in an expunged disk.
```
root@[fd00:1122:3344:105::3]:32221/omicron> update zpool set time_deleted = time_modified where id = '3af01cc4-1f16-47d9-a489-abafcb91c2db';
UPDATE 1


Time: 3ms total (execution 3ms / network 0ms)

root@[fd00:1122:3344:105::3]:32221/omicron> select * from zpool where id = '3af01cc4-1f16-47d9-a489-abafcb91c2db';
                   id                  |         time_created          |         time_modified         |         time_deleted          | rcgen |               sled_id                |           physical_disk_id           | control_plane_storage_buffer
---------------------------------------+-------------------------------+-------------------------------+-------------------------------+-------+--------------------------------------+--------------------------------------+-------------------------------
  3af01cc4-1f16-47d9-a489-abafcb91c2db | 2023-08-30 18:57:52.826594+00 | 2024-03-27 21:18:20.842573+00 | 2024-03-27 21:18:20.842573+00 |     4 | 0c7011f7-a4bf-4daf-90cc-1c2410103300 | 0bffef3c-56b1-4b01-b897-161bbf766bea |                 268435456000
(1 row)
```
But that still doesn't allow the `omdb db zpool` and `omdb db crucible-dataset` commands to work. They still complain about the zpool on an expunged disk:
```
root@oxz_switch0:~# omdb db zpool list
Error: zpool 7ab10d7d-2b90-4080-ad3c-9b4187d4e122 not found in inventory!
```
```
root@oxz_switch0:~# omdb db crucible-dataset list
Error: zpool 3af01cc4-1f16-47d9-a489-abafcb91c2db not found!
```

### PR DESCRIPTION
**Pull request by jmpesp**
In omdb, if a zpool is not part of the latest inventory, ignore this and continue displaying rows for other zpools and datasets. Several columns had to change to Option to support this.

Fixes #7963

### CODE REVIEW

File: dev-tools/omdb/src/bin/omdb/db.rs [hunk 1]
```diff
@@ -1636,11 +1636,21 @@ struct CrucibleDatasetRow {
...
     // computed fields
-    size_left: i128,
+    #[tabled(display_with = "option_impl_display")]
+    size_left: Option<i128>,
+}
+
+fn option_impl_display<T: std::fmt::Display>(t: &Option<T>) -> String {
+    match t {
+        Some(v) => format!("{v}"),
+        None => String::from("n/a"),
```
Comment (jgallagher) [inline dev-tools/omdb/src/bin/omdb/db.rs:1652]: Not trying to bikeshed and probably not worth holding up the PR, but I'm not sure about `n/a`. A zpool could be missing from inventory for multiple reasons, right? At least

* the disk has been expunged
* the sled-agent holding this zpool failed to report its inventory in this collection pass

which seem pretty different in terms of "what should we report here". Can we tell the difference between these at this point? (Fine to say "let's land this as-is for R14 then figure out what to do here next week".)

**Review by jgallagher — APPROVED** [review]

File: dev-tools/omdb/src/bin/omdb/db.rs (hunk 1 above)
Comment (jmpesp) [reply dev-tools/omdb/src/bin/omdb/db.rs:1652]: In this little display function, no, it just knows that it's an Option. It may make sense to put an enum here like

```rust
enum Thingy {
  PresentInInventory(value),
  
  NotPresentInInventory,
  
  Expunged,
}
```

I'd say we could check for time_deleted (except for https://github.com/oxidecomputer/omicron/issues/7962) or the backing physical disk status, but I'm inclined to land this for R14 as-is.
