### PR TITLE
Ensure required subdirectories of /var/fm/fmd exist

### LINKED ISSUE #4444: fmd backing store is missing some directories
While reviewing a fault management error log from a server, I observed a number of reports about missing directories underneath `/var/fm/fmd`. Sled agent should create these as part of setting up the filesystem.

```
        msg = failed to mkdir /var/fm/fmd/ckpt/eft
        msg = failed to mkdir /var/fm/fmd/ckpt/software-diagnosis
        msg = failed to mkdir /var/fm/fmd/ckpt/zfs-diagnosis
        msg = failed to open asru cache directory /var/fm/fmd/rsrc
        msg = failed to open log /var/fm/fmd/rsrc/295aaa57-5d0f-4a63-aaef-a805cb2725fb
        msg = failed to open log /var/fm/fmd/rsrc/590b1dbf-97a8-448c-90c0-7f23357d3a82
        msg = failed to open log /var/fm/fmd/rsrc/873e3a20-9e66-4f26-8149-3ea095cb15c4
        msg = failed to open log /var/fm/fmd/rsrc/a26d76e4-71b5-4c54-9e60-df89e3542556
```

### PR DESCRIPTION
**Pull request by citrus-it**
When a blank ZFS dataset is created to back /var/fm/fmd, the fault management daemon creates the files it needs but it does not create subdirectories that are required to store data. sled-agent needs to ensure these exist after mounting the dataset

Fixes #4444

### CODE REVIEW

**Comment by citrus-it** [comment]
I tested this on a bench gimlet with no pre-existing pools.

```
gimlet-sn06 # tail -F `svcs -L sled-agent` | looker -c 'r.component == "BackingFs"'
16:06:49.602Z INFO SledAgent (BackingFs): Processing fmd
    file = sled-agent/src/backing_fs.rs:126
16:06:49.602Z INFO SledAgent (BackingFs): Ensuring dataset oxi_a462a7f7-b628-40fe-80ff-4e4189e2d62b/backing/fmd
    file = sled-agent/src/backing_fs.rs:136
16:06:49.871Z INFO SledAgent (BackingFs): Stopping service svc:/system/fmd:default
    file = sled-agent/src/backing_fs.rs:170
16:06:51.042Z INFO SledAgent (BackingFs): Mounting oxi_a462a7f7-b628-40fe-80ff-4e4189e2d62b/backing/fmd on /var/fm/fmd
    file = sled-agent/src/backing_fs.rs:178
16:06:51.092Z INFO SledAgent (BackingFs): Ensuring directory /var/fm/fmd/rsrc
    file = sled-agent/src/backing_fs.rs:186
16:06:51.093Z INFO SledAgent (BackingFs): Ensuring directory /var/fm/fmd/ckpt
    file = sled-agent/src/backing_fs.rs:186
16:06:51.093Z INFO SledAgent (BackingFs): Ensuring directory /var/fm/fmd/xprt
    file = sled-agent/src/backing_fs.rs:186
16:06:51.093Z INFO SledAgent (BackingFs): Starting service svc:/system/fmd:default
    file = sled-agent/src/backing_fs.rs:192
```

```
gimlet-sn06 # ls -CF /var/fm/fmd
ckpt/           fltlog          infolog_hival   xprt/
errlog          infolog         rsrc/
```

File: sled-agent/src/backing_fs.rs [hunk 1]
```diff
@@ -49,16 +53,19 @@ struct BackingFs {
     compression: Option<&'static str>,
     // Linked service
     service: Option<&'static str>,
+    // Subdirectories to ensure
+    subdirs: Option<&'a [&'static str]>,
```
Comment (jgallagher) [inline sled-agent/src/backing_fs.rs:57]: This is completely fine as-is, but I'll just note that you could do `Option<&'static [&'static str]>` here to avoid the `<'a>` bound on `BackingFs`. (Doing so would be less flexible than what you have, but since everything else in here has a `'static` bound we could make this match.)

**Review by jgallagher — APPROVED** [review]
