### PR TITLE
HardwareManager: Rework to use a watch channel instead of broadcasting updates

### LINKED ISSUE #10187: sled-agent doesn't always restart the switch zone after the Tofino restarts
Today on madrid, @Nieuwejaar ran into an issue where upon restarting the Tofino, `sled-agent` tore down the switch zone (as expected) but never restarted it (definitely not expected). Looking at the logs, we see that on startup, the `HardwareMonitor` was notified that a Tofino was available, so started the switch zone:

```
00:01:28.281Z INFO SledAgent (HardwareMonitor): tofino present and policy allows switch zone; will activate it
    file = sled-agent/src/hardware_monitor.rs:265
00:01:28.281Z INFO SledAgent (ServiceManager): Ensuring scrimlet services (enabling services)
    file = sled-agent/src/services.rs:3279
00:01:28.281Z INFO SledAgent (ServiceManager): Re-enabling running switch zone (new address)
```

And when the Tofino went away, the `tofino-monitor` process (from #9181) noticed, shut down the switch zone, and that `HardwareMonitor` received a `TofinoUnavailable` message:

```
Mar 30 17:00:12.630 DEBG back from contract ioctl, unit: tofino-monitor
Mar 30 17:00:12.632 INFO Got tofino removed notification, unit: tofino-monitor
Mar 30 17:00:12.650 INFO halting the switch zone, unit: tofino-monitor
Mar 30 17:00:14.369 INFO acknowledging the remove event, unit: tofino-monitor
Mar 30 17:00:16.369 DEBG entering contract ioctl, unit: tofino-monitor
Mar 30 17:00:16.369 DEBG back from contract ioctl, unit: tofino-monitor
Mar 30 17:00:16.369 INFO closing out the device contract, unit: tofino-monitor
Mar 30 17:00:16.370 INFO tofino monitor exiting, unit: tofino-monitor
17:00:16.374Z INFO SledAgent (HardwareManager): child exited with code: Some(0)
    file = sled-hardware/src/illumos/mod.rs:730
17:00:16.375Z INFO SledAgent (HardwareMonitor): Received hardware update message
    file = sled-agent/src/hardware_monitor.rs:154
    update = Ok(TofinoUnavailable)
17:00:16.375Z INFO SledAgent (HardwareMonitor): Hardware monitor got TofinoUnavailable message
    file = sled-agent/src/hardware_monitor.rs:201
17:00:16.375Z INFO SledAgent (ServiceManager): Disabling switch zone (was running)
```

However, when the Tofino came back, `tofino-monitor` noticed, but `HardwareMonitor` never got a `TofinoAvailable` message, so it never restarted the switch zone:

```
Mar 30 17:00:21.383 INFO tofino monitor online, unit: tofino-monitor
Mar 30 17:00:21.414 INFO tofino device found, unit: tofino-monitor
Mar 30 17:00:21.414 DEBG entering contract ioctl, unit: tofino-monitor
```

Most events `HardwareMonitor` receives come from the internal `sled_hardware` task that periodically polls devinfo. That task emits logs either noting "nothing changed" or a list of updates: https://github.com/oxidecomputer/omicron/blob/dfcd9ac2d3321f7d286c6bde832faf0306b1e535/sled-hardware/src/illumos/mod.rs#L681-L688

I initially assumed from the `Hardware monitor got TofinoUnavailable message` log that this polling had noticed the Tofino had gone away, but that was wrong:

1. There was no corresponding `Update from polling device tree:` log
2. That `TofinoUnavailable` message was sent by the  `tofino-monitor` machinery itself: https://github.com/oxidecomputer/omicron/blob/dfcd9ac2d3321f7d286c6bde832faf0306b1e535/sled-hardware/src/illumos/mod.rs#L732

We did confirm via `dtrace` that the polling system was polling every 5 seconds and did know that the Tofino is available:

```
BRM42220081 # dtrace -n 'slog15282:::debug { printf("%s\n", copyinstr(arg0)); }' -q | grep sled_hardware
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":369},"level":"DEBUG","timestamp":"2026-03-30T17:55:57.396110244Z","message":"Found tofino node, with asic available","kv":{"component":"HardwareManager"}
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":682},"level":"DEBUG","timestamp":"2026-03-30T17:55:58.385531396Z","message":"No updates from polling device tree","kv":{"component":"HardwareManager"}}}
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":369},"level":"DEBUG","timestamp":"2026-03-30T17:56:03.415312964Z","message":"Found tofino node, with asic available","kv":{"component":"HardwareManager"}
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":682},"level":"DEBUG","timestamp":"2026-03-30T17:56:04.365675256Z","message":"No updates from polling device tree","kv":{"component":"HardwareManager"}}}
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":369},"level":"DEBUG","timestamp":"2026-03-30T17:56:09.395331786Z","message":"Found tofino node, with asic available","kv":{"component":"HardwareManager"}
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":682},"level":"DEBUG","timestamp":"2026-03-30T17:56:10.305673451Z","message":"No updates from polling device tree","kv":{"component":"HardwareManager"}}}
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":369},"level":"DEBUG","timestamp":"2026-03-30T17:56:15.333921636Z","message":"Found tofino node, with asic available","kv":{"component":"HardwareManager"}
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":682},"level":"DEBUG","timestamp":"2026-03-30T17:56:16.324512269Z","message":"No updates from polling device tree","kv":{"component":"HardwareManager"}}}
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":369},"level":"DEBUG","timestamp":"2026-03-30T17:56:21.355846860Z","message":"Found tofino node, with asic available","kv":{"component":"HardwareManager"}
{"ok":{"location":{"module":"sled_hardware::illumos","file":"sled-hardware/src/illumos/mod.rs","line":682},"level":"DEBUG","timestamp":"2026-03-30T17:56:22.362137839Z","message":"No updates from polling device tree","kv":{"component":"HardwareManager"}}}
```

My theory here is:

* The polling task never completed a poll where the Tofino was _unavailable_ (I'm not sure about the exact mechanics here - maybe it was a timing issue since we only poll every 5 seconds and the Tofino wasn't gone for very long, or maybe polling devinfo itself is affected somehow by the Tofino going away and coming back?)
* Therefore, it never sent a `TofinoAvailable` message, because it _itself_ never sent a `TofinoUnavailable` message

I'm very hesitant to suggest any quick fixes here, because this feels a bit like we've got two different paths of control that are interfering. Some ideas:

* Should the `tofino-monitor` path send a `TofinoAvailable` message, akin to how it sends `TofinoUnavailable`?
* Should the `tofino-monitor` path coordinate more closely with the polling path? (E.g., if the `tofino-monitor` path told the polling path that the tofino was unavailable instead of bypassing it to talk to `HardwareMonitor` directly, a future poll that saw the tofino would be able to know enough to send a `TofinoAvailable` message)
* Should the poller -> `HardwareMonitor` communication be reworked to be level-triggered instead of edge triggered? (This might also require something like the previous bullet.)

I don't think this is a release blocker, but it does mean we're back in the "we can't ship updates containing sidecar FPGA changes because online-updating to that might knock out the switch zones" world we were before #9181 landed.

### PR DESCRIPTION
**Pull request by jgallagher**
This is an attempt to make hardware monitoring somewhat more level-triggered and somewhat less edge-triggered. In #10187, we had a case where the two different sources of `HardwareUpdate` notifications got out of sync, resulting in the polling source failing to send a `TofinoAvailable` update even though it realized the Tofino was, in fact, available.

On this branch, we keep the current `HardwareView` in a watch channel; any changes made to it will result in a `.changed()` notification firing, removing the possibility of mismatched updates.

(Hopefully) fixes #10187 - I'll get this on a racklette for some testing before merging.

### CODE REVIEW

File: sled-hardware/src/illumos/mod.rs [hunk 1]
```diff
@@ -729,7 +652,20 @@ fn monitor_tofino(log: slog::Logger, tx: broadcast::Sender<HardwareUpdate>) {
             Err(e) => error!(&log, "failed to collect exit status: {e:?}"),
             Ok(s) => info!(&log, "child exited with code: {:?}", s.code()),
         }
-        let _ = tx.send(HardwareUpdate::TofinoUnavailable);
```
Comment (jgallagher) [inline sled-hardware/src/illumos/mod.rs:732]: This is the main behavioral fix in the PR. Prior to this change, this `tx.send(_)` went directly to sled-agent's `HardwareMonitor` and bypassed the `hardware_tracking_task()` thread created in this module, leaving open a window where `hardware_tracking_task()` might never see the Tofino be unavailable (and therefore never send an update back to `HardwareMonitor` that it became available again).

Now, we still send a change here that `HardwareMonitor` picks up, but it's in a watch channel we share with `hardware_tracking_task()`, so the next time it runs, it will see that we marked the Tofino as unavailable - if it's become available again, it will correctly update the channel contents and fire another `.changed()` event to `HardwareMonitor`.

File: sled-agent/src/hardware_monitor.rs [hunk 2]
```diff
@@ -179,70 +186,6 @@ impl HardwareMonitor {
...
-                    );
-                    if let Some(sled_agent) = &mut self.sled_agent {
-                        sled_agent.notify_nexus_about_self(&self.log).await;
-                    }
-                }
-                HardwareUpdate::DiskAdded(disk) => {
-                    self.raw_disks_tx
-                        .add_or_update_raw_disk(disk.into(), &self.log);
-                }
-                HardwareUpdate::DiskRemoved(disk) => {
```
Comment (jgallagher) [inline sled-agent/src/hardware_monitor.rs:224]: Losing the fine-grained updates is a bit of a bummer - now we only get notified when the entire set of `(tofino, all_disks)` changes in any way, so we go through the more heavyweight `check_latest_hardware_snapshot()` on any change. But (a) I think it's easier to understand, (b) the methods `check_latest_hardware_snapshot()` talks to are already themselves prepared to handle "nothing actually changed - don't do anything", and (c) we expect this event to fire _very_ infrequently.

File: sled-hardware/src/illumos/mod.rs [hunk 3]
```diff
@@ -624,74 +499,122 @@ fn poll_blkdev_node(
...
-        let mut inner = inner.lock().unwrap();
-        inner.update_tofino(&polled_hw, &mut updates);
-        inner.update_blkdev(&polled_hw, &mut updates);
-        inner.baseboard = Some(polled_hw.baseboard);
-    };
+    let HardwareSnapshot {
+        tofino: polled_tofino,
+        disks: polled_disks,
+        baseboard: polled_baseboard,
+    } = polled_hw.clone();
```
Comment (smklein) [inline sled-hardware/src/illumos/mod.rs]: Could we destructure `polled_hw` without cloning, and log these inner fields directly down below?

(I think that would help us skip an unnecessary clone)

File: sled-hardware/src/illumos/mod.rs (hunk 1 above)
Comment (smklein) [reply sled-hardware/src/illumos/mod.rs:732]: makes sense, a watch channel seems like a more correct primitive here.

File: sled-agent/config-reconciler/src/raw_disks.rs [hunk 4]
```diff
@@ -305,19 +282,6 @@ mod tests {
                     states[index].present = true;
                     true
                 }
-                Operation::Remove(index) => {
```
Comment (smklein) [inline sled-agent/config-reconciler/src/raw_disks.rs:308]: Was this dead code? I was looking for a caller constructing an `Operation::Remove` but couldn't find one

File: sled-agent/src/hardware_monitor.rs (hunk 2 above)
Comment (smklein) [reply sled-agent/src/hardware_monitor.rs:224]: Agreed, the performance hit here seems really low (since changes are so uncommon) and the cost of missing a change is much worse.

**Comment by jgallagher** [comment]
Testing this on dublin looks good. sled-agent startup shows us finding the tofino and all the disks:

```
00:00:45.422Z INFO SledAgent (HardwareManager): Completed poll of device tree
    did_modify_baseboard = true
    did_modify_disks = true
    did_modify_tofino = true
    file = sled-hardware/src/illumos/mod.rs:594
00:00:45.422Z INFO SledAgent (HardwareManager): Updated tofino
    file = sled-hardware/src/illumos/mod.rs:601
    tofino = TofinoSnapshot { exists: true, available: true }
00:00:45.422Z INFO SledAgent (HardwareManager): Updated baseboard
    baseboard = Gimlet { identifier: "BRM23230018", model: "913-0000019", revision: 11 }
    file = sled-hardware/src/illumos/mod.rs:604
00:00:45.422Z INFO SledAgent (HardwareManager): Updated disks
    disks = { ... all the disks ... }
```

Later, I power cycled the Tofino. We see this sequence:

1. Last poll before the power cycle; no changes (switch zone is still up)

```
19:07:23.080Z INFO SledAgent (HardwareManager): Completed poll of device tree
    did_modify_baseboard = false
    did_modify_disks = false
    did_modify_tofino = false
    file = sled-hardware/src/illumos/mod.rs:594
```

2. `tofino-monitor` notices the Tofino go away; it shuts down the switch zone and updates the watch channel, which triggers `HardwareMonitor` to shut down the switch zone:

```
Mar 31 19:07:24.383 DEBG back from contract ioctl, unit: tofino-monitor
Mar 31 19:07:24.383 INFO Got tofino removed notification, unit: tofino-monitor
Mar 31 19:07:24.396 INFO halting the switch zone, unit: tofino-monitor
Mar 31 19:07:25.805 INFO acknowledging the remove event, unit: tofino-monitor
Mar 31 19:07:27.805 DEBG entering contract ioctl, unit: tofino-monitor
Mar 31 19:07:27.806 DEBG back from contract ioctl, unit: tofino-monitor
Mar 31 19:07:27.806 INFO closing out the device contract, unit: tofino-monitor
Mar 31 19:07:27.806 INFO tofino monitor exiting, unit: tofino-monitor
19:07:27.808Z INFO SledAgent (HardwareManager): child exited with code: Some(0)
    file = sled-hardware/src/illumos/mod.rs:653
19:07:27.808Z INFO SledAgent (HardwareMonitor): Received notification hardware view has changed
    file = sled-agent/src/hardware_monitor.rs:152
19:07:27.809Z INFO SledAgent (HardwareMonitor): Checking current full hardware snapshot
    file = sled-agent/src/hardware_monitor.rs:251
    snapshot = HardwareView { tofino: Real(TofinoSnapshot { exists: true, available: false }), disks: {... all the disks ...}, baseboard: Some(Gimlet { identifier: "BRM23230018", model: "913-0000019", revision: 11 }), online_processor_count: 128, usable_physical_pages: 265285376, usable_physical_ram_bytes: 1086608900096, cpu_family: AmdMilan }
19:07:27.809Z INFO SledAgent (ServiceManager): Disabling switch zone (was running)
    file = sled-agent/src/services.rs:4059
```

3. The next time `HardwareManager` polls the device tree, the Tofino is available again. This confirms we are hitting the race this branch fixes: the Tofino went away and came back in between two poll events. But now since the `tofino-monitor` updated the shared watch channel, the polling thread realizes there's been a change, triggering `HardwareMonitor` to start up the switch zone:

```
19:07:29.114Z INFO SledAgent (HardwareManager): Completed poll of device tree
    did_modify_baseboard = false
    did_modify_disks = false
    did_modify_tofino = true
    file = sled-hardware/src/illumos/mod.rs:594
19:07:29.114Z INFO SledAgent (HardwareManager): Updated tofino
    file = sled-hardware/src/illumos/mod.rs:601
    tofino = TofinoSnapshot { exists: true, available: true }
19:07:29.114Z INFO SledAgent (HardwareMonitor): Received notification hardware view has changed
    file = sled-agent/src/hardware_monitor.rs:152
19:07:29.114Z INFO SledAgent (HardwareMonitor): Checking current full hardware snapshot
    file = sled-agent/src/hardware_monitor.rs:251
    snapshot = HardwareView { tofino: Real(TofinoSnapshot { exists: true, available: true }), disks: {... all the disks ...}, baseboard: Some(Gimlet { identifier: "BRM23230018", model: "913-0000019", revision: 11 }), online_processor_count: 128, usable_physical_pages: 265285376, usable_physical_ram_bytes: 1086608900096, cpu_family: AmdMilan }
19:07:29.114Z INFO SledAgent (HardwareMonitor): tofino present and policy allows switch zone; will activate it
    file = sled-agent/src/hardware_monitor.rs:208
19:07:29.114Z INFO SledAgent (ServiceManager): Ensuring scrimlet services (enabling services)
    file = sled-agent/src/services.rs:3257
19:07:29.114Z INFO SledAgent (ServiceManager): Enabling switch zone (new)
    file = sled-agent/src/services.rs:3611
19:07:29.114Z INFO SledAgent (ServiceManager): Starting switch zone
    file = sled-agent/src/services.rs:4110
```

File: sled-hardware/src/illumos/mod.rs (hunk 3 above)
Comment (jgallagher) [reply sled-hardware/src/illumos/mod.rs]: I thought I needed the clone because the `send_if_modified()` takes ownership of these, but it only does that if there have actually been changes. [2c4d11b](https://github.com/oxidecomputer/omicron/pull/10194/commits/2c4d11b94f67c6e8476d0ac8d4c1dc54788b287a) removes this clone, and adds some clones inside `send_if_modified()` (only in the "there are changes" path).

File: sled-agent/config-reconciler/src/raw_disks.rs (hunk 4 above)
Comment (jgallagher) [reply sled-agent/config-reconciler/src/raw_disks.rs:308]: No, this was constructed by a proptest, but since we got rid of `remove_raw_disk()` there's no way to implement this branch (nor any reason to try to proptest explicit removals).
