### PR TITLE
ls-apis should fail if it finds inconsistency between Cargo deps and API metadata

### LINKED ISSUE #6827: clickhouse-admin-client is missing API metadata
If you run `cargo xtask ls-apis apis` (or any other subcommand), you get this warning:

```
$ cargo xtask ls-apis apis
...
warning: workspace omicron: found client package missing from API manifest: clickhouse-admin-client
...
```

This is because we've recently added a package called `clickhouse-admin-client` that depends on Progenitor.  `ls-apis` correctly infers that it's a Progenitor-based API client.  But it has no metadata about the API.

### LINKED ISSUE #6828: `ls-apis` should fail when API metadata is inconsistent with Cargo package dependencies
We're at the point where I think it's reasonable to say that if you add a new Progenitor-based client, you should also update the api-manifest.toml file.  The `ls-apis` tool currently emits warnings when the API manifest is inconsistent with what it found in the Cargo dependency tree.  These should be errors instead.  This would catch cases like #6827 because they'd fail in CI.

### PR DESCRIPTION
**Pull request by davepacheco**
Fixes #6828.
Fixes #6827.
Includes a workaround for #6829.

### CODE REVIEW

File: dev-tools/ls-apis/src/system_apis.rs [hunk 1]
```diff
@@ -436,6 +444,22 @@ impl<'a> ServerComponentsTracker<'a> {
...
+        // TODO Work around omicron#6829.
+        // Through the dependency tree, omicron-nexus appears to export the
+        // clickhouse-admin-api, but it doesn't really.
+        // This is just like the Crucible Pantry one above in that we can't
+        // build our data model unless we ignore it so we have to hardcode this
+        // here rather than use "dependency_filter_rules".
+        if **server_pkgname == "omicron-nexus"
+            && *api.client_package_name == "clickhouse-admin-client"
+        {
+            eprintln!(
```
Comment (andrewjstone) [inline dev-tools/ls-apis/src/system_apis.rs:456]: Looks like some copy-pasta

**Review by andrewjstone — APPROVED** [review]
Thanks @davepacheco
