### PR TITLE
Fix "project" (silo) IP pool view perms for non-admins

### LINKED ISSUE #5883: `project_ip_pool_view` 404s for non-fleet viewers
This is the cause of https://github.com/oxidecomputer/console/issues/2278. Working on a test to repro. Should be an easy repro and easy fix.

### PR DESCRIPTION
**Pull request by david-crespo**
Closes #5883

Authz for IP pools is undercooked. Every user has `CreateChild` on them so they can allocate IPs, but they generally don't have `Read` on them unless they're a fleet viewer. Ideally, we'd be able to say "you have `Read` on an IP pool if it is linked to your silo", but I don't know how to express that relationship with polar (plus it requires a join to the silo-pool links table to tell).

Update: after [discussing](https://matrix.to/#/!YNYPOVxjAUeXksTcRj:oxide.computer/$XTbZiYkEFRKWHwe6XSVivBrqiWWl_z25u2_TcjwRohE?via=oxide.computer&via=unix.house&via=matrix.org) this with @davepacheco in chat, we agreed on a direction but also agreed it might be fairly complicated. Based on that, I think it would be most expedient to 

1. Merge this fix as-is (with a link to https://github.com/oxidecomputer/omicron/issues/3995, which I forgot I had made 10 months ago 😢)
2. Update #3995 with more details from the chat

### CODE REVIEW

File: nexus/src/app/ip_pool.rs [hunk 1]
```diff
@@ -99,8 +99,14 @@ impl super::Nexus {
...
-        let (authz_pool, pool) =
-            self.ip_pool_lookup(opctx, pool)?.fetch().await?;
+        let (authz_pool, pool) = self
+            .ip_pool_lookup(opctx, pool)?
+            // TODO: This is a smell. This works because it is the permission
+            // for allocating IPs from a pool, which any authenticated user has.
+            // But what we really want to say is that any authenticated user has
+            // actual Read permission on any IP pool linked to their silo.
+            .fetch_for(authz::Action::CreateChild)
+            .await?;
```
Comment (david-crespo) [inline nexus/src/app/ip_pool.rs:109]: 🤔

File: nexus/tests/integration_tests/ip_pools.rs [hunk 2]
```diff
@@ -1142,52 +1147,94 @@ async fn test_ip_pool_range_pagination(cptestctx: &ControlPlaneTestContext) {
 #[nexus_test]
 async fn test_ip_pool_list_in_silo(cptestctx: &ControlPlaneTestContext) {
     let client = &cptestctx.external_client;
-    let mypool_name = "mypool";
 
-    const PROJECT_NAME: &str = "myproj";
-    create_project(client, PROJECT_NAME).await;
+    let silo_url = format!("/v1/system/silos/{}", cptestctx.silo_name);
+    let silo: Silo = object_get(client, &silo_url).await;
```
Comment (david-crespo) [inline nexus/tests/integration_tests/ip_pools.rs:1152]: None of this is particularly interesting — I'm just setting up a silo with a non-admin user and hitting IP pool list and view.

File: nexus/tests/integration_tests/ip_pools.rs [hunk 3]
```diff
@@ -1142,52 +1147,94 @@ async fn test_ip_pool_range_pagination(cptestctx: &ControlPlaneTestContext) {
...
-    assert_eq!(pool.identity.name.as_str(), mypool_name);
+    assert_eq!(list[1].identity.name.to_string(), other_name);
+    assert!(!list[1].is_default);
+
+    // fetch the pools directly too
+    let url = format!("/v1/ip-pools/{}", default_name);
+    let pool = NexusRequest::object_get(client, &url)
+        .authn_as(AuthnMode::SiloUser(user.id))
+        .execute_and_parse_unwrap::<SiloIpPool>()
+        .await;
```
Comment (david-crespo) [inline nexus/tests/integration_tests/ip_pools.rs:1213]: This fails due to 404 without the fix in the app code.
