### PR TITLE
fix spurious metrics test failures

### LINKED ISSUE #2994: spurious failures from disk/instance metric test
I've seen a couple of apparently-spurious failures of test_instance_metrics and test_disk_metrics.  Here's one from CI:

https://github.com/oxidecomputer/omicron/pull/2951/checks?check_run_id=13190550818
(buildomat job id 01GZFQ8S6NGARWQ8Z7HECHBTA2)

```
5045 | 2023-05-03T03:39:35.710Z | ---- integration_tests::instances::test_instance_metrics stdout ----
-- | -- | --
5046 | 2023-05-03T03:39:35.716Z | log file: /var/tmp/omicron_tmp/test_all-208dd36b5428cdaf-test_instance_metrics.7237.69.log
5047 | 2023-05-03T03:39:35.722Z | note: configured to log to "/var/tmp/omicron_tmp/test_all-208dd36b5428cdaf-test_instance_metrics.7237.69.log"
5048 | 2023-05-03T03:39:35.727Z | thread 'integration_tests::instances::test_instance_metrics' panicked at 'Expected at least one measurement', nexus/tests/integration_tests/metrics.rs:34:5
5049 | 2023-05-03T03:39:35.733Z | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
5050 | 2023-05-03T03:39:35.738Z | WARN: dropped CockroachInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
5051 | 2023-05-03T03:39:35.744Z | WARN: temporary directory leaked: /var/tmp/omicron_tmp/.tmpkj2Pnr
5052 | 2023-05-03T03:39:35.750Z | WARN: dropped ClickHouseInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
5053 | 2023-05-03T03:39:35.758Z | WARN: dropped DendriteInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
5054 | 2023-05-03T03:39:35.769Z | WARN: dendrite temporary directory leaked: /var/tmp/omicron_tmp/.tmpg0eygN
5055 | 2023-05-03T03:39:35.774Z |  
5056 | 2023-05-03T03:39:35.780Z |  
5057 | 2023-05-03T03:39:35.785Z | failures:
5058 | 2023-05-03T03:39:35.790Z | integration_tests::instances::test_instance_metrics
```

### PR DESCRIPTION
**Pull request by davepacheco**
Fixes #2994.  See https://github.com/oxidecomputer/omicron/issues/2994#issuecomment-1533786110 for details.

I'm going to see if the instances test failure looks similar.

### CODE REVIEW

File: nexus/tests/integration_tests/disks.rs [hunk 1]
```diff
@@ -1349,6 +1347,11 @@ const ALL_METRICS: [&'static str; 6] =
 
 #[nexus_test]
 async fn test_disk_metrics(cptestctx: &ControlPlaneTestContext) {
+    // Record the current start time.  When fetching data points, we never need
+    // to look at times before this timestamp, since all the events we're
+    // interested in happen after this test starts.
```
Comment (smklein) [inline nexus/tests/integration_tests/disks.rs:1352]: As mentioned in chats: This will work for "metrics on a single disk", but might not work as well for "system-wide resources", which are made during the populate step.

Should be fine for this test, but caused me issues with the instance metrics test, where the sample "cpu_count = 0" was taken before the test started.

**Review by smklein — APPROVED** [review]
Thank you for fixing this!

**Comment by davepacheco** [comment]
I confirmed that the test_instance_metrics test failure seen in CI looks the same:
https://github.com/oxidecomputer/omicron/issues/2994#issuecomment-1533813138

I updated the PR as discussed in chat so that we grab a timestamp as the very first thing when setting up a ControlPlaneTestContext.  That's what we use now as the start time of our window when querying for metrics.  The end time is `Utc::now()`, which as discussed seems like it should be fine now that we're waiting for oximeter collections to finish.

I was never able to reproduce the `test_instance_metrics` test failure locally so it'll be hard to be positive this fixed the problem, but it clearly fixes _a_ problem and I will run a bunch of iterations and make sure I don't continue to see any of these failures.

**Comment by davepacheco** [comment]
This ran for a few hours without issue: `while RUST_BACKTRACE=1 cargo test -p omicron-nexus -- integration_tests::instances integration_tests::disks; do :; done` so I think this is at least an improvement.
