### PR TITLE
[reconfigurator] Executor: only do cleanup for zones that are `ready_for_cleanup`

### LINKED ISSUE #6999: many Reconfigurator execution steps are fatal that shouldn't be
Right now, failure at many blueprint execution steps causes all of execution to stop.  That feels like the conservative thing to do, but it's not necessarily.  When fixing a broken system requires Reconfigurator to proceed despite some failures, this choice is problematic.  This came up in a colo incident a few weeks ago where we wanted to use Reconfigurator to repair the system by deploying a second Oximeter zone.  In trying to do so, execution failed because it couldn't deploy datasets to a sled agent that was known to be broken (and unrelated to the problem we were trying to repair).  There's no reason that failure to deploy datasets to one sled should prevent Reconfigurator from trying to deploy zones to a _different_ sled.  Arguably, it's wrong to say that failing to deploy datasets to a sled should prevent us from trying to deploy zones to the _same_ sled.  After all, it's totally possible that we successfully deployed datasets during a previous execution, or that there are no new datasets to be created there.  We could instead leave it to the sled agent to check this dependency, failing the zones request if it's missing some dataset that needs to be there.

In today's update call I proposed a pattern where:

- we build the individual execution operations such that when they have strict dependencies like this, the request fails cleanly when the dependency is not satisfied (i.e., `PUT /omicron-zones` should fail if the body refers to datasets that haven't been configured).
- having done that, it's generally safe to call these operations even if their dependencies haven't succeeded; this allows Reconfigurator execution to _always_ try to do these operations rather than skipping them if some dependent operation seems to have failed

The conclusion was that this is directionally a good pattern, but it's not clear how unsafe it would be to just ignore these dependencies today.  So the proposal here is:

- build new operations using this pattern where possible
- for existing operations, evaluate them to determine if we _can_ do things this way and convert them where possible

### PR DESCRIPTION
**Pull request by jgallagher**
Changes the three steps that required the earlier `PUT /omicron-zones` execution step to succeed because they needed to clean up after zones that were definitely shut down to now ready the `ready_for_cleanup` blueprint disposition (which is set by the _planner_ after it confirms via inventory that the zones are dead).

While I was here, I removed both the special case error-to-warning implementation in a couple of steps and the `finalize` step that compiled those. I believe all of that predates the ability for `omdb` to interpret the update-engine event report. Now that it can, emitting step warnings directly is fine. I spun this branch up in a4x2 and then shut down one of the sled-agents; that results in this report the executor:

```
  last completed activation: iter 47, triggered by a periodic timer firing
    started at 2025-03-03T19:49:51.027Z (23s ago) and ran for 11711ms
    target blueprint: 3680509e-77c3-4d98-a8a4-276de89b2c53                                                                                                                                                                                                       
    execution:        enabled                                                                                                                                                                                                                                    
    status:           completed (15 steps)                                                                                                                                                                                                                       
    warning:          at: Plumb service firewall rules: failed to plumb service firewall rules to sleds: Internal Error: Communication Error: error sending request for url (http://[fd00:1122:3344:102::1]:12345/vpc/001de000-074c-4000-8000-000000000000/firewall/rules)
    warning:          at: Deploy Omicron zones: Failed to put OmicronZonesConfig {                                                                                                                                             

... snip the OmicronZonesConfig Debug output ...

} to sled e2389240-03a7-4a96-a04a-aa4ee3a38381: Communication Error: error sending request for url (http://[fd00:1122:3344:102::1]:12345/omicron-zones): error sending request for url (http://[fd00:1122:3344:102::1]:12345/omicron-zones): client error (Connect): tcp connect error: Connection refused (os error 146): Connection refused (os error 146)
    warning:          at: Deploy datasets: Failed to put DatasetsConfig {                                                                                                                                              

... snip the DatasetConfig Debug output ...

} to sled e2389240-03a7-4a96-a04a-aa4ee3a38381: Communication Error: error sending request for url (http://[fd00:1122:3344:102::1]:12345/datasets): error sending request for url (http://[fd00:1122:3344:102::1]:12345/datasets): client error (Connect): tcp connect error: Connection refused (os error 146): Connection refused (os error 146)
    warning:          at: Deploy physical disks: Failed to put BlueprintPhysicalDisksConfig {                                                                                                                                              

... snip the BlueprintPhysicalDisksConfig Debug output ...

} to sled e2389240-03a7-4a96-a04a-aa4ee3a38381: Communication Error: error sending request for url (http://[fd00:1122:3344:102::1]:12345/omicron-physical-disks): error sending request for url (http://[fd00:1122:3344:102::1]:12345/omicron-physical-disks): client error (Connect): tcp connect error: Connection refused (os error 146): Connection refused (os error 146)
    error:            (none)                                                                                                                                                                                                                                     
```

Closes #6999, under the assumption that as of this PR we've identified all the inter-step dependencies and broken them.

### CODE REVIEW

File: nexus/reconfigurator/execution/src/lib.rs [hunk 1]
```diff
@@ -198,40 +195,35 @@ pub async fn realize_blueprint_with_overrides(
...
-// Convert a `Result<(), anyhow::Error>` nto a `StepResult` containing either a
-// `StepSuccess` or `StepWarning` and wrap it in `Result::Ok`.
+// Convert a `Result<(), anyhow::Error>` into a `StepResult` containing either a
+// `StepSuccess` or `StepWarning`.
 //
-// This is necessary because we never want to return an error from execution.
-// Doing so stops execution at the errored step and prevents other independent
-// steps after the errored step from executing.
-fn result_to_step_result(
+// Most steps use this to avoid stoping execution at the errored step, which
```
Comment (smklein) [inline nexus/reconfigurator/execution/src/lib.rs:219]:
```suggestion
// Most steps use this to avoid stopping execution at the errored step, which
```

File: nexus/reconfigurator/execution/src/omicron_zones.rs [hunk 2]
```diff
@@ -110,20 +104,12 @@ pub(crate) async fn clean_up_expunged_zones<R: CleanupResolver>(
...
-            // TODO We should be looking at `ready_for_cleanup` here! But
-            // currently the planner never sets it to true, so we're dependent
-            // on `DeployZonesDone` instead.
-            if !matches!(
-                config.disposition,
-                BlueprintZoneDisposition::Expunged { .. }
-            ) {
+            // We expect to only be called with expunged zones that are ready
+            // for cleanup; skip any with a different disposition.
+            if !config.disposition.is_ready_for_cleanup() {
```
Comment (smklein) [inline nexus/reconfigurator/execution/src/omicron_zones.rs:112]: Would this conditional be a bug if it was invoked? Should we at least be logging something here?

**Review by smklein — APPROVED** [review]

**Review by andrewjstone — APPROVED** [review]
Great cleanup. Love to see the progress here!

File: nexus/reconfigurator/execution/src/omicron_zones.rs (hunk 2 above)
Comment (jgallagher) [reply nexus/reconfigurator/execution/src/omicron_zones.rs:112]: Hmm, I could arguments for any of these options:

* Document this function as "panics if called with a zone that isn't ready for cleanup" and assert.
* Document this function as "returns an error for any zone that isn't ready for cleanup".
* Keep this check and log a warning.
* Keep this check and don't log anything.

I prefer option 4, I think? "Call this method with whatever set of zones you want, and I locally choose to act on the ones I know it's safe to act on". Honestly I'd kind of prefer this take a `&Blueprint` instead of an iterator of zones to avoid this problem altogether, but that makes the tests more awkward. Maybe this should be split into a `pub(crate)` version that takes a `&Blueprint` and a private version that takes this iterator; the `&Blueprint` one could do the filtering, and tests could call the private one?

Comment (jgallagher) [reply nexus/reconfigurator/execution/src/omicron_zones.rs:112]: I'm going to take a stab at cleaning this up in a small followup PR.

**Review by davepacheco — COMMENTED** [review]
Nice!
