### PR TITLE
[update-engine] fix GroupDisplayStats to avoid integer underflow

### LINKED ISSUE #4507: [wicket] "Running" count wrong in rack-update attach
image

Looks like an underflow?

### PR DESCRIPTION
**Pull request by sunshowers**
This could happen if an empty `EventReport` is passed in -- in that case we'd
transition to `Running` but return `NotStarted`.

Fix this by not transitioning `self.kind` to `Running` if we're going to return
`NotStarted`. This does bloat up the code a little but I think is clearer
overall.

Thanks to @jgallagher for all the help debugging this!

Also clean up some related logic and add tests.

Fixes #4507.

### CODE REVIEW

File: update-engine/src/display/group_display.rs [hunk 1]
```diff
@@ -236,18 +236,9 @@ impl GroupDisplayStats {
     }
 
     fn apply_result(&mut self, result: AddEventReportResult) {
-        // Process result.after first to avoid integer underflow.
```
Comment (sunshowers) [inline update-engine/src/display/group_display.rs:239]: This wasn't really good enough to avoid integer underflow 😅, so I decided to just check for equality and then do the more obvious thing of applying `before` before `after`.

**Review by jordanhendricks — APPROVED** [review]
nice find!
