### PR TITLE
fix flaky test_demo_saga

### LINKED ISSUE #6383: test failed in CI: omicron-nexus::test_all integration_tests::demo_saga::test_demo_saga
This test failed on a CI run on **#6382**:

* https://github.com/oxidecomputer/omicron/runs/28904588566

Log showing the specific test failure:

* https://buildomat.eng.oxide.computer/wg/0/details/01J5HWQSG5E84795E8VSVP46VP/ekL0MjAiUdwn7V5MJjAnGEiOPz5GyuiSQNOtUyEpcJ0BlEvu/01J5HWRA8WV9MP33WJRDQDXKTT#S5300

Excerpt from the log showing the failure:

```
5300	2024-08-18T05:08:11.743Z	        FAIL [  12.012s] omicron-nexus::test_all integration_tests::demo_saga::test_demo_saga
5301	2024-08-18T05:08:11.743Z	
5302	2024-08-18T05:08:11.743Z	--- STDOUT:              omicron-nexus::test_all integration_tests::demo_saga::test_demo_saga ---
5303	2024-08-18T05:08:11.743Z	
5304	2024-08-18T05:08:11.743Z	running 1 test
5305	2024-08-18T05:08:11.743Z	test integration_tests::demo_saga::test_demo_saga ... FAILED
5306	2024-08-18T05:08:11.744Z	
5307	2024-08-18T05:08:11.744Z	failures:
5308	2024-08-18T05:08:11.744Z	
5309	2024-08-18T05:08:11.744Z	failures:
5310	2024-08-18T05:08:11.744Z	    integration_tests::demo_saga::test_demo_saga
5311	2024-08-18T05:08:11.744Z	
5312	2024-08-18T05:08:11.744Z	test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 356 filtered out; finished in 11.97s
5313	2024-08-18T05:08:11.744Z	
5314	2024-08-18T05:08:11.744Z	
5315	2024-08-18T05:08:11.744Z	--- STDERR:              omicron-nexus::test_all integration_tests::demo_saga::test_demo_saga ---
5316	2024-08-18T05:08:11.744Z	log file: /var/tmp/omicron_tmp/test_all-9db623fb1941bb12-test_demo_saga.86163.0.log
5317	2024-08-18T05:08:11.744Z	note: configured to log to "/var/tmp/omicron_tmp/test_all-9db623fb1941bb12-test_demo_saga.86163.0.log"
5318	2024-08-18T05:08:11.744Z	DB URL: postgresql://root@[::1]:34479/omicron?sslmode=disable
5319	2024-08-18T05:08:11.744Z	DB address: [::1]:34479
5320	2024-08-18T05:08:11.744Z	log file: /var/tmp/omicron_tmp/test_all-9db623fb1941bb12-test_demo_saga.86163.2.log
5321	2024-08-18T05:08:11.744Z	note: configured to log to "/var/tmp/omicron_tmp/test_all-9db623fb1941bb12-test_demo_saga.86163.2.log"
5322	2024-08-18T05:08:11.744Z	log file: /var/tmp/omicron_tmp/test_all-9db623fb1941bb12-test_demo_saga.86163.3.log
5323	2024-08-18T05:08:11.744Z	note: configured to log to "/var/tmp/omicron_tmp/test_all-9db623fb1941bb12-test_demo_saga.86163.3.log"
5324	2024-08-18T05:08:11.744Z	found sagas (before): []
5325	2024-08-18T05:08:11.744Z	found sagas (after): [Saga { id: 7a368bd7-7d70-4c6e-8f67-ca55883aa6ac, state: Running }]
5326	2024-08-18T05:08:11.744Z	thread 'integration_tests::demo_saga::test_demo_saga' panicked at nexus/tests/integration_tests/demo_saga.rs:47:68:
5327	2024-08-18T05:08:11.744Z	called `Result::unwrap()` on an `Err` value: Error Response: status: 404 Not Found; headers: {"content-type": "application/json", "x-request-id": "9b836ae0-4371-4012-8513-0a64b8626cc5", "content-length": "170", "date": "Sun, 18 Aug 2024 05:08:11 GMT"}; value: Error { error_code: Some("Not Found"), message: "demo saga with id 1dbc1a62-d748-4b15-8cbb-ae32499389be (demo_saga)", request_id: "9b836ae0-4371-4012-8513-0a64b8626cc5" }
5328	2024-08-18T05:08:11.744Z	stack backtrace:
5329	2024-08-18T05:08:11.744Z	   0: rust_begin_unwind
5330	2024-08-18T05:08:11.744Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
5331	2024-08-18T05:08:11.744Z	   1: core::panicking::panic_fmt
5332	2024-08-18T05:08:11.744Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
5333	2024-08-18T05:08:11.745Z	   2: core::result::unwrap_failed
5334	2024-08-18T05:08:11.745Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1679:5
5335	2024-08-18T05:08:11.745Z	   3: unwrap<progenitor_client::progenitor_client::ResponseValue<()>, progenitor_client::progenitor_client::Error<nexus_client::types::Error>>
5336	2024-08-18T05:08:11.745Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1102:23
5337	2024-08-18T05:08:11.745Z	   4: {async_fn#0}
5338	2024-08-18T05:08:11.745Z	             at ./tests/integration_tests/demo_saga.rs:47:5
5339	2024-08-18T05:08:11.745Z	   5: {async_block#0}
5340	2024-08-18T05:08:11.745Z	             at ./tests/integration_tests/demo_saga.rs:21:1
5341	2024-08-18T05:08:11.745Z	   6: poll<&mut dyn core::future::future::Future<Output=()>>
5342	2024-08-18T05:08:11.745Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/future/future.rs:123:9
5343	2024-08-18T05:08:11.745Z	   7: poll<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5344	2024-08-18T05:08:11.745Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/future/future.rs:123:9
5345	2024-08-18T05:08:11.745Z	   8: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
5346	2024-08-18T05:08:11.745Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:673:57
5347	2024-08-18T05:08:11.745Z	   9: with_budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
5348	2024-08-18T05:08:11.745Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
5349	2024-08-18T05:08:11.745Z	  10: budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
5350	2024-08-18T05:08:11.745Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
5351	2024-08-18T05:08:11.745Z	  11: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
5352	2024-08-18T05:08:11.745Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:673:25
5353	2024-08-18T05:08:11.745Z	  12: tokio::runtime::scheduler::current_thread::Context::enter
5354	2024-08-18T05:08:11.745Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:412:19
5355	2024-08-18T05:08:11.745Z	  13: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
5356	2024-08-18T05:08:11.745Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:672:36
5357	2024-08-18T05:08:11.745Z	  14: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
5358	2024-08-18T05:08:11.745Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:751:68
5359	2024-08-18T05:08:11.746Z	  15: tokio::runtime::context::scoped::Scoped<T>::set
5360	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/scoped.rs:40:9
5361	2024-08-18T05:08:11.746Z	  16: tokio::runtime::context::set_scheduler::{{closure}}
5362	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:26
5363	2024-08-18T05:08:11.746Z	  17: try_with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>), tokio::runtime::scheduler::current_thread::{impl#8}::enter::{closure_env#0}<tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>, core::option::Option<()>>>, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>)>
5364	2024-08-18T05:08:11.746Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/thread/local.rs:283:12
5365	2024-08-18T05:08:11.746Z	  18: std::thread::local::LocalKey<T>::with
5366	2024-08-18T05:08:11.746Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/thread/local.rs:260:9
5367	2024-08-18T05:08:11.746Z	  19: tokio::runtime::context::set_scheduler
5368	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:9
5369	2024-08-18T05:08:11.746Z	  20: tokio::runtime::scheduler::current_thread::CoreGuard::enter
5370	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:751:27
5371	2024-08-18T05:08:11.746Z	  21: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
5372	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:660:19
5373	2024-08-18T05:08:11.746Z	  22: {closure#0}<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5374	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:180:28
5375	2024-08-18T05:08:11.746Z	  23: tokio::runtime::context::runtime::enter_runtime
5376	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
5377	2024-08-18T05:08:11.746Z	  24: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5378	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:168:9
5379	2024-08-18T05:08:11.746Z	  25: tokio::runtime::runtime::Runtime::block_on_inner
5380	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:361:47
5381	2024-08-18T05:08:11.746Z	  26: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5382	2024-08-18T05:08:11.746Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:335:13
5383	2024-08-18T05:08:11.746Z	  27: test_demo_saga
5384	2024-08-18T05:08:11.746Z	             at ./tests/integration_tests/demo_saga.rs:21:1
5385	2024-08-18T05:08:11.746Z	  28: test_all::integration_tests::demo_saga::test_demo_saga::{{closure}}
5386	2024-08-18T05:08:11.747Z	             at ./tests/integration_tests/demo_saga.rs:22:61
5387	2024-08-18T05:08:11.747Z	  29: core::ops::function::FnOnce::call_once
5388	2024-08-18T05:08:11.747Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
5389	2024-08-18T05:08:11.747Z	  30: core::ops::function::FnOnce::call_once
5390	2024-08-18T05:08:11.747Z	             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
5391	2024-08-18T05:08:11.747Z	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
5392	2024-08-18T05:08:11.747Z	WARN: dropped CockroachInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
5393	2024-08-18T05:08:11.747Z	WARN: temporary directory leaked: "/var/tmp/omicron_tmp/.tmpAmqAKR"
5394	2024-08-18T05:08:11.747Z	If you would like to access the database for debugging, run the following:
5395	2024-08-18T05:08:11.747Z	
5396	2024-08-18T05:08:11.747Z	# Run the database
5397	2024-08-18T05:08:11.747Z	cargo xtask db-dev run --no-populate --store-dir "/var/tmp/omicron_tmp/.tmpAmqAKR/data"
5398	2024-08-18T05:08:11.747Z	# Access the database. Note the port may change if you run multiple databases.
5399	2024-08-18T05:08:11.747Z	cockroach sql --host=localhost:32221 --insecure
5400	2024-08-18T05:08:11.751Z	WARN: dropped ClickHouseInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
5401	2024-08-18T05:08:11.751Z	WARN: dropped DendriteInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
5402	2024-08-18T05:08:11.751Z	WARN: dendrite temporary directory leaked: /var/tmp/omicron_tmp/.tmpioUB6l
5403	2024-08-18T05:08:11.751Z	WARN: dropped DendriteInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
5404	2024-08-18T05:08:11.751Z	WARN: dendrite temporary directory leaked: /var/tmp/omicron_tmp/.tmpzyeLyy
5405	2024-08-18T05:08:11.751Z	WARN: dropped MgdInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
5406	2024-08-18T05:08:11.751Z	WARN: mgd temporary directory leaked: /var/tmp/omicron_tmp/.tmpyOCDKK
5407	2024-08-18T05:08:11.751Z	WARN: dropped MgdInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
5408	2024-08-18T05:08:11.751Z	WARN: mgd temporary directory leaked: /var/tmp/omicron_tmp/.tmpQQic04
5409	2024-08-18T05:08:11.751Z	
```

### PR DESCRIPTION
**Pull request by davepacheco**
Fixes #6383.

In that issue, it looks like the test successfully created the demo saga, but then when it went to complete it, it wasn't found in the `CompletingDemoSagas` struct.  I didn't appreciate that there's a race here: a newly-created demo saga does not register itself with `CompletingDemoSagas` until its (first and only) saga action starts running, but that's asynchronous with respect to the internal API HTTP request that creates the demo saga.  As a result, clients can get a 404 when they try to complete the demo saga, but if they retry after that first saga action starts running, then it will succeed.

The first fix I had here (9f6b11a) just has the test retry a 404 from this request, using `wait_for_condition` so that this won't hang nor sleep much longer than it needs to.  This works fine to fix the test and if we have to fall back to this then that's okay.  The only consumers of this API are probably humans (who won't be fast enough to hit this race) or other automated tests.  But I wanted to try to do better because this API kind of sucks: you create a thing, then you want to operate on it, but you have to wait for some other thing to happen first.  It's this weird eventual consistency pattern that we've avoid everywhere else.  And we'll have to replicate the retry behavior in other consumers (mainly, future automated tests).

So instead I've reworked the `CompletingDemoSagas` struct so that you can do the completion and subscription steps in either order.  The reason I hadn't done this before was that the obvious solution (create the entry for a demo saga id when _either_ of these events happen) creates a different, worse problem: if the consumer provides the wrong id (which is easier than you'd think with this API, for a few reasons), then the request would silently succeed, leading to implicit failures later (because you hadn't actually completed the saga you thought you had).  What I did instead here was add a preregistration step that happens when we create the demo saga.  If we get a request to complete a saga that hasn't started waiting _and_ isn't preregistered, then we produce the 404.  Notably, this doesn't cover the case that the demo saga was recovered (rather than created in this Nexus's lifetime).  There's no good way to do that, but I think it doesn't really matter since saga recovery is always asynchronous anyway.

### CODE REVIEW

File: nexus/tests/integration_tests/demo_saga.rs [hunk 1]
```diff
@@ -44,7 +44,33 @@ async fn test_demo_saga(cptestctx: &ControlPlaneTestContext) {
...
+                            eprintln!("transient 404 -- will try again");
+                            return CondCheckError::NotYet;
+                        }
+                    }
+
+                    CondCheckError::Failed(err)
+                })
+        },
+        &std::time::Duration::from_millis(20),
+        &std::time::Duration::from_secs(10),
```
Comment (hawkw) [inline nexus/tests/integration_tests/demo_saga.rs:70]: nitpicky, take it or leave it: perhaps we should just import `std::time::Duration`?

**Review by hawkw — APPROVED** [review]
This seems good to me!

**Comment by davepacheco** [comment]
Okay I re-did the testing I'd done for #6215 / #6281 and it all still works.

**Comment by davepacheco** [comment]
In case anybody is watching this issue, I completely rewrote the PR since the review so I want another review round.

File: nexus/src/app/sagas/demo.rs [hunk 2]
```diff
@@ -21,56 +21,66 @@
...
-            self.ids.insert(id, tx).is_none(),
-            "multiple subscriptions for the same demo saga"
-        );
-        Ok(rx)
+    ) -> impl Future<Output = Result<(), anyhow::Error>> {
+        let sem =
+            self.sagas.entry(id).or_insert_with(|| Arc::new(Semaphore::new(0)));
+        let sem_clone = sem.clone();
+        async move {
+            sem_clone
```
Comment (hawkw) [inline nexus/src/app/sagas/demo.rs:66]: nit, take it or leave it: why not just write:
```suggestion
        let sem =
            self.sagas.entry(id).or_insert_with(|| Arc::new(Semaphore::new(0))).clone();
        async move {
            sem
```

File: nexus/src/app/sagas/demo.rs [hunk 3]
```diff
@@ -21,56 +21,66 @@
...
+/// This is where:
+///
+/// - demo sagas wait for a completion message
+/// - completion messages are recorded for demo sagas that haven't started
+///   waiting yet
+///
+/// Nexus maintains one of these structures at the top level.
 pub struct CompletingDemoSagas {
-    ids: BTreeMap<DemoSagaUuid, oneshot::Sender<()>>,
+    sagas: BTreeMap<DemoSagaUuid, Arc<Semaphore>>,
```
Comment (hawkw) [inline nexus/src/app/sagas/demo.rs:46]: Could we, perhaps, add some documentation explaining the motivation for using a `Semaphore` with one 0-1 permit, rather than a `Notify`?

**Review by hawkw — APPROVED** [review]
This implementation makes sense to me overall! I left a couple small comments.

File: nexus/src/app/sagas/demo.rs (hunk 3 above)
Comment (davepacheco) [reply nexus/src/app/sagas/demo.rs:46]: Ah, I think there is no good reason!  I _thought_ if you called `notify.notify_one()`, but nobody was waiting, then that wakeup would be lost.  I just checked the docs and that's not the case.  Do you think I should change it to use `Notify`?

Comment (davepacheco) [reply nexus/src/app/sagas/demo.rs:46]: In the interest of fixing the flaky test quickly, I'm going to land anyway, but we can always change this.

Comment (hawkw) [reply nexus/src/app/sagas/demo.rs:46]: Yeah, that seems fine to me. I agree that `Notify::notify_one` would also have gotten you the exact same behavior, but it also doesn't actually matter. `Notify` might be _very marginally_ more efficient but this is far from a hot path...
