### PR TITLE
Break `EarlyNetworkConfig` up to support cleaner bootstore type changes

### LINKED ISSUE #9943: Network changes during an update to R18 could replicate unreadable bootstore contents
(This came up from asking Claude to review a branch I have working toward #9801, and it found this problem with my branch, but we also shipped it in R18.)

R18 revved the sled-agent `write_network_bootstore_config()` API. Following what we usually do for API changes, the "old" handler converts the incoming request into the latest version and delegates to the new handler: https://github.com/oxidecomputer/omicron/blob/7c56d21f5fb8127a619cb8557cbcc286e8ae0af7/sled-agent/api/src/lib.rs#L823-L829. However, in the case of bootstore, this is fundamentally incorrect, because of this possible sequence:

```
    // 1. One scrimlet is updated; its sled agent is now running the new
    //    version.
    // 2. Nexus (still running the old version) sends a
    //    `write_network_bootstore_config_vN()` request to the updated scrimlet.
    // 3. The scrimlet converts the from-old-Nexus `vN` request to the latest
    //    bootstore format and tells the bootstore to replicate it.
    // 4. Other sleds, which have NOT YET been updated, will now see the new
    //    version and be unable to deserialize it.
```

We would need a combination of things to happen for this to be a problem:

1. Nexus would need to tell sled-agent to write new bootstore contents during an update, after one or both scrimlets have had host OS updates but before all other sleds have completed their host OS updates.
2. After the scrimlet(s) propagate the bootstore changes to all the other sleds, one or more of the sleds still on the old OS would need to reboot. (This can happen routinely during an update; e.g., to update a sled's SP prior to updating its OS.)
3. sled-agent would be unable to read the new bootstore version.

I think if we hit this, we'd see sled-agent spin while trying to start up, continuously logging that it was unable to get the network config from the bootstore: https://github.com/oxidecomputer/omicron/blob/ccede3cb5287e447b0f30916000c7943b1596689/sled-agent/src/sled_agent.rs#L620-L633

We should advise customers not to change upstream network configuration during updates to R18. I've got a branch in progress that will fix this for R19 (and will fix it for updating _to_ R19 as well, since the root cause here is the _newer_ software pushing out information that isn't readable by not-yet-updated prior versions).

### PR DESCRIPTION
**Pull request by jgallagher**
This PR is pretty widespread and touches some easily-broken bits, so I'll go into some background here. The replicated bootstore (soon to be backed by trust quorum instead, but that's not relevant to the context here) gives an eventually-consistent copy of data to all sleds. The type exposed by the bootstore is https://github.com/oxidecomputer/omicron/blob/7c56d21f5fb8127a619cb8557cbcc286e8ae0af7/bootstore/src/schemes/v0/storage.rs#L119-L126

`generation` ensures any write requests from an out-of-date Nexus can't overwrite newer changes. Prior to this PR, `blob` contains a JSON-serialized `EarlyNetworkConfig`, defined as https://github.com/oxidecomputer/omicron/blob/7c56d21f5fb8127a619cb8557cbcc286e8ae0af7/sled-agent/types/versions/src/bgp_v6/early_networking.rs#L23-L35

`EarlyNetworkConfigBody` contains a variety of networking configuration information required to bring up connectivity on a rack cold boot, including BGP details, which switches have transceivers and in which slots, etc. This type is quite complex, and historically changing it has been quite painful - addressing that is the point of this PR and #9801 in general. This PR does not change `NetworkConfig` or `EarlyNetworkConfigBody` - the focus is on `EarlyNetworkConfig`. It has a couple of problems:

* `schema_version` is supposed to tell us what version of `body` is present, but it's defined _in line_ with the body. That means any time we rev a new version of `EarlyNetworkConfigBody`, we also have to rev a new version of `EarlyNetworkConfig`, and don't have an opportunity to inspect `schema_version` before already needing to know how to deserialize `body`.
* `generation` is duplicated with the `generation` in `NetworkConfig`. (This is not nearly as much of a problem in practice as the previous point, but is an opportunity for illegal states - what would it mean for a `NetworkConfig` at generation N to hold a blobified `EarlyNetworkConfig` with a different generation?)

`EarlyNetworkConfig` is used in three places on `main`:

* Serialized as `blob` in the bootstore as described above
* Serialized as `data` in the `bootstore_config` CRDB table (this has the same "duplicated generation" problem as `NetworkConfig` - this table also stores `generation` as a separate column next to `data`)
* As the type for the `write_network_bootstore_config()` sled-agent OpenAPI

This PR breaks `EarlyNetworkConfig` up into two types to address the problems above. The serialized form is now `EarlyNetworkConfigEnvelope`: https://github.com/oxidecomputer/omicron/blob/a8de498858cbeb2a58ebf835ccb11b21536de59b/sled-agent/types/versions/src/bootstore_versioning/early_networking.rs#L45-L55

This has `schema_version` and an _opaque_ `body` (typed as `serde_json::Value`). This fixes both problems with `EarlyNetworkConfig`:

* `EarlyNetworkConfigEnvelope` does not have to have a new type revved any time `EarlyNetworkConfigBody`, because `body` is opaque. We can deserialize the envelope, then inspect `schema_version` to know which version of `EarlyNetworkConfigBody` it contains. (My hope is we _never_ have to rev this type.)
* No duplicated `generation`.

This is fully backwards-compatible as far as _deserialization_ is concerned: any existing `EarlyNetworkConfig` can be safely deserialized as an `EarlyNetworkConfigEnvelope`:

* `schema_version` is unchanged
* `generation` will be ignored
* `body` will be read as a `serde_json::Value` instead of an `EarlyNetworkConfigBody`

`EarlyNetworkConfigEnvelope` does not implement `JsonSchema`, because it should not be used in HTTP / OpenAPI contexts; it's only meant to be a serialization wrapper. That brings us to the second type added in this PR, `WriteNetworkConfigRequest`: https://github.com/oxidecomputer/omicron/blob/a8de498858cbeb2a58ebf835ccb11b21536de59b/sled-agent/types/versions/src/bootstore_versioning/early_networking.rs#L38-L42

This is now the type accepted by sled-agent's `write_network_bootstore_config()` endpoint. sled-agent will convert this request into a `bootstore::NetworkConfig` in the straightforward way:

1. Wrap `body` in an `EarlyNetworkConfigEnvelope`
2. Serialize the now-wrapped `body` as `NetworkConfig::blob`
3. Include `generation` as `NetworkConfig::generation`

I believe this gets us most of the way to #9801. I want to do an actual rev of `EarlyNetworkConfigBody` to confirm this puts us in a good place (and also work on the mechanics of ensuring that any revs made are required to update the relevant bits of implementation that need to be updated, such as `EarlyNetworkConfigEnvelope` knowing how to deserialize the new body type) before closing the issue. I'll also do some update testing on a racklette to confirm I didn't break anything w.r.t. backwards compatibility, but I believe all of these changes should be safe.

This PR also fixes #9943: sled-agent should never "upconvert" `EarlyNetworkConfigBody` requests from Nexus into a newer version; it needs to replicate the exact version it's given.

### CODE REVIEW

File: nexus/db-model/src/bgp.rs [hunk 1]
```diff
@@ -160,3 +166,60 @@ pub struct BgpPeerView {
...
+        // TODO-correctness We should have db constraints to ensure these can't
+        // fail.
+        let router_lifetime =
+            RouterLifetimeConfig::new(value.router_lifetime.0)
+                .map_err(BgpPeerConfigDataError::RouterLifetime)?;
+        let min_ttl = value
+            .min_ttl
+            .map(|val| {
+                u8::try_from(*val)
+                    .map_err(|_| BgpPeerConfigDataError::MinTtl(*val))
```
Comment (jgallagher) [inline nexus/db-model/src/bgp.rs:197]: This is a (potential?) behavior change: the old code in `sync_switch_configuration.rs` had:

```rust
min_ttl: c.min_ttl.map(|x| x.0 as u8), //TODO avoid cast return error
```

so I addressed this TODO while I was here. But if we have any `min_ttl` values greater than 255 in the db, we'll now fail to convert configs instead of silently converting them to `value % 256`. I could change this back if that's a concern, and leave the TODO for later?

Comment (smklein) [reply nexus/db-model/src/bgp.rs:197]: hey I just bumped into this in https://github.com/oxidecomputer/omicron/pull/9941

This is a divergence between the database and diesel.

Comment (jgallagher) [reply nexus/db-model/src/bgp.rs:197]: ... huh! I guess that means all deployed systems must have NULL `min_ttl` values, otherwise we'd be seeing diesel serialization errors? So this conversion code won't run anyway, and once #9941 lands we can drop it. Thanks!

Comment (smklein) [reply nexus/db-model/src/bgp.rs:197]: I'm not sure if they're all NULL, but I'm positive they're "INT2", and relatively sure they can all be parsed as a "SqlU8" value - otherwise, yeah, would see a serialization error.

Comment (jgallagher) [reply nexus/db-model/src/bgp.rs:197]: I'm thinking of https://github.com/oxidecomputer/omicron/pull/8587 - I think that was basically the same case, except there inserting _any_ non-NULL value (even one in range!) resulted in a serialization error. I assume the postgres protocol is sending back 2 bytes and diesel is expecting 8, if it thinks the column is actually a `SqlU32` (`i64`).

File: nexus/src/app/background/tasks/sync_switch_configuration.rs [hunk 2]
```diff
@@ -1174,35 +1191,7 @@ impl BackgroundTask for SwitchPortSettingsManager {
                             .get(0) //TODO breakout support
                             .map(|l| l.autoneg)
                             .unwrap_or(false),
-                        bgp_peers: peer_configs.into_iter()
```
Comment (andrewjstone) [inline nexus/src/app/background/tasks/sync_switch_configuration.rs:1177]: 🤌

File: sled-agent/types/versions/src/impls/early_networking/early_network_config_serialization.rs [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+        schema_version: u32,
+        #[source]
+        err: serde_json::error::Error,
+    },
+    #[error("unknown early network config schema version: {schema_version}")]
+    UnknownSchemaVersion { schema_version: u32 },
+}
+
+impl EarlyNetworkConfigEnvelope {
+    /// Seriealize the contents of this envelope into a bootstore-suitable type,
```
Comment (andrewjstone) [inline sled-agent/types/versions/src/impls/early_networking/early_network_config_serialization.rs]:
```suggestion
    /// Serialize the contents of this envelope into a bootstore-suitable type,
```

File: sled-agent/types/versions/src/bootstore_versioning/early_networking.rs [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+/// sled-agent not attempt to rewrite old `EarlyNetworkConfigBody` types to the
+/// latest version. For more about this, see the comments on the relevant
+/// endpoint in `sled-agent-api`.
+#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, PartialEq)]
+pub struct WriteNetworkConfigRequest {
+    pub generation: u64,
+    pub body: EarlyNetworkConfigBody,
+}
+
+/// Envelope containing a versioned JSON blob (an `EarlyNetworkConfigBody`).
```
Comment (andrewjstone) [inline sled-agent/types/versions/src/bootstore_versioning/early_networking.rs]: Worth adding a comment that this gets serialized into a `bootstore::NetworkConfig` using the `generation` from `WriteNetworkConfigRequest`?

File: sled-agent/types/versions/src/initial/early_networking.rs [hunk 5]
```diff
@@ -31,6 +31,22 @@ pub struct EarlyNetworkConfig {
     pub body: EarlyNetworkConfigBody,
 }
 
+impl From<EarlyNetworkConfig> for bootstore::NetworkConfig {
+    fn from(value: EarlyNetworkConfig) -> Self {
+        // We're serializing in-memory; this can only fail if
+        // `EarlyNetworkConfig` contains types that can't be represented as
+        // JSON, which (a) should never happened and (b) we should catch
```
Comment (andrewjstone) [inline sled-agent/types/versions/src/initial/early_networking.rs]:
```suggestion
        // JSON, which (a) should never happen and (b) we should catch
```

File: nexus/src/app/background/tasks/sync_switch_configuration.rs [hunk 6]
```diff
@@ -1525,10 +1538,21 @@ impl BackgroundTask for SwitchPortSettingsManager {
...
+                        let envelope = EarlyNetworkConfigEnvelope::from(
+                            &write_request.body,
+                        );
                         let config = BootstoreConfig {
                             key: NETWORK_KEY.into(),
-                            generation: desired_config.generation as i64,
-                            data: serde_json::to_value(&desired_config).unwrap(),
+                            generation,
+                            // We're serializing an envelope (guaranteed to be
+                            // representable as JSON) to JSOn in memory, so this
```
Comment (andrewjstone) [inline nexus/src/app/background/tasks/sync_switch_configuration.rs]:
```suggestion
                            // representable as JSON) to JSON in memory, so this
```

File: sled-agent/types/versions/src/bgp_v6/early_networking.rs [hunk 7]
```diff
@@ -297,16 +216,26 @@ pub struct EarlyNetworkConfigBody {
...
-        // Can this ever actually fail?
-        // We literally just deserialized the same data in RSS
-        let blob = serde_json::to_vec(&value).unwrap();
-
-        // Yes this is duplicated, but that seems fine.
-        let generation = value.generation;
+// This impl must be here, not in the crate-level `impls` module, because every
+// version of `EarlyNetworkConfigBody` has its own distinct `SCHEMA_VERSION`.
+impl EarlyNetworkConfigBody {
+    pub const SCHEMA_VERSION: u32 = 2;
```
Comment (andrewjstone) [inline sled-agent/types/versions/src/bgp_v6/early_networking.rs:221]: It would be nice if we could ensure at CI time (via a test I suppose) that this version gets bumped on each modification to this type.

File: sled-agent/types/src/early_networking/serialization.rs [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+        })
+    }
+
+    /// Deserialize the body of this envelope, based on the `schema_version`,
+    /// and convert the contained config to the latest version of
+    /// [`EarlyNetworkConfigBody`].
+    pub fn deserialize_body(
+        &self,
+    ) -> Result<EarlyNetworkConfigBody, EarlyNetworkConfigEnvelopeError> {
+        // TODO: This only handles the current schema version (2). Once we add a
```
Comment (andrewjstone) [inline sled-agent/types/src/early_networking/serialization.rs:130]: Are we always going to convert and return the latest type here? I suppose there has to be a mechanism to do that or else this couldn't return a single type.

File: sled-agent/api/src/lib.rs [hunk 9]
```diff
@@ -805,14 +806,53 @@ pub trait SledAgentApi {
         Ok(HttpResponseOk(result))
     }
 
+    // -------------------------------------------------------------------------
+    // WARNING WARNING WARNING
```
Comment (andrewjstone) [inline sled-agent/api/src/lib.rs:811]: Great comment!

File: sled-agent/api/src/lib.rs [hunk 10]
```diff
@@ -805,14 +806,53 @@ pub trait SledAgentApi {
...
     #[endpoint {
         method = PUT,
         path = "/network-bootstore-config",
-        versions = VERSION_BGP_V6..,
+        versions = VERSION_BOOTSTORE_VERSIONING..,
     }]
     async fn write_network_bootstore_config(
         rqctx: RequestContext<Self::Context>,
-        body: TypedBody<latest::early_networking::EarlyNetworkConfig>,
+        body: TypedBody<v24::early_networking::WriteNetworkConfigRequest>,
```
Comment (sunshowers) [inline sled-agent/api/src/lib.rs]: Should this use `latest::`?

File: sled-agent/src/sim/http_entrypoints.rs [hunk 11]
```diff
@@ -393,22 +396,79 @@ impl SledAgentApi for SledAgentSimImpl {
...
+            generation: config.generation,
+            schema_version: EarlyNetworkConfigBody::SCHEMA_VERSION,
+            body,
+        }))
     }
 
     async fn write_network_bootstore_config(
         rqctx: RequestContext<Self::Context>,
-        body: TypedBody<EarlyNetworkConfig>,
+        body: TypedBody<v24::early_networking::WriteNetworkConfigRequest>,
```
Comment (sunshowers) [inline sled-agent/src/sim/http_entrypoints.rs]: Same comment here, seems like as a latest endpoint this should provide `latest::`.

File: sled-agent/api/src/lib.rs (hunk 10 above)
Comment (jgallagher) [reply sled-agent/api/src/lib.rs]: No, I don't think so. I put the reasoning for that at the end of the big block comment above: https://github.com/oxidecomputer/omicron/blob/e6955638f4784c898193de9efe7c8ec323ac8023/sled-agent/api/src/lib.rs#L833-L837

File: sled-agent/types/src/early_networking/serialization.rs (hunk 8 above)
Comment (jgallagher) [reply sled-agent/types/src/early_networking/serialization.rs:130]: Yeah, exactly. I think it's okay for sled-agent to always operate on the newest type it knows about, since it only writes values to the bootstore as provided by Nexus. This does feel a little precarious, but I didn't want to return a trait object or an enum with all possible versions or anything like that. :-/

File: sled-agent/types/versions/src/bgp_v6/early_networking.rs (hunk 7 above)
Comment (jgallagher) [reply sled-agent/types/versions/src/bgp_v6/early_networking.rs:221]: The next PR adds a compile-time check that each one is exactly equal to "previous + 1".

File: sled-agent/api/src/lib.rs (hunk 10 above)
Comment (sunshowers) [reply sled-agent/api/src/lib.rs]: Aha, completely missed that.

Comment (sunshowers) [reply sled-agent/api/src/lib.rs]: What I'm now wondering is if we want to call it `write_network_bootstore_config_v25` even if it's the latest endpoint (since it is an exception to our general rule that endpoints in the newest version use `latest::`)

Comment (jgallagher) [reply sled-agent/api/src/lib.rs]: I thought the same thing! I landed on not doing that because I didn't want the progenitor client to have the version number in it, but maybe I should put `v25` in the method name and provide an explicit operation ID that omits it?

Comment (sunshowers) [reply sled-agent/api/src/lib.rs]: I think that makes sense.

Comment (jgallagher) [reply sled-agent/api/src/lib.rs]: Done in [ee4bafa](https://github.com/oxidecomputer/omicron/pull/9944/commits/ee4bafaefb55d38dd25076fc47cd71725a7d2f54)

**Comment by jgallagher** [comment]
FYI @andrewjstone @sunshowers - I don't think this necessarily requires a rereview but wanted to ping in case you disagree. Merging `main` was more annoying than I expected because I'd gone back to `v20` to import `v24::EarlyNetworkConfigEnvelope`, which is pretty un-RFD-619 of me. Given `EarlyNetworkConfigEnvelope` is not actually part of the API (and that shouldn't change: it doesn't impl `JsonSchema`, and we shouldn't be sending `serde_json::Value` blobs across API boundaries if we can help it) and I don't expect it to ever change (it's pretty minimal at this point, and it's hard to imagine how it _could_ change while maintaining backwards compatibility), I decided to move it under `crate::impls::*` instead of putting it in a versioned module. This change is in [57d1955](https://github.com/oxidecomputer/omicron/pull/9944/commits/57d1955630ae051c4019142d855696074ee40b19) if you want to give it a glance.

**Comment by andrewjstone** [comment]
> FYI @andrewjstone @sunshowers - I don't think this necessarily requires a rereview but wanted to ping in case you disagree. Merging `main` was more annoying than I expected because I'd gone back to `v20` to import `v24::EarlyNetworkConfigEnvelope`, which is pretty un-RFD-619 of me. Given `EarlyNetworkConfigEnvelope` is not actually part of the API (and that shouldn't change: it doesn't impl `JsonSchema`, and we shouldn't be sending `serde_json::Value` blobs across API boundaries if we can help it) and I don't expect it to ever change (it's pretty minimal at this point, and it's hard to imagine how it _could_ change while maintaining backwards compatibility), I decided to move it under `crate::impls::*` instead of putting it in a versioned module. This change is in [57d1955](https://github.com/oxidecomputer/omicron/pull/9944/commits/57d1955630ae051c4019142d855696074ee40b19) if you want to give it a glance.

I'm sure it's fine!

**Comment by jgallagher** [comment]
> I'm sure it's fine!

@sunshowers and I chatted about it briefly and decided to move it one step further out - c9be9db93 moves the envelope type (which isn't part of any versioned APIs) from `sled-agent-types-versions` to just `sled-agent-types`, which makes it crystal clear it's not expected to change in any future API version bumps.

**Comment by andrewjstone** [comment]
> > I'm sure it's fine!
> 
> @sunshowers and I chatted about it briefly and decided to move it one step further out - [c9be9db](https://github.com/oxidecomputer/omicron/commit/c9be9db93bab5569bf0b064cb5502034b81e8998) moves the envelope type (which isn't part of any versioned APIs) from `sled-agent-types-versions` to just `sled-agent-types`, which makes it crystal clear it's not expected to change in any future API version bumps.

Very good idea!

**Comment by jgallagher** [comment]
I tested this joined in with the followup PR on dublin; notes on that PR: https://github.com/oxidecomputer/omicron/pull/9948#issuecomment-4013332854.

Will be landing both of these imminently.
